### ISSUE TITLE
Remaining problems with CI tests

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#1012]
Summarizing current state of the CI tests.
The following are the intended tests
- (msbuild.yml) On each platform, build a release zip, then unpack it into a new location and attempt to run the lit tests
- (release-downloads.yml) Download each release from GitHub and run a few smoke tests against it
- (release-brew.yml) Install Dafny from brew and run a few smoke tests against it
- (refman.yml) Check that the reference manual builds on Mac and Linux platforms
- (gradle.yml) Build and test DafnyRuntime.jar 

Remaining problems
1) The tests are running for ubuntu-latests, ubuntu-16.04 and macOS-latest. The build on Windows fails (though execution on windows of a build *for* windows succeeds).
2) A number of lit tests fail under windows (grep for UNSUPPORTED in the .dfy files)
3) Current the Windows test of the downloaded release hardcodes the release number -- this should be auto detected as it is for the other platforms.
4) The c++ tests are disabled (because of a lack of C++ compiler)
5) The Reference Manual only builds on MacOS, because of unresolved difficulties in installing LaTeX in the virtual environment.

**Comment by keyboardDrummer** [comment]
I've put problems 1,2 and 5 into separate tickets. @davidcok can you say more about problem 3 and 4. Do you have a reference to where these are visible in the code?

https://github.com/dafny-lang/dafny/issues/1313
https://github.com/dafny-lang/dafny/issues/1314
https://github.com/dafny-lang/dafny/issues/1315

**Comment by robin-aws** [comment]
Found the spot in the workflow config for 3 and cut #1455

4 is already addressed: https://github.com/dafny-lang/dafny/pull/1242
