### ISSUE TITLE
Change to generated Java artifacts

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#1014]
Currently the Dafny->Java translator emits a directory out containing file out.java for a dafny file A.dfy., where 'out' is specified by the -out option and is by default 'A' (the root of the day file).

I propose that
- the output folder be specified by the -out option and by default be A-java
- the filename be specified by "extern" attributes, by default be A.java and not be affected by the -out option

**Comment by RustanLeino** [comment]
Sounds good.

**Comment by davidcok** [comment]
I agree. This was implemented, and most of the time users should use the executable jar.
