### ISSUE TITLE
Dafny with Visual Studio Community 2017

### ISSUE THREAD

**Issue by araybold** [dafny-lang/dafny#103]
Is it possible to use Dafny with Visual Studio Community 2017? When I ran DafnyLanguageService.visx from dafny-1.9.9.40414-x64-win.zip, I get the response "This extension is not installable on any currently installed products". The attached log file shows that Visual Studio Community 2017 was found, but it also seems that the only community versions supported are 14.0 and 15.0.

[VSIXInstaller.log.txt](https://github.com/Microsoft/dafny/files/949820/VSIXInstaller.log.txt)

I am reluctant to go through the build-from-source route unless I know that the instructions at https://github.com/Microsoft/dafny/wiki/INSTALL, which are for VS 2012 Ultimate, will work for VS Community 2017.

Ironically, it is easier to get it running on Linux!

**Comment by peterzeller** [comment]
> I am reluctant to go through the build-from-source route unless I know that the instructions at https://github.com/Microsoft/dafny/wiki/INSTALL, which are for VS 2012 Ultimate, will work for VS Community 2017.

I tried to build the extension on Visual Studio Community 2017 and it did not work with these  instructions.

I managed to build the extension after fixing a few project errors. Syntax highlighting Dafny files was working, but when I tried to compile a file it crashed. 
I did not look further into the reasons for the crash.

**Comment by tyler274** [comment]
Has there been any progress towards VS2017 support?

**Comment by seanmcl** [comment]
Plugins for IDEs should live in different repos, e.g. https://github.com/DafnyVSCode/Dafny-VSCode.
