### ISSUE TITLE
Feature request: additional map operations

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#1044]
I'm noticing that building some basic map operations in user code is a common pattern, and while that exercise is a great way to learn the ropes with Dafny, it also means Dafny users have to spend a bunch of time getting that working instead of the more interesting work of proving correctness of their actual code!

Compared to sets, multisets, and sequences, maps feel like they are missing a few fundamental built-in operations. They could be defined in a standard library, but using operators will help with legibility and also open up the opportunity to optimize these very common operations in the compilers.

Namely, I propose adding the following two new operations:

1. Map "merging" using the `+` operator. The RHS would be another `map<T,U>` value. This would be associative but not commutative, just as sequence concatenation is. Mappings in the RHS would take precedence over those in the LHS where keys are duplicated.
2. Map "subtraction" using the `-` operator. The RHS should arguably be a `set<T>` rather than a `map<T, U>`.

**Comment by RustanLeino** [comment]
One further map-related suggestion--and breaking change--is to change `x in m`, where `m` is a `map` type from the current meaning of `x in m.Keys` to `x in m.Items`.

**Comment by RustanLeino** [comment]
Note, a related breaking change about maps is that `!!` is no longer supported for maps.

**Comment by RustanLeino** [comment]
> One further map-related suggestion--and breaking change--is to change `x in m`, where `m` is a `map` type from the current meaning of `x in m.Keys` to `x in m.Items`.

I have long wanted to make this change. However, now that map subtraction takes a _set_ as one of its operands, it seems natural to keep the current `in` behavior. For example, with map subtraction (and keeping `in` as it is), you can write down the following property:

``` dafny
x !in m - {x}
```

So, I'm thinking we should keep the behavior that `x in m` expects `x` to be a _key_ of `m`, not a _key-value pair_ of `m`. This may be the last time we can decide on this issue. Any opinions?

**Comment by robin-aws** [comment]
I agree we should leave `in` as is for maps. I don't think there's a clear right answer which is more correct, and since the current design expects a key AND most other languages define similar ambiguous operations on keys instead of items (Ruby, Python, Scala, etc.) I don't think it's worth the trouble to change it.

**Comment by RustanLeino** [comment]
Implemented in PRs https://github.com/dafny-lang/dafny/pull/1050 and https://github.com/dafny-lang/dafny/pull/1055.
