### ISSUE TITLE
Compilation targets not found

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#1045]
While the test suite exercises `/compile:[34]` a lot, the behavior of `/compile:[12]` and of `/spillTargetCode:[123]` seems to have fallen off the wagon.

The idea is the following. A target platform (which is specified by `/compileTarget`) has a _textual language_ and an _executable format_. For example, for `/compileTarget:cs`, the textual language is C# and the executable format is a `.dll`. In some targets, the textual language and executable format are the same. For example, for `/compileTarget:js`, both the textual language and the executable format is a JavaScript program with the `.js` extension.

* `/compile:[12]` say to compile the Dafny program into the executable format of the target platform. The executable format is written to disk, so that users can run the executable format on the target platform without needing to read, store, or further process the textual form.
* `/compile:[34]` say to compile the Dafny program and to then run it. The execution takes place on the target platform. If this can all be done in memory, there is no need to write to executable format to disk.
* `/spillTargetCode:[1234]` say to write out textual language.

Use cases:
* A user who wants to verify, compile, and run the program just would naturally choose the `/compile:3` option (and not using `/spillTargetCode`). This is used ubiquitously by the test suite.
* A user who wants to verify and compile the program once, and then run it multiple times would choose `/compile:1`.
* A user who has the need to debug the Dafny-generated target code or wants to recompile the textual language using the target compiler would use `/spillTargetCode:1`.

There are currently several problems with these options. Evidently,
* `/compileTarget:cs /compile:1` writes the compiled assembly to a temporary directory somewhere where a user would never find it. Even so, the `.dll` emitted apparently must be accompanied by some additional configuration files in order for `dotnet` to run it. Those files are not emitted.
* `/compileTarget:js /compile:1` does not emit anything
* `/compileTarget:js /compile:1 /spillTargetCode:1` emits the expected `.js` file, but also runs the programs
* `/compile:3 /compileTarget:cpp` crashes (strange -- isn't this tested anywhere in the test suite?)

It would be nice to have, in the `Test/comp` directory, a test along the lines of:

```
// RUN: %dafny /compileTarget:cs "%s" > "%t"
// RUN: dotnet run CompileAndThenRun.dll >> "%t"
// RUN: %dafny /compileTarget:js "%s" >> "%t"
// RUN: node CompileAndThenRun.js >> "%t"
// RUN: %dafny /compileTarget:go "%s" >> "%t"
// RUN: go run CompileAndThenRun-go/src/CompileAndThenRun.go >> "%t"
// RUN: %dafny /compileTarget:java "%s" >> "%t"
// RUN: java CompileAndThenRun-java/dafny/CompileAndThenRun >> "%t"
// RUN: %dafny /compileTarget:cpp "%s" >> "%t"
// RUN: ./CompileAndThenRun >> "%t"
// RUN: %diff "%s.expect" "%t"

method Main() {
  print "hello, Dafny\n";
}
```

**Comment by parno** [comment]
Regarding the crash with `/compile:3 /compileTarget:cpp`, it looks like the Java version also crashes for a similar reason: both try to call `Path.GetFullPath(Path.GetDirectoryName(targetFilename))` to pick a working directory for compilation, even though `targetFilename` is null in this case.  For such cases, should we default to using the current directory, and a name picked based on the dafnyProgramName (e.g., swapping `.dfy` for `.exe`)?

**Comment by davidcok** [comment]
a) What command line crashes with java? That is pretty well tested, though less so with erroneous input

b) As for cpp -- very little tested and not robust in my experience.

**Comment by parno** [comment]
Hmm, looks like my checkout from earlier this month was nonetheless stale.  Previously `./Scripts/dafny /compile:3 /compileTarget:java t.dfy` for a trivial file `t.dfy` was enough to crash, but it appears that changes Rustan made in`cb7ebc1108` fixed the problem.
