### ISSUE TITLE
misuse of ?? operator

### ISSUE THREAD

**Issue by jonhnet** [dafny-lang/dafny#1053]
https://github.com/dafny-lang/dafny/blob/master/Source/Dafny/Cloner.cs#L110 and line 113 have this idiom:

`return new AliasModuleDecl(a.TargetQId ?? a.TargetQId.Clone(false), a.tok, m, a.Opened, a.Exports);
`
`a??b` in C would be `a!=null ? a : b`. That is, the Cloning expression will only ever be evaluated if `a.TargetOld` is false. That can't be the intention.

**Comment by davidcok** [comment]
Thanks: a.TargetQId ?? a.TargetQId.Clone(false) 
Should be a.TargetQId?.Clone(false)
