### ISSUE TITLE
Add a command-line option to use Z3 resource limits instead of wall-clock time

### ISSUE THREAD

**Issue by parno** [dafny-lang/dafny#106]
Currently, Dafny tells Z3 to give up looking for a proof after a fixed amount of wall clock time elapses.  This can be useful for ensuring a desired latency for providing feedback to the user.  However, it causes challenges when verification is done across developers, or even for the same developer on different platforms.  The same proof that succeeds on a powerful desktop machine may fail on a laptop, or succeed on the laptop, but fail when the laptop is running on battery power.  

Recent versions of Z3 allow clients to specify a resource limit instead, which should be more consistent across such platform variations.  Essentially, it requires emitting:
```
(set-option :rlimit 2723280)
(check-sat)
```
for some appropriately chosen value of rlimit.  As a starting point, the Dafny test suite should provide some good fodder for choosing an appropriate scaling factor.

FWIW, F* recently made this switch and found that it provides a much more uniform verification experience across developers.  The discuss the experience:

https://github.com/FStarLang/FStar/wiki/rlimits:-Machine-Independent-Resource-Limits-for-Deterministic-Execution

and the commits from November 23 - 30 here:

https://github.com/FStarLang/FStar/commits/master?after=2505daa54bbc34f148cc28f8fb3c9e3dc35b5fd5+104&author=catalin-hritcu

**Comment by parno** [comment]
Actually, this might be better done at the Boogie level, rather than in Dafny itself.

**Comment by qunyanm** [comment]
Added by boogie commit  c9c39035a5cc53e96a5fb054cb48ee4a907bbaa1

**Comment by Chris-Hawblitzel** [comment]
It looks like rlimits almost work in Dafny, but the reporting doesn't quite work.  If I run Dafny on the following:

```
function f(i:nat, j:nat):int {if i == 0 then 0 else f(i - 1, i * j + 1) + f(i - 1, 2 * i * j)}

lemma{:rlimit 10000} L()
{
  assert f(10, 5) == 0;
}
```

I get the following output:

```
Dafny.exe x.dfy -trace
Parsing x.dfy
Coalescing blocks...
Inlining...

Running abstract interpretation...
  [0.032866 s]
[TRACE] Using prover: \download\dafny-3.0.0-x64-win\dafny\z3\bin\z3.exe

Verifying CheckWellformed$$_module.__default.f ...
  [0.320 s, 12 proof obligations]  verified

Verifying Impl$$_module.__default.L ...
  [2.192 s, 3 proof obligations]  out of resource
x.dfy(3,21): Verification out of resource (Impl$$_module.__default.L)

Dafny program verifier finished with 1 verified, 0 errors
Compiled assembly into x.dll
```

It ran out of resource, but it didn't count this as an error or timeout and therefore it generated a dll anyway.
