### ISSUE TITLE
PreRelease binaries for Mac doesn't run "because the developer cannot be verified"

### ISSUE THREAD

**Issue by LukeXuan** [dafny-lang/dafny#1079]
When I try `dotnet Dafny.dll`, a prompt claiming `"libhostpolicy.dylib" cannot be opened because the developer cannot be verified.` pops up and the following text pops in the console,

```
Failed to load /Users/[username]/Downloads/dafny/libhostpolicy.dylib, error: dlopen(/Users/[username]/Downloads/dafny/libhostpolicy.dylib, 1): no suitable image found.  Did find:
	/Users/[username]/Downloads/dafny/libhostpolicy.dylib: code signature in (/Users/[username]/Downloads/dafny/libhostpolicy.dylib) not valid for use in process using Library Validation: library load disallowed by system policy
An error occurred while loading required library libhostpolicy.dylib from [/Users/[username]/Downloads/dafny/]
```

Directly executing `./dafny` also gives a similar popup but with no console output.

**Comment by tchajed** [comment]
You can fix this yourself with `xattr -d com.apple.quarantine *.dylib dafny DafnyServer *.dll z3/bin/z3`.

I doubt that will work for fixing the packaging, since somebody else shouldn't be able to change the security settings for a binary; instead they should be signed appropriately, with `codesign` I think.

**Comment by LukeXuan** [comment]
> You can fix this yourself with `xattr -d com.apple.quarantine *.dylib dafny DafnyServer *.dll z3/bin/z3`.

It's nice to learn that.

> instead they should be signed appropriately

That's the point. I myself don't (usually) use Dafny on MacOS anyway.

**Comment by RustanLeino** [comment]
Thanks for the suggestion, @tchajed . We have added the `xattr` command to the installation instructions on the wiki.
