### ISSUE TITLE
CheckWellFormed handle old@ as old

### ISSUE THREAD

**Issue by 857b** [dafny-lang/dafny#1112]
Dafny has the following behavior which allows to de-reference `null` in `old@` expressions:

```
class C {
	var d : D?
}
class D {
	var b : bool
}

method Good()
{
	var d : D? := new D;
	d.b := true;
	label L:
	assert d == old@L(d) != null;
	assert old@L(d.b);
	//            ^
	//Error: receiver must be allocated in the state in which its fields are accessed
}

method Bad(c:C)
	modifies c
	requires c.d != null
{
	c.d := null;
	label L:
	assert c.d == old@L(c.d) == null;
	assert (old@L(c.d.b) || !old@L(c.d.b));
	// Accepted
}
```
The first assertions are not necessary but emphasize the apparent bug. The reason seems to be the translation in Boogie of the well-formedness of the assertions' expressions with `old` instead of the copy of the heap:
```
implementation Impl$$_module.__default.Good() returns ($_reverifyPost: bool)
{
...
    // ----- assert statement ----- ...
    assert {:subsumption 0} d#0 != null;
    assert $IsAlloc(d#0, Tclass._module.D?(), old($Heap)); // <---
    assume true;
    assert read($Heap_at_0, d#0, _module.D.b);
}

```
Those preconditions are generated by `CheckWellformedWithResult` in [Translator.cs](https://github.com/dafny-lang/dafny/blob/e9a59d80e8dc174c0a084c22597be0b7d52db0a3/Source/Dafny/Translator.cs#L7730) whose `OldExpr` case hasn't been updated when the `old@` feature has been introduced  ([91374f65](https://github.com/dafny-lang/dafny/commit/91374f654f58e2d165d40c55ccf7d3c87785f365)).

**Comment by RustanLeino** [comment]
Thanks for the bug report. And good sleuthing!
