### ISSUE TITLE
Dafny 4.0 suggestion: Compiled Dafny programs should accept command-line arguments, return an exit code

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#1116]
Compiled Dafny programs should accept command-line arguments. To do so, the allowed Main methods should be permitted to take a string[] argument.

**Comment by robin-aws** [comment]
While we're at it let's support returning an exit code as well.

**Comment by cpitclaudel** [comment]
Note for future implementers: `string[]` would be a reasonable choice with the current definition of the type `string`, but we might need to use a different type when we switch to unicode `string`s.

**Comment by robin-aws** [comment]
I'd say `string[]` (or even better `seq<string>` :) should definitely be the default choice, but we may want support for some kind of `OsString` a.l.a. Rust to handle edge cases of OS-native strings that aren't valid UTF code unit sequences.

Also I don't see a breaking change so I don't think this is relevant for Dafny 4.0.
