### ISSUE TITLE
Sequence comprehensions do not promise indices are in bounds to comprehension lambda

### ISSUE THREAD

**Issue by tchajed** [dafny-lang/dafny#1119]
In `seq(n, i => f(i))` it would be really helpful for the lambda to have a promise that `0 <= i < n`. This would make it possible to use sequence comprehensions to derive sequences from other sequences, for example:

```dfy
function seq_fmap<T,U>(f: T -> U, xs: seq<T>): seq<U>
{
    seq(|xs|, n => f(xs[n]))
}
```

**Comment by parno** [comment]
That would be handy.  One way we've worked around that is to include the condition in the body of the lambda, e.g., 
```
seq(|xs|, n => if n < |xs| then f(xs[n]) else 42)
```

**Comment by tjhance** [comment]
You can also include a `requires` clause in the lambda,

```
function seq_fmap<T,U>(f: T -> U, xs: seq<T>): seq<U>
{
    seq(|xs|, n requires 0 <= n < |xs| => f(xs[n]))
}
```

**Comment by tchajed** [comment]
Oh wow that totally fixes the issue, and it indicates that the lambda is being given this promise but has to use a `requires` clause to get the benefit. Thanks!

I expect this issue is invalid then but I'll leave it to a maintainer to close it.

**Comment by RustanLeino** [comment]
It would be nice if the `seq` comprehension would automatically add this to the given lambda (and similarly for the initialization function that can be passed in to `new`). However, this is nonstandard in Dafny. One could, of course, special case it (for when the argument is a lambda expression), but it would be nicer to have a good rule. In the meantime, writing the precondition explicitly on the lambda is the way to go.

**Comment by erniecohen** [comment]
It does seem a little bit odd that it requires the "0 <=", indicating that it is expecting a domain of int rather than nat.

**Comment by robin-aws** [comment]
Closely related: https://github.com/dafny-lang/dafny/issues/1332. 

@tchajed - I think I'll close this in favour of that if you like the proposed `seq(length) i :: f(i)` syntax? Your example would become:

```dafny
function seq_fmap<T,U>(f: T -> U, xs: seq<T>): seq<U>
{
    seq(|xs|) n :: f(xs[n])
}
```

Although the function you're after is now part of the Dafny standard library anyway: https://github.com/dafny-lang/libraries/blob/master/src/Collections/Sequences/Seq.dfy#L551 :)

**Comment by tchajed** [comment]
Sure, I also like that proposal. As noted above you can also still use the current sequence comprehension with a `requires` clause, which I consider an adequate fix on its own.
