### ISSUE TITLE
Dafny 1.9.9

### ISSUE THREAD

**Issue by jiplucap** [dafny-lang/dafny#112]
I have installed the last version dafny-1.9.9.40414-x64-win in my computer. I did what I did with many previous versions: uninstall the Dafny Language Mode in MVS, re-initialize MVS, and then click the file DafnyLanguageService.vsix. It reported that it was successfully installed. But all my .dfy files report a "Verification Inconclusive " for each definition and lemma. Please, some help?

**Comment by jaylorch** [comment]
Is this still a problem with version 2.0.0?

**Comment by seanmcl** [comment]
This is ancient.  Please reopen if it's still an issue.
