### ISSUE TITLE
Visual Studio build always runs Coco

### ISSUE THREAD

**Issue by jaylorch** [dafny-lang/dafny#1123]
Even if Dafny.atg hasn't changed since the last time Coco ran, and even if Parser.cs and Scanner.cs are there, the build script reruns Coco.

**Comment by RustanLeino** [comment]
A related (and, I would argue, bigger) problem is that if you change _only_ `Dafny.atg`, then the build does not rerun Coco.

Perhaps both of these problems can be solved by somehow specifying more accurate dependencies of the Coco build event.

**Comment by jaylorch** [comment]
Yes, I thought so too.  I believe the pull request I linked fixes both problems.
