### ISSUE TITLE
Type-characteristic checks not done in ghost code

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#1127]
An actual type parameter must satisfy the declared type characteristics of the corresponding formal parameter. This is not being checked in some ghost code.

For example,

``` dafny
function method Func<T(00)>(): int {
  5
}

type PossiblyEmpty = x: int | true witness *

method Test()
{
  ghost var w;
  w := Func<PossiblyEmpty>();  // error: PossiblyEmpty is not known to be nonempty (BOGUS: no error reported)
}
```

Dafny (incorrectly) reports no error for the program above. However, if `w` is changed from a ghost variable to a compiled variable (i.e., drop the `ghost` keyword in its declaration), then the error is reported as expected.

**Comment by tchajed** [comment]
This issue should also be labeled soundness, right? Here's a proof of false:

```dfy
function GetInhabitant<T(0)>(): T {
  var x: T :| true; x
}

type EmptyInt = x: int | false witness *

lemma oops() ensures false
{
  ghost var w := GetInhabitant<EmptyInt>();
}
```
