### ISSUE TITLE
Loop invariant well-formedness check relies on the Boogie verifier incompleteness

### ISSUE THREAD

**Issue by 857b** [dafny-lang/dafny#1128]
Dafny verifier appears to output correct Boogie programs (according to Boogie semantic, not the verifier) for some incorrect input.
Consider the following incorrect Dafny program, where the invariant tries to perform a division by zero after the first iteration.
```dafny
method Bad()
	decreases *
{
	var i  := 0;
	while i < 2
		invariant i==0 || 1/0 == 42 || true
		decreases *
	{
		i  := i + 1;
	}
}
```
Dafny correctly rejects it and flags the division by zero. However the translation in Boogie is correct, surprisingly:
```boogie
// extract of: dafny /compile:0 /print:- bad.dfy
implementation Impl$$_module.__default.Bad() returns ($_reverifyPost: bool)
{
  var $w$loop#0: bool;
  havoc $w$loop#0;
  while (true)
      free invariant $w$loop#0 ==> true;
      invariant $w$loop#0
         ==> i#0 == LitInt(0) || LitInt(Div(1, LitInt(0))) == LitInt(42) || true;
  {
     if (!$w$loop#0)
     {
        // Check that the invariant is well-formed
        if (i#0 != LitInt(0))
        {
           assert {:subsumption 0} LitInt(0) != 0;
        }
        assume false;
     }
     i#0 := i#0 + 1;
  }
}
```
This can be seen by adding an invariant to the generated loop: `i#0 == 0 || $w$loop#0`. Dafny also accept the initial program if the Boogie option `/loopUnroll:1` is passed. Indeed the well-formedness check of the invariant can (in Boogie's semantic) only be performed at the beginning of the first iteration since `$w$loop#0` is constant and causes the execution to reach an `assume false` if false.

It seems that the generated program is not accepted (by default) by the Boogie verifier because of the way it removes back-edges and that the whole verification pipeline is sound. So this behavior might be intentional ?
I feel that this should be mentioned somewhere and warnings associated with the Boogie options which might break the global soundness.

**Comment by RustanLeino** [comment]
You are right that Boogie's `/loopUnroll` option is not sound for Dafny. I agree that this would be a good thing to document somewhere.

If you're curious, the reason for introducing the `$w$loop` variable in the translation from Dafny to Boogie is to let Boogie be the one to compute syntactic loop targets.
