### ISSUE TITLE
Java compiler crashes on extern class with extern constructor

### ISSUE THREAD

**Issue by mschlaipfer** [dafny-lang/dafny#1129]
The following code crashes on the 3.0 release version with `dafny /compileTarget:java`

```dafny
module M {
  module Inner {
    import Test
    datatype T = Inner(test: Test.T)
  }

  module Test {
    class {:extern} T { 
      constructor {:extern} (name: string)
    }
  }
}
```

I'm not providing the extern code yet, though. I also find it curious that the stack trace refers to "/Users/leino" (and the prerelease 2 version refers to "davidcok"):

```
<snip>
```

**Comment by mschlaipfer** [comment]
Probably just an unhandled error, I assume the error itself is correct and I resolved it by adding an extern to the `Test` module and adding the extern Java code

```java
package Test_Compile;

public class T {
  public T (String name) {
  }
}
```

and adding the Java file as a command line parameter

**Comment by RustanLeino** [comment]
> I'm not providing the extern code yet, though. I also find it curious that the stack trace refers to "/Users/leino" (and the prerelease 2 version refers to "davidcok")

:O
