### ISSUE TITLE
Datatype const members' definitions are inlined into triggers in Boogie

### ISSUE THREAD

**Issue by tchajed** [dafny-lang/dafny#1150]
Let's say you have a `const` field in a datatype:

```dfy
module ConstBug {
  datatype Foo = Foo(x: nat)
  {
    const good?: bool := 0 < x < 5;
  }

  method Test()
  {
    var x := Foo(2);
    assert x.good?;
  }
}
```

This produces Boogie including this (using `dafny /noNLarith /arith:5 /print:tmp.bpl /noVerify const.dfy`):

```boogie
function {:inline} ConstBug.Foo.good_q(this: DatatypeType) : bool
{
  INTERNAL_lt_boogie(0, ConstBug.Foo.x(this))
     && INTERNAL_lt_boogie(ConstBug.Foo.x(this), 5)
}

// Foo.good?: Type axiom
axiom 2 < $FunctionContextHeight
   ==> (forall $o: DatatypeType :: 
    { ConstBug.Foo.good_q($o) } 
    $Is(ConstBug.Foo.good_q($o), TBool));

```

Notice that the entire body of `good_q` is now a pattern; this includes `INTERNAL_lt_boogie` and `&&`, which triggers a Z3 warning with `/proverWarnings:1`, `'and' cannot be used in patterns`.

@wilcoxjay tells me that this is a bug in Dafny. This behavior is responsible for most of the performance problems that James found and fixed in https://github.com/mit-pdos/dafny-jrnl/pull/2. I can't come up with a small reproducible example, but basically the body of the const in that case was a really bad trigger.

**Comment by wilcoxjay** [comment]
It looks like a bug to me, but I only kinda know what I'm talking about, so that doesn't guarantee it's really a bug!

**Comment by wilcoxjay** [comment]
If you pass `/proverWarnings:1` you can see a bunch of Z3 warnings that stem from this bug.

**Comment by tchajed** [comment]
Update: I added some more complexity to this example in order to trigger the Z3 warning.
