### ISSUE TITLE
`error CS0103: The name '_default_T' does not exist in the current context`

### ISSUE THREAD

**Issue by hmijail** [dafny-lang/dafny#1151]
I'm not sure if this is me missing something in my C# code, or a bug in Dafny?

```
$ dafny /compile:1  types.dfy concrete_types.cs                  

Dafny program verifier finished with 0 verified, 0 errors
Wrote textual form of target program to types.cs
Errors compiling program into types
(1780,51): error CS0103: The name '_default_T' does not exist in the current context
```

Adding `/spillTargetCode:1` shows that indeed the generated code uses `_default_T` without declaring it.

File types.dfy:
```dafny
module {:extern "M"} M {
    type {:extern "T"} T
    datatype D = D (
        T: T
    )
}
```

File concrete_types.cs:
```csharp
namespace M {
    public class T {
    }
}
```

**Comment by saltiniroberto** [comment]
The main issue here (I work with @hmijail ) is that `types.dfy` above is compiled to the following C# code,
```C#
namespace M {
...

  public class D {

    private static readonly D theDefault = create(_default_T);
...
```
which, in order to be compiled, requires to have `_default_T` defined in the `namespace M`. 
However, I am not aware of any way that this can be done in C#.

**Comment by RustanLeino** [comment]
I fixed the problem, but
* only in C#
* only for opaque types that don't take type parameters
* no special initializer is called even if the opaque type is declared as auto-init (that is, with type characteristic `(0)`)

If you're okay with divulging that `T` is a class, then you can change its declaration to
``` dafny
class {:extern "T"} T { }
```
By declaring an export set, you can still hide from module `M`'s clients the fact that `T` is a reference type:

``` dafny
module {:extern "M"} M {
  export
    provides T
    reveals D

  class {:extern "T"} T { }
  datatype D = D(t: T)
}
```
However, if `T` really is a class like this, you will not be able to write unbounded quantifications over `T` (which is usually not a problem).
