### ISSUE TITLE
Map-domain-equality verification fails despite manual proof

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#1158]
The following program tries to prove the sets `a.Keys` and `b.Keys` to be equal. It gives a proof that shows that the sets are element-wise equal. Nevertheless, the verifier complains that the sets may not be equal.

``` dafny
type Id(==)

function F(s: set<Id>): int

lemma Test(x: Id)
{
  var X := {x};
  var a := map i | i <= X :: F(i);
  var b := map[{} := F({}), X := F(X)];

  assert a.Keys == b.Keys by {  // spurious error reported here
    forall i
      ensures i in a.Keys <==> i in b.Keys
    {
      calc {
        i in a.Keys;
      ==
        i <= X;
      ==  { assert i <= X <==> i == {} || i == X; }
        i in b.Keys;
      }
    }
  }
}
```

**Comment by tjhance** [comment]
This might be related (been meaning to file an issue for this)

```
lemma foo(a: seq<int>, i: int, j: int, k: int, l: int)
requires 0 <= i <= j < |a|
requires 0 <= k <= l <= j-i
{
  var x := a[i..j][k..l];
  var y := a[i+k .. i+l];

  assert |x| == |y|;
  forall t | 0 <= t < |x|
  ensures x[t] == y[t]
  {
  }

  assert x == y; // assertion fails
}
```

**Comment by RustanLeino** [comment]
@tjhance Sorry, I closed this issue before responding.

Your issue is indeed similar (both have to do with the way Dafny boxes container elements), but not solved by the same fix as for map. Please file as a separate issue.

In the meantime, you can work around the problem by using a `seq<T>` (where `T` is type parameter) instead of `seq<int>`:

``` dafny
lemma foo<T>(a: seq<T>, i: int, j: int, k: int, l: int)
  requires 0 <= i <= j < |a|
  requires 0 <= k <= l <= j-i
{
  // ta dah!
}
```
