### ISSUE TITLE
Trigger selection for map/set comprehensions leads to invalid Boogie triggers

### ISSUE THREAD

**Issue by parno** [dafny-lang/dafny#1165]
In the snippet below, either comprehension will result in a Boogie error `Error: boolean operators are not allowed in triggers`.  
```
predicate P()

function Test(s0:set<int>, s1:set<int>) : bool {
  var m := map key | (key in (s0 + s1)) && P() :: true;
  //var m := set key | (key in (s0 + s1)) && P() :: key;
  true
}
```
The problem in the Boogie file is in the definition axiom for `Test`, which looks like:
```
// definition axiom for _module.__default.Test (revealed)
axiom 1 <= $FunctionContextHeight
   ==> (forall s0#0: Set Box, s1#0: Set Box :: 
    { _module.__default.Test(s0#0, s1#0) } 
    _module.__default.Test#canCall(s0#0, s1#0)
         || (1 != $FunctionContextHeight && $Is(s0#0, TSet(TInt)) && $Is(s1#0, TSet(TInt)))
       ==> (forall key#0: int :: 
          { s0#0[$Box(key#0)] || s1#0[$Box(key#0)] } 
          s0#0[$Box(key#0)] || s1#0[$Box(key#0)] ==> _module.__default.P#canCall())
         && _module.__default.Test(s0#0, s1#0)
           == (var m#0 := Map#Glue((lambda $w#0: Box :: 
                  $IsBox($w#0, TInt) && (s0#0[$w#0] || s1#0[$w#0]) && _module.__default.P()), 
                (lambda $w#0: Box :: $Box(Lit(true))), 
                TMap(TInt, TBool)); 
            Lit(true)));
```
Note that Dafny created a trigger of `s0#0[$Box(key#0)] || s1#0[$Box(key#0)]`, i.e., one that includes a logical OR `||`.  

The inclusion of the `&& P()` seems important.  Without it, everything translates correctly.  In particular, without it, the quantifier over `key#0` isn't introduced (because we don't need the canCall check any more?).

This recent commit: https://github.com/dafny-lang/dafny/commit/ccc6d146eb7cec7dc99b0a5da7344f4921babd5b appears to be the culprit, as the bug doesn't manifest in its parent (3d9e476), but it does manifest as soon as I advance to ccc6d14.

**Comment by RustanLeino** [comment]
The problem manifests only when there are parentheses around `s0 + s1`. It seems `RewriteInExpr` in the recent commit doesn't cover that case.
