### ISSUE TITLE
Feature request: named arguments and default parameter values

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#1189]
These features always make for more self-documenting code, fewer mistakes in passing arguments in the wrong order, and being able to add new optional parameters to existing declarations without breaking existing call sites.

There is tons of precedent for this in "modern" languages (Python, Kotlin, Scala, C#, ...) and they have very consistent requirements:

1. Declarations must declare all required parameters before any optional parameters.
2. Call sites must declare all positional arguments before any named arguments.

The proposed syntax would be:

```dafny
method Foo(a: int, b: int, c: int := 0, d: int := 42) {
  // ...
}

method Main() {
  Foo(1, 2);                      // == Foo(1, 2, 0, 42)
  Foo(b := 2, a := 1);            // == Foo(1, 2, 0, 42)
  Foo(1, 2, 3);                   // == Foo(1, 2, 3, 42)
  Foo(1, 2, d := 3);              // == Foo(1, 2, 0, 3)
  Foo(1, c := 3, d := 4, b := 2); // == Foo(1, 2, 3, 4)

  Foo(d := 3);                    // Error: a and b not provided
  Foo(1, c := 2, d := 3);         // Error: b not provided
  Foo(a := 1, 2, c := 2, d := 3); // Error: positional argument after named argument
}
```

This pattern applies equally well to any language construct that declares a named list of parameters: methods, constructors, functions, datatype constructors, lemmas, etc. Personally I'm most interested in datatype constructors, but I suspect implementing this for one construct is not much less effort than most/all of them.

For consistency with the rest of Dafny, I submit that the RHS of both parameter declarations with defaults and named arguments must be expressions. That is, method invocations would not be allowed.

**Comment by RustanLeino** [comment]
I like it.

Personal nostalgia: Modula-3, which predates all the languages mentioned above, also had this feature. Even with the `:=` syntax. :)

**Comment by robin-aws** [comment]
Yes I should rephrase a little: I meant to claim that many modern languages are including this feature, certainly not that they came up with it for the first time. :)

**Comment by tchajed** [comment]
I like this feature, too.

I have a hack for named arguments if I really need it: use a struct with a dummy default value, then update all of its fields with the setter syntax `r.(f := v)`. For example, see https://github.com/mit-pdos/dafny-nfsd/blob/45075dadeedc1cdf104d1d324e18fa0e323604b8/src/fs/dir_fs.dfy#L1742-L1744:

```dfy
r := Fsstat3.zero;
r := r.(tbytes := tbytes).(fbytes := fbytes);
r := r.(tfiles := tfiles).(ffiles := ffiles);
```

**Comment by robin-aws** [comment]
I've realized there's an issue with the way I've specified this feature, specifically related to the goal of not breaking existing call sites when adding new parameters. Because callers can still provide positional arguments to parameters with defaults, it's still possible to break existing call sites by adding new parameters anywhere other than the end of the parameter list:

```dafny
// Before:
method Foo(a: int, c: int := 0) {
  // ...
}
// After:
method Foo(a:int, b: int := 0, c: int := 0) {
  // ...
}

// Different semantics before vs. after.
// Before: a := 1, c := 2
// After: a := 1, b := 2, c := 0
Foo(1, 2);
```

There is a feature in Python, for example, that supports specifying keyword-only arguments: https://www.python.org/dev/peps/pep-3102/ We need something similar here, although I'm not yet sure what syntax to propose.

**Comment by RustanLeino** [comment]
If Dafny were to support variable number of arguments, it could adopt a solution for named arguments like that in Python. (Side note: At the moment, variable number of arguments are best done by putting square brackets around the arguments and passing them as a `seq`.)

If Dafny were to support the `a,c` -> `a,b,c` case above, then some new syntax is needed, maybe through some kind of adornment. Even with additional syntax, I find it likely that we'd want the simpler syntax to be the one originally proposed.

Therefore, I suggest we can steam ahead with the original proposal for now. It seems amenable to changes that could in the future allow both variable number of arguments and keyword-only arguments.

**Comment by robin-aws** [comment]
True, specifying default values should be fully orthogonal to whether a parameter can be provided by position, keyword, or both. This request can be completed as designed, as I agree the simple syntax is just too natural and appealing, and I will cut a follow-up request to support keyword-only parameters somehow.

(Side note response: I suspect varargs are not super desirable in Dafny given its strong typing, and that the syntax for sequence literals is very lightweight, but I certainly have no objection to them if someone wants them badly enough!)

**Comment by RustanLeino** [comment]
While other languages do have the requirement

> Declarations must declare all required parameters before any optional parameters.

there's no need to have it. For example, a method declared as

``` dafny
method M(x: int := 100, y: int, z: int := 200)
```

can still be called, as long as `y` is passed by keyword. The following calls all make sense:

``` dafny
M(2, 3, 5);
M(2, 3);
M(y := 3, x := 2);
M(z := 5, x := 2, y := 3);
```

Is there a good reason to forbid it?

**Comment by RustanLeino** [comment]
One more example:

``` dafny
M(y := 3);
```
