### ISSUE TITLE
Dafny crash when refining imported module

### ISSUE THREAD

**Issue by erniecohen** [dafny-lang/dafny#1203]
The following gets the error "Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Microsoft.Dafny.AliasModuleDecl' to type 'Microsoft.Dafny.LiteralModuleDecl'.
   at Microsoft.Dafny.ModuleQualifiedId.Set(ModuleDecl m) in /Users/leino/Source/dafny/Source/Dafny/DafnyAst.cs:line 3907  ...
```
module A {}
module B {
    import C = A    
    module D refines C {}
}
```

**Comment by davidcok** [comment]
Closed because this example no longer fails.
