### ISSUE TITLE
Feature request: 'Or' patterns

### ISSUE THREAD

**Issue by seanmcl** [dafny-lang/dafny#1205]
Or patterns would be nice to have.  For example, to write the code below without them we'd need helper methods which adds to syntactic noise.  

```
function method foo(doc: Doc): nat {
    match doc
      case Empty | Line => something complicated
      case X1 | X2 | X3 => something else complicated
  }
```

**Comment by stefan-aws** [comment]
Support was added in https://github.com/dafny-lang/dafny/pull/2448
