### ISSUE TITLE
Error: Boolean operators are not allowed in triggers

### ISSUE THREAD

**Issue by Raghavendra80** [dafny-lang/dafny#1207]
I updated Dafny to 3.1.0, and I now get this error

Error: boolean operators are not allowed in triggers

on even a simple thing like

requires forall a:set<T>, b:set<T> :: a <= b ==> a < b

where no triggers are specified. I noticed these errors only when there is an implication involved.

**Comment by RustanLeino** [comment]
Thanks for the bug report. As a temporary workaround, you can change `a < b` to `a <= b && !(b <= a)`.
