### ISSUE TITLE
type cardinality paradox & extern types

### ISSUE THREAD

**Issue by tjhance** [dafny-lang/dafny#1216]
Okay ... I'm not a super-expert on my type-theoretic paradoxes, but I think there needs to be some kind of error in this situation:

```
module M {
  type {:extern} T<!X>

  datatype A = A(s: T<A>) | B // Problem: No error message here
}
```

If the type `T` were instantiated (externally) as `T -> nat`, it would cause a paradox. Dafny _does_ correctly give an error message for the case where you actually instantiate T (and a rather fun error message at that):

```
module M {
  type T<!X> = T -> nat

  datatype A = A(s: T<A>) | B // Error: using the type being defined ('A') here violates strict positivity, that is, it would cause a logical inconsistency by defining a type whose cardinality exceeds itself (like the Continuum Transfunctioner, you might say its power would then be exceeded only by its mystery)
}
```

Anyway, as far as I know, it's only a problem when dealing with `:extern` types. You can make a similar example with abstract modules, although one might or might not call it a bug (Dafny gives an error only when you create the refining module)

```
abstract module M {
  type T<!X>

  datatype A = A(s: T<A>) | B
}

module M' refines M {
  type T<!X> = X -> nat // Error is here (but no earlier)
}
```

**Comment by typerSniper** [comment]
Hey @tjhance, 

You are right that this may lead to a paradox. However, Dafny does give an error message when I write

```
module M {
  type {:extern} T<!X>

  datatype A = A(s: T<A>) | B  // Correction: there is an error message here.
}
```

Let me know if you had something else in mind, or if I missed something!

**Comment by typerSniper** [comment]
Thanks for the suggestion. I am working on it. (I don't know if the fix was an accident)

**Comment by keyboardDrummer** [comment]
@tjhance Would you mind undoing the accidental fix commit and seeing if this lets the build pass? @RustanLeino has recently added regression tests related to strict and permissions variance.

**Comment by typerSniper** [comment]
I added the "intentional" solution in this commit: 
[https://github.com/dafny-lang/dafny/commit/6d6e6ae458947bab449d2bfdb6fc5a12eb911a1a](url)

The issue can be closed.

**Comment by keyboardDrummer** [comment]
Your link has the wrong address ^^
https://github.com/dafny-lang/dafny/commit/6d6e6ae458947bab449d2bfdb6fc5a12eb911a1a
