### ISSUE TITLE
Feature request: named-only parameters, shorthand named arguments

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#1243]
Follow-up to https://github.com/dafny-lang/dafny/issues/1189.

Now that we have named argument passing, it is highly desirable to specify that some (or all) parameters to a callable entity can ONLY accept named arguments, and not positional. This supports the ability to add new parameters with default values anywhere in the parameter list without breaking existing call sites.

My straw-person proposal for the syntax is as follows:

```dafny
method Foo(a: int, b: int, c: int := 0, named d: int := 42) {
  // ...
}

method Main() {
  Foo(1, 2);                      // == Foo(1, 2, 0, 42)
  Foo(b := 2, a := 1);            // == Foo(1, 2, 0, 42)
  Foo(1, 2, 3);                   // == Foo(1, 2, 3, 42)
  Foo(1, 2, d := 3);              // == Foo(1, 2, 0, 3)
  Foo(1, c := 3, d := 4, b := 2); // == Foo(1, 2, 3, 4)

  Foo(d := 3);                    // Error: a and b not provided
  Foo(1, c := 2, d := 3);         // Error: b not provided
  Foo(a := 1, 2, c := 2, d := 3); // Error: positional argument after named argument
  Foo(1, 2, 3, 4);                // Error: d does not allow positional arguments
}
```

I considered using some kind of symbol to indicate named-only parameters, but I think a pseudo-keyword here is not too much typing and hopefully clearer.

The other feature I'd love to include as well is inspired by JavaScript's "shorthand properties" syntax (see https://262.ecma-international.org/6.0/#sec-object-initializer):

```javascript
const a = 'foo';
const b = 42;
const c = {};
const object = { a, b, c, d: 5 };  // == { a: a, b: b, c: c, d: 5 }
```

This really cuts down on repetition when you tend to use the same symbol to refer to the same values in multiple scopes. I'm less sure here what syntax to suggest for Dafny; the JavaScript syntax won't work because that looks like positional arguments instead. Here are a few options:

```dafny
method Foo(a: int, b: int, c: int := 0) {
  // ...
}
var a = "foo";
var b = 42;
var c = [];

Foo(:a=, :b=, :c=);   // Derived by putting the symbol "inside" the :=
Foo([a], [b], [c]);   // Meant to look like array or map dereferencing, to suggest looking up the symbol in the calling scope
// ???
// Profit!
```

**Comment by seebees** [comment]
For posterity, I suggest `Foo(:={ a, b, c});`

**Comment by robin-aws** [comment]
Nice, I just went off on a tangent and arrived at almost the same variation. :)

```dafny
Foo(* := {a, b, c});  // == Foo(a := a, b := b, c := c);

// Also sensible to support it in map displays. 
// Produces a map<string, T> where T is the unification of the types of all LHS symbols
// (as per the desugaring).
var myMap := map[* := {a, b, c}];  // == map[a := a, b := b, c := c]
```

I suggest the `*` on the LHS just to distance the syntax a little further from Update with Failure statements, which also kind of look like assignment statements with a missing LHS (`:- SomeExpression(a, b, c);`). It also implies the fact that multiple LHS symbols are produced in the desugared semantics.

**Comment by robin-aws** [comment]
I should explicitly write down an alternative approach that I already rejected, for posterity or possibly to be convinced it's the right approach after all!

This alternative approach involves two separate features, which when used together achieves a similar shorthand syntax:

1. Allow a syntax similar to Javascript's shorthand properties in map displays. E.g.:

   ```dafny
   map[a, b, c] // == map["a" := a, "b" := b, "c" := c]
   ```

2. Allow splatting callable arguments from map values, similar to Python's keyword argument splatting:

   ```dafny
   Foo(**map[a, b, c])
   ```

This could be technically possible, but there are multiple disadvantages compared to a syntax that is localized to the invocation of callable features:

1. Dafny does not currently have a common "any" supertype for all types, so most combinations of arguments will not be valid map displays. This expression fails to type check, for example, with the error "All elements of display must have some common supertype (got int, but needed type or type of previous elements is seq<char>)": `map["name" := "Robin", "age" := 40]`
2. As shown by the map display examples above, quotes are necessary on the argument names, which is unfortunate (I missed them originally but have corrected them).
3. Relying on splatting of arbitrary map values means reifying argument maps at runtime, which is a performance hit. It can be avoided through compiler optimization in the specify case of a map display, but this adds complexity and performance regressions when refactoring that will likely surprise users.

Some of these disadvantages could be avoided by adding record types and using them for argument bindings instead, but that would be a major and deep feature I wouldn't want to add just to support this one.

**Comment by robin-aws** [comment]
An alternative syntax for named-only parameters:

```dafny
method Foo(a: int, b: int, c: int := 0, [d]: int := 42, [e]: string := "") {
  // ...
}
```

Even though the original version wouldn't require `named` to be a fully-reserved keyword, I'm not a fan of making words reserved in only some locations, because simplistic syntax highlighters don't tend to handle that well. I'd prefer to avoid any new keywords here if possible.

**Comment by seebees** [comment]
From offline conversation, some notes

The `<:=` operator could be used.
This would all be syntactic sugar.
Everything below relies on the structural names being the same.

Some examples of pushing values in:

```dafny
datatype Foo := Foo(a: int, b: string, c: map<string, string>)
datatype Bar := Bar(a: int, b: string, c: map<string, string>)

var a := 5
var b := "asdf"
var c := map{ "some": "thing"}

var myBar := Bar( <:= { a, b, c } )
var myFoo := Foo( <:= myBar )
```

But it could also be used to pluck values out.
Getting a variable from an object involves naming the variable,
and deraferanceing the same property off of the object
e.g. `id = obj.id`.

```dafny
method Baz(obj: Foo): int {
  var a <:= obj
  return Bar(<:= { a }, <:= { b, c } <:= obj )
}

var a, b, c <:= Baz(obj)
```

**Comment by seebees** [comment]
Thinking about this more, is this large enough that we should move this to a Dafny RFC (https://github.com/dafny-lang/rfcs)?

**Comment by robin-aws** [comment]
I just realized I didn't respond to this earlier, sorry about that. Yes, I think the `<:=` operator deserves a proper RFC before moving ahead with implementing it.

I'm hoping the "named-only parameter" syntax is less controversial though. @RustanLeino what do you think?

**Comment by RustanLeino** [comment]
A detailed RFC may change my mind about the third point.

**Comment by robin-aws** [comment]
Yeah, I agree that `[a]` might look too optional. We can discuss the syntax more on the #1261 PR since that's open now.
