### ISSUE TITLE
Building on Ubuntu fails

### ISSUE THREAD

**Issue by bara1980** [dafny-lang/dafny#127]
Just following the instructions from INSTALL.md and it turns out by default the build fails, updating the projects to use .NET framework v4.5 fixes the build (see this SO question: https://stackoverflow.com/questions/42913418/xbuild-dafny-on-linux-cs0518-error).

**Comment by bara1980** [comment]
Commit on my fork here: https://github.com/bara1980/dafny/commit/fb0d355b22bf8a522dee06f849f7930659541cd3
Have not been able to run the tests (getting a pile of errors when writing a file), as soon as I figure that out I'll send out a merge request.

**Comment by RustanLeino** [comment]
Nice. Thanks!
