### ISSUE TITLE
Documentation of `{:opaque}` doesn't match the implementation

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/dafny#1295]
[The documentation of `{:opaque}`](https://dafny-lang.github.io/dafny/DafnyRef/DafnyRef#sec-opaque) describes the attribute `opaque_full` even though that doesn't occur in the Dafny codebase. There are also two unused dictionaries in the codebase:

```
    protected Dictionary<Function, Function> fullVersion; // Given an opaque function, retrieve the full
    protected Dictionary<Function, Function> original;    // Given a full version of an opaque function, find the original opaque version
```

Was the `opaque` feature finished? Is using it currently any different than annotating a method with `{:fuel 0,0}` ?

**Comment by MikaelMayer** [comment]
I removed these two extra fields and updated the documentation to reveal that we no longer actually duplicate the original functions (if ever we did that), so `opaque_full` is no longer needed.
I made it clear that the fuel which used to be a constant is now a variable that the internal `reveal_*` lemma provide an axiom for.
