### ISSUE TITLE
Does subset-type constraint use z3?

### ISSUE THREAD

**Issue by adsharma** [dafny-lang/dafny#1323]
I'm trying to figure out how this is implemented in dafny:

```
type u8 = x: int | 0 <= x < 255
type u16 = x: int | 0 <= x < 65536
```

Are these verified by z3? Or are they verified by some other code and then the rest passed to z3 for verification?

The reason I ask is that I'm having trouble getting z3 to solve simple constraints:

https://github.com/Z3Prover/z3/discussions/5428

Some of the stackoverflow discussion suggests that z3 is not good at doing this and some other tool should be used instead.

My understanding is that z3 uses a variety of tools/tactics. So why not make this a new tactic?

**Comment by keyboardDrummer** [comment]
> I'm trying to figure out how this is implemented in dafny

Dafny verifies its programs by translating each Dafny module into a Boogie program, which is then translated to a Z3 script. You find out how your initial program is mapped to to Z3 by using Dafny's `/print` option to print the Boogie program and the `/providerLog` option to print the Z3 script.

**Comment by adsharma** [comment]
Thank you. I think you meant `/proverLog`. I was able to run it against:

```
type u8 = x: int | 0 <= x < 255
type u16 = x: int | 0 <= x < 65536

method Add(x: u8, y: u8) returns (r: u8)

{
  r := x+y;
}
```

But it spit out a 11k line z3 script :) I think the key constraint in the output file is:

```
(assert (forall ((|x#0@@1| T@U) ) (!  (=> (= (type |x#0@@1|) intType) (= ($Is |x#0@@1| Tclass._module.u8)  (and (<= (LitInt 0) (U_2_int |x#0@@1|)) (< (U_2_int |x#0@@1|) 255))))
 :qid |unknown.0:0|
 :skolemid |481|
 :pattern ( ($Is |x#0@@1| Tclass._module.u8))
)))
```

A simplified/human readable version of the above would be greatly helpful for me to make forward progress.

**Comment by keyboardDrummer** [comment]
> A simplified/human readable version of the above would be greatly helpful for me to make forward progress.

That seems useful to me too, but Dafny doesn't have that feature (yet). @typerSniper any comments?

**Comment by adsharma** [comment]
I think the minimal z3 script is something along the lines of:

```
from z3 import *

mytype = Datatype('Type')
mytype.declare("u8", ("u8val", IntSort()))
mytype.declare("u16", ("u16val", IntSort()))
m = mytype.create()
u8 = m.u8
u16 = m.u16
u8val = m.u8val
u16val = m.u16val

i = Int("i")
i1 = Int("i1")
i2 = Int("i2")

axioms = [
  ForAll(i, u8val(u8(i)) == i, patterns = [u8val(u8(i))]),
  ForAll(i, u16val(u16(i)) == i, patterns = [u16val(u16(i))]),
  ForAll(i, Implies(m.is_u8(u8(i)), And(0 <= i, i < (1 << 8))), patterns = [u8(i)]),
  ForAll(i, Implies(m.is_u16(u16(i)), And(0 <= i, i < (1 << 16))), patterns = [u16(i)]),
  ForAll([i1, i2], Implies(And(m.is_u8(u8(i1)), m.is_u8(u8(i2))), m.is_u8(u8(i1 + i2))), patterns = [MultiPattern(u8(i1), u8(i2))]),
]

s = Solver()
#s.set(auto_config=False, mbqi=False)
result = s.check(*axioms)
print(result)
print(s.model())
```

While this prints `unsat`, if I changed the last assertion to 

```
Implies(And(m.is_u8(u8(i1)), m.is_u8(u8(i2))), m.is_u16(u16(i1 + i2)))
```

I expect it to print `sat`, but still doesn't work. Any hints on what I'm doing wrong would be great.

**Comment by NikolajBjorner** [comment]
This is already unsat:
```
  ForAll(i, Implies(m.is_u8(u8(i)), And(0 <= i, i < (1 << 8))), patterns = [u8(i)]),

```
ADT theory has m.is_u8(u8(i))) hold for every i, including i = 300
So instantiate with i := 300 and you get the contradiction.

**Comment by adsharma** [comment]
Is this a better formulation then?

```
axioms = [
  ForAll(ub, Implies(m.is_u8(ub), And(0 <= u8val(ub), u8val(ub) < (1 << 8))), patterns=[u8val(ub)]),
  ForAll(us, Implies(m.is_u16(us), And(0 <= u16val(us), u16val(us) < (1 << 16))), patterns=[u16val(us)]),
  ForAll(i, Implies(m.is_u8(ub), u8val(u8(i)) == i), patterns = [u8val(u8(i))]),
  ForAll(i, Implies(m.is_u16(us), u16val(u16(i)) == i), patterns = [u16val(u16(i))]),
  u8val(ub) == 100,
  m.is_u8(ub),
  u16val(us) == 300,
  m.is_u16(us),
]


z3.solve(*axioms, auto_config=False, mbqi=False, show=True)
```

Am I doing something wrong with patterns here? How can I get the solver to find [ub=u8(100), us=u16(300)] which satisfies all constraints?

**Comment by adsharma** [comment]
Perhaps you meant the problem is on this line:

> mytype.declare("u8", ("u8val", IntSort()))

I noticed that dafny/boogie don't use IntSort(). They create two separate sorts `T@U` and `T@T` and define functions to convert between the two. Is that what you were suggesting?

**Comment by adsharma** [comment]
I wrote a script to minimize the 11k z3 script to ~100 lines, while producing the same `unsat` output:

https://paste.ubuntu.com/p/6GrfvsPf6t/

I've used constants 1234 and 2468 instead of 255 and 65536, so they're easy to find in the z3 script.
I've removed all the correctness checks around heap allocations failing etc, trying to focus on just the math and fixed width types.

Hopefully this is useful to the next language implementer trying to leverage z3 for correctness checks.

One of the constraints for me is that I'm starting from typpete (my fork here: https://github.com/adsharma/Typpete) which is already using datatypes in a certain way vs starting from scratch (in which case I would try to emulate what dafny/boogie do more closely).

Thank you for any more hints/advice.

**Comment by adsharma** [comment]
I hacked on typpete a bit more in my fork: https://github.com/adsharma/Typpete

* It can now produce s-expression output that can be fed to `z3 -smt2` or sent to pastebin for further analysis.
* I've extended the type hierarchy here to make fixed width ints subtypes of `int`, which is a subtype of `float`/`complex` etc.
https://github.com/adsharma/Typpete/blob/master/typpete/src/constants.py (format: subtype: [list-of-supertypes])
* All of the fixed width integer support is now in one commit: https://github.com/adsharma/Typpete/commit/050bd30a90781d6689a1969c569992b9a5005a31

In doing so, I've leveraged existing typpete code to generate subtype constraints. So there is a good chance that the subtype and the `ForAll` constraints are right.

```
$ cat test.py
def foo():
    a: u8 = 300
$ typpete -l DEBUG --sexpression test.py
$ cat inference_output/test_constraints_log.txt | pastebinit
https://paste.ubuntu.com/p/RKXzNd4MW5/
```

produced https://paste.ubuntu.com/p/RKXzNd4MW5/.

```
$ z3 -smt2 inference_output/test_constraints_log.txt
unknown
```

I was expecting it to print `unsat`, since 300 > 255 in `assertion_bool_189`. But it's possible that I have gotten that one assertion wrong. Any hints or working examples highly appreciated.

**Comment by adsharma** [comment]
https://paste.ubuntu.com/p/Jc4f9KKbmP/  and https://github.com/adsharma/Typpete/commit/38068caab098616dd5956affe07a491f181180e6 work for me.
