### ISSUE TITLE
/useArrayTheory crash

### ISSUE THREAD

**Issue by croizier** [dafny-lang/dafny#136]
Dafny 1.9.9.40414 (Windows) crashes on any program that processes an array, for instance `function len(a: array<int>): int requires a != null { a.Length }`, producing a stacktrace starting at TypeErasure.cs:702.

BTW, what benefits can we expect from Z3 array theory?

**Comment by seanmcl** [comment]
Not enough info to address this.  Please reopen if you still have an issue and include code that crashes.
