### ISSUE TITLE
set comprehension not allowed in function definition, contradicting manual

### ISSUE THREAD

**Issue by erniecohen** [dafny-lang/dafny#1366]
The following code gets the error "a set comprehension involved in a function definition is not allowed to depend on the set of allocated references, but values of 'o' may contain references", even though the manual explicitly states that the expression used is allowed within ghost contexts (which should include function definitions):
```
function obs():set<object> { set o:object | true }
```

**Comment by MikaelMayer** [comment]
> Why is `set i: int | true :: P(i)` known to be finite (from the previous paragraph), but `set i: int | P(i)` isn't?

`set i: int | true :: P(i)` is a `set<bool>`, which by definition is finite. However, it might not be computable (if for example `P(i)` tests whether there is a Fibonacci cycle of length at most i starting at i)
`set i: int | P(i)` == `set i: int | P(i) :: i`, which is a potentially infinite set of integer
