### ISSUE TITLE
Go: bug in multiple occurrences of the same key in map

### ISSUE THREAD

**Issue by sorawee** [dafny-lang/dafny#1367]
```
method Main () 
{
  var e := map[1 := false, 1 := true];
  print e == e;
}
```

prints `false` in Go.

**Comment by sorawee** [comment]
The data representation of `map` in Go makes multiple occurrences difficult to get right (or efficient, for that matter), since it's just a list of key value pairs, with no invariant that keys are distinct.

**Comment by sorawee** [comment]
Actually, this also affects JS:

```
method Main() {
  print |map[1 := 2, 1 := 3]|;
}
```

prints `2`.

**Comment by RustanLeino** [comment]
Thanks for pointing out this bug. I think the language ought not to allow this case. That is, I think the verifier should check that the keys given in the map display expressions are distinct.

**Comment by ShubhamChaturvedi7** [comment]
This also leads to inconsistency when converting from `dafny.Map` to Go native `map` where the last value in the array is written into the Go map.
