### ISSUE TITLE
refinement of nested imported module crashes verifier

### ISSUE THREAD

**Issue by erniecohen** [dafny-lang/dafny#1381]
The following gets the exception "Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Microsoft.Dafny.AliasModuleDecl' to type 'Microsoft.Dafny.LiteralModuleDecl'.":
```
module A { 
    module B {}
}
import C = A.B
module D refines C {}
```

**Comment by MikaelMayer** [comment]
I fixed it some time ago already.
https://github.com/dafny-lang/dafny/pull/2993
