### ISSUE TITLE
Possible grammatical error in FAQ

### ISSUE THREAD

**Issue by user454322** [dafny-lang/dafny#1404]
The [dafny-lang/dafny FAQ page](https://github.com/dafny-lang/dafny/wiki/FAQ) reads

> As a result, Dafny sometimes reports verification-time errors on programs are correct on every run-time execution. 

Is _that_ missing between _programs_ and _are_?
So it reads  
 _As a result, Dafny sometimes reports verification-time errors on programs_ **that** _are correct on every run-time execution._

**Comment by keyboardDrummer** [comment]
Updated, thanks.
