### ISSUE TITLE
Unable to produce EXE on Mac

### ISSUE THREAD

**Issue by potanin** [dafny-lang/dafny#1417]
Using the latest macOS and got Dafny from "brew":

alex@taniwha Research/Dafny % dafny /version
Dafny 3.2.0.30713

Trying trivial program:

alex@taniwha Research/Dafny % cat Main.dfy
method Main() {
    print "Hello";
}

But what is produced is Main.dll while I expect Main.exe as there is a Main method?

alex@taniwha Research/Dafny % dafny Main.dfy

Dafny program verifier finished with 0 verified, 0 errors
Compiled assembly into Main.dll
alex@taniwha Research/Dafny %

**Comment by potanin** [comment]
Of note, the non-obvious "/compiler 4" way still works fine. :)

alex@taniwha Research/Dafny % dafny Main.dfy /compile 4 

Dafny program verifier finished with 0 verified, 0 errors
Running...

Hello

**Comment by keyboardDrummer** [comment]
Have you tried running `Main.dll` with `dotnet Main.dll` ?

**Comment by potanin** [comment]
Yes, that works "dotnet Main.dll". Perhaps a new version can add a message like "output runnable dll, use "donnet"" or something like that so that one doesn't think something as wrong as much of the older documentation online mentions that it will generate "exe". :) Thanks!

**Comment by keyboardDrummer** [comment]
Seems like the reference manual documentation for the command line options ([here](https://dafny-lang.github.io/dafny/DafnyRef/DafnyRef#sec-command-line-options)) is not in sync with the built in command line option documentation.
