### ISSUE TITLE
Feature request: ghost const

### ISSUE THREAD

**Issue by tjhance** [dafny-lang/dafny#1424]
Title pretty much says it all, it would be nice to do this sometimes:

```
ghost const x := ...
```

to signal that `x` is only used in proof code. There's already an easy workaround:

```
function x() { ... }
```

But consts are a little easier on the eyes.

**Comment by erniecohen** [comment]
You just need to provide the type for x:
```
ghost const x:nat := 3
```

**Comment by tjhance** [comment]
Hm... I dunno what happened, I could have sworn it wasn't working when I tried it yesterday!

My bad.
