### ISSUE TITLE
Command-line help message out of data in reference manual

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#1428]
The reference manual includes Dafny's command line `/help` output. However, it seems to be out of date. For example, it mentions that `/printModel` has several different modes, whereas it only supports 2. Indeed, running `dafny /help` shows only 2, so the documentation needs to be updated.

**Comment by davidcok** [comment]
This is updated. The release publishing process also ensures that it will be updated at release time.
It can be updated manually by running 'make' in dafny/docs/DafnyRef
