### ISSUE TITLE
TODOs in the Dafny reference manual [Goal to complete by end of November]

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#1450]
By my count there are 41 instances of `TODO` in the built reference manual at https://dafny-lang.github.io/dafny/DafnyRef/DafnyRef

Many of them should be easily convertible to `enhancement` issues instead, or replaced by links to other documentation or papers.

**Comment by robin-aws** [comment]
Just spotted a "TO BE WRITTEN" variation in section 20.22, so let's call it 42 instances :)

**Comment by keyboardDrummer** [comment]
I've been slowed down several times by missing documentation.

**Comment by robin-aws** [comment]
Would be nice to prioritize these in particular, since the different arrow types frequently trip up new Dafny users:

`TO BE WRITTEN: add --> (subset of ~>), -> (subset of -->), non-null types subset of nullable types`

`TO BE WRITTEN - various kinds of arrow types: ~> -> –>`

**Comment by davidcok** [comment]
All TODOs and TO BE WRITTENs are resolved.
