### ISSUE TITLE
Break label location can be improved

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#1458]
## Problem

The incorrect program

``` dafny
method SwingoutSister() {
  break Out;
}
```

gives the error

```
test.dfy(2,2): Error: break label is undefined or not in scope: Out
```

where source location `2,2` is where the keyword `break` is. It would be slightly nicer if the error location pointed to the label itself, that is, location `2,8`.

## Fix

Fixing this issue is a task suitable for someone wanting to get started with working with the Dafny sources. Here's how to implement the fix:

* Change the type of `BreakStmt.TargetLabel` (in `DafnyAst.cs`) from `string` to `IToken`. (And change the type of the corresponding constructor parameter.)
* In the `BreakStmt` production in `Dafny.atg`, capture `id`, not `id.val`, when parsing a `LabelName`. (And change the type of `label` to `IToken`.)
* Change all uses of `TargetLabel` that need a `string` to `TargetLabel.val`.
* In `Resolver.cs` where the `break label is undefined or not in scope` message is produced, use `s.TargetLabel` instead of `s` in the call to `reporter.Error`.

Also, add a test file (e.g., in folder `Test/git-issues`) as a regression test for the fix.

**Comment by hirataqdees** [comment]
Hi, I have implemented the changes listed above, wanted to make sure that I am following the build and test steps correctly. 
1. Does a build is require after a change?
    - Building `DafnyDriver` project from Rider doesn't complain about the changes, but output this error:
   `*** Error: No input files were specified.` 
    - ` make all` from the terminal generates a Boogie config error
    
2. I have placed these two test files(extended with .txt here), running `lit git-issue-1458.dfy` from terminal generates the error: `fatal: Could not find solver`
[git-issue-1458.dfy.txt](https://github.com/dafny-lang/dafny/files/7260389/git-issue-1458.dfy.txt)
[git-issue-1458.dfy.expect.txt](https://github.com/dafny-lang/dafny/files/7260391/git-issue-1458.dfy.expect.txt)

I might be using `lit` incorrectly, what would be the correct way please?

**Comment by RustanLeino** [comment]
Building from Rider is supposed to work. I'm guessing there's something that isn't set up correctly. The `No input files` message you're getting seems like it's coming from Dafny, which I wouldn't expect when building Dafny from C#. Which project/solution are you building from inside Rider?

(I don't use `make all`.)

These [instructions (here, for Mac)](https://github.com/dafny-lang/dafny/wiki/INSTALL#Mac-source) go through the installation steps. When things work, you should be able to run `lit .` in the `Test` directory and then (after 20-40 minutes, depending on your machine) all tests should pass. You should also be able to point `lit` to a particular file. For example, from the `Test` directory, doing `lit dafny0/SmallTests.dfy` should give a `Passed: 1` outcome. In the same way, you should be able to run `lit git-issues/git-issue-1458.dfy` and that should run the `RUN:` commands from the top of that file.

PS. Since this particular issue should give a resolution error, the verifier and compiler will not be run. Therefore, there is no reason to call the compiler among the `RUN:` commands. You can just do what, for example, `git-issues/git-issue-1005.dfy` does.

**Comment by hirataqdees** [comment]
Hi Rustan, thanks for your comments.

I am opening `Dafny.sln` through Rider. I just noticed that the project `DafnyServer` builds fine, its `DafnyDriver` that ends up in the `No input files` error message. Is it correct (and enough) to build `DafnyServer` only?

Thanks for directing me to the manually installing Dafny and related packages, I have followed the steps. I guess I was missing z3 solver and its configuration. I was also able to run `lit .` in the `Test` directory (without any change to Dafny source files) with this output:
`Testing Time: 2638.16s
  Unsupported      :    1
  Passed           : 1120
  Expectedly Failed:    3
  Failed           :   26` 
I think no test should fail, as I haven't introduced any changes yet. I will now try to find which tests failed.

**Comment by hirataqdees** [comment]
Please note that I have installed the dependencies listed under `Compiling Dafny` on the [instructions](https://github.com/dafny-lang/dafny/wiki/INSTALL#Mac-source) page

**Comment by hirataqdees** [comment]
Hi, I looked into some of the failed tests today, it seems that `danfy` is generating warnings about some deprecated features, that are unspecified in `.expect` files. e.g: 
`c++/arrays.dfy` fails because the test generates this output (attached), while it expects this (attached).

I tried adding `/deprecation:0` to suppress warnings, but it didn't work. Should we update expected results of failing tests please, not sure as the generated warnings specify local paths etc.

[arrays.dfy.expect.txt](https://github.com/dafny-lang/dafny/files/7277401/arrays.dfy.expect.txt)
[arrays.dfy.gen.txt](https://github.com/dafny-lang/dafny/files/7277402/arrays.dfy.gen.txt)

**Comment by robin-aws** [comment]
Hi @hirataqdees! Those g++ warnings should be resolved now if you rebase to the latest master, thanks to https://github.com/dafny-lang/dafny/pull/1478

**Comment by hirataqdees** [comment]
Thanks Robin, [#1478](https://github.com/dafny-lang/dafny/pull/1478) did fix the warnings, and all tests passed for me locally!
