### ISSUE TITLE
soundness: subtype predicate not checked on update of value taken from map

### ISSUE THREAD

**Issue by erniecohen** [dafny-lang/dafny#1479]
The following verifies. The call to launder in `cpy` shouldn't verify; it doesn't if you pass in an R directly instead of getting one from `rep`:
```
type R = r:R_ | r.i() witness *
datatype R_ = R(v:nat) {
    predicate i() { v == 0 } 
}

datatype S = S(
    rep:map<nat,R>
) {
    function launder(r:R):R { r } 

    function cpy(r:nat,v:nat):R                              
    requires r in rep 
     {  
        launder(rep[r].(v := v))                           
    }
    static method bad() ensures false {
        ghost var s := S(map[0 := R(0)]).cpy(0,1);
        assert s.v == 1;
    }
}
```

**Comment by robin-aws** [comment]
To clarify since I was a bit confused at first: both the `launder` call and using the indirection through `rep` are necessary to trigger this. Using just either `rep[r].(v := v)` or `launder(v)` as the body of `cpy` do not verify.
