### ISSUE TITLE
Way to include a `function` as a `function method`

### ISSUE THREAD

**Issue by seebees** [dafny-lang/dafny#1492]
Functions are very powerful, but sometimes I need to verify things at runtime.
It would be great to easily be able to re-use an existing function.

Also, this way the standard library could write things as `function`
and then consumer could pick only the specific functions they need for their compiled code.

**Comment by robin-aws** [comment]
I like the spirit of this idea, at least. There is the technical issue that not all `function` definitions can be compiled, so if such a feature existed it would lead to an error if applied to an ineligible function.

I wouldn't want to try to remove the responsibility of deciding "is my `function` intended to be compiled or not" from anyone writing shared Dafny code. If the standard library only provided `function` definitions, I worry it would be too easy to change the definition in the future and break consumers that decided to compile it, or cause a huge performance regression.

**Comment by seebees** [comment]
Perhaps an additional ensures clause or decorator? Something that says "It is possible to convert"?

Or perhaps the going the other direction would be better?
We could make most everything a `function method` and then have Dafny try and figure out what it could... tree-shake out?

If a function-method is only used in formal verification, then we downgrade it automatically?
