### ISSUE TITLE
Internal error when export providing equality-supporting type

### ISSUE THREAD

**Issue by wilcoxjay** [dafny-lang/dafny#150]
Consider the following program:

```
module M1 {
    export provides T, Equal, Foo

    type T(==) = seq<real>

    predicate Equal(u: T, v: T)
    {
        u == v
    }

    lemma Foo()
        ensures forall u, v :: Equal(u, v) ==> u == v  // errors reported here, but only if called from M2
    {}
}

module M2 {
    import M1

    lemma Bar()
    {
        var u: M1.T;
        var v: M1.T;
        assume M1.Equal(u, v);
        M1.Foo();
        assert u == v;
    }
}
```

Module `M1` defines an abstract, equality supporting type `T`, with a custom equality predicate `Equal`, and a lemma that `Equal` implies `==`. `M2` wants to use that lemma. 

However, Dafny reports an internal error during Boogie-level typechecking:
```
(12,47): Error: invalid type for argument 0 in application of Seq#Equal: Box (expected: Seq T)
(12,52): Error: invalid type for argument 1 in application of Seq#Equal: Box (expected: Seq T)
```

My guess is that Dafny is replacing `u == v` in the postcondition of `Foo` with `Seq#Equal`, even when exporting to `M2`. Instead, exporting should use `==`.

**Comment by seanmcl** [comment]
Error has changed, but Dafny still doesn't handle this:

```
...Error: assertion violation
Execution trace:
    (0,0): anon0
```

**Comment by davidcok** [comment]
Confirmed no type checking error, but still the unexpected assertion error.
