### ISSUE TITLE
Commandline /out option not outputting to specified directory

### ISSUE THREAD

**Issue by yizhou7** [dafny-lang/dafny#1512]
I ran the following command: `./tools/dafny/dafny /compile:1 /noNLarith /vcsCores:2 /out:./gen/arch/otbn/printer arch/otbn/printer.s.dfy`. It only generated `printer.dll` and `printer.runtimeconfig.json` in the current directory, but not in the `./gen/arch/otbn/`. We suspect this might be a bug. @parno suggested the followings:
> Compiler-Csharp.cs, it appears to use targetFileName rather than dafnyProgramName when choosing where to emit the output file: https://github.com/dafny-lang/dafny/blob/dcd1c18718d8c1dbcd15364f735f5174a4aeef0c/Source/Dafny/Compilers/Compiler-Csharp.cs#L2785
> The latter is set by the /out flag.  The former defaults to null in DafnyDriver.cs, and it only gets updated if Dafny explicitly writes out files before compiling: https://github.com/dafny-lang/dafny/blob/dcd1c18718d8c1dbcd15364f735f5174a4aeef0c/Source/DafnyDriver/DafnyDriver.cs#L725

**Comment by fabiomadge** [comment]
Probably fixed by #1598. Can you confirm that it works for you?

**Comment by yizhou7** [comment]
I think it still requires the `/spillTargetCode` to be set to a none-zero value, otherwise the dll and the json are outputted in the current directory.

**Comment by fabiomadge** [comment]
Did you try it? Here's what happens for me on master:
```
❯ dafny /compileTarget:cs /out:JN/JN.dfy JN.dfy

Dafny program verifier finished with 0 verified, 0 errors
Compiled assembly into JN.dll
❯ ls JN   
JN.dll                JN.runtimeconfig.json
```

**Comment by yizhou7** [comment]
I actually didn't specify the `/compileTarget`. So something like 
```
./Binaries/Dafny Test/dafny1/BinaryTree.dfy /out:JN/test
```

**Comment by fabiomadge** [comment]
Like this?
```
❯ dafny /out:JN/JN.dll JN.dfy

Dafny program verifier finished with 0 verified, 0 errors
Compiled assembly into JN.dll
❯ ls JN                                                 
JN.dll                JN.runtimeconfig.json
```

**Comment by fabiomadge** [comment]
Or, more to your point:
```
❯ dotnet ./Binaries/Dafny.dll Test/dafny1/BinaryTree.dfy /out:JN/test

Dafny program verifier finished with 19 verified, 0 errors
Compiled assembly into test.dll
❯ ls JN
test.dll                test.runtimeconfig.json
```

**Comment by yizhou7** [comment]
Sorry I think I actually had the wrong dafny checked out, it was the master branch of our group's fork. I have tried the official dafny and seems to work. Thanks!

**Comment by fabiomadge** [comment]
Don't worry. I'm glad this resolved your problem as well.
