### ISSUE TITLE
Elephant `:-` does not unwrap through a subtype

### ISSUE THREAD

**Issue by seebees** [dafny-lang/dafny#1514]
The line `var res :- foo.Bar(a);` gives the error "The type of the first expression is not a failure type in :- statement"

```dafny
  trait Foo<A, B> {
    method Bar(a: A) returns (r: B)
  }

  type FooWithResult<A, B, E> = Foo<A, Result<B, E>>

  method Bar<A, B, E>(
    a: A,
    foo: FooWithResult<A, B, E>
  ) returns (r: Result<B, E>) {
    var res :- foo.Bar(a);
  }
```

However Dafny is happy with:

```dafny
  method Bar<A, B, E>(
    a: A,
    foo: FooWithResult<A, B, E>
  ) returns (r: Result<B, E>) {
    var res := foo.Bar(a);

    if res.Success? {
      return Success(res.value);
    } else {
      return Failure(res.error);
    }
  }
```

**Comment by MikaelMayer** [comment]
Giving more thoughts on that, it actually fails when the resolver cannot **statically** infer that the return type of the method is an failure-compatible type. For example:

```
method id<T>() returns (r: T)  {}

method test() returns (r: Option<int>) {
  var x :- id<Option<int>>();
}
```
fails with "The type of the first expression is not a failure type in :- statement" but

```
method wrap<T>() returns (r: Option<T>)  {}

method test() returns (r: Option<int>) {
  var x :- wrap<int>();
}
```
resolves and verify correctly.

In the first example, when it will try to see if the type of the first returned variable of id is a failure-compatible type, it will look at the Outs of the method, find, T, and won't try to resolve it before concluding.

**Comment by RustanLeino** [comment]
In an UpdateStmt, the `:-` does allow a method call as the right-hand side.

**Comment by MikaelMayer** [comment]
Indeed, my assumption was wrong. Thanks for rectifying. method calls cannot appear inside expressions, but in this example they are the first expression on the right-hand side so it's working.
