### ISSUE TITLE
Add trivia (whitespace, comments, and other non-semantic data) to the AST

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#1528]
This will be necessary to augment the existing pretty-printer into a true, opinionated auto-formatter in the style of `gofmt` or `rustfmt`, which has been a very common ask from Dafny users and the most promising solution to #1311.

The issue is that the current parser discards things like whitespace and comments, and the AST does not represent them in its model. It may be difficult to customize the Coco/R-generated parser to not throw away this information. Even if that is true, however, it should be possible to do an additional pass on the initial AST to rescue the skipped-over text, by retrieving the ranges in between AST nodes based on source position data on the nodes (and cheers to @mschlaipfer for passing on this idea :).

**Comment by codyroux** [comment]
Silly question: Do we need whitespace for an autoformatter? We can at least get by if we want a "trivial" one, where whitespace is entirely determined by the AST.

**Comment by robin-aws** [comment]
Probably not, no. The main concern would be preserving comments AFAICT.

**Comment by keyboardDrummer** [comment]
Preserving newlines is also important because some formatting tasks such as deciding when to put a newline in a list, such as method argument lists, are difficult for formatters.

**Comment by MikaelMayer** [comment]
> Roslyn introduced the term "trivia" for these pieces of the source code and I've seen others pick that up, so I suggest we use the same term.

The article says
"Trivia is a concept that I've only seen in Roslyn. Trivia is associated with a token. A token can have leading and trailing trivia"

Seems like they are not the first one:
