### ISSUE TITLE
make runtime fails

### ISSUE THREAD

**Issue by sorawee** [dafny-lang/dafny#1529]
`make runtime` fails with:

```
Task 'copyJarToBinaries' not found in root project 'DafnyRuntime'.
```

This appears to be due to a recent commit https://github.com/dafny-lang/dafny/commit/bb504a064648ee2048706c9a473cc264da7f6648# which removes `copyJarToBinaries`.

**Comment by sorawee** [comment]
I don't need it. I simply follow the instructions in https://github.com/dafny-lang/dafny/wiki/INSTALL

So as I understand, we should:

- Remove that target from `Makefile`
- Modify the wiki to remove any reference to `make runtime`

**Comment by robin-aws** [comment]
Ah yes, you were unlucky to be caught in the gap between me merging that PR and updating the wiki. :) Will do!

**Comment by robin-aws** [comment]
I've updated the wiki, and have a PR with some followup started to remote the `Makefile` target I should be able to get in tomorrow.

**Comment by tchajed** [comment]
#1534 removed the `runtime` target, but it's still a dependency for the `default` and `all` pseudo-targets.

**Comment by atomb** [comment]
There are some further updates and simplifications to the `Makefile` in #2037, including removal of the `runtime` target.

**Comment by MikaelMayer** [comment]
Looks like this issue is no longer actual, was fixed in two subsequent PRs, so I mark it as resolved.
