### ISSUE TITLE
Feature request: Dafny project file

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#1546]
This has come up in several contexts and I think the time is ripe to figure this out. The benefits include but are not limited to:

* Making it easier to define the set of Dafny files to build (meaning verify, compile, etc.)
* Documenting/locking down the version of Dafny your codebase should be built with.
* Maintaining the switches the codebase requires (for many codebases a switch like `/definiteAssignment:3` is particularly critical)
* Providing more rigour around the different requirements between source and test code (as per this comment: https://github.com/dafny-lang/dafny/issues/1376#issuecomment-938998738)
* Enabling a more standard build system for Dafny (rather than relying on things like Makefiles)

The `dafny.msbuild` task provides some of this functionality, but I suspect it's worth defining a separate if similar format rather than permanently squatting on a .NET-specific (or at least C#-specific) `*.csproj` file format.

**Comment by davidcok** [comment]
Completed with PR 3851
