### ISSUE TITLE
Language Server missing Newtonsoft.Jsoft assembly?

### ISSUE THREAD

**Issue by hmijail** [dafny-lang/dafny#1584]
VSCode 1.62.1
Dafny Extension v2.0.0
macOS 11.6
Dafny 3.3 (commit 88cf232)

I tried to set the VSCode Dafny extension to use the Language Server that was built at `Binaries/DafnyLanguageServer.dll`. VSCode complains:
```The Dafny Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.```

The output tab shows crashes like this:

```
[Info  - 11:25:29 AM] Connection to server got closed. Server will restart.
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Microsoft.Dafny.LanguageServer.Program.Main(String[] args)
   at Microsoft.Dafny.LanguageServer.Program.<Main>(String[] args)
```

**Comment by camrein** [comment]
Thanks a lot for sharing the detailed information.
I've quickly tested the build on Windows. The *Newtonsoft.Json* binary is present after a clean build. Could you please try the following?

- Is the *Newtonsoft.Json* binary present in the *Binaries* dir?
- How do you build Dafny? Using `dotnet build`?
- Try clearing the whole *Binaries* dir and rebuild Dafny.

I have to check the build on OSX later.

If you're still having issues. You could try the command we use to package Dafny:
```sh
# Run within the root dir of the Dafny repository
dotnet publish -c Release -o out Source/Dafny.sln
```

The publish command will create a new directory *out* at the root level.

**Comment by hmijail** [comment]
> Is the Newtonsoft.Json binary present in the Binaries dir?  

Yes, there is a Newtonsoft.Json.dll file. Checking it with `tail`, it seems to be version 9.
```FileVersion9.0.1.19813HInternalNameNewtonsoft.Json.dllj#LegalCopyrightCopyright � James Newton-King 2008*LegalTrademarksPOriginalFilenameNewtonsoft.Json.dll2	ProductNameJson.NET0ProductVersion9.0.1Assembly Version9.0.0.00```

> How do you build Dafny? Using dotnet build?  

I follow the instructions in https://github.com/dafny-lang/dafny/wiki/INSTALL#Mac-source, so I used `make exe`.

> Try clearing the whole Binaries dir and rebuild Dafny.

I realized that the Makefile contains a `clean` target, so I did `make clean` and `make exe`. The Newtonsoft DLL got replaced by another one that now says version 11, and now the VSCode plugin starts correctly! 🎉

**Comment by hmijail** [comment]
> Is the Newtonsoft.Json binary present in the Binaries dir?  

Yes, there is a Newtonsoft.Json.dll file. Checking it with `tail`, it seems to be version 9.
```FileVersion9.0.1.19813HInternalNameNewtonsoft.Json.dllj#LegalCopyrightCopyright � James Newton-King 2008*LegalTrademarksPOriginalFilenameNewtonsoft.Json.dll2	ProductNameJson.NET0ProductVersion9.0.1Assembly Version9.0.0.00```

> How do you build Dafny? Using dotnet build?  

I follow the instructions in https://github.com/dafny-lang/dafny/wiki/INSTALL#Mac-source, so I used `make exe`.

> Try clearing the whole Binaries dir and rebuild Dafny.

I realized that the Makefile contains a `clean` target, so I did `make clean` and `make exe`. The Newtonsoft DLL got replaced by another one that now says version 11, and now the VSCode plugin starts correctly! 🎉

**Comment by hmijail** [comment]
Turns out that running the tests seems to rebuild the Language Server in such a way that it once again fails to start.
```bash
$ make clean exe
# Start VSC: Dafny Extension starts up correctly
# Close VSC
$ dotnet test -v:d Source/IntegrationTests 
# You can interrupt the tests after a couple of them run
# Start VSC: Dafny Language Server crashes complaining about the lack of Newtonsoft.Json 11.0
$ make exe # NOTE: no clean needed!
# Start VSC: again Dafny extension works correctly
```

This is in Dafny commit 1fc7bff2ccaf1b30297efc9bc2c6c9fa26b1a493

**Comment by hmijail** [comment]
I just found that this Language Server crash is also caused by running  Source/DafnyPipeline.Test and Source/DafnyLanguageServer.Test.
Again, running `make exe` fixes the crash.

Dafny commit dce51b3e44b7be652b72fa68a56be2448479b2d4

**Comment by hmijail** [comment]
I saw that the release notes for 3.4.0 mention fixing a Newtonsoft-related bug that sounded like this issue, so I tried reproducing in commit 6d06a0de90ec06c9ec80544dc7c543cff178b1ed . I can't reproduce it, so I'll close.
