### ISSUE TITLE
Measure verification time per "assertion"

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#1597]
Follow-up on the `/verificationLogger:trx` feature. It looks possible to use the splitting feature of Boogie to support a mode where each assertion in a procedure is verified separately, to gain more insight into which assertions in particular are the most expensive and should be refactored to bring the overall verification time down.

While I'm at it, I should be able to improve how Dafny program elements are identified in the TRX format: what is currently something like `Impl$$MyModule.__default.MyMethod` should be something more like `MyModule.MyMethod (implementation)`.

**Comment by robin-aws** [comment]
Depends on https://github.com/boogie-org/boogie/issues/465

**Comment by atomb** [comment]
From what I understand, the Dafny flag `/vcsSplitOnEveryAssert` does the first half of this, and the remaining work has to do with naming. Is that right?

**Comment by robin-aws** [comment]
Split off https://github.com/dafny-lang/dafny/issues/1734 and closing this
