### ISSUE TITLE
Proving a refactor is correct and the new code behaves correctly relative to old code 

### ISSUE THREAD

**Issue by seebees** [dafny-lang/dafny#1614]
Sometimes I want to refactor some code.
Compose/decompose or just move things around.
These kinds of changes can get rather complicated
and involve lots of small changes,
especially in Dafny with all the details I can put into specifications.

As I work the problem the scope of change can get mingled with what was previously correct.
To try and avoid this I will often write a lemma to prove that my two "ways" are equivalent.

However, the problem comes when I want to commit something.
The goal of the refactor is to not leave the old code around.
So while the lemma is useful to me,
and maybe it could exist in the PR for a time,
eventually it needs to be removed.
It needs to be removed because the code that it is based on is getting removed.
Once it is removed, if any additional changes happen,
how do I know that everything is still equivalent?

My idea was to have a way to include a file from a git SHA1.
Obviously this would need to be carefully done,
but it would let me commit a lemma that includes code from a previous version of a file in git history.
In fact, this verification could stick around after the refactor to ensure correctness.

I offer an example.
Say I have a predicate function that defines a type of Valid.

```dafny
module Foo
  predicate method ValidBar(bar: Bar){
    //Something important
  }
}
```

I want to move this predicate and expand on it slightly.
I also want to start using a Subset type based on this new predicate.
Rather than having `requires ValidBar` all over the place.

```dafny
module NotFoo {
  predicate method MoreValidBar(bar: Bar) {
    // `ValidBar` is a SubSet of MoreValidBar requirements
  }
  type BetterBar = b: Bar | MoreValidBar(b)
}
```

Now for the magic.
I was thinking of something like this.

```dafny
include "NotFoo.dfy"
gitInclude "SHA1/Foo.dfy"

module IntegrationMagic {
  import NotFoo
  gitImport Foo = SHA1.Foo

  lemma NeverBreakOldCode(b: NotFoo.BetterBar)
    ensures Foo.ValidBar(b)
  {}
```

`SHA1` is the git commit with `Foo.dfy` that I want to verify against.
So if I want to verify things in old versions of Foo or even delete Foo because I'm done with it,
this test will continue to act as a memory and keep me honest.

**Comment by keyboardDrummer** [comment]
I don't understand the need for the feature your propose. Why don't you move the things you want to delete to a folder 'OLD' and import from there?

**Comment by keyboardDrummer** [comment]
I don't understand the need for the feature you propose. Why don't you move the things you want to delete to a folder 'OLD' and import from there?

**Comment by keyboardDrummer** [comment]
I don't understand the need for the feature you propose. Why don't you move the things you want to delete to a folder 'OLD' and import from there?
