### ISSUE TITLE
Improving Documentation

### ISSUE THREAD

**Issue by smswz** [dafny-lang/dafny#1622]
There is missing documentation in the [reference](https://dafny-lang.github.io/dafny/DafnyRef/DafnyRef) for:
* `--> ~>` and their relation to `->`
* `T(00)`

There are 32 total instances of **TO BE WRITTEN** in the reference.

It would also be helpful to have examples for some forms _e.g._ `:-`

**Comment by robin-aws** [comment]
Thanks @smswz - looks like a dupe of #1450 though?

**Comment by smswz** [comment]
Ah yes, it does. Remy asked me to open an issue, but I think #1450 is more comprehensive
