### ISSUE TITLE
Be consistent in error messages about uncertainly of results

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#1629]
The error text "Error: assertion violation" arguably implies that the assertion is definitely not always true, when in reality it's just that the verifier was unable to prove that it is always true. This might be because there exists a real counterexample, or it may be because the verifier hit internal limits and gave up.

Experienced Dafny programmers tend to understand this property of any verification failure, regardless of the actual error text. But when newcomers are first learning Dafny they can believe there is a real difference between "index out of range" and "*possible* division by zero".

The most superficial improvement here would be to ensure every error message has "possible" or some variation in it. The better improvement would be to attempt to prove a counterexample exists as described in #1628, so that at least sometimes the "possible" would not be necessary!

**Comment by MikaelMayer** [comment]
I think we fixed it in in #1915
