### ISSUE TITLE
On failure to prove tautologies

### ISSUE THREAD

**Issue by tjhance** [dafny-lang/dafny#1631]
Occasionally, Dafny will fail to prove a post-condition which is already so obviously true that there is no possible way to insert intermediate steps. Here is an example I ran into recently:

```dafny
function {:opaque} Choose<A>(s: multiset<A>) : (result: A)
  requires 0 < |s|
  ensures result in s
{
  var a :| a in s;
  a
}

function {:opaque} Apply<A, B>(fn: A ~> B, s: multiset<A>) : (result: multiset<B>)
  requires forall x | x in s :: fn.requires(x)
  ensures |result| == |s|
  reads set x, o | x in s && o in fn.reads(x) :: o
{
  if |s| == 0 then
    multiset{}
  else
    var x := Choose(s);
    multiset{fn(x)} + Apply(fn, s - multiset{x})
}

lemma ApplyAdditive<A,B>(fn: A ~> B, s1: multiset<A>, s2: multiset<A>)
  requires forall x | x in s1 :: fn.requires(x)
  requires forall x | x in s2 :: fn.requires(x)
  ensures Apply(fn, s1+s2) == Apply(fn, s1) + Apply(fn, s2)
  // ...

lemma MultisetSimplificationForall<P,Q>()
  // This is the postcondition that might not hold.
  ensures forall fn: P -> Q, s, t :: Apply(fn, s + t) == Apply(fn, s) + Apply(fn, t)
{
  forall fn: P -> Q, s, t
  ensures Apply(fn, s + t) == Apply(fn, s) + Apply(fn, t)
  {
    ApplyAdditive(fn, s, t);
  }

  // Assertion violation
  assert forall fn: P -> Q, s, t :: Apply(fn, s + t) == Apply(fn, s) + Apply(fn, t);

  // Assertion violation
  assert forall fn: P -> Q, s, t :: Apply(fn, s + t) == Apply(fn, s) + Apply(fn, t);
}
```

As you can see, the code proves the post-condition within the lemma body, but Dafny fails to recognize it.
I added the assertions for extra emphasis: Dafny can't prove the last one, even though it's syntactically identical to the preceding one.

In this particular instance, it's probably a bug relating to the triggers involving function values, multisets, generics, or the intersection thereof. I also know that I can work around it by munging around with triggers (this often involves creating some kind of dummy predicate to act as a trigger).

Still, since I've run into this sort of bug a handful of times over my experience with Dafny - where Dafny fails a proof obligation which appears syntactically identical to a premise - I'm hoping with this issue to spark a discussion about the problem a bit more generally. Is there a way Dafny can be more robust, in general, against this type of failure? Can Dafny guarantee that a user will be able to prove an `ensures forall` by writing a `forall` block in the lemma body?

**Comment by tjhance** [comment]
Ah, so it was the opaque function again causing the problem. Now I feel a little silly, since I'm pretty sure I've filed that same issue previously ... 😅

**Comment by MikaelMayer** [comment]
How would this problem be related to the opaqueness of the function? I think it's a legit use case.

**Comment by MikaelMayer** [comment]
Ok, Actually, after revisiting it, a simple call to 

`reveal Apply();`

before the two asserts fixes the problem.
As described in a [new piece of the documentation]([url](https://github.com/dafny-lang/dafny/pull/1821)), the fuel provided for an assert is 2, whereas the fuel provided for the assume that follows is one. So it's not totally true that, if we have `assert F(); assert F();` the second assertion will always prove automatically. Am I correct @RustanLeino ?

**Comment by RustanLeino** [comment]
I'm late to the party, but yes, adding `reveal Apply();` at the beginning of lemma `MultisetSimplificationForall` is necessary and sufficient.
