### ISSUE TITLE
Error messages involving subset types

### ISSUE THREAD

**Issue by seebees** [dafny-lang/dafny#1637]
Sometimes I get an error message when using a subset type.
I can't seem to get a simple repo, so this is just an example, not a full repo.

```dafny
datatype Thing = Thing
type Foo = s: seq<uint8> | |s| < 10 witness *

function Bar(t: Thing): Foo

predicate Baz(f: Thing -> seq<uint8>)

predicate compose() {
  Baz(Bar)
}
```

I would get an error at `Baz(Bar)` that says something like "Bar does not match Thing -> seq<uint8>" and something about covariance...
I propose that we include what Bar does provide so that it is more clear what Dafny is confused about.
Sometimes Dafny can work things out,
but other time it can not.
If the error message was more like "Bar provides Thing -> Foo which does not match Thing -> seq<uint8>"
it would be clearer what is going on.

**Comment by davidcok** [comment]
Created some examples, but these now show the target type. So I'm closing this issue as fixed.
