### ISSUE TITLE
Design verification metrics reporting system

### ISSUE THREAD

**Issue by atomb** [dafny-lang/dafny#1657]
During the process of verification, Dafny currently collects some additional metrics beyond the success and failure of each proof goal, including the time taken to verify an individual method. Soon it may include the time taken to verify individual assertions (#1597, #1626). And it could include more abstract notions of resource usage rather than clock time (#1605).

For assessment of verification stability (#1582) multiple attempts at an individual proof goal based on, for example, starting Z3 with several different random seeds, could be useful.

Beyond these, there may be reason to measure other aspects of Dafny's behavior in the future.

To make both reporting and analyzing these metrics convenient, it would be useful for them all to use a consistent internal data structure and output format, ideally one supported by other tools. The `/verificationLogger:trx` option provides a first iteration, using infrastructure from [VSTest](https://github.com/microsoft/vstest). Continuing to use VSTest, but taking advantage of its full flexibility, is one option.

For the current goals of measuring resource use by proof goal (whether coarse-grained or fine-grained), the following two data elements are probably sufficient:

* A meaningful goal name/description (identifying a whole procedure or an individual assertion, for instance)
* A resource use value (as a time, abstract resource counter, or other quantitative metric)

It may be useful to have a way to place the goal names in some sort of hierarchy, so that we could have a measurement for an entire procedure as well as each individual assertion within it. It may also be useful to measure resource use of other stages of the analysis pipeline (parsing, translation to Boogie, etc.).

For cases of comparing the resource use of multiple goal proof attempts, a few extra data points could be worth including:

* Mean resource use
* Minimum resource use
* Maximum resource use
* Standard deviation

This issue is meant to track the process of designing this system, and as a place to collect ideas.

**Comment by robin-aws** [comment]
Nice write up! You reminded me of something I had trouble with myself:

> It may be useful to have a way to place the goal names in some sort of hierarchy, so that we could have a measurement for an entire procedure as well as each individual assertion within it.

AFAICT this is one fundamental disadvantage of reusing the VSTest model: I couldn't find any way of representing test results in a hierachy.

**Comment by keyboardDrummer** [comment]
How about using CSV if a table is all we need, and JSON if we want a hierarchy?

**Comment by atomb** [comment]
I'm inclined to agree about leaving things tabular, for simplicity. I think all metrics we're likely to collect will be about the "leaves" of the tree of verification tasks, so a flat table will be fine. The names used in the table can encode the hierarchical structure as needed (which would allow, for example, a tool that calculates the total verification time for a procedure by adding up the entries that have the prefix corresponding to that procedure).

This could also allow us to include the results in VSTest TRX format. However, it doesn't look like that format is extensible to the point of including things like means or standard deviations. The most concrete description of the format I've been able to find is [here](https://github.com/iinteractive/IInteractive.WebTest/blob/master/IInteractive.WebConsole/Schema/Microsoft.VisualStudio.TestTools.Common.Xml.VSTST.xsd). It's got quite a few constructs, but doesn't include all of those from my list above.

Given that, CSV is probably the way to go, given its ubiquity, and the fact that it's especially widely used for statistical analysis and profiling. Also, @robin-aws has already begun to write code in that direction!

**Comment by atomb** [comment]
For reference, here are some branches that begin to gather some of the information that would be reported through a system like this:
* Boogie changes to assign resources to splits: https://github.com/robin-aws/boogie/tree/per-assert-splitting
* Dafny changes to log resources used in CSV format: https://github.com/robin-aws/dafny/tree/resource-count

**Comment by atomb** [comment]
I'm now convinced that it may make more sense to log information with less processing than described above. Rather than choosing a single metric (such as Z3 resource count), calculating statistics, and including those in the output, we could include all metrics all the time, without any statistical computations, but allow multiple rows per proof goal. If there are multiple rows for a proof goal, a later post-processing pass could perform any statistical computations that would be useful.

**Comment by atomb** [comment]
PR #1766 makes a step in this direction, though it currently will never output multiple rows per proof goal.

**Comment by keyboardDrummer** [comment]
> I'm now convinced that it may make more sense to log information with less processing than described above. Rather than choosing a single metric (such as Z3 resource count), calculating statistics, and including those in the output, we could include all metrics all the time, without any statistical computations, but allow multiple rows per proof goal. If there are multiple rows for a proof goal, a later post-processing pass could perform any statistical computations that would be useful.

How about working backwards from the use-cases?

**Comment by atomb** [comment]
> How about working backwards from the use-cases to determine what we want to show?

You make a good point that the issue as written doesn't describe that use case very well.

The key use case that's been driving my thoughts on this is that of measuring verification stability (as described in #1582) through comparison of various resources used by solvers during multiple attempts at proving a single goal.

I currently think that the output format provided by #1766 (with room to include additional columns in the future) seems like a pretty solid resolution to the question this issue was meant to track, and therefore that it makes sense to close this issue once that PR is merged.

To fully support the use case, Boogie will need support for attempting a proof goal multiple times. I'll track the design for that in a separate Boogie issue.

**Comment by atomb** [comment]
Given the merge of #1766, I think the remainder of this issue is tracked more precisely [here](https://github.com/boogie-org/boogie/issues/494), and this issue can be closed.
