### ISSUE TITLE
Add opinionated auto-formatter for Dafny source code

### ISSUE THREAD

**Issue by alex-chew** [dafny-lang/dafny#1658]
"[To] augment the existing pretty-printer into a true, opinionated auto-formatter in the style of gofmt or rustfmt... has been a very common ask from Dafny users."

(from discussion in #1528, which is a prerequisite (I think) for this issue)

**Comment by cpitclaudel** [comment]
I think a nice first step for this would be an auto-indenter (same as auto-formatting except no change to line breaks or interword spaces); only beginning of line spaces.  There's a lot less subtlety there, so it could be a good starting point.

dafny-mode for Emacs already has this based on a tiny custom parser, and it's super nic,e when it works well and super annoying when it makes mistakes.  It would be great to swap that out for a proper indenter based on the Dafny parser.

**Comment by keyboardDrummer** [comment]
Some ideas for what to normalise:

- Correct indentation and use 2 spaces per step
- Remove trailing whitespace
- Remove redundant parenthesis
- Order function/method specifications:
    * returns
    * modifies/reads
    * requires
    * ensures
- Order loop specifications
    * decreases
    * invariant
- Place line breaks before modifies/reads/requires/ensures clauses
