### ISSUE TITLE
RPrint crashes when ran into the elephant operator

### ISSUE THREAD

**Issue by unboxedtype** [dafny-lang/dafny#1665]
RPrint (dafny /rprint:- ) crashes with the following sample. Both the elephant operator and match statement are essential to reproduce the bug.

```
module ConcreteModule
{
   datatype Status =
 	| Success
	| Failure(error: nat)
   { predicate method IsFailure() { this.Failure? }
     function method PropagateFailure(): Status
       requires IsFailure()
     {  Failure(this.error) }
   }
	
   method execute_external_method(n:nat) returns (r:Status)
   {
     match n { // match is essential.
	case 0 =>
	  :- Func1(); // this call is essential to reproduce the bug
        case _ =>
	  return Success;
     }
   }
   method Func1() returns (r:Status) { return Success; }
}
```
The following command:
> dafny /compile:0 /dafnyVerify:0 /rprint:- ./RPrintFailure2.dfy

crashes with the error:

> Assertion failed.                                                            at Microsoft.Dafny.Printer.PrintUpdateRHS(ConcreteUpdateStatement s, Int32 indent) in /home/unboxedtype/src/dafny/Source/Dafny/AST/Printer.cs:line 1632
> ...
> 

Environment:
Dafny 3.3.0.31104

P.S. Do you accept pull requests from external contributors? I would like to get involved into this. 

UPDATE: added info about match statement necessity.

**Comment by fabiomadge** [comment]
We'd be happy to have you tackle this, or any other open issue. We we try to assign issues once we start looking into them to avoid duplicate effort.

**Comment by unboxedtype** [comment]
Hi! 
I found a root cause of this bug, and proposed a fix that works on my tests. However, there are some secondary design decisions need to be made. Should I submit a pull request and await a feedback from developers? Are there any guidelines on how to do pull requests properly in the Dafny ecosystem?

**Comment by fabiomadge** [comment]
Great! Opening a PR is a good next step. There is not much beyond common sense to heed. Please include your example as a test. You can use `dafny/Test/git-issues/git-issue-1665.dfy` as a filename.

**Comment by MikaelMayer** [comment]
And use the LIT syntax available in the other files where you define in top-level comments how the tests should be run on that file. We will help you with this once you submit the PR.

**Comment by unboxedtype** [comment]
I ran the test suite and found out that part of the tests stopped working after my changes. Seems that the suggested fix breaks the resolution algorithm in some way.

After digging deeper in the problem, I realized that I do not even understand what precisely the _RPrint_ is aiming for. 
The help states that it is "_print Dafny program after resolving it_". But what it actually means? What exactly is expected to be printed? 

When I first encountered this option, I thought it is basically a great de-sugaring: all refinements are put in place, match statements converted into if/then/else, default types definition inserted, default attributes made explicit etc. But after studying some outputs, I see that it is not the case: for example, the match statement is still there, it is just equipped with a de-sugared version put into comments. 

My second observation: the program that I receive after RPrint does not compile anymore. Should that be this way?

Can we precisely define what the RPrint aims to accomplish? Maybe this knowledge could be transferred into the Reference also?

**Comment by MikaelMayer** [comment]
To my understanding, it will explicit all the types and print them, so there will be no implicit types. In essence, it will print the same Dafny program, without original comments and formatted, plus the types annotations everywhere. Plus, as you discovered, desugared versions into comment.
The program produced after RPrint should compile, so you discovered an error in rprint.

**Comment by unboxedtype** [comment]
One more question about desugaring. For the provided sample, specifically for the match statement, what is the right way to provide desugaring? 

I have prepared two samples.
The first one shows desugaring for the whole match statement, including all cases, and then, specifically for the elephant operator.
The second one does desugaring only for the whole match statement, but the elephant operator does not receive a separate desugaring.

**Sample 1**
```
  method execute_external_method(n: nat) returns (r: Status)
    decreases n
  {
    
    /*---------- desugared ----------
    if n == 0 {
      :- Func1()
      /*---------- desugared ----------
      var valueOrError0: Status;
      valueOrError0 := Func1();
      if valueOrError0.IsFailure() {
        r := valueOrError0.PropagateFailure();
        return;
      }
      ---------- end desugared ----------*/;
    } else {
      return Success;
    }    ---------- end desugared ----------*/
    match n {
      case {:split false} 0 =>
        :- Func1()
        /*---------- desugared ----------
        var valueOrError1: Status;
        valueOrError1 := Func1();
        if valueOrError1.IsFailure() {
          r := valueOrError1.PropagateFailure();
          return;
        }
        ---------- end desugared ----------*/;
      case {:split false} _v0 =>
        return Success;
    }
  }
```

**Sample 2**
```
  method execute_external_method(n: nat) returns (r: Status)
    decreases n
  {
    
    /*---------- desugared ----------
    if n == 0 {
      :- Func1()
      /*---------- desugared ----------
      var valueOrError0: Status;
      valueOrError0 := Func1();
      if valueOrError0.IsFailure() {
        r := valueOrError0.PropagateFailure();
        return;
      }
      ---------- end desugared ----------*/;
    } else {
      return Success;
    }    ---------- end desugared ----------*/
    match n {
      case {:split false} 0 =>
        :- Func1();
      case {:split false} _v0 =>
        return Success;
    }
  }
```

I have a feeling that the first sample provides excessive comments, while the second one looks more concise.

**Comment by MikaelMayer** [comment]
I have the feeling that rprint is used in any case for debugging, so having more comments is probably not an issue.
In the case you mention, I would feel surprised that the second `:- Func1()` is not desugared and I might think it's a bug, especially, if I don't see the if before the match.

**Comment by unboxedtype** [comment]
So, you mean the sample1 is the correct one from your standpoint? 

Regarding the second `:- Func1()` not being desugared. After being desugared in the above match desugaring block, why should it be desugared the second time? Does it provide any extra information for the user?

**Comment by MikaelMayer** [comment]
Wait, on the second reading, I better understand what the desugaring is about. I thought it was adding a sentence in front of the match statement. However, what it does is that it replaces the match with the if/else statement, right?
In this sense, the second example is better.
