### ISSUE TITLE
Compilation error: error CS0103: The name '_td___T' does not exist in the current context

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#1679]
This issue is related to #1514  but concerns the compiler and the elephant operator. Here is a MVE:

```
method s<E>() returns (r: Option<E>)  {
}

method test<T>() returns (r: Option<T>) {
  var x :- s<T>();
  r := Some(x);
}

method Main() {
  var x := test<int>();
  print "ok";
}
```

Although it verifies and compiles to c#, the compilation of c# gives

    (2099,20): error CS0103: The name '_td___T' does not exist in the current context

An easy fix is to write `method test<T(0)>()` instead of `method test<T>()`. Indeed, the translation of `var x :- s<T>();` is:

```
var x: T;
var valueOrError := s<T>();
if(valueOrError.IsFailure()) {
  return valueOrError.PropagateFailure();
}
x := valueOrError.Extract();
```

The problem in the original code is that, if T is not auto-initializable, `var x: T` will try to initialize x but the type descriptor is not available, hence the compilation error.

Two solutions here:
1. Either require that T to be auto-initializable
2. Or in case of declarations, move the _declaration_ `var`  to when x is actually initialized, so that there is no need for auto-initializable descriptor.

I'm trying to implement 2 right now.

**Comment by RustanLeino** [comment]
Solution 2 would do the trick. However, the real problem seems to be that `var x: T;` is not compiled correctly. If `T` is not an auto-init type, then the compiler should use a "placebo" value instead of the "default" value (that is, the compiler should call `PlaceboValue(...)` instead of `DefaultValue(...)`).

**Comment by fabiomadge** [comment]
#1553
