### ISSUE TITLE
Dafny warnings are reported as errors; Dafny won't run program; breaks VSCode plug-in

### ISSUE THREAD

**Issue by kevinsullivan** [dafny-lang/dafny#168]
I'm running current Dafny with the Dafny VSCode plugin in VSCode.

The problem is that my Dafny program verifies, but when I try to "Compile and Run" in VSCode,
 Dafny reports, "Errors compiling program into basic-dafny.exe." Here's the full compiler output. 

```
Dafny program verifier finished with 9 verified, 0 errors
Errors compiling program into basic-dafny.exe
/var/folders/5n/6hml8q9s39300wsyb2kb89b00000gn/T/4bcad2d0/5e25f480.0.cs(1792,19) : warning CS1718: A comparison made to same variable. Did you mean to compare something else?
/var/folders/5n/6hml8q9s39300wsyb2kb89b00000gn/T/4bcad2d0/5e25f480.0.cs(1854,7) : warning CS0162: Unreachable code detected
```

The problem I face is that Dafny won't run the compiled code when this happens, even though compiled code is generated, and in the "Dafny VSCode" plugin, (1) the only way to run a Dafny program is using the Compile and Run option, and (2) VSCode does not report the warnings at all. So one is left with a mysterious situation in which the code verifies, an inexplicable error is given, and the program can't be run. (It can be run if one launches a terminal window and uses mono to execute the .exe file that *is* generated by the compiler).

Suggested fixes: (1) Change "Errors compiling program into basic-dafny.exe" to "Warnings compiling program into basic-dafny.exe" when only warnings are generated, and (2) let the compiled executable run under these circumstances. If you don't want do (2) I understand but (1) could help the plug-in developers to better handle the "warnings generated" situation.

Kevin

**Comment by seanmcl** [comment]
Thanks for the report.  Please open an issue in https://github.com/DafnyVSCode/Dafny-VSCode if you're still interested in this issue.

**Comment by Tom852** [comment]
The next release of the language server will actually fix this issue.

- Warnings are reported as such.
- Information Diagnostics as well.
- Compilation is possible with warnings.

https://marketplace.visualstudio.com/items?itemName=correctnessLab.dafny-vscode-preview
