### ISSUE TITLE
Feature request: language server: terminate running Z3s when client disconnects

### ISSUE THREAD

**Issue by dijkstracula** [dafny-lang/dafny#1690]
Dear Dafny team,

Last night I was having what I thought were unresponsiveness issues with the Dafny plugin, so I closed and reopened VS Code a few times.  I eventually noticed I had several z3 processes pinning CPU cores - I think what's happened is that I've written some code that z3 seems to take forever to verify (related to #1689 ) but when I close the editor the solver is still running.

I'm not familiar with the language server protocol and its connection lifecycle so I'm not sure if this is an issue with the VS Code plugin or the language server itself, but, it might be nice if a running z3 is terminated when a client disconnects to avoid zombie solvers piling up in such cases.  Thanks!

**Comment by keyboardDrummer** [comment]
This issue was resolved with https://github.com/dafny-lang/dafny/pull/1664 but that fix still has to be released. We will release 3.4, which includes the fix, shortly.
