### ISSUE TITLE
Change wording in error messages that mention arguments when referring to parameters

### ISSUE THREAD

**Issue by amaurremi** [dafny-lang/dafny#1697]
Following up on a [discussion](https://github.com/dafny-lang/dafny/pull/1659/files#r773272560) on type-error messages, I think that the messages sometimes use the term "argument" when referring to (in-)parameters. For example, given the following code:
```
function foo(x: int) ...
...
foo(true)
```
according to the type error 
```
Error: incorrect type of function argument at index 0 named 'x' (expected int, found bool)
```
the argument is named `x`, whereas it's the _paramer_ to `foo` that is named `x`. 

This also applies to other places in the code, such as the "Error: no actual argument passed for datatype constructor argument" or "...function argument", etc. messages.

**Comment by keyboardDrummer** [comment]
Are you saying the term "function argument" is incorrect, and should be replaced with "function parameter" ?

I think the error message wants to say that the type of the argument is incorrect, not that the type of the parameter is, so I'm not surprised that it uses the term argument.

**Comment by amaurremi** [comment]
> Are you saying the term `function argument` is incorrect, and should be replaced with function parameter ?

A parameter refers to the variable in the function declaration, and an argument refers to the expression that is passed in a function call.

`function f(x: int)` -- here, `x` is a function parameter

`var y := f(x);` -- here, `x` is a function argument

I like @MikaelMayer's suggestion to change the message.

**Comment by MikaelMayer** [comment]
This PR implements the suggested change, along with other reformulations that makes it clearer.
https://github.com/dafny-lang/dafny/pull/1698
We can continue the discussion there.

**Comment by cpitclaudel** [comment]
> A parameter refers to the variable in the function declaration, and an argument refers to the expression that is passed in a function call.

But then the message is at least partly correct, isn't it?  "incorrect type of function argument" says that the expression that is passed in the call has the wrong type (the rest of the message is wrong to call `x` the argument, though)

**Comment by MikaelMayer** [comment]
Yes it is at least partly correct. The wrong part is to say ` named 'x'` when it's not the argument that has this name, it's the parameter.
