### ISSUE TITLE
print statement allowed in function methods

### ISSUE THREAD

**Issue by yizhou7** [dafny-lang/dafny#1703]
The [documentation](https://dafny-lang.github.io/dafny/DafnyRef/DafnyRef.html#1919-print-statement)  seems to suggest that print statement is allowed in function methods:

> Dafny does not keep track of print effects. `print` statements are allowed only in non-ghost contexts and not in expressions, with one exception. The exception is that a function-by-method may contain print statements, whose effect may be observed as part of the run-time evaluation of such functions.

However the [allowed statements](https://github.com/dafny-lang/dafny/blob/ef078776903b76a34bb47338187d0af03ecacebe/Source/Dafny/Dafny.atg#L4070) in expressions does not seem to include `print`. 

I have tried something like the following, which gives syntax error:
```
    function method test(v: int): int
    {
        print "hi";
        1
    }
```

Maybe the documentation can be updated. Alternatively it would also be nice to support `print` statement in function method.

**Comment by RustanLeino** [comment]
As the quoted document says, `print` statements are not allowed in expressions. Expressions in Dafny do not allow side effects, so they do not support `print` statements.

Note that a `function method` is simply a compiled function. The "`function-by-method`" that the documentation mentions is a different kind of declaration.

If you had intended to use `print` statements for debugging, I suggest you instead use an `assert` or `expect` statement, both of which are allowed in expressions.
