### ISSUE TITLE
LSP server does not report timeouts as diagnostics

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/dafny#1710]
DafnyServer and the command line both report timeouts by highlighting the name of the procedure. DafyLanguageServer does not produce any diagnostics.  Example input:

```
predicate P(n: int)
predicate Q(n: int)

function method {:unroll 100} Ack(m: nat, n: nat): nat
  decreases m, n
{
  if m == 0 then
    n + 1
  else if n == 0 then
    Ack(m - 1, 1)
  else
    Ack(m - 1, Ack(m, n - 1))
}

method test() {
  assert Ack(5, 5) == 0;
}
```

Related issue: https://github.com/dafny-lang/ide-vscode/issues/115

**Comment by MikaelMayer** [comment]
Wow, that's a big issue. I wasn't aware of that and that can explain why some have a bad experience with the VSCode extension.
