### ISSUE TITLE
Synonym type members

### ISSUE THREAD

**Issue by xtrm0** [dafny-lang/dafny#1719]
On the dafny reference (https://dafny-lang.github.io/dafny/DafnyRef/DafnyRef.html#11-types-that-stand-for-other-types), it seems that synonym type members are supported, but it seems that it is not supported by dafny.atg (we either have the "=" for new type or TypeMembers<module, members> : https://github.com/dafny-lang/dafny/blob/45ed0a39d24b95a84a787a357491a3058b279aee/Source/Dafny/Dafny.atg#L1397-1425).

Example of something that doesn't get parsed:
```dafny
type x = seq<int>
{
  predicate PREDICATE() { true }
}
```

Regarding this, is there a way to achieve the following with just a type synonym or do we need a datatype for mySeq? 
```dafny
datatype Elem = Elem(x: int) { predicate WF() { true }}

type mySeq = seq<Elem>
{
  predicate WF() { forall i | 0 <= i < |this| :: this[i].WF() }
}
```

**Comment by MikaelMayer** [comment]
Are your referring to a subset type like this:

    type mySeq = x : seq<Elem> | forall i | 0 <= i < |x| :: x[i].WF()
    
 Otherwise I agree it would be nice to be able to add method to existing types.

**Comment by xtrm0** [comment]
Oh ok sorry bad example, yes I meant adding method to existing types.

Another story then, using subset types:
```dafny
datatype Elem = Elem(r: int, im: int) { predicate WF() { r > 0 }}
type matrix = that : seq<seq<Elem>> | forall i,j | 0 <= i < |that| && 0 <= j < |that[i]| :: that[i][j].WF()
{
  function AtRealOnly(i:int) : Elem
    requires 0 <= i < |that|
    requires 0 <= j < |that[i]|
    requires that[i][j].im = 0
  {
    that[i][j]
  }
}
```
Having some syntathic sugar to be able to call instanceOfMySeq.AtRealOnly(i) (rather than defining a function AtRealOnly that received mySeq as an argument) would be nice as it would avoid having to write the right module name for AtRealOnly and still being sure that the right function is being called.

**Comment by RustanLeino** [comment]
Thank you for the report. The bug is in the documentation (the grammar in Section 11.1 should not include the line `[ TypeMembers ]`).

Dafny supports members only for `class` types, `trait` types, `datatype` and `codatatype` types, `newtype` types, and opaque types. You cannot add members to a type "later"; that is, you must declare members as part of the type declaration. Neither type synonyms nor subset types allow members, because of its impact on name resolution.
