### ISSUE TITLE
Dafny language design glitch involving file include

### ISSUE THREAD

**Issue by kevinsullivan** [dafny-lang/dafny#172]
My program start as follows. 

 include "syntax.dfy"
 module bool_interp
 {
     import opened bool_syntax

It imports the context of syntax.dfy, which encloses its contents in a module called bool_syntax. The problem seems to be that the include causes the module definition to be copied into the compilation unit, but then the import opened bool_syntax directive causes what amounts to a duplicate module definition in the same compilation unit. The errors that this situation produces can be misleading.

The solution that is forced is simply to give the opened module a different name so that the names don't conflict. That is, rather than "import opened bool_syntax" do something like "import opened bs = bool_syntax". The name (here "bs") can be anything unique.

This a little weird to have to do, as the whole purpose of "opening" the module is not to have to refer to it by name. In any case, the following code works. 

 include "syntax.dfy"
 module bool_interp
 {
     import opened bs = bool_syntax

Maybe the language/compiler can be defined to give the imported module a synthesized, unique name when the module is imported opened?

**Comment by seanmcl** [comment]
Thanks for the report!  We are interested in looking at this, but could you please create an issue with a working example of the problem, rather than describing it in text.
