### ISSUE TITLE
Support verifying with multiple random seeds

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#1726]
Suspected to provide a more accurate instability metric by revealing more of the underlying complexity.

This implicitly also involves the plumbing to expose this metric separately from the plain verification time (which is currently used as the proxy "stability metric").

**Comment by atomb** [comment]
This is available with the `/randomSeedIterations:n` flag to Boogie, which is typically useful along with `/verificationLogger:csv` flag to Dafny.
