### ISSUE TITLE
Rise4Fun tutorial is out of date about set cardinality

### ISSUE THREAD

**Issue by kevinsullivan** [dafny-lang/dafny#173]
https://rise4fun.com/Dafny/tutorialcontent/Sets says "...there is no way to get the cardinality (size) of a set in Dafny." But the following code provides a counterexample.

method Main()
{
    var x: set<int> := {1, 2, 3};
    var n: int := |x|;
    print n;
}

Suggested fix is to update the tutorial.

**Comment by wilcoxjay** [comment]
I've just deleted the offending sentence in the markdown in this [commit](https://github.com/Microsoft/dafny/commit/f53d45c5e4b4e0c601496d2e14ec32355d6d2b5d). We will update rise4fun soon and then I'll close this issue.
