### ISSUE TITLE
Improve display name of "test results" when using `/verificationLogger:...`

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#1734]
Splitting this off from #1597

What is currently something like Impl$$MyModule.__default.MyMethod should be something more like MyModule.MyMethod (implementation)

This MIGHT not be worth doing if we want to model the metadata of test results separately somehow, and use more of a unique identifier in the test results themselves, so this depends on some decisions as part of #1657

**Comment by atomb** [comment]
I've closed #1657, and plan to use this issue to track the naming facet of the design.
