### ISSUE TITLE
Investigate providing understandable identifiers/descriptions for individual Dafny assertions

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#1735]
Currently these are only available as verification error strings instead. E.g. “possible violation of function precondition”. This is necessary to describe what a given VC contains and hence understand how to fix it, especially when using /vcsSplitOnEveryAssert.

It also includes being better about the distinction between “assertion definitely not always true” and “assertion not necessarily always true, I’m not sure” - the error messages are currently inconsistent, but at the moment the actual answer is always the latter.

**Comment by atomb** [comment]
I believe that #1915 fixed this. There is certainly room to improve individual assertion descriptions and error messages, but the mechanism is in place to describe what each assertion is attempting to establish.
