### ISSUE TITLE
Dafny feature to diagnose individual cost of individual Dafny assertions

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#1754]
It's possible to use the new Boogie `/vcsSplitOnEveryAssert` feature to approximate the verification cost of individual assertions, which can be very helpful in identifying why verification of a single method is timing out, or in getting the cost of a method down to improve its stability. However, identifying the contents of each split requires scrolling through a ton of `/traceverify` output, and then attempting to map a Boogie assert statement back to the corresponding element of the Dafny program.

Depends on #1735 and #1657: we probably want a switch that turns on `/vcsSplitOnEveryAssert` and then labels each split with the Dafny description of the assertion that induced it.

**Comment by atomb** [comment]
PR #1766 provides part of this functionality more conveniently than `/trace`. The key remaining step is to describe each assertion in terms of Dafny constructs instead of Boogie constructs.

**Comment by atomb** [comment]
PR #1947 now provides a human-readable description of each assertion along with time and solver resource count used to prove it, enabled with the combination of `/verificationLogger:text` and `/vcsSplitOnEveryAssert`.

**Comment by keyboardDrummer** [comment]
Shouldn't this be integrated with the IDE as well?

**Comment by atomb** [comment]
Yeah, I think it should (and will be once #1942 and related PRs are merged). I considered having one way to achieve the goal to be sufficient for closing this, but one could argue that it's not fully done until those are merged.
