### ISSUE TITLE
Rise4Fun tutorial is out of date about old nat bug

### ISSUE THREAD

**Issue by kevinsullivan** [dafny-lang/dafny#177]
https://rise4fun.com/Dafny/tutorialcontent/Sequences says "Note a known bug in Dafny prevents you from creating sequences of naturals, nat" but at least the following code works fine.

    method Main()
    {
        var a: seq<nat> := [1, 2, 3];
        assert 2 in a;
        print a[1];
    }

**Comment by wilcoxjay** [comment]
I've just deleted the offending sentence in the markdown in this [commit](https://github.com/Microsoft/dafny/commit/f53d45c5e4b4e0c601496d2e14ec32355d6d2b5d). We will update rise4fun soon and then I'll close this issue.
