### ISSUE TITLE
README.md is missing instructions for contributors

### ISSUE THREAD

**Issue by mschlaipfer** [dafny-lang/dafny#1781]
The README just mentions how to install Dafny from pre-built binaries, but does not point to building from source or how to contribute (https://github.com/dafny-lang/dafny/wiki/INSTALL#building-and-developing-from-source-code). The only instructions are for how to install `pre-commit` which seem out of place. Maybe there's place for a CONTRIBUTING.md.

**Comment by robin-aws** [comment]
I'll go further and say we should absolutely have a `CONTRIBUTING.md`, even if we want to keep the instructions for building from source in a more shared location for it to link to (since that can be useful for end users that want to use the latest Dafny changes).
