### ISSUE TITLE
Show Dafny options first in output of /?

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/dafny#1798]
`Dafny /?` should start with Dafny options, and then show other categories.

Current order:

- General options
- Boogie options
  - Inference options
  - Debugging and general tracing options
  - Civl options
  - Verification-condition generation options
  - Verification-condition splitting
  - Prover options
- Dafny options

Proposed order

- General options
- Dafny options
- Boogie options
  - Inference options
  - Debugging and general tracing options
  - Civl options
  - Verification-condition generation options
  - Verification-condition splitting
  - Prover options

**Comment by MikaelMayer** [comment]
Should we even include a file so that it would hide Boogie's options by default?

**Comment by cpitclaudel** [comment]
I think not, because users won't realize that it exists (I often grep through the output of `/?`)
