### ISSUE TITLE
Update reference manual to explain use of !new in type parameter declarations

### ISSUE THREAD

**Issue by kevinsullivan** [dafny-lang/dafny#181]
The compiler refused to accept a type parameter (to a class in this case0 without a "!new" qualifier. Example: "class binRelationS<T(!new,==)> { ... }". The existence and use of this qualifier is not yet explained in the reference manual. Probably should be.

**Comment by acioc** [comment]
A link to release notes would be helpful here: https://github.com/dafny-lang/dafny/releases/tag/v2.1.0

**Comment by kevinsullivan** [comment]
Thank you!
