### ISSUE TITLE
VSCode plugin occasional UI issue

### ISSUE THREAD

**Issue by emina** [dafny-lang/dafny#1854]
I've observed that the Dafny VSCode plugin sometimes fails to localize parsing and type errors by underlining them with the red squiggles. 

This behavior is not easy to reproduce, but I'm reporting it here in case others run into it.

In general, it happens when I'm working on a large file (300+ LOC), and VSCode has been open for a long time (several days).

Even when the errors aren't localized in the UI, the "Problems" window does list the locations correctly, and they're also listed / found by running the verifier manually.

**Comment by cpitclaudel** [comment]
Thanks!  Moved it to a dafny/ide-vscode issue at https://github.com/dafny-lang/ide-vscode/issues/139
