### ISSUE TITLE
Incorrect initialization of ThreadStatic variable in `DafnyAst.cs`

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/dafny#1920]
In `DafnyAst.cs` we have this:

https://github.com/dafny-lang/dafny/blob/b133a187c80e26c25af32bdb6488e3a40e631f41/Source/Dafny/AST/DafnyAst.cs#L612-L613

That code is wrong. Quoting from https://docs.microsoft.com/en-us/dotnet/api/system.threadstaticattribute:

> Do not specify initial values for fields marked with ThreadStaticAttribute, because such initialization occurs only once, when the class constructor executes, and therefore affects only one thread. If you do not specify an initial value, you can rely on the field being initialized to its default value if it is a value type, or to null if it is a reference type.

More details [here](https://stackoverflow.com/questions/18086235/initializing-threadstatic-field-still-causes-nullreferenceexception).

I'm afraid that the fix isn't as simple as just initializing on each thread.  We are starting to use `Task`s in Dafny, and control can switch between different tasks on the same thread, causing issues with this `scope` variable.

There's a comment about this in the server ("*The resolution requires mutual exclusion since it sets static variables of classes like Microsoft.Dafny.Type. Although, the variables are marked "ThreadStatic" - thus it might not be necessary.*")

**Comment by keyboardDrummer** [comment]
Does the fix in this PR not work? https://github.com/dafny-lang/dafny/pull/1870

**Comment by cpitclaudel** [comment]
Fixed in #1870.
