### ISSUE TITLE
/vcsLoad does not parse non-integers in Dafny 3.5.0

### ISSUE THREAD

**Issue by tchajed** [dafny-lang/dafny#1922]
This is a bug in Boogie which I've reported as boogie-org/boogie#546, but I'm posting it here in case anyone else runs into it, and because fixing it will require Dafny to bump the Boogie version to one with a fix.

Starting in Dafny 3.5.0 (due to the upgrade in Boogie version), `/vcsLoad:0.5` now fails with `Error: Invalid argument "0.5" to option /vcsLoad`.

Dafny should have a test that uses `/vcsLoad`, perhaps `/vcsLoad:0.1` (or an even smaller value) if you don't want to actually use too many cores in the test build. It's mentioned in `Test/concurrency/12-MutexLifetime-long.dfy` for example but only in a comment.

**Comment by fabiomadge** [comment]
Can we close this?

**Comment by tchajed** [comment]
Yes, this looks to be fixed on Dafny master. Thanks!
