### ISSUE TITLE
Bug: Using Dafny.dll to build an AST fails if no compiler specified.

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#1932]
Since #1894 , `ModuleExportDecl.FullCompileName` used in the constructor of `ModuleExportDecl` can throw a null pointer exception because `TopLevelDecl.FullCompileName` now [depends on](https://github.com/dafny-lang/dafny/commit/d9aa57676e1ceca6bf151e0fe30d7b0b83e63cc5#diff-fa257574acd41f12645bbc3b82e23fc93ac386d13a9fb58c0f5f54944a8359e3R4313) `DafnyOptions.O.Compiler`, which does not have a default value.

**Comment by cpitclaudel** [comment]
Can you give a repro for this issue?  The option-parsing code does `Compiler ??= new CsharpCompiler();`; when is it not called?

**Comment by cpitclaudel** [comment]
In other words, it's intended that `FullCompileName` depends on the compiler; the bug is that Compiler is null, and that's what we should fix.

**Comment by MikaelMayer** [comment]
The method `ApplyDefaultOptions()` is never called if one builds a `DafnyOptions` using the constructor.
Previously, it was only depending on whether the compiler target was C# or not, not the full compiler.

**Comment by cpitclaudel** [comment]
> Previously, it was only depending on whether the compiler target was C# or not, not the full compiler.

Initializing a compiler instance doesn't really do that much, so it would be fine to initialize the compiler to be the C# one.  But isn't it good that you get an error?  It tells you that your code may depend on the internals of the compiler, which is good to know?

**Comment by keyboardDrummer** [comment]
When this does bug occur? It seems like it occurs if DafnyOptions.O are not properly initialised. Isn't that the fix then?
