### ISSUE TITLE
C# runtime's tuple deconstruction incompatible with .NET Framework pre-4.7

### ISSUE THREAD

**Issue by alex-chew** [dafny-lang/dafny#1951]
The C# runtime in Dafny v3.5.0 uses tuple deconstruction (see first and last lines):

https://github.com/dafny-lang/dafny/blob/76c8d599155f45e9745ce854ab54d0ab4be52049/Source/DafnyRuntime/DafnyRuntime.cs#L1192-L1203

This is problematic because it fails to compile on .NET Framework versions below 4.7, which are [missing runtime support](https://github.com/Microsoft/dotnet/blob/master/releases/net47/dotnet47-changes.md#bcl) for this feature:

```
error CS8179: Predefined type 'System.ValueTuple`2' is not defined or imported [/home/runner/work/Foobar.csproj]
error CS8130: Cannot infer the type of implicitly-typed deconstruction variable 'leftBuffer'.
error CS8130: Cannot infer the type of implicitly-typed deconstruction variable 'rightBuffer'.
error CS8179: Predefined type 'System.ValueTuple`2' is not defined or imported
```

This seems to be a [known](https://stackoverflow.com/q/42549491) [issue](http://www.interact-sw.co.uk/iangblog/2018/04/12/deconstruct-keyvaluepair) that can be worked around either by manually deconstructing the tuple, or by [depending on the `System.ValueTuple` package](https://stackoverflow.com/a/38383064).

**Comment by alex-chew** [comment]
To add some context - we want to support .NET Framework 4.6.2 because Microsoft hasn't announced an end-of-support date: https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-framework

**Comment by texastony** [comment]
Ideally, Dafny would advertise the details of the supported compiled languages:
i.e.: Dafny's compiled output uses features from JavaScript X, Java Y, Go Z, etc.

**Comment by cpitclaudel** [comment]
> Ideally, Dafny would advertise the details of the supported compiled languages:

Or even better it would target a version so old that this issue doesn't even pop up

**Comment by alex-chew** [comment]
> > Ideally, Dafny would advertise the details of the supported compiled languages:

> Or even better it would target a version so old that this issue doesn't even pop up

Regardless of the age of language runtime versions that Dafny supports, I'd still prefer that Dafny be explicit about which versions it supports.

**Comment by robin-aws** [comment]
> Ideally, Dafny would advertise the details of the supported compiled languages:
i.e.: Dafny's compiled output uses features from JavaScript X, Java Y, Go Z, etc.

Split off #1983 to track this as a separate and actually more important ask.

**Comment by atomb** [comment]
I believe that this issue is fixed. Looking at the [latest version](https://github.com/dafny-lang/dafny/blob/master/Source/DafnyRuntime/DafnyRuntime.cs#L1314-L1325) of the runtime, it no longer uses tuple destruction. We're also building the runtime for framework `net452`, which I would imagine would fail if we were using features introduced more recently.
