### ISSUE TITLE
Empty type of let variable assumed before binding

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#1958]
The following program verifies, but should not:

``` dafny
type R = r: BaseType | r.i() witness *

function F(v: nat): R {
  var o: R := Ctor(v);
  o
}
```

The following similar code, but without the let expression, does produce an error (which is good):

``` dafny
function G(v: nat): R {
  Ctor(v) // error: This does not produce an R
}
```

A quick look at the generated Boogie shows that `var o: R ...` generates an assumption about `o`'s type before the RHS has been evaluated and checked. That assumption should not be there (at least for a possibly empty type).

**Comment by cpitclaudel** [comment]
@RustanLeino it looks like your OP is missing some context.  Do you still have the full example?

In the meantime, here's one possible completion:

```
type BaseType {
  predicate i()
}

function Ctor(x: nat) : R
  requires exists b: BaseType :: b.i()
{ var b : BaseType :| b.i(); b }

type R = r: BaseType | r.i() witness *

function F(v: nat): R {
  var o: R := Ctor(v);
  o
}
```

**Comment by RustanLeino** [comment]
@cpitclaudel  Sorry, I must have lost the rest of the example. But your example is good, and also I reconstructed a repro for when the function result is named. It think those example cover what this Issue is reporting.
