### ISSUE TITLE
Linter rule: `old` should only refer to heap values

### ISSUE THREAD

**Issue by mschlaipfer** [dafny-lang/dafny#1989]
Dafny does not provide a warning when using the `old` keyword on immutable values. This doesn't make sense and can lead to misunderstanding. Pointing this out in an analysis exposed via the IDE would clear this up.

For example, the following code verifies, and it's not immediately obvious why.

```dafny
module Test {

  class C {
  }

  function arrSet(a: array<C>) : set<object>
    reads a
  {
    set i : int | 0 <= i < a.Length :: a[i]
  }

  method test(a: array<C>, i : int, x : C)
    modifies a
    requires 0 <= i < a.Length
    requires x !in arrSet(a)
  {
    a[i] := x;
    assert(arrSet(a) == arrSet(old(a)));
  }
}
```

The reason that `assert(arrSet(a) == arrSet(old(a)));` verifies is that `old(a)` refers to the reference, and not to the values in `a`. This is [documented](https://dafny-lang.github.io/dafny/DafnyRef/DafnyRef#sec-old-expression), but a linter pass warning about using `old` on an immutable value would be helpful.

**Comment by keyboardDrummer** [comment]
I guess you want to receive a warning when `old` is used on an expression that does not contain a heap access, so `old` has no affect, is that right?
