### ISSUE TITLE
Variable name not occurring in program occurs in error message

### ISSUE THREAD

**Issue by mschlaipfer** [dafny-lang/dafny#1992]
In the following example I get the error message `missing case in match expression: c: int (not all possibilities for constant 'c' in context have been covered)Verifier
`

```dafny
function foo(x: int): int {
  match x // Error here
    case 0 => 1
}
```

**Comment by davidcok** [comment]
As of 4.0.0+ the error message is Error: missing case in match expression: not all possibilities for selector of type int have been covered

so the issue is resolved. Test case added.
