### ISSUE TITLE
Simplify using Dafny as a library

### ISSUE THREAD

**Issue by mschlaipfer** [dafny-lang/dafny#2084]
Currently, to use Dafny as a software library, one needs to use `DafnyPipeline.csproj` and then replicate most of the code in https://github.com/dafny-lang/dafny/blob/master/Source/DafnyDriver/DafnyDriver.cs in order verify a program. 

Dafny's CLI project, `DafnyDriver.csproj` is not published as a library (i.e., `<OutoutType>Library</OutputType>`). Furthermore, only the `Main` methods in DafnyDriver.cs are exposed with `public`, so one would need to pass an arguments string if it were available as a library in its current state.

**Comment by keyboardDrummer** [comment]
I suggest we publish `DafnyPipeline.csproj` as a NuGet library. Code that is in `https://github.com/dafny-lang/dafny/blob/master/Source/DafnyDriver/DafnyDriver.cs` and should be available to library consumers should be moved to `DafnyPipeline.csproj`.

I think we will publish `DafnyDriver.csproj` as a .NET tool at some point, which means we can't also publish it as a library.

**Comment by cpitclaudel** [comment]
> I suggest we publish DafnyPipeline.csproj as a NuGet library.

:+1:.  Also, we should refactor DafnyDriver, DafnyServer, and DafnyLanguageServer so that they all use a shared interface from DafnyPipeline.
