### ISSUE TITLE
parser crash on lambda taking a function from a nonexistent type 

### ISSUE THREAD

**Issue by erniecohen** [dafny-lang/dafny#2115]
The following triggers "Internal Error - System.InvalidOperationException: Sequence contains no elements" on 3.5.0.40314.
```
function f():() { (x:S->())=>() }
```

**Comment by erniecohen** [comment]
I recommend regular fuzz testing. (Or better, prove that Dafny doesn't crash.)

**Comment by cpitclaudel** [comment]
Duplicate of https://github.com/dafny-lang/dafny/issues/2104

**Comment by cpitclaudel** [comment]
> (Or better, prove that Dafny doesn't crash.)

Working on it :)
