### ISSUE TITLE
`{:rlimit}` is undocumented

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/dafny#2131]
The reference manual has a link to `#sec-rlimit`, but no such section exists in the manual.  @MikaelMayer did you intend to add one when you added the link?

**Comment by MikaelMayer** [comment]
Good catch. I did not intend to add one myself, but I thought it will eventually exist as this attribute is in the /attrHelp. I preferred to leave the link there to remind us one day (like today maybe?) that we need this documentation in DafnyRef.

**Comment by robin-aws** [comment]
It also seems like `{:rlimit N}` ends up setting an rlimit of `N * 1000` in Z3. @MikaelMayer
