### ISSUE TITLE
types imported via different paths aren't equivalent

### ISSUE THREAD

**Issue by jonhnet** [dafny-lang/dafny#216]
Suppose I want to define an abstract comparator, an abstract datatype, then define a concrete instance of the comparator, and bring that definition together with the ADT to create a concrete instance of the ADT. This implies a DAG of imports. Unfortunately, when importing names in a DAG, Dafny can't see that they're equivalent.

```
module Comparator {
    datatype Comparison = Less | Equal | Greater
    datatype Comparator<!V> = Comparator(cmp:(V, V)->Comparison)
}

module ADT {
    import opened C : Comparator

    datatype Struct<!V> = Struct(cmp:Comparator<V>, value: V)

    method New<V>(cmp:Comparator<V>, value: V) returns (s: Struct)
    {
        s := Struct(cmp, value);
    }

    
}

module IntConcreteComparator {
    import opened C : Comparator

    function method IntComparator() : Comparator<int>
    {
        Comparator((a, b) =>
            if a<b then Less else if a==b then Equal else Greater)
    }
}

module IntADT {
    import opened ADT : ADT
    import opened CC : IntConcreteComparator

    method NewIntADT() returns (s: Struct<int>)
    {
        var cmp : CC.C.Comparator := IntComparator();
        var cmp2 : ADT.C.Comparator := cmp;
        s := New(cmp2, 0);
    }
}
```
fails with
```module-dag.dfy(36,36): Error: RHS (of type CC.C.Comparator<int>) not assignable to LHS (of type ADT.C.Comparator<int>)```

I can work around this problem by straightening the DAG into a linear chain:

```
module Comparator {
    datatype Comparison = Less | Equal | Greater
    datatype Comparator<!V> = Comparator(cmp:(V, V)->Comparison)
}

module ADT {
    import opened C : Comparator

    datatype Struct<!V> = Struct(cmp:Comparator<V>, value: V)

    method New<V>(cmp:Comparator<V>, value: V) returns (s: Struct)
    {
        s := Struct(cmp, value);
    }
}

module IntConcreteComparator {
    import opened ADT : ADT

    function method IntCompare(a: int, b: int) : ADT.C.Comparison
    {
        if a<b then ADT.C.Less else if a==b then ADT.C.Equal else ADT.C.Greater
    }

    function method IntComparator() : ADT.C.Comparator<int>
    {
        ADT.C.Comparator(IntCompare)
    }
}

module IntADT {
    import opened CC : IntConcreteComparator

    method NewIntADT() returns (s: CC.ADT.Struct<int>)
    {
        var cmp : CC.ADT.C.Comparator := IntComparator();
        var cmp2 : ADT.C.Comparator := cmp;
        s := CC.ADT.New(cmp2, 0);
    }
}
```
Problem 1. Notice that I can't use a second *import opened* statement in the downstream modules, because it reintroduces the same problem; hence the example uses lots of fully-qualified names (```CC.ADT.C.Comparator```).

Problem 2. I don't want to organize my code that way. If I have two ADTs, does the ConcreteComparison module need to import both so that both can be instantiated? Yuck.

Problem 3. Even in the first example, I'm not delighted with tucking a comparator into a higher-order lambda  If that interface gets more complex, I sure would rather read it as a bunch of named function definitions. But I couldn't get 'abstract module' to do anything sane.

**Comment by acioc** [comment]
Let's add the above to documentation

**Comment by davidcok** [comment]
No change to code. Leaving it as a reminder to write RM material.

**Comment by davidcok** [comment]
As we are moving toward deprecating the import : , I won't burden the reference manual with an explanation of diamond type refinement.
