### ISSUE TITLE
Unsound recursion via a lambda that reads a mutable class field ("Landin's knot")

### ISSUE THREAD

**Issue by mattmccutchen-amazon** [dafny-lang/dafny#2178]
The following code achieves unrestricted recursion in ghost code via a lambda that reads another lambda from a mutable class field and invokes it, where the field contains a copy of the original lambda.  Like any unrestricted recursion, this can lead to unsoundness.  I tested the example on `master` as of this writing (c8598c83a09a2ae61f816d1a088a9959a14634b7).

```dafny
class Ref<T> {
  ghost var target: T
  constructor(target_init: T)
    ensures target == target_init {
    target := target_init;
  }
}
​
method Knot() ensures false {
  var r := new Ref<() ~> bool>(() => false);
  var tf := () reads r, r.target.reads() => (
    if r.target.requires() then !r.target() else false
  );
  r.target := tf;
  assert tf() == !tf();
  assert false;
}
```

Apparently this method of recursion is known as "Landin's knot", though I couldn't find a source that originally presented it under that name.  Credit goes to Cody Roux for asking whether Landin's knot could be realized in Dafny.

**Comment by MikaelMayer** [comment]
Wow what an awful finding! Thanks for spotting it.
I simplified the body, you don't need an if-then-else, only to ensure that invoking target is possible:
```dafny
  var tf := () reads r, r.target.reads() => (
    r.target.requires() && !r.target()
  );
```

This soundness issue is actually a more sophisticated version of:
```dafny
function contradiction(): bool {
  !contradiction()
}
```
which is (fortunately) not allowed because of termination check. The bottleneck here is that we are not checking termination for the finally-recursive call `!r.target()`

Here is ways we could fix the problem above.
- The `read()` clause of this function should itself have a termination check, because as defined, tf.reads() := { r } U r.target.reads() which can become nonterminating if `r.target := tf`; If we could prove that reads terminate, I bet we wouldn't be able to come up with one of the examples above. However, if this definition is not an assignment, but rather a definition to the limit (the smallest set such that), then we cannot do this.
- A dual call graph detection like for top-level declarations: Assuming closures are object, it's possible to compute the "dependency graph" of a function. For the function above, the "dependency graph" would be {r.target} U {r.target.dependencies()}. We only either need to prove that this dependency graph does not contain the function itself (`assert <function itself> !in {r.target} U {r.target.dependencies()}`), or that there is a `decreases` clause attached to closures that works like for functions or methods.

**Comment by atomb** [comment]
Although there's no reason to think that this is a new issue, I did a little investigation of how far back it goes. Dafny 3.0.0 accepts it. Dafny 2.3.0 does not, but for reasons having nothing to do with termination, so it may be possible to modify it to make it work with pre-3.0 versions.

**Comment by mattmccutchen-amazon** [comment]
Here are my thoughts about potential fixes.  Please take them with a shaker full of salt since this seems like a deep problem in program verification (as Cody has pointed out elsewhere) and I'm no expert in the area.

At risk of stating the obvious, I think our design goals are:

1. Fix the unsoundness.

2. Limit the disruption to legitimate code.

3. Limit the amount of complexity added to Dafny.

Re (2), I'm not familiar with the full range of real-world Dafny code that might be affected by any new restriction, but I can think of one example that I imagine would be valuable to keep working if feasible: the [function to map a lambda over a sequence](https://github.com/dafny-lang/libraries/blob/44f5891e7b5b21a5f13f139b22fb5559b46de36f/src/Collections/Sequences/Seq.dfy#L572-L581) from the Dafny libraries collection.  I'll quote it in full:
```dafny
  /* applies a transformation function on the sequence */
  function method {:opaque} Map<T,R>(f: (T ~> R), s: seq<T>): (result: seq<R>)
    requires forall i {:trigger s[i]} :: 0 <= i < |s| ==> f.requires(s[i])
    ensures |result| == |s|
    ensures forall i {:trigger result[i]}:: 0 <= i < |s| ==> result[i] == f(s[i]);
    reads set i, o {:trigger o in f.reads(s[i])} | 0 <= i < |s| && o in f.reads(s[i]):: o
  {
    if |s| == 0 then []
    else [f(s[0])] + Map(f, s[1..])
  }
```

One approach to a fix that seems promising to me is to just disallow storing functions that read memory (`A ~> B`) on the heap.  (Storing functions that don't read memory, i.e., of type `A --> B` or `A -> B`, would still be allowed.)  Users who want the effect of storing a function `A ~> B` would have to simulate it using a trait, at which point they become subject to the usual termination checks for trait methods, blocking the unsoundness (I hope; we should think about it more carefully).  For example, this code:
```dafny
class Foo {
  var x: int;
  var reader: () ~> int;
  constructor() ensures reader.requires() {
    x := 42;
    new;
    reader := () reads this => x;
  }
}
```
could be rewritten as follows:
```dafny
trait ReadingFun<A, B> {
  function method call(a: A): B reads *
}

class DummyReadingFun<A, B> extends ReadingFun<A, B> {
  const dummy: B;
  constructor(dummy_init: B) {
    dummy := dummy_init;
  }
  function method call(a: A): B reads * {
    dummy
  }
}

class FooReaderImpl extends ReadingFun<(), int> {
  const foo: Foo;
  constructor(foo_init: Foo) {
    foo := foo_init;
  }
  function method call(a: ()): int reads * {
    foo.x
  }
}

class Foo {
  var x: int;
  var reader: ReadingFun<(), int>;
  constructor() {
    reader := new DummyReadingFun(0);
    x := 42;
    new;
    reader := new FooReaderImpl(this);
  }
}
```
(I know that's a lot of boilerplate.  Maybe there are ways to simplify it.)

This approach potentially makes a lot of work for anyone who was storing `A ~> B` functions on the heap.  (How common is that?)  In exchange, users who don't store their `A ~> B` functions on the heap are completely unaffected.  For example, users can still do things like call `Map` with a callback that itself calls `Map` on a nested list, as long as the callback is never stored on the heap.  For users who do store `A ~> B` functions on the heap, most of the migration work is straightforward.  The part that might not be straightforward is proving termination, but I'm unclear on how much easier we can hope to make it and still maintain soundness.

One other issue with this approach is that to support class fields whose type involves type variables, we'd need a new type variable restriction for "does not contain functions that read memory", which could be written something like `A(!~>)`.  It would be annoying if a lot of existing code that doesn't use first-class functions at all had to be updated to add this constraint.  Hopefully it can be inferred automatically in most cases.

Re Mikaël's suggestions:

* I'm not sure that developing a framework to prove that `tf.reads` terminates would be any easier than our original problem of proving that `tf` terminates, as long as both `tf` and `tf.reads` have the ability to invoke arbitrary `A ~> B` functions read from memory.
* Under my proposal, the existing termination check for trait functions is probably somewhat similar to what you envisioned for `dependencies`.  Depending on your exact design, `dependencies` might be able to automatically verify some cases where trait functions would require extra work from the user, but we'd want to assess whether the extra precision justifies adding a new mechanism to Dafny.  Examples could be helpful here.

**Comment by cpitclaudel** [comment]
Let's merge this into #2750
