### ISSUE TITLE
Issue with compound argument of bit-vector type

### ISSUE THREAD

**Issue by VictorYYW** [dafny-lang/dafny#2193]
```
assert Bits.ToBv128(left, right) == (left as bv128 << 64) | right as bv128;
```
where `Bits.ToBv128` is a function and its body is exactly the same as the RHS. As expected, the assertion easily passes. However, when fed with a compound argument, Dafny timeout on the following assertion
```
assert Bits.ToBv128(left, right | (v << idx)) == (left as bv128 << 64) | (right | (v << idx)) as bv128;
```
Introducing a temporary variable does not help (regardless of ghost or not)
```
ghost var tmp := right | (v << idx);
assert Bits.ToBv128(left, tmp) == (left as bv128 << 64) | tmp as bv128;
```
However, if we make `tmp` a field of the class where the method we are trying to verify resides, Dafny is able to verify the assertion.

**Comment by cpitclaudel** [comment]
Thanks for the report!  Could you give a self-contained version of that example?  It's pretty tricky to reason about this as-is, since I don't have the definition of `ToBv128`

**Comment by VictorYYW** [comment]
Sorry about the late reply! Looking back, I feel like it is an issue about unstability in Dafny -- the issue only occurred when the assertion is in a specific proof context. I resolved the issue by adding `{:vcs_split_on_every_assert}` to the method to be proved. The assertion alone, as shown below, is not problematic.
```Dafny
function ToBv128(left: bv64, right: bv64): bv128 {
  (left as bv128 << 64) | right as bv128
}

method M(left: bv64, right: bv64, v: bv64, idx: nat)
  requires idx <= 64
{
  assert ToBv128(left, right) == (left as bv128 << 64) | right as bv128;
  assert ToBv128(left, right | (v << idx)) == (left as bv128 << 64) | (right | (v << idx)) as bv128;
}
```
With that being said, I will close the issue.
