### ISSUE TITLE
Show expected argument types for incorrect number of arguments

### ISSUE THREAD

**Issue by codyroux** [dafny-lang/dafny#2200]
Currently (v 3.6.0) when a function gets an incorrect number of arguments, the following message is displayed:

```
(7,5): Error: wrong number of arguments (function 'foo' expects 2, got 1)
```

In my development flow, I often know which function to call, but need to figure out which arguments to call it with; having the argument types in the error message would greatly help with that.

E.g.
```
(7,5): Error: wrong number of arguments (function 'foo' expects 2 parameters 'a' of type int, 'b' of type string, got 1)
```

or maybe

```
(7,5): Error: wrong number of arguments (function 'foo' expects 2 parameters (a: int, b: string), got 1)
```
but that is less in tune with the error message on mismatched types (but correct number of args).

An obvious workaround is to guess the number of arguments, and give them "dummy" values, e.g. `42`, but this seems like a pretty easy fix.

**Comment by atomb** [comment]
I agree. This would be a nice improvement to the message.

**Comment by codyroux** [comment]
@MikaelMayer yes, most likely. (But then I'd be tempted to ask for type holes _a la_ Haskell https://wiki.haskell.org/GHC/Typed_holes :) )
