### ISSUE TITLE
Calling `f.reads(x)` on `x` such that `!f.requires(x)` leads to unsoundness

### ISSUE THREAD

**Issue by mattmccutchen-amazon** [dafny-lang/dafny#2201]
Here's a soundness bug I noticed while reading the reference manual, confirmed on `master` as of a few days ago (5cc1331858342042a45c7a4b86bf754f18487b99).  Please prioritize it as you see fit.

As [the reference manual says](https://dafny.org/dafny/DafnyRef/DafnyRef#sec-arrow-types):

```dafny
f.reads.requires(t) == true
```

But the `reads` clause of a function `f` seems to be verified under the assumption that the `requires` clause holds.  Thus, the user can call `f.reads` with an argument for which it wasn't verified, which seems potentially dangerous.

At first, I tried performing invalid operations such as indexing sequences out of bounds, but I wasn't able to prove `false` that way.  The reason seems to be that operations such as sequence indexing are valid at the Boogie level regardless of their operands, and their behavior is characterized by Dafny-generated axioms that each have a hypothesis that the preconditions of the individual operation are satisfied.  Thus, I couldn't deduce anything about the return value of an invalid operation that would lead to a contradiction.

However, I was able to get a contradiction by using the frame axiom for `f.reads`.  The reference manual says `f.reads.reads(t) == f.reads(t)`, i.e., the `reads` clause may only read objects that are themselves included in the returned set.  But this condition is only checked under the assumption that the `requires` clause holds.  So we can just specify `requires false`, write a `reads` clause that returns different values depending on a value read from an object not in the returned set, and apply the frame axiom.

An example:
```dafny
class MyObject {
  var inner: MyObject?;
}

function f(o: MyObject): ()
  requires false
  reads {o.inner} {
  ()
}

method m() ensures false {
  var outer := new MyObject;

  var inner1 := new MyObject;
  outer.inner := inner1;
  var reads1 := f.reads(outer);
  assert reads1 == {inner1};

  var inner2 := new MyObject;
  outer.inner := inner2;
  var reads2 := f.reads(outer);
  assert reads2 == {inner2};

  // Frame axiom for f.reads, because the only object we modified is `outer`,
  // and it is not an element of `reads1`.
  assert reads1 == reads2;
  assert false;
}
```

The obvious approach to a solution is to redefine `f.reads.requires(t) == f.requires(t)`, but unfortunately I don't think this is sufficient.  As long as `f.requires` is a first-class function with `f.requires.requires(t) == true` and `f.requires.reads(t) == f.reads(t)`, then we just let `g := f.requires` and replace `f` with `g` in the body of `m`.  We'll be able to call `g.reads` because `g.reads.requires = g.requires = f.requires.requires` is true, and then we'll get the same contradiction based on the values actually returned by our `reads` clause.

In essence, if we want to keep `f.requires` as a first-class function with `f.requires.requires(t) == true`, then we need a function `f.requires.reads` that is valid (e.g., satisfies the frame axiom) on the entire domain of `f.requires`.  We could set `f.requires.reads(t) = *`, but that would be painful for a function such as [`Map` in the Dafny library collection](https://github.com/dafny-lang/libraries/blob/44f5891e7b5b21a5f13f139b22fb5559b46de36f/src/Collections/Sequences/Seq.dfy#L572-L581) whose `requires` clause calls an `f.requires` function: for the `requires` clause to verify, the `reads` clause would have to be changed to `reads *`, which would then affect callers.

If we want a precise `f.requires.reads` function, conceivably Dafny could try to infer it by combining the user-specified `requires` and `reads` clauses, but I don't know if this could be made to work well for arbitrary code.  Instead, we may need to just make the user write the original `reads` clause of `f` so that it verifies without assuming the `requires` clause.  This may be painful if it forces the user to duplicate checks in the `requires` clause as conditionals in the `reads` clause.  One way to ease that pain would be to allow the `requires` and `reads` information to be specified in the form of a combined clause that returns a `datatype ReqRead = ReqRead(req: bool, read: set<object?>)` and then provide language constructs to facilitate working with `ReqRead` objects, such as an `&&`-like operator that short-circuits on the `req` field and also combines the `read` fields.  That would still require significant reworking of existing code, but at least the end result would be nicer.  In cases such as `Map` where the `requires` and `reads` already contained parallel logic, the end result may even be nicer than what we started with, something like:
```dafny
  function method {:opaque} Map<T,R>(f: (T ~> R), s: seq<T>): (result: seq<R>)
    reqreads ReqRead.combine(set i | 0 <= i < |s| :: f.reqreads(s[i]))
    /* other clauses and body... */
```
I can imagine various other possible compromises, but rather than taking the time to try to work out the details myself, I'll let the experts here come up with their own ideas, which are probably better than mine. :slightly_smiling_face:

**Comment by atomb** [comment]
Thanks for a thorough report of the issue!

**Comment by RustanLeino** [comment]
Yes, this is a bug. While `f.requires(x) == true` (that is, the `.requires(x)` member should always allow one to ask if the precondition holds, even for values of `x` for which it does not hold), it should be that `f.reads.requires(x) == f.requires(x)` (that is, to ask for the reads frame of a function applied to `x`, one should first have to prove that the precondition holds for `x`). It may be, as you talk about above, that the latter shouldn't be an equality.

A related problem is that `reads f` currently desugars to `set x, obj | obj in f(x) :: obj`. This is also ignoring the precondition of `f`, which it shouldn't. (When bug 2201 is fixed, our test suite is likely to detect the problem I'm mentioning here, since the desugaring is passed through the verifier.)

Btw, in some related things that I happened to explore this afternoon, I believe I found that `f.reads(x)` (which internally uses a `FunctionCallExpr` where the function being called is the `MemberSelectExpr` that selects member `reads` from the value returned by the expression `f`) immediately uses `true` as the precondition (which is consistent with your bug report above). But I think I saw that `(f.reads)(x)` (that is, an `ApplyExpr` where the function is the first-class function value returned by the expression `(f.reads)`) may actually have a non-`true` precondition. I may be mistaken, but this should be revisited when this bug is fixed, to make sure the two are in sync.

**Comment by jtristan** [comment]
After some discussion with @RustanLeino , we concluded that the following set of axioms
is necessary to ensure soundness.

```
f.reads.requires(t) == f.requires(t)
f.requires(t) ==> f.reads.reads(t) == f.reads(t)
f.requires.requires(t) == true
f.requires(t) ==> f.requires.reads(t) == f.reads(t)
```

We are still investigating whether they are sufficient.

To this end, we would need to update the verifier (Translator.cs) and in particular the FuntionHandle and AddArrowTypeAxioms methods.

**Comment by jtristan** [comment]
Fixing the logical part of this issue revealed a compounding issue with the verifier. We are going to fix them separately, and as a result will close this issue and replacing it with #4488 and #4489
