### ISSUE TITLE
Unstable CI test OpeningDocumentWithMultipleVerificationCoresReturnsStableDiagnostics

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#2210]
Appeared in [this PR CI tests](https://github.com/dafny-lang/dafny/runs/6757591932?check_suite_focus=true):

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed OpeningDocumentWithMultipleVerificationCoresReturnsStableDiagnostics [19 s]
  Error Message:
   Assert.AreEqual failed. Expected:<5>. Actual:<4>. 
  Stack Trace:
     at Microsoft.Dafny.LanguageServer.IntegrationTest.Synchronization.DiagnosticsTest.OpeningDocumentWithMultipleVerificationCoresReturnsStableDiagnostics() in D:\a\dafny\dafny\Source\DafnyLanguageServer.Test\Synchronization\DiagnosticsTest.cs:line 602
```

I've assigned it to you, @keyboardDrummer  because it might be related to the way GetLastDocument now works. Can it miss diagnostics?

**Comment by keyboardDrummer** [comment]
`Severity: low` ? I would rather say this is critical than low

**Comment by MikaelMayer** [comment]
Low as described means there is a workaround, in this case, just re-run the failing test. However, it's is critical we still solve this issue.

**Comment by keyboardDrummer** [comment]
Closing because it might be resolved after recent merges.
