### ISSUE TITLE
Support `or` patterns in matches

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/dafny#2220]
Desired syntax:

```dafny
datatype T = A(i: int) | B(j: int) | C(bool) | D

method Test(t: T) {
  match A
    case A(i) | B(i) => print i;
    case C(_) | D => print "";
}
```

**Comment by cpitclaudel** [comment]
It was a typo, good catch; thanks!  I was hoping to use that case to demonstrate that you could use `_` :/

**Comment by MikaelMayer** [comment]
What about:

```dafny
method Test(t: T) {
  match AORB(t)
    case X_AORB(i) => print i;
    case X_OTHER => print "";
}

function method AORB(t: T): XT {
  if t.A? then X(t.i) else if t.B? then X(t.i) else X_OTHER
}
```

**Comment by cpitclaudel** [comment]
There are a few problems with this alternative:

- It's longer than the original code
- It has a runtime cost.
- It doesn't scale: you have to define a new datatype and a new function to project the original one for each new match that groups constructors differently.  

When you have tens of constructors, it's not really viable to do it this way, I think (and even for this specific example, I find the `or` pattern a lot more readable)

**Comment by cpitclaudel** [comment]
In the long term, we'd like to have support for fully general or-patterns, including or patterns nested inside constructors and or patterns including variables.  Prior to doing this, we need to refactor the computation of pattern match decision trees, which currently is done during resolution.

For the first iteration of this feature, we'll support only top-level patterns with `_`, literals, and constructors — no variable bindings and no nested `|` patterns.
