### ISSUE TITLE
LSP Crashes during editing because failed position

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#2246]
I have code that now looks like this:

```dafny
// Trait.
method {:extern} mymethod() {}
```

and it now throws an error when I place my cursor over the "." saying that it's not a valid position on hover and crashes. The error message is interesting, because it explains that my current text is:
```dafny
// T
a
method {:extern} mymethod() {}
```
The error is the following:

>  Message: Internal Error - System.ArgumentException: could not resolve the absolute position (line: 0, char: 8) in text 

So there is a discrepancy between what LSP believes my code is and what my code is actually. I don't know exactly what are the steps that I did to arrive at that point, only that I added a newline and then wrote `// Trait.` perhaps with a typo that I fixed and then realized that something was wrong with lots of error messages.

**Comment by MikaelMayer** [comment]
I have a trace of all the edits, I'm going to investigate it. It could be related to the LSP handling events in the wrong order. I was typing very fast.

**Comment by MikaelMayer** [comment]
So the trace of edits looks like this:

1. line 10 character 0: inserted "\r\n"
1. line 11 character 0: inserted "/"
1. line 11 character 1: inserted "/"
1. line 11 character 2: inserted " "
1. line 11 character 3: inserted "T"
1. line 11 character 4: inserted "r"
1. line 11 character 5: inserted "a"
1. line 11 character 6: inserted "i"
1. line 11 character 7: inserted "t"

So my current interpretation is that it performed steps 2-4 first, (that's why we have `// ` on a line) and then it performed 1, and then 5, 6, 7, 8,

When I look at the errors, it says I first hovered over the "t" of `// Trait` (position 7), and at the time the text of Dafny was believed to be the following: (`document.TextDocumentItem.Text`)

```dafny
// 
r
method {:extern} 
```

then later as I wrote a dot, and hovered the dot again (on `// Trait.`), the text was believed to be the following:

```dafny
// T
a
```

After a few more tries, the language server never recovered.

**Comment by cpitclaudel** [comment]
Could it be that the location request is resolved before other previous messages (document updates) are processed?

**Comment by MikaelMayer** [comment]
It could be, but it fails consistently, and when I look at a processing request and the current document text, it's wrong.

**Comment by cpitclaudel** [comment]
> but it fails consistently, 

!! Nice

**Comment by keyboardDrummer** [comment]
One thing I've noticed is that we update our text buffer quite late in the change request handling process, so if a crash occurs, the text buffer might not get updated and then the LSP server state is corrupted and subsequent request may fail with errors such as the one in this issue.

I'll move updating the text buffer to the top of the change handler, which I think should improve graceful degradation.

**Comment by MikaelMayer** [comment]
I think this issue has been fixed, otherwise we will reopen it.
