### ISSUE TITLE
Dafny translates a file from the standard library to a syntacticly invalid Boogie code

### ISSUE THREAD

**Issue by Dargones** [dafny-lang/dafny#2263]
Version of Dafny (current HEAD): `92736033599c34dc3c5cd9f0f46e3dccbd5a3210`
Version of Standard Library (also current HEAD): `44f5891e7b5b21a5f13f139b22fb5559b46de36f`

How to reproduce:

1. Generate Boogie code (note that Dafny successfully verifies the file): `dotnet dafny-head/Binaries/Dafny.dll libraries/src/Collections/Sequences/Seq.dfy /print:Seq.bpl /compile:0`

1. Attempt to verify generated code with Boogie 3.15 (version currently used by Dafny): `dotnet boogie-2.15.0/Source/BoogieDriver/bin/Debug/net6.0/BoogieDriver.dll /infer:j /proverOpt:O:auto_config=false /proverOpt:O:type_check=true /proverOpt:O:smt.case_split=3 /proverOpt:O:smt.qi.eager_threshold=100 /proverOpt:O:smt.delay_units=true /proverOpt:O:smt.arith.solver=2 Seq.bpl`

Error message:

```
Seq.bpl(20222,43): error: the type of the last parameter is unspecified
1 parse errors detected in Seq.bpl
```

Here is the line mentioned in the error message: 
`function Reads1#Handle(#$T0: Ty, #$R: Ty, HandleType) : HandleType;`

**Comment by Dargones** [comment]
The problem appears to manifest itself starting with this commit: https://github.com/dafny-lang/dafny/commit/81cf582cce3fdeb482ed2746da6a812df8023514

**Comment by robin-aws** [comment]
Thanks for the report @Dargones. If I'm following correctly, there is either something different in the way that you're invoking Boogie directly compared to how Dafny does, or there is a bug in the Boogie printer (`/print`) that produces a slightly different program. To help diagnose which is the case: how did you determine the correct set of CLI parameters to pass to Boogie?

**Comment by Dargones** [comment]
Thank you, @robin-aws. I think the issue is a one-line bug with the Translator (see the PR above) but I am not completely sure. If my fix is correct, could you merge it? It would speed me up on advancing test generation!

As for parameters I pass to Boogie, I used [these](https://github.com/dafny-lang/dafny/issues/1153)
