### ISSUE TITLE
Wanna see a really weird typechecker bug?

### ISSUE THREAD

**Issue by jonhnet** [dafny-lang/dafny#227]
In the enclosed example, note that tla_crash_safe_disk_refinement.dfy typechecks (but doesn't verify) just fine. Then uncomment line 228 -- an expression in the bowels of a calc -- and all heck breaks loose. Suddenly the type check for Is' back on line 203 fails -- even though the type of the LHS should be inferred anyway! This isn't a verification failure; it's something bonkers in the type system. Some collision of an internal name with my variable names? It's really confusing.

**Comment by jonhnet** [comment]
Further fiddling (adding explicit types to the var:=) leads me to believe this error _should_ have been:
Error: all lines in a calculation must have the same type
...because there is indeed a typecheck error inside the calc. But somehow that error caused Dafny to reconsider the type of the var back at the assignment, even though the assignment fully constrains the variable's type.

**Comment by davidcok** [comment]
Verified that current master has correct behavior. Added the given case as a test. PR #710
