### ISSUE TITLE
Verification diagnostics not updated correctly

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#2349]
Take the following file, no IDE caching, and verification on save
```dafny
method test() {
}

// Press and hold enter for two seconds before this function
function f(i: int, j: int): int
{
   1 +
    (assert i == 1; i) +
    (assert j == 1; j)
}
```
* Save so that it finishes verification
* Press and hold enter for two seconds before the function.
* The verification are not migrated and completely disappear.

**Comment by keyboardDrummer** [comment]
Can't reproduce in latest VSCode extension
