### ISSUE TITLE
Dafny 4 proposal: Make `-xyz` mean the same as `-xyz:1` when `-xyz` accepts only `:0` and `:1`

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/dafny#2360]
We have `-showSnippets:<0|1>` but `-printTooltips` (no `:1`, my fault) and `-funcCallGraph` (not my fault).  This is confusing and unnecessary.

Also, let's move to named options (as in `-printIncludes:<None|Immediate|Transitive>`) instead of numeric ones (`-compile:<0-4>`).

**Comment by cpitclaudel** [comment]
Actually, this doesn't even have to be a Dafny 4 proposal, we could do it right now.

**Comment by davidcok** [comment]
And :true and :false as preferred alternatives to :0 and :1 ?

**Comment by cpitclaudel** [comment]
I'm more used to `:on` and `:off`, but I like this!

**Comment by RustanLeino** [comment]
Note that Boogie (and thus Dafny) allows both `/flag:arg` and `/flag arg`, which means you need to know the exact number of arguments that a command-line option has.

As @cpitclaudel just suggested in a private conversation, the (breaking) change suggested by this Issue would be good to act on at the same time as adding the elsewhere-proposed `dafny <verb> <arguments>` syntax (https://github.com/dafny-lang/dafny/issues/2036).

**Comment by robin-aws** [comment]
Just to clarify, AFAICT adding the new syntax isn't a breaking change by itself, only no longer accepting the old one. If the plan is to accept the new syntax when and only when (wwhen? :) using the new `dafny <verb> <arguments>`, then this doesn't have to be done over the Dafny 4.0 bump.

The part that WOULD be a breaking change is to no longer accept the old argument syntax, or more likely to start requiring a top-level verb. Dropping that support DOES require a major version bump for sure. But continuing to support the old syntax doesn't seem too onerous to me so I don't think it's worth being that aggressive. We can save that for Dafny 5.0. :)

(Conservatively tagged with breaking-change just in case this perception is off)

**Comment by cpitclaudel** [comment]
> Just to clarify, AFAICT adding the new syntax isn't a breaking change by itself, only no longer accepting the old one.

I think it would be breaking: `-showSnippets 1` means the same as `-showSnippets:1`, and it would not mean the same after the change.

**Comment by robin-aws** [comment]
We can make it not breaking by containing that syntax over the change to use top-level verbs:

1. `dafny /compile:0 /showSnippets` - Rejected (missing argument)
1. `dafny /compile:0 /showSnippets:1` - Accepted
1. `dafny /compile:0 /showSnippets 1` - Accepted
1. `dafny verify /showSnippets` - Accepted
1. `dafny verify /showSnippets:1` - Accepted
1. `dafny verify /showSnippets 1` - Rejected ("1" is not a valid file, or something like that)

I may not have all of those exactly right depending on the exact proposal for that specific option, but the general pattern should apply no matter how we want to change the syntax.
