### ISSUE TITLE
Map-extensionality axioms are unsound

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#2375]
The verifier encodes a `map` comprehension by a triple `(keys, values, type)`. This triple is constructed using a function called `Map#Glue`. The idea is that the second component of this triple (`values`) is a Boogie map where only the mappings from the `keys` should matter. Regrettably, the `Map#Elements` function currently returns the second component of `Map#Glue` without, in any way, projecting that Boogie map to the `keys`.

To demonstrate the unsoundness, start by translating the following Dafny program to Boogie:

``` dafny
function F(x: nat): nat { x }
function G(x: nat): nat { if x < 100 then x else x + 1 }

ghost method Test() {
  var m := map i | 0 <= i < 10 :: F(i);
  var n := map i | 0 <= i < 10 :: G(i);
  assert m == n;
  assert false;
}
```

Then, in the generated Boogie, before the translation of the `assert false;`, insert

``` boogie
assert Map#Elements(m#0)[$Box(200)] == $Box(200);
assert Map#Elements(n#0)[$Box(200)] == $Box(201);
```

Now, the entire Boogie program, including the `assert false;`, verifies.

**Comment by jtristan** [comment]
Found solution to #4147 so closing again.
