### ISSUE TITLE
Incompleteness in map cardinality equality

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#2380]
The following without uncommenting the commented line fails to verify:
```dafny
method M(t: map<int, int>, k: int)
  requires k in t
{
  var lt := |t|;
  var lt' := |t - {k}|;
  // var _ := |(t - {k}).Keys|;
  assert lt == lt' + 1;
}
```

Uncommenting the line makes it verify, because it triggers an axiom that is needed.

**Comment by cpitclaudel** [comment]
Assigning myself; the issue is with the triggers of the Map#Card / Set#Card axioms
