### ISSUE TITLE
Confusing error message in override check for `modifies` clause

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/dafny#2384]
The following example causes Dafny to complain about reads:

```
trait T {
  method M()
}

class C {}

class C' extends T {
  var c: C
  constructor (c: C) { this.c := c; }
  method M() // expression might read an object not in the parent trait context's reads clause
    modifies this.c
  {
  }
}
```

There are two problems here:

1. The error mentions an expression, but it doesn't point to one (it's attached to `M`)
2. The error talks about a `reads clause`, but the problem is with a `modifies` clause.  There are no explicit read clauses in this program, so if the problem is that the `modifies` expression reads too much, it would be much better to have a custom message to report that.

h/t @seebees

**Comment by seebees** [comment]
I would also review the error message for locations and field names.
There are some cases were it is pretty unclear _what_ Dafny is concerned is being modified.
If, for example, a stack of methods is getting called
the `modifies` clause needs to agree everywhere and it can be unclear at the top of the stack (first caller)
what is getting modified...

**Comment by seebees** [comment]
different error, but basically the same "problem". This talks about `decreases` instead of `reads`

```dafny
trait T {
  predicate P()
    reads {this}
}

class C extends T {
  predicate P() // predicate's decreases clause must be below or equal to that in the trait
  {
    true
  }
}
```

**Comment by RustanLeino** [comment]
In @seebees 's example, the problem stems from the automatically generated `decreases` clause. It would be nice to change `decreases clause` to `(automatically generated) decrease clause` in the error message in this case, to try to reduce confusion.
