### ISSUE TITLE
Initializing a new array with an initializer function not documented

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#2415]
There are three cases for array initialization, and the reference manual doesn't mention the third (using an initializer function, as in sequence constructions like `seq(5, i => i * 2)`):

```dafny
var a := new int[5];                // Elements initialized with arbitrary values
var b := new int[] [1, 2, 3, 4, 5]; // Elements initialized with the given values
var b := new int[5] (i => i * 2);   // Elements initialized with the given initializer function

```

**Comment by cpitclaudel** [comment]
I think it's mentioned already in 

`````
## 21.16. Array Allocation
````grammar
ArrayAllocation_ =
  "new" [ Type ] "[" [ Expressions ] "]"
  [ "(" Expression(allowLemma: true, allowLambda: true) ")"
  | "[" [ Expressions ] "]"
  ]
````

This allocates a new single or multi-dimensional array as explained in
section [Section 15](#sec-array-types).
The initialization portion is optional. One form is an
explicit list of values, in which case the dimension is optional:
```dafny
var a := new int[5];
var b := new int[5][2,3,5,7,11];
var c := new int[][2,3,5,7,11];
var d := new int[3][4,5,6,7]; // error
```
The comprehension form requires a dimension and uses a function of
type `nat -> T` where `T` is the array element type:
```dafny
var a := new int[5](i => i*i);
```
`````

**Comment by davidcok** [comment]
Yes it is, but there is a discussion of initialization both in the presentation of array types and in the presentation of array allocation expressions. The comprehension option was missing (but is now added) in the array type section, though it was  (and is) present in the expression section.

I suppose there is an opportunity to avoid duplication, but it is annoying to a reader to be constantly pointed to another section of the manual (and that also raises the danger of circular references that never say the actual information)

**Comment by cpitclaudel** [comment]
I think that's fair.  We might consider mentioning the multi-dimensional case on both sides too, then?

**Comment by davidcok** [comment]
I did add some text

**Comment by cpitclaudel** [comment]
Not in https://github.com/dafny-lang/dafny/pull/2419/files , right?

**Comment by davidcok** [comment]
I don't recall which PR it was in, but the text for multi-dimensional arrays is now (I decided not to duplicate the description for this case)

"In contrast to one-dimensional arrays, there is no operation to convert stretches of elements from a multi-dimensional array to a sequence.

There is however syntax to create a multi-dimensional array value using a function: see [Section 21.16](https://dafny.org/dafny/DafnyRef/DafnyRef#sec-array-allocation).
"
