### ISSUE TITLE
feat: Expand Main() to take command-line arguments

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#2420]
For most compilation targets there does not seem to be a way to use the command-line arguments in the Dafny generated executable. This just seems a usability problem. Suggest that Dafny allow Main() to take an array or seq of string as well as the current 0-arity Main().

**Comment by davidcok** [comment]
Well I didn't remember that I had already suggested this in #1116

**Comment by robin-aws** [comment]
Closed as duplicate
