### ISSUE TITLE
Allow compilation of `assume {:axiom} P`

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#2426]
The compiler currently rejects all `assume` statements, under the assumption that they are only for use in pure modelling/proof assistant applications or as temporary "TODO"s while developing. However, this is easy to work around by defining and using this lemma:

```dafny
lemma {:axiom} Assume(p: bool) ensures p
```

The `{:axiom}` attribute is generally used to assume the post-condition of something without proof, and is reasonable to use in cases where a proof is intractable or very expensive. We might as well allow compilation of `assume {:axiom} P` (that is, it should be erased rather than rejected) as a more convenient alternative to the lemma above.

**Comment by keyboardDrummer** [comment]
Should allowing this be behind a CLI flag?

**Comment by cpitclaudel** [comment]
> Should allowing this be behind a CLI flag?

Yes: once we have a flag for `{:axiom}` on methods and functions, it should cover `{:axiom}` on assume statements as well.

 Do we have an issue to track this?

**Comment by cpitclaudel** [comment]
Implemented in https://github.com/dafny-lang/dafny/pull/2510
