### ISSUE TITLE
Generated Java vulnerable to name confusion

### ISSUE THREAD

**Issue by texastony** [dafny-lang/dafny#2441]
### **What is happening**?

I have `ADataType` that depends on `AnotherDataType` that can only be `A_CONSTANT`.

I compile that from Dafny to Java.
I try to compile the Generated Java.
Java is an unhappy.

### **How can any one reproduce this?**
Download this: [July18.zip](https://github.com/dafny-lang/dafny/files/9135427/July18.zip)
Unzip it: `mkdir July18; unzip July18.zip -d July18`
Glance at the `build.zsh` to ensure that I am not hacking your computer: `less July18/build.zsh`.
See that I depend on `dafny` and `mvn`.
Run the build: `cd July18; ./build.zsh`.
See the Compile error.

### **What is expected?**
I expect valid Dafny to become Valid Java.

### **I have a fix suggestion**
When generating Java, fully qualify Dafny generated Java objects.

The issue is that I have been a jerk and ~~ambiguously~~ poorly named the field
of my `ADataType` to be identical to the field's Datatype's name.

Thus Java is upset, 
because it appears to be using a non-static field
in a static method.

Which is not Dafny's intent,
it is trying to use the Datatype's static method.

Which can be achieved by changing the manner the `Default` method is called,
by fully qualifying it as `Example.Types.AnotherDataType.Default`.

### **What is my environment**:
I am using: `Dafny 3.6.0.40511` on a Mac OS X ( `11.6.6 (20G624)` ).
The `pom.xml` specifies Java-11.

**Comment by robin-aws** [comment]
Thanks for the detailed bug report! Note that it's pretty easy to reproduce this with a simple CLI command on the source in the zip:

```dafny
module {:extern "Example.Types" } Types
{
  datatype ADataType = | ADataType (
    nameonly AnotherDataType: AnotherDataType
  )

  datatype AnotherDataType = | A_CONSTANT
}
```

```
$ dafny src/Scratch.dfy /compileTarget:java

Dafny program verifier finished with 0 verified, 0 errors
Wrote textual form of target program to Scratch-java/Scratch.java
Additional target code written to Scratch-java/Example/Types/ADataType.java
Additional target code written to Scratch-java/Example/Types/AnotherDataType.java
Additional target code written to Scratch-java/_System/nat.java
Picked up JAVA_TOOL_OPTIONS: -Dlog4j2.formatMsgNoLookups=true
/Users/salkeldr/Documents/GitHub/libraries/src/Scratch-java/Example/Types/ADataType.java:39: error: non-static variable AnotherDataType cannot be referenced from a static context
  private static final ADataType theDefault = Example.Types.ADataType.create(AnotherDataType.Default());
                                                                             ^
1 error
Error while compiling Java files. Process exited with exit code 1
```
