### ISSUE TITLE
Would love to name predicate result

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#2453]
Consider this:

```
predicate method {:opaque} MyPredicate(
  a: A,
  b: B,
  c: C
  d: D,
  e: E)
  ensures (...)MyPredicate(a, b, c, d, e) (...)
  ensures (...)MyPredicate(a, b, c, d, e) (...)
  ensures (...)MyPredicate(a, b, c, d, e) (...)
{
  (...)
}
```
To specify conditions about the return value of this predicate, I need to repeat the entire predicate.
It would be nice if, like for functions, we could give the predicate's value a name. This would
* Make it easier for maintaining the signature of such predicates
* Reduce code size
* Make it consistent with functions.

**Comment by keyboardDrummer** [comment]
> It would be nice if, like for functions, we could give the predicate's value a name

Do you mean like for methods, we could give the return value a name?
