### ISSUE TITLE
Dafny cheatsheet should be moved into docs

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#2475]
We have this link to a Google doc from our README: https://docs.google.com/document/d/1kz5_yqzhrEyXII96eCF1YoHZhnb_6dzv-K3u79bMMis/edit?pref=2&pli=1#

It's a blind spot in our documentation maintenance, and the style is inconsistent with the rest of our documentation. It also has a dead link to rise4fun.com that needs to be removed.

**Comment by robin-aws** [comment]
@davidcok Do you have access to edit that doc by chance?

**Comment by davidcok** [comment]
I have requested edit access. I don't remember who authored it, but id does date back ~2 years at least.
