### ISSUE TITLE
Confusing message about automatically generated decrease clauses

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/dafny#2477]
Forked from #2384 :

```
trait T {
  predicate P()
    reads {this}
}

class C extends T {
  predicate P() // predicate's decreases clause must be below or equal to that in the trait
  {
    true
  }
}
```

Quoth @RustanLeino : the problem stems from the automatically generated `decreases` clause. It would be nice to change `decreases clause` to `(automatically generated) decrease clause` in the error message in this case, to try to reduce confusion.

**Comment by RustanLeino** [comment]
An additional note: I had expected to IDE to provide hover text that shows what the two default `decreases` clauses are. Apparently, we don't generate any such hover text in this case. We should.

**Comment by davidcok** [comment]
Fixed
