### ISSUE TITLE
Add `Rewriter.PreResolve` method to allow transforming parsed AST before it is type-checked

### ISSUE THREAD

**Issue by amaurremi** [dafny-lang/dafny#2479]
The use case I'm looking for is to automatically add imports (to a custom standard library for a custom Dafny compiler) to all modules in a Dafny project, without having the user having to choose which standard-library files to add.

**Comment by cpitclaudel** [comment]
Is this in the context of plugins? We already have `internal virtual void PreResolve()` on `IRewriter`, so maybe the easiest would be to let plugins implement the whole IRewriter interface?

**Comment by amaurremi** [comment]
I actually ended up not needing this any more, but if I do I'll follow your suggestion. Thanks!
