### ISSUE TITLE
lemma vs. ghost method

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#2498]
The RM says that a lemma is a ghost method.
In places where a method may be called, it does not matter whether the lemma is named a ghost method.

But some situations, at least calc and assert-by statements, require the method to be called a lemma and reject it if it is called a ghost method.

1) do we want to change Dafny so that `lemma` and `ghost method` are entirely equivalent?, or
2) do we like the distinction because `lemma` emphasizes the purpose of the method at hand?

**Comment by robin-aws** [comment]
My 2 cents is that the distinction between `lemma` and `ghost method` is very small and subtle, and I'd prefer there was just one concept and one name for it.

Given the meaning of the term "lemma" literally only makes sense in the context of a larger proof, and yet there is no actual "proof" concept in Dafny source code terminology, I vote for using `ghost method` instead. It would be the most consistent with post `/functionSyntax:4` keyword usage as well.

**Comment by robin-aws** [comment]
Mind you, just as we have `predicate` as sugar for `function that returns a bool`, we could keep `lemma` as `ghost method that modifies and allocates nothing`. But I think I'm still inclined to just have calling contexts enforce that extra restriction on `ghost method` calls instead. This would again be more consistent with the existing framing verification of regular method calls.

**Comment by atomb** [comment]
Another argument for preferring `ghost method` is that it emphasizes the similarity with a compiled method, which makes the idea of testing for assurance less surprising.

**Comment by robin-aws** [comment]
I think we don't need a breaking change here, if we keep `lemma` as a pure alias for `ghost method`. That's nicely consistent with having `predicate` as a more readable alias for `function that returns a bool`.

**Comment by davidcok** [comment]
Corresponding edits made to the RM, in PR#2755
