### ISSUE TITLE
Code formating?

### ISSUE THREAD

**Issue by seanmcl** [dafny-lang/dafny#252]
Microsoft released their code formatting tool:

https://github.com/dotnet/codeformatter

I wonder if we could apply this to the Dafny code base and suggest/require new commits to run it.  This would make the codebase uniform and obviate formatting discussion in CRs.  

Thoughts?

**Comment by mschlaipfer** [comment]
Sounds good to me. I assume it can be integrated into Travis?

**Comment by acioc** [comment]
It sounds like this is for C# code. We have https://github.com/dafny-lang/dafny/issues/614 for linting/formatting Dafny code.

**Comment by robin-aws** [comment]
Closing this since we recently added https://github.com/dotnet/format
