### ISSUE TITLE
Make it easier to have VS Code use the language server of the same Dafny version we use for a command-line build

### ISSUE THREAD

**Issue by mattmccutchen-amazon** [dafny-lang/dafny#2536]
My team is developing Dafny code as part of a larger project using a build system that is capable of importing NuGet packages, so we're planning to have our CI use the `dafny` command-line compiler/verifier from the `Dafny` NuGet package.  To actually write the code, we're using VS Code with the Dafny extension and language server.  To ensure we get consistent behavior between the IDE and the CI, we'd like the VS Code extension to use the _same Dafny version_ as the CI instead of the version it automatically downloads by default.  Once the right version of `DafnyLanguageServer.dll` is available on the local machine, we can just put its path in the "Dafny: Language Server Runtime Path" setting in VS Code.  However, downloading the right version is a bit awkward.  If `DafnyLanguageServer.dll` were available in a NuGet package, we could just tell our build system to download it, but it doesn't look like any of the existing Dafny-related NuGet packages contains that file.  So as a workaround, we'll probably have to write our own script to download the Dafny binary release from GitHub (including `DafnyLanguageServer.dll`) that matches the version of the NuGet package we're using.

Please consider publishing the language server in a NuGet package (either adding it to an existing package or making a new one).  Remy Willems mentioned you might be planning to merge the language server into the main `dafny` executable, which would also solve the problem.  Thanks!

**Comment by cpitclaudel** [comment]
Could you set the desired Dafny version from the extension settings menu?

![image](https://user-images.githubusercontent.com/8181630/182507543-cd2e36ad-411c-4ab8-9135-bb57fa0a7548.png)

**Comment by mattmccutchen-amazon** [comment]
Good idea.  I see I'm guilty of an XY problem in framing the issue and have updated the title accordingly.  We're currently on Dafny version 3.7.1, which isn't one of the displayed options, but if I manually enter that value in `settings.json`, it seems to work.  I do want to streamline this process for our users, but I should be able to have our script query the Dafny version from the build system, poke it into `settings.json`, and let the extension's automatic downloader do the rest.  That's much better than maintaining our own inferior reimplementation of the automatic downloader.

I'll tentatively close this issue now.  If you're still interested in using the issue to track work (e.g., packaging the language server for another reason), feel free to reopen the issue.
