### ISSUE TITLE
We should document, for each Dafny release, what version of the runtime it is expected to work with.

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#2537]
We should document, for each Dafny release, what version of the runtime it is expected to work with.

**Comment by MikaelMayer** [comment]
Of the DafnyRuntime? Of the dotnet runtime?

**Comment by davidcok** [comment]
The original statement meant the DafnyRuntime

**Comment by atomb** [comment]
Now that we're applying the same version number to the runtime that we do to Dafny overall, do you still see this as an issue, @davidcok?

**Comment by davidcok** [comment]
OK
