### ISSUE TITLE
Extract Dafny grammar definition from reference manual into a separate reference

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#2542]
I would argue that the low-level BNF-style grammar definition snippets in the current reference manual are a bit misplaced, since most readers will be trying to understand Dafny features at a higher-level and will prefer to read user-facing descriptions and examples. However, I do find the simplified (compared to reading `Dafny.atg` at least :) declarations of the language grammar very handy at times.

Related to this issue, a feature request for extracting railroad diagrams from the Coco/R grammar: https://github.com/dafny-lang/dafny/issues/1244

**Comment by davidcok** [comment]
Completed by PRs 3525-3528
