### ISSUE TITLE
Change default values of CLI options for Dafny 4.0

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#2548]
This is the primary proposed breaking change for Dafny 4.0. The changes are currently planned to be (with the PRs that add/affect the new functionality):

* https://github.com/dafny-lang/dafny/pull/1832: `/functionSyntax:3 -> /functionSyntax:4`
* https://github.com/dafny-lang/dafny/pull/2195: `/quantifierSyntax:3 -> /quantifierSyntax:4`
* https://github.com/dafny-lang/dafny/pull/3016: `/unicodeChar:0` -> `/unicodeChar:1`
* https://github.com/dafny-lang/dafny/pull/3613: The default version of Z3 used (4.8.5 -> 4.12.1)
* ~https://github.com/dafny-lang/dafny/pull/3553: `/allowAxioms:1 -> /allowAxioms:0`~ (punted for now)
* https://github.com/dafny-lang/dafny/pull/3609: `/allocated:3 -> /allocated:4`

This will also involve documentation changes, not just on these options but also to have examples in the reference manual and other places to use the new defaults (especially to remove `function method`!)

https://github.com/dafny-lang/dafny/pull/3466 has the first three changes applied and adjusts all tests to pass, but the others will need similar tweaks (although touching far fewer files). The plan is to merge that into a `main-4.x` branch once it's approved, and we can incrementally apply other 4.x-only changes like these onto that branch, while preferring any other changes that should be in both 3.Last and 4.0 go into `master`.

As new changes are merged to master that imply these kinds of changes, please add to the list above, and preferably drop a comment for visibility!

**Comment by atomb** [comment]
Do you mean `\quantifierSyntax:3 -> \quantifierSyntax:4` above?

**Comment by robin-aws** [comment]
> Do you mean `\quantifierSyntax:3 -> \quantifierSyntax:4` above?

Yup :) Thanks! Fixed.

**Comment by RustanLeino** [comment]
The `/allocated:3` -> `/allocated:4` change is in PR https://github.com/dafny-lang/dafny/pull/3637 against the `main-4.0` branch.
