### ISSUE TITLE
Each compile target should ensure that output streams (stdout and stderr) are flushed before a program exits.

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#2559]
And there should be tests added to check that print statements without newlines do get printed eventually.

**Comment by davidcok** [comment]
This appears to be OK -- except that Java adds a newline terminator to
```
method Main() {
  print "Hi";
}
```
which the other platforms do not.

**Comment by davidcok** [comment]
Fixed along with #2733 in PR #2879

**Comment by cpitclaudel** [comment]
Reopened by 4b2bcd3bb3e5ba8b0c28584a4e88eb27bf6d16b2

**Comment by davidcok** [comment]
And fixed again by #3000
