### ISSUE TITLE
Error reporting signature disagreement when doing case matching without importing modules as opened

### ISSUE THREAD

**Issue by txiang61** [dafny-lang/dafny#256]
```
module List {
  datatype t<A> = Nil | Cons(A, t<A>)
}

module String_Utils {
  import List
  lemma compareNth(A : List.t<char>, B : List.t<char>) {
     match (A, B)
      case (Nil, Cons(_, _)) => 
  }
}
```

I get report ` the declared type of the formal (t<?>) does not agree with the corresponding type in the constructor's signature (t<char>)` pointing to the two case statements. 

Importing the List as opened seem to fix the issue. 

Edit:
This is only a issue when matching a tuple that contains a case with argument

**Comment by acioc** [comment]
This has likely been resolved. Please verify and close.

**Comment by davidcok** [comment]
Added tests to verify fix. PR#770.
