### ISSUE TITLE
dafny CLI installed from NuGet never completes

### ISSUE THREAD

**Issue by seebees** [dafny-lang/dafny#2561]
Using the latest version of dafny from NuGet the well-formedness checks pass,
but then the command line hangs.

However verifying the same using Dafny: Compile in the IDE (with the same version) works.

**Comment by MikaelMayer** [comment]
Can you please post a small repro?

**Comment by atomb** [comment]
I believe that this is an instance of #2370, and can be resolved by installing [Z3 4.8.5](https://github.com/Z3Prover/z3/releases/tag/Z3-4.8.5) and putting it in the path. Dafny should really be providing a more useful error message here.

**Comment by robin-aws** [comment]
Closing as dupe of #2370
