### ISSUE TITLE
inconsistency in how print is compiled

### ISSUE THREAD

**Issue by gancherj** [dafny-lang/dafny#262]
```
function method tst (x : nat) : nat {
    x + 1
}

method Main() {
    var f := tst;
    print(f);
    print(tst);
}
```

The first print succeeds to compile, but the second print fails to do so

**Comment by davidcok** [comment]
Notes: Fixed for Java. but for cs, the code produced is (in part) -- here C# apparently does not do the needed type inference for __default.tst

    public static void Print<G>(G g) {
      System.Console.Write(ToString(g));
    }

  public partial class __default {
    public static BigInteger tst(BigInteger x) {
      return (x) + (BigInteger.One);
    }
    public static void _Main()
    {
      Func<BigInteger,BigInteger> _11_f;
      _11_f = __default.tst;
      Dafny.Helpers.Print(_11_f);
      Dafny.Helpers.Print(__default.tst);
    }
  }

**Comment by davidcok** [comment]
Fixed by adding a type argument to Print for function (arrow) types. Doing it for all types causes some errors for integer types, but might be needed in the future. PR #653
