### ISSUE TITLE
dafny fails to unfold definitions within existentials

### ISSUE THREAD

**Issue by gancherj** [dafny-lang/dafny#263]
Consider the below:
```
predicate all_eq (k : nat, s : seq<nat>) {
    forall i :: i in s ==> i == k
}

predicate consistent (s : seq<nat>) {
    forall i, j :: i in s ==> j in s ==> i == j
}

lemma consistent_all_eq(s : seq<nat>)
    requires |s| > 0
    requires consistent(s)
    ensures exists k :: all_eq(k, s) {
        assert (s[0] in s);
        assert (forall i :: i in s ==> i == s[0]);
        // assert (all_eq(s[0], s));
    }
```

The lemma fails to verify with the last line commented out, but succeeds when I uncomment the last line. I would expect that the commented version should work?

**Comment by parno** [comment]
This looks like a trigger issue.  See this FAQ for more details:
https://github.com/Microsoft/dafny/wiki/FAQ#how-does-dafny-handle-quantifiers-ive-heard-about-triggers-what-are-those
but essentially to prove your existential, you need to use a trigger to demonstrate a witness.  In this case, the only trigger available is `all_eq`.  You need to syntactically mention `all_eq` (or something that expands to `all_eq` to provide a witness for the existential.  Just mentioning things that are logically equivalent won't chain "backwards" to connect up to a function like `all_eq`, unfortunately.
