### ISSUE TITLE
Location of verification error not shown

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#2651]
The following code snippet does say it failed and shows yellow in the gutter, but does not squiggly-underscore the assert statement to show the location of the error.

```
  method z(x: string, y: string) {
    var a: string := "abc";
    var b: string := x + y;
    assert a <= x ==> a < b; // SHOULD FAIL
  }
```

**Comment by MikaelMayer** [comment]
This does not work on the command-line either.
