### ISSUE TITLE
Dafny suggests making a type parameter invariant instead of contravariant

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/dafny#2659]
Input: 

```
datatype T<A, B> = T(A --> B)
```

Output:

> invariant.dfy(1,21): Error: formal type parameter 'A' is not used according to its variance specification (it is used left of an arrow) (perhaps try declaring 'A' as '!A')

This should suggest `-A`, not `!A`

**Comment by RustanLeino** [comment]
Sometimes `!A` may be correct, so the hint should probably suggest both as possible fixes.
