### ISSUE TITLE
internal compiler error when performing type inference on large expressions

### ISSUE THREAD

**Issue by gancherj** [dafny-lang/dafny#267]
Consider the below code:

```
method Main() {
    var c := 0;
    print(c + c + c + c + c + c + c
          + c + c + c + c + c + c + c
          + c + c + c + c + c + c + c);
}
```

The above code crashes the compiler, reaching line 3455 in Resolver.cs, in which the compiler runs Contract.Assume(false) if the recursion depth of type inference is too large. Getting rid of one of the "+ c"'s makes the code compile. Changing 0 to [] (or something else which supports "+" and has an underspecified type) similarly makes the compiler throw. 

(Annotating the declaration of c with int (or nat, or whatever) makes the bug go away, since type inference doesn't kick in.)

An almost identical issue is that curiously the below code fails for the same reason:
```
method Main() {
    var c := 255 as char;
    print(c + c + c + c + c + c + c
          + c + c + c + c + c + c + c
          + c + c + c + c + c + c + c + c);
}
```

but changing the declaration of c to "var c : char := 255 as char" makes the code compile.

**Comment by mschlaipfer** [comment]
Tried to reproduce, but due to code contracts not working on my machine, it did not crash for me.

However, for future reference, the offending lines are
```C#
      if (_recursionDepth == 20) {
        Contract.Assume(false);  // possible infinite recursion
      }
```
in `AssignProxyAndHandleItsConstraints`.

**Comment by acioc** [comment]
We should likely take this out

**Comment by davidcok** [comment]
Raised recursion limit to 20000.
