### ISSUE TITLE
Fix the use of {.edit} and {.edit-only} in the online tutorial pages

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#2676]

**Comment by cpitclaudel** [comment]
Here is a version that I had started working on: https://gist.github.com/cpitclaudel/9d87d4e0232bf913cb3817ee7285c94c
We could have a look together at some point if you want

**Comment by davidcok** [comment]
I'd like to. I see some metadata annotations (e.g. exercise) but I'm not sure what it is that would render them in a thug pages environment.
