### ISSUE TITLE
Test all examples in the RM and OnlineTutorial

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#2679]
Do this for all examples in the RM, in the online pages such as the FAQs and tutorials.
Further put the examples in testable form so that any changes in behavior are noted by CI tests.

It would be good to parse&type check even code snippets, but that seems more difficult.

**Comment by cpitclaudel** [comment]
Splitting the code into separate files works well but it makes the documents harder to read and to maintain.

Maybe we could extract the code directly from the markdown documents, using something like https://github.com/cpitclaudel/alectryon/ ?  I tried that with the tutorial and it worked decently well: https://gist.github.com/cpitclaudel/d76e385bb376ccb5ee5686053c4b5258

**Comment by davidcok** [comment]
a) This sounds a bit like Jupiter notebooks

b) Agree that a tool that extracts (and checks) dafny code from markdown files would be an approach to take here. I'm am open to ideas of tools to build on.

**Comment by cpitclaudel** [comment]
> I'm am open to ideas of tools to build on.

Alectryon does that out of the box, and there's support for Dafny on the `next` branch.  We could use it wholesale.

**Comment by davidcok** [comment]
Still need to do the refman

**Comment by davidcok** [comment]
Completed -- though code templates and simple expressions are not checked -- just code blacks that are programs (even just sequences of simple declarations)
