### ISSUE TITLE
References to undefined variables in dynamic languages can cause runtime crashes

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/dafny#2691]
Simple mistakes in the compiler that create references to undefined variables are a minor pain in compiled languages, but are arguable soundness issues in dynamic languages.  

This is a meta-issue to track instances of this pattern:

- https://github.com/dafny-lang/dafny/issues/2690
- https://github.com/dafny-lang/dafny/issues/2608
- https://github.com/dafny-lang/dafny/issues/2852

**Comment by MikaelMayer** [comment]
I'm closing it because only #2608 remains
