### ISSUE TITLE
Unexpected PropagateFailure/Extract side effects

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#2693]
Dafny's error mechanism `:-` makes use of three user-defined members: `IsFailure`, `PropagateFailure`, and `Extract`. I think we made a design error when we allowed the latter two to be methods. I suggest we change the design to insist that these 3 members (or 2, in the case where `Extract` is not present) be functions.

The problem with the current design is that it allows one statement to have more than one round of side effects. For example, if `M()` is a method with side effects, then the statement

``` dafny
x :- M();
```

will (first round) have the side effects of `M` and and then (second round) the side effects of either `PropagateFailure()` or `Extract()`. Having more than one round of side effects is more taxing for a human, and it's especially insidious because the `PropagateFailure()` and `Extract()` calls are not directly visible in the program text.

## Example

To further illustrate the issue, here is a complete example. Two lines in method `Test()` are marked with `// surprise`. If you read only method `Test()`, you'd expect the conditions on those two lines to hold. To figure out what's going wrong, you need to figure out that `PropagateFailure()` and `Extract()` can have side effects. Along the way, you may also be further confused, thinking that the side effects of `IncreaseAndReturn` have something to do with the two surprises (which they do not).

``` dafny
method Test() returns (result: Result)
  ensures result.Bad? ==> result.c.IsFailure()
{
  var c := new EvenGood_OddBad;
  c.a := 0;
  var x :- IncreaseAndReturn(c);
  assert !c.IsFailure();
  return Good(x);
}

class EvenGood_OddBad {
  var a: int

  function method IsFailure(): bool
    reads this
  {
    a % 2 == 1
  }

  method PropagateFailure() returns (r: Result)
    requires IsFailure()
    modifies this
  {
    a := 0;
    return Bad(this);
  }

  method Extract() returns (x: int)
    requires !IsFailure()
    modifies this
  {
    x := a;
    a := 19;
  }
}

datatype Result = Good(x: int) | Bad(c: EvenGood_OddBad)

method IncreaseAndReturn(c: EvenGood_OddBad) returns (r: EvenGood_OddBad)
  modifies c
  ensures old(c.a) <= c.a && r == c
{
  var n: nat;
  c.a := c.a + n;
  return c;
}
```

**Comment by davidcok** [comment]
While we are revising this mechanism, we should deal with #2436 as well.
