### ISSUE TITLE
Dafny reports verification error twice

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/dafny#2703]
```dafny
abstract module StillAsby {
  import A : Absy

}

abstract module Absy {
  method Foo() 
    ensures 2 / 0 == 1 {
    var x := 1;
  }
}
```

Reports:

```
abstractModuleImport.dfy(10,14): Error: possible division by zero
abstractModuleImport.dfy(10,23): Error: A postcondition might not hold on this return path.
abstractModuleImport.dfy(10,18): Related location: This is the postcondition that might not hold.
abstractModuleImport.dfy(10,14): Error: possible division by zero
```

Note the double "possible division by zero"

Also note that this program causes an exception in the Dafny language server:
```
[Trace - 3:40:41 PM] Received notification 'telemetry/event'.
Params: {
    "kind": "UnhandledException",
    "payload": "System.ArgumentException: An item with the same key has already been added. Key: ImplementationId { NamedVerificationTask = (line: 9, char: 9), Name = CheckWellFormed }\n   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)\n   at Microsoft.Dafny.LanguageServer.Workspace.Compilation.PrepareVerificationTasksAsync(DocumentAfterResolution loaded, CancellationToken cancellationToken)\n   at Microsoft.Dafny.LanguageServer.Workspace.Compilation.TranslateAsync()"
}
```

**Comment by keyboardDrummer** [comment]
I see the verification of the wellformedness of Absy.Foo is done twice. Is that required for soundness? I have trouble overseeing the implication of the `import A : Absy` and whether that could effect the wellformedness of `Absy.Foo`. In any case, suppose `import A : Absy` would cause a verification issue, then the error should be shown at the import, not at the original method definition.

**Comment by cpitclaudel** [comment]
Here is a variant of this same issue, which shows that it's not restricted to imports:

```
abstract module Absy {
  function f(): int { 0 / 0 }
}

abstract module StillAsby refines Absy {
}
```

This produces the following output:

```
test.dfy(2,22): Error: possible division by zero
  |
2 |   function f(): int { 0 / 0 }
  |                       ^^^^^

test.dfy[StillAsby](2,22): Error: possible division by zero
  |
2 | <nonexistent line>
  |                       ^


Dafny program verifier finished with 0 verified, 2 errors
```

For this variant, however, we did not use to print two errors until very recently; that bug was introduced in 3.7.2.

The problem in the original post:

```
abstract module Absy {
  function f(): int { 0 / 0 }
}

abstract module StillAsby {
  import A: Absy
}
```

reports two errors in every version of Dafny that can parse it.

I don't think it should: module verification is supposed to be modular, so I don't see why we're re-checking well-formedness :/

**Comment by RustanLeino** [comment]
I agree that there should be no need to verify this twice. I don't know how come we do.

This is how these things are generally performed: There are two cases when we make a refinement clone of a module--when you say `module B refines A` and when you say `import X: SomeModule`. The refinement cloner wraps each `IToken` in a `RefinementToken`. This signals to the verifier that the AST node was created during refinement, which implies that the original AST node is verified elsewhere.

So, perhaps what's going wrong in the report bug is that the `RefinementToken` is either not created or not detected. It should have been created using a call to the virtually dispatched `Tok` method in `Cloner`. Maybe the detection doesn't handle multiply-wrapped tokens correctly--perhaps it only checks `tok is RefinementToken`, whereas it should keep unwrapping `WrappedToken`s to see if any of the wrappers is a `RefinementToken`.
