### ISSUE TITLE
Support all (most?) CLI options as language server options

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#2732]
Currently only a subset of options are available, and frequently under different names. This is especially an issue for options like `/definiteAssignment` that affect verification goals.

Tagged with `breaking-change` only because this is relevant for other breaking changes such as `/functionSyntax:4` that are less painful because of being able to opt-out through CLI options: the IDE needs to support at least all such options.

**Comment by keyboardDrummer** [comment]
Should be resolved by: https://github.com/dafny-lang/dafny/issues/2906
