### ISSUE TITLE
Dafny's C++ compiler prints `true` as `"1"`, not as `"true"`

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/dafny#2773]
Input:

```
method M() {
  print true;
}
```

Output:

```
1
```

**Comment by parno** [comment]
Does Dafny's semantics cover printed output?  In C/C++, `1` is `true` :)

**Comment by cpitclaudel** [comment]
Not at the moment (though we do have a flag to track print effects, at least ^^)
But we do try to make the output of the compilers consistent (and we print `string`s differently from other sequences)
