### ISSUE TITLE
On windows /useRuntimeLib

### ISSUE THREAD

**Issue by seebees** [dafny-lang/dafny#2785]
Does not appear to function properly.
I get the following:

```
dafny \
	/vcsCores:4 \
	/compileTarget:cs \
	/spillTargetCode:3 \
	/compile:0 \
	/useRuntimeLib \
	/out runtimes/net/ImplementationFromDafny \
	./src/*.dfy
*** Error: 'C:/Program Files/Git/useRuntimeLib': Filename extension '' is not supported. Input files must be Dafny programs (.dfy) or supported auxiliary files (.cs, .dll)
```

**Comment by robin-aws** [comment]
That flag is definitely supported on Windows, see https://github.com/dafny-lang/dafny/blob/master/Test/dafny0/DafnyLibClient.dfy for example.

I suspect it's a shell parsing issue instead. Does it work if you put the command on a single line?

**Comment by seebees** [comment]
It works on OSX, but not in a bash shell on windows.
However, this works. Note the `./` that is required...
```
	dafny \
		/vcsCores:4 \
		/compile:0 \
		/definiteAssignment:3 \
		/verificationLogger:trx \
		./src/*.dfy ./src/**/*.dfy \
		./test/*.dfy
```

**Comment by MikaelMayer** [comment]
Can you please try the alternative with "-" instead of "/"

```
dafny \
	-vcsCores:4 \
	-compileTarget:cs \
	-spillTargetCode:3 \
	-compile:0 \
	-useRuntimeLib \
	-out runtimes/net/ImplementationFromDafny \
	./src/*.dfy
```

I've found that I'm always better ignoring "/" in Windows because it creates problems.

**Comment by seebees** [comment]
@MikaelMayer This worked. I don't think that the existence of `-` options is documented.
If this is the most stable to make it work,
then we should update the help output.
