### ISSUE TITLE
Wrong error position in if statement without else branch

### ISSUE THREAD

**Issue by samuelgruetter** [dafny-lang/dafny#280]
In the following example, Dafny reports an error for the line containing the `if`, which made me think that the then-branch of the function contains a mistake, even though the then-branch is correct, and the mistake is in the case where the then-branch is not taken.

```
method foo(n: nat) returns (res: nat)
    ensures res > 0
{
    if (n == 0) { // Error at wrong position: A postcondition might not hold on this return path. Related location 1: Line: 2, Col: 16"
        return 1;
    }
} // <--- here would be a better position to report the error
```

So I started to debug the then-branch, and was very confused why it seemingly didn't verify.

**Comment by seanmcl** [comment]
Temporary workaround, always end your methods with `return 0` (or whatever default value of the right type).  Getting this error message right is a Boogie issue that is not obvious.

**Comment by seanmcl** [comment]
The error message above isn't clear that Dafny points to the `if`, which is about as good as can be hoped for here.  Boogie does not, afaict, save end-of-block line numbers, so getting what you want here would require tumult in the Boogie code.
