### ISSUE TITLE
Replace --args with -- (for arguments to the Dafny program main method)

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#2807]
Split off from https://github.com/dafny-lang/dafny/pull/2603#issuecomment-1261205331.

This will have to be handled as a deprecation/breaking change process since the new top-level commands CLI UI will also accept `--args`.

Edit: @cpitclaudel filled in lots of detail on why we avoided `--` on the original PR, copying here so we can continue the discussion separately from the PR:

Adressing feedback on `--` from @seebees and @robin-aws:

> Isn't that an argument for -- being the least surprising syntax, since it's exactly what dotnet run does, and many other similar CLIs?

> I'll jump on too. -- is a standard way to express this.

I thought so too at first, but we ended up concluding the opposite and going with `--args`.  

POSIX specifies that `--` should be used to indicate the end of options (aka flags), i.e. to force a program to treat all that follows it as operands (non-option arguments).  In that convention, `--` is *not* used to set apart certain arguments.  E.g. from [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html):

> Guideline 10:
>    The first -- argument that is not an option-argument should be accepted as a delimiter indicating the end of options. Any following arguments should be treated as operands, even if they begin with the '-' character.

What this means is that adding `--` anywhere should not change the meaning of a command if none of the arguments start with `-`.

This is not the semantic that is being proposed here, since `Dafny run a.dfy --args b.dfy c.dfy` means something different from `Dafny run a.dfy b.dfy --args c.dfy`.  This is what led us to reject `--` as inadequate: `--` is an escape character, not a separator.

Another illustration of this might be: how do you run a Dafny file called `--print=.dfy`?  You would write `Dafny run -- --print=.dfy --args foo bar baz`.  `--` escapes what follows and prevents `--print=.dfy` from being treated as an option.  `--args` then delimits arguments to the command.

This is the reason why GNU parallel uses `--`, not `:::`, I believe (but I could be wrong, since it also has `::::` and `:::+` etc).

Other tools use explicitly named arguments, like `find -exec` (which takes a terminator, `;` or `+`).

Btw, tools like `dotnet run` get to use `--` because they don't have operands; only options: you write `dotnet run --project=blah.csproj arg1 arg2`, not `dotnet run blah.csproj arg1 arg2`.   But note that for most of these tools, the `--` is optional (as it "should" be).  

If `Dafny run` were changed to use an implicit project file instead of a `.dfy`, then using `--` would be reasonable. (Note that it would not be enough to require exactly one `.dfy` file, because of the escaping remark above.)

We could also decide to repurpose `--` as a delimiter instead of an escape character.  The argument would be that we don't need escapes, because one can always use `./` as a quoting mechanism: `Dafny run ./--print=.dfy -- foo bar baz`.  It looks pretty for sure.

**Comment by keyboardDrummer** [comment]
Resolved by: https://github.com/dafny-lang/dafny/pull/2823
