### ISSUE TITLE
Indentation and interpretation of verbatim strings

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#2831]
A verbatim string is everything between an initial @" and closing " with the only escape being "".
But this means that verbatim strings cannot be indented at all.
We could leave this as is (presuming the formatter does not alter verbatim strings), or
we could omit from each line of the verbatim string an amount of white space equal to the indentation of the first "
Then
```
@"abc
def
ghi
"
```
and
```
        @"abc
          def
          ghi
         "
```
are the same, if the spaces are rendered correctly. The initial " is in the 9th (0-based) column, so 10 spaces at the beginning of each line , and 9 from the one containing the final " are omitted from the string.

**Comment by MikaelMayer** [comment]
This can be solved programmatically by defining a library function, as it is idiomatic for Scala's triple quote.
That way, you can decide on how you want to resolve ambiguities: For example, do you want:
```
@"abc
  def"
```
or
```
@"
abc
def")
```
to actually even further minimize indentation? As you can see, it's not obvious. So here is a programmatic answer that I think will let me close this issue, that implements the second behavior, and it also supports all lines starting with `|` to visually see the left alignment.


```dafny
function method RemoveMargin(multiline: string, i: nat := 0, acc: string := "", newline: bool := false): string
  requires 0 <= i <= |multiline|
  decreases |multiline|-i
{
  if i == |multiline| then acc
  else if multiline[i] == '\n' then
    RemoveMargin(multiline, i + 1, acc + (if i == 0 then "" else "\n"), true)
  else if newline then
    if multiline[i] == ' ' then
      RemoveMargin(multiline, i + 1, acc, newline)
    else if multiline[i] == '|' then
      RemoveMargin(multiline, i + 1, acc, false)
    else
      RemoveMargin(multiline, i + 1, acc + [multiline[i]], false)
  else
    RemoveMargin(multiline, i + 1, acc + [multiline[i]], false)
}

method Main() {
  print RemoveMargin(@"
  |This is a line
  |This is another line");
}
```
prints
```
This is a line
This is another line
```
