### ISSUE TITLE
Lambdas forget not to close over ghost values at compile time

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#2852]
Running the following code shows that Dafny's c# compiler forgot to remove ghost variables from the closed variables.
```dafny
// Returns a function that computes the sum of n consecutive integers starting at pos
function method Sum(
  ghost remaining: nat,
  n: nat
): (p: nat -> nat)
  decreases remaining
  requires remaining == n
{
  (pos: nat) =>
    var x: nat := if n == 0 then 0 else Sum(remaining - 1, n - 1)(pos+1) + pos;
    x
}
method Main() {
  print Sum(5, 5)(10);
}
```
Run:
```
> dafny -compile:3 -spillTargetCode:2 -compileTarget:cs the_test.dfy

Dafny program verifier finished with 2 verified, 0 errors
Errors compiling program:
(1836,15): error CS0103: The name 'remaining' does not exist in the current context
```

Might be related to https://github.com/dafny-lang/dafny/issues/531 ?

**Comment by MikaelMayer** [comment]
Just tested with JavaScript, we have the same issue, but this time the error happens only when invoking the function.

**Comment by MikaelMayer** [comment]
Might also be related to
https://github.com/dafny-lang/dafny/issues/2843

**Comment by cpitclaudel** [comment]
The Javascript soundness part of this issue is tracked in https://github.com/dafny-lang/dafny/issues/2691 ; I added this issue to that list.
