### ISSUE TITLE
Feature request: pattern matching on standard library values

### ISSUE THREAD

**Issue by seanmcl** [dafny-lang/dafny#286]
It would be nice to support standard pattern matching on builtin types:

```
match x {
    case Some(true) => false
}

match x {
    case Some(5) => false
  }
```

etc.

**Comment by robin-aws** [comment]
Will be addressed by #458 I believe?

**Comment by davidcok** [comment]
Confirmed fixed with this example.

datatype Option<T> = None | Some(t:T)

class C {
  method m(x: Option<bool>) {
    var a := match x { case Some(true) => false case _ => true };
  }
}

class D<T> {
  method mm(x: Option<int>) {
    var b := match x { case Some(5) => false case _ => true };
  }
}

**Comment by davidcok** [comment]
Sean - please confirm this example was your use case.
