### ISSUE TITLE
Confusing error message when input argument is not a supported input

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#2894]
This error message is confusing as after the -- nothing should be interpreted as an option

dafny translate B.dfy -- --no-verify A.dfy
*** Error: Command-line argument '/Users/davidcok/projects/dafny/cli/dafny/--no-verify' is neither a recognized option nor a filename with a supported extension (.dfy, .cs, .dll).

**Comment by keyboardDrummer** [comment]
This occurs when an input file that doesn't have an extension and starts with option syntax, is passed on the CLI.

Should we simplify to `*** Error: Command-line argument '/Users/davidcok/projects/dafny/cli/dafny/--no-verify' is not a filename with a supported extension (.dfy, .cs, .dll).` in all cases where an argument is not identified as an option and is not a valid file and has no extension?

This would simplify the logic and mean that we don't have to take `--` into account.

**Comment by davidcok** [comment]
That is fine with me

**Comment by davidcok** [comment]
Completed with PR#3542
