### ISSUE TITLE
Name resolution error

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#2905]
```dafny
datatype DT = DT {
  static method m(){}
}

datatype DD = AA | BB | CC
{
  method problem() {
    match this {
      case CC =>
      case _ =>
        var a := "value";
        DT.m();
    }
  }
}
```
This minimal code, if executed with Dafny, will trigger the following error:

```
file.dfy(11,12): Error:
 more than one declaration of variable name: a#1_0
1 name resolution errors detected in file.bpl

*** Encountered internal translation error - re-running Boogie to get better deb
ug information

file.bpl(3069,6): Error: more than
one declaration of variable name: a#1_0
1 name resolution errors detected in file.bpl
```

**Comment by MikaelMayer** [comment]
Two workarounds for now, until @keyboardDrummer  or myself find a fix

1) Declare the variable `a` before the match case statement.
2) Wrap the second case in a `match true { case true => ` ... `}`

**Comment by keyboardDrummer** [comment]
I think this PR will fix it: https://github.com/dafny-lang/dafny/pull/2734

**Comment by cpitclaudel** [comment]
The issue seems to be new in 3.8.0; the original example was OK in 3.7.3.
The following shows a variant of this problem, I think:

```
datatype DT = A | B

method M(dt: DT) {
  match dt {
    case A | B => var x := 1; assert x == 1;
  }
}

function method F(dt: DT): int {
  match dt {
    case A | B => var x := 1; assert x == 1; 0
  }
}
```

**Comment by cpitclaudel** [comment]
Looks like we might be able to fix this before the refactoring by reverting / fixing this commit:

```
commit d65085d22a97371ac33c77de7e77b3b95a41acbb
Date:   Fri Jul 29 13:50:32 2022 -0500

    Fix: null pointer exception in the case of hovering local variables (#2437)
```

**Comment by keyboardDrummer** [comment]
> Looks like we might be able to fix this before the refactoring by reverting / fixing this commit:

Yes, I'd be in favour of that, although note that it would break the hover feature in the IDE which #2437 fixed.
