### ISSUE TITLE
Feature request: Style guide

### ISSUE THREAD

**Issue by seanmcl** [dafny-lang/dafny#293]
It would be great to have a syntactic style guide.  If we had one we could write a formatter and never need to discuss formatting issues in PRs.

**Comment by seanmcl** [comment]
Created skeleton

https://github.com/dafny-lang/dafny/wiki/Style-Guide

**Comment by seanmcl** [comment]
Style guide is being worked on in #304

**Comment by robin-aws** [comment]
Closing this since a style guide exists now - please feel free to cut more specific issues/PRs to improve it!
