### ISSUE TITLE
Ability to assign constants in classes even if defined in traits

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#2944]
The following code raises an error
```dafny
trait T {
  const a: int := b + b
  const b: int
}

class A extends T {
  const b: int := 5 // Error, b already declared
}
```

So the workaround currently consists of defining invariants in A and requiring them before and after each method. Since class A's requirements have to be weaker than T, we also need this invariant to be present in T, etc.

But the code above should be legit and that way we don't need invariants to assert that b == 5 and a == 10 in the class A above.

**Comment by MikaelMayer** [comment]
Duplicate of https://github.com/dafny-lang/dafny/issues/2381

**Comment by demapvertu-dotcom** [comment]
Comment puis-je avoir un bot whatsapp svp
