### ISSUE TITLE
Nested extern attribute creates stub with incorrect file name in Python

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#2963]
Follow-up from #2952.

After #2952, ` module {:extern "A.B.C"} A.B.C` works in Python, but creates an unnecessary and confusing stub named `A.B.C.py` (as opposed to where you actually implement the extern, `A/B/C.py`). As clean up we should have the Python code generation not create this stub.

**Comment by fabiomadge** [comment]
I think the file should be created, but with the correct name and location.
