### ISSUE TITLE
Running Dafny with a glob that results in no files is an error

### ISSUE THREAD

**Issue by seebees** [dafny-lang/dafny#2970]
I want my verification command to look like
`dafny ./src/*.dfy ./src/**/dfy ./test/*.dfy ./test/**/*.dfy`

This way no matter what files I add
they will get verified.

However, if these globs don't result in files,
then Dafny will error.

```
(0,-1): Error: Unable to open included file
Error opening file "./test/*.dfy":
```

This forces me to not include all my files and then remember to update my CI if I add something.

**Comment by MikaelMayer** [comment]
Would the following solve your issue?

```
find ./src ./test -name "*.dfy" | xargs dafny
```

**Comment by seebees** [comment]
That is what I ended up doing :(

This feels like a push for something like a project file.
The idea that I can this easily fail to verify my project makes me sad.

**Comment by MikaelMayer** [comment]
Yeah I think that, when we will want to devote time to do what would do the job for you, it will be through a project file. So I'm closing this issue for now.

**Comment by MikaelMayer** [comment]
Will be solved when https://github.com/dafny-lang/dafny/issues/2907 is solved
