### ISSUE TITLE
[Feature request]: Replace default /timeLimit in integration tests with /rLimit

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#2985]
I've noticed `SetData (correctness)` from `11-MutexGuard2.dfy` is getting quite flaky and frequently timing out when we get unlucky with wall clock time: https://github.com/dafny-lang/dafny/actions/runs/3390338518/jobs/5634383901

Will just take a bit of investigation to pick a reasonable resource limit.

**Comment by atomb** [comment]
I'm going to be experimenting with the performance of the test suite as part of the process of preparing for upgrading to a newer Z3, so I'm happy to take this on in the process.
