### ISSUE TITLE
Change `dafny run` to always force UTF-8 output

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/dafny#2999]
The `dafny run` command currently makes no effort to control the encoding of its output (what bytes get generated when the user writes `print "foo"`.

Concretely, strings get printed using the default printing of the target language (`System.out.print` in Java, `Console.Write` in C#, etc.).  This leads to inconsistencies in printing, because different language runtimes use different encodings by default: some use UTF-8, and others obey the system’s codepage (`GetConsoleCP` on Windows) or locale (`LANG` / `LC_*` on Linux).  Often the behavior changes depending on whether the code is attached to a console or to a pipe (this is the case for Python and C#, for example)

The problem mostly shows up on Windows, because most Linux distributions default to UTF-8, and so we get the same output whether a language defaults to UTF-8 or to the system’s locale.

Examples of broken output are given in https://github.com/dafny-lang/dafny/issues/2976

Such discrepancies are not necessarily an issue for `dafny build`: its task is to produce code in each of its target languages, and then it’s the user’s responsibility to configure each runtime (maybe?).

But for `dafny run` we own the whole experience, and so we should strive to print consistent output.

There are three ways to do this:

1. Always use UTF-8, on all platforms.
2. Always use UTF-8 on Windows and always respect the system locale on Linux and macOS.  
3. Always use the current codepage or encoding.  This is the “right” thing to do, but it’s also inconsistent with a lot of languages.

Option 1 is “wrong” on all platforms (it ignores the user’s locale / codepage), but it’s very simple to explain to users.  Arguably, it’s also more important for Dafny to be completely predictable than for other languages (?).  The implementation is simple.

Option 2 is “wrong” on Windows, but it’s what some other languages do, so at least we’d be in good company.  The implementation is somewhat complicated, because we’d have to override what some of our languages do (for example C# seems to ignore LANG and use UTF-8 on Linux).  Testing is also hard, because different languages behave differently even for the same locale (Java and Python look at LANG but behave differently for LANG=C, etc.)

Option 3 is the “right” one, but it’s also not what most languages do. As far as I understand, the reason they don’t do this is that users on Windows don’t know about `chcp` and codepages, so they get confused by the non-utf-8-default, and blame application vendors instead of blaming their own configuration and/or their OS.  Even then it would be my preference, it’s tricky to implement, especially in Python (Python 3.7 moved to default-UTF-8 on Windows and added an environment variable to revert to using the current codepage instead, but then Python 3.8 broke that flag; it’s a [known issue](https://github.com/python/cpython/issues/86427)).

So, we will change `dafny run` to always force UTF-8 output (option 1).  There will be no change for now to `dafny build`.

**Comment by keyboardDrummer** [comment]
> Such discrepancies are not necessarily an issue for dafny build: its task is to produce code in each of its target languages, and then it’s the user’s responsibility to configure each runtime (maybe?).

I would still argue the use-case for `dafny build` is running a standalone Dafny program many times, in which case `dafny run` would be too slow. With that in mind, Dafny should provide a language agnostic way to run the output of `dafny build`. I imagine having `dafny run` accept the output from `dafny build`. The behavior of running the output of `dafny build` in that way should be consistent with using `dafny run`.

**Comment by cpitclaudel** [comment]
I'm fine with enhancing `dafny run` to reuse the output of `dafny build`
