### ISSUE TITLE
Warn on expressions that never change value

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/dafny#3023]
Examples:
- `x == x`
- `1 == 2`
- `str[0..1] == "12"`
- `x - x`

This is extremely useful for detecting whether ensures clauses on axioms, such as externally implemented methods, are always false, which corrupt the verification of other proofs by introducing an `assume false`.

**Comment by atomb** [comment]
Ah, nice, this is a specific instance of a more general analysis that I'm currently looking into implementing.

**Comment by keyboardDrummer** [comment]
Resolved by https://github.com/dafny-lang/dafny/pull/4461 and follow-ups
