### ISSUE TITLE
First sentence in dafny /help is wrong

### ISSUE THREAD

**Issue by samuelgruetter** [dafny-lang/dafny#303]
`dafny /help` prints

>  Multiple .dfy files supplied on the command line are concatenated into one Dafny program.

In my experience, this is not true. Here's what I think it should be:

> Multiple .dfy files supplied on the command line are considered as one Dafny program. All the .dfy files given on the command line as well as all .dfy files recursively reachable through "include" directives are parsed and compiled, but only the .dfy files mentioned as command line arguments are verified.

**Comment by seanmcl** [comment]
Seems like a nice pull request.

**Comment by mschlaipfer** [comment]
I think this is a bit too convoluted for the first sentence of the help page. Look at man pages. It should just be usage. What are the semantics should be learned in a tutorial or further down the help page.

**Comment by samuelgruetter** [comment]
The information I suggested should definitely be printed by `/help`, but I agree that it could be phrased better or put elsewhere within the `/help` output, any suggestions @mschlaipfer or others?

**Comment by davidcok** [comment]
Text edited. PR #654.
