### ISSUE TITLE
Symbols that don't seem to have anything to verify still show up in the test panel

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/dafny#3035]
Predicates with no body show up in the test panel, but what is there to verify for them?

<img width="768" alt="image" src="https://user-images.githubusercontent.com/3121201/201064756-79005cf6-4c8e-4c85-89f4-ef83a1ca00e7.png">

**Comment by MikaelMayer** [comment]
Note that some start to depend on the test list like an outline, so this might still be a desired behavior, if not, at least configurable.
Can you reproduce this on the command-line? Will it says 1 verified?

**Comment by keyboardDrummer** [comment]
> Can you reproduce this on the command-line? Will it says 1 verified?

Good question. Yes it does. It's just the wellformedness check of the ensures clause.
