### ISSUE TITLE
[Bug]: Preservation of `{:opaque}` not verified on classes implementing a trait

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/dafny#3040]
### Dafny version

latest

### Code to produce this issue

```dafny
trait TTT {
  function {:opaque} FFF(): int
}

class CCC extends TTT {
  function FFF() : int { 412 }
}

method M0() {
  var c := new CCC;
  assert c.FFF() == 412; // This passes
}

method M1() {
  var c := new CCC;
  reveal c.FFF();
  assert c.FFF() == 412; // This fails
}
```

### What happened?

This is a follow up to the fix in #2974 .  The difference between `M0` and `M1` in the example above is the type inference:

```
method M0'() {
  var c: TTT := new CCC;
  assert c.FFF() == 412; // This fails
}

method M1'() {
  var c: CCC := new CCC;
  reveal c.FFF();
  assert c.FFF() == 412; // This passes
}
```

### What type of Operating System are you seeing the problem on?

Other

**Comment by MikaelMayer** [comment]
Verification being inherently static, if we can't know what is the reveal lemma to invoke (which requires dynamic dispatch), we can't actually reveal a function defined on a trait. We need to have a function body to be able to declare a function opaque.
This remark made it possible to close one long standing issue https://github.com/dafny-lang/dafny/pull/4546
I'm closing this thread now.
