### ISSUE TITLE
[Bug]: runAllTests:1 MUST return an exit code

### ISSUE THREAD

**Issue by texastony** [dafny-lang/dafny#3043]
### Dafny version

3.9.0.41003

### Code to produce this issue

Any Dafny file with more than one test in it should suffice.

### Command to run and results

There are two.
First:

```code
dafny \
		-vcsCores:$(CORES) \
		-compileTarget:cs \
		-spillTargetCode:3 \
		-runAllTests:1 \
		-compile:0 \
		-useRuntimeLib \
		-out runtimes/net/tests/TestsFromDafny \
		`find ./test -name '*.dfy'` \
		-library:src/Index.dfy
```

Which will get you `TestsFromDafny.cs`.
Next, we will tell dotnet to execute those tests:
```
dotnet run \
		--project runtimes/net/tests/ \
		--framework net6.0
```

The result will be that every test is run and its result is reported as PASSED or FAILED. 

However, the generated `TestsFromDafny.cs` will exit 0 regardless of the results of the tests. 

This is very bad.

### What happened?

When Dafny is told to:
- `spillTargetCode:3`
- `runAllTests:1`

It generates something like:
```
bool _367_success;
_367_success = true;
...<All the tests in try catch blocks, on catch, set _367_success False>...
if (!(_367_success)) {
  Dafny.Helpers.Print(Dafny.Sequence<char>.FromString(@"Test failures occurred: see above."));
}
```

Which is very groovy.
But, it really needs to also add an exit or return code based on the value of `success`. 
Otherwise, you are running the tests, 
and printing the result of them,
but not exposing the result in a use-able form for CI.

### What type of Operating System are you seeing the problem on?

Linux, Windows, Mac

**Comment by alex-chew** [comment]
This is related to the feature request to allow Main methods to set exit codes in general: https://github.com/dafny-lang/dafny/issues/2699

But since this is counter-intuitive we should prioritize fixing this specific case first. I've labeled the issue as a breaking change because users may be relying on the exit code to be `0` today (even if it doesn't indicate what they think it does).
