### ISSUE TITLE
[Bug]: Non-integer Seq#Indexes lead to LSP crash

### ISSUE THREAD

**Issue by dijkstracula** [dafny-lang/dafny#3048]
### Dafny version

3.9.1.41027

### Code to produce this issue

https://gist.github.com/dijkstracula/b2863891f53650fcf4607abd2b35991f

### Command to run and results

```code
Trying to extract a counterexample leads to a BigInteger parsing exception.
```

### What happened?

The issue is that not every Seq#index appears to be a `Model.Integer`: in particular, the above code generates a Seq such that one of the "indices" is in fact a `DatatypeValue`:  here's such an example

![image](https://user-images.githubusercontent.com/8949748/201387983-a1b77d5d-4a91-439e-9863-0c7203c62444.png)

With the BigInteger parsing code removed, the counterexample that crashes is:

```
At "{" (file:///Users/ntaylor/school/smrt/src/Disks/CowZonedDisk.dfy:173):
...
    @1:seq<int> = (Length := 2, [2] := @10)
    @2:ZonedDisk.State = State(zones := @11)
    @11:seq<Zone.State> = (Length := 3, [(- 1)] := @15, [0] := @16, [2] := @17)
    @15:? = ()
```

This makes sense: the string `(- 1)` can't be correctly parsed as a BigInteger, so the exception being thrown is what we expect.  

I'm not sure that removing the BigInteger parsing code is completely the correct solution, in that I as a user don't really know how one is meant to read the meaning of the above counterexample: is the non-integral index morally index `1`?  If so, that value should be patched up before handing it up towards the user.  An index of `-1` doesn't make sense, so that's unlikely to be the intended value.  And, if it's an indirect reference to something else in the counterexample context, it too should be patched up.

I understand that `-` and `/` refer to constructors at some level of the Dafny stack, but don't really understand their meaning here.  If the "fix" is to simply check the type of the Seq#index and return `Arguments[1]` if it's a `DatatypeValue` then I can put that patch out; however, it feels slightly hacky and I get the sense that there is a more principled solution that probably lies farther down the stack (or potentially even in Boogie?).

### What type of Operating System are you seeing the problem on?

Mac

**Comment by MikaelMayer** [comment]
Hey what is this interface to navigate through counter-examples? I want the same !

**Comment by dijkstracula** [comment]
Do you mean the textual counterexample?  That was just from my IDE patch from a few weeks ago https://github.com/dafny-lang/ide-vscode/pull/290

**Comment by dijkstracula** [comment]
(in case you were wondering or concerned, the "negative" index also appears in the GUI)

![image](https://user-images.githubusercontent.com/8949748/201415375-0afa540d-14b2-490a-af01-d1ba53efdf79.png)

**Comment by dijkstracula** [comment]
OK, now that I've taken a break and come back to this, [here's a smaller failing repro case](https://gist.github.com/dijkstracula/b2863891f53650fcf4607abd2b35991f) than what I'd originally posted.  Critically, one of the counterexamples returned has the following sequence: `@4:seq<seq<seq<_module.uint8>>> = (Length := 9899, [(- 1)] := @14, [0] := @15, [8100] := @16, [9898] := @17)`.  Apologies that the repro case has a bunch of business logic in it; this was, strangely enough, as small as I could make this test without having the issue seemingly disappear.

Interestingly, this _doesn't_ seem to be related to the such-that predicate so my intuition was wrong.  Maybe I assumed that only because I'd added that predicate right before I started hitting the crash.

**Comment by dijkstracula** [comment]
Looking at this a bit more, the `(- 1)` "function application" is indeed in the modelview file, so it isn't the case that the language server is corrupting data that it's being passed.  

```
2130 Seq#Index -> {
2131   T@U!val!57 0 -> T@U!val!48
2132   T@U!val!59 0 -> T@U!val!68
2133   T@U!val!59 8100 -> T@U!val!54
2134   T@U!val!59 9898 -> T@U!val!69
2135   T@U!val!61 (- 1) -> T@U!val!50
2136   T@U!val!61 8100 -> T@U!val!66
2137   T@U!val!61 9898 -> T@U!val!72
2138   T@U!val!63 8100 -> T@U!val!45
2139   T@U!val!63 9898 -> T@U!val!72
2140   else -> T@U!val!74
2141 }
```

Further, elsewhere in the model file `Type T@U!val!50 -> T@T!val!11` and `DatatypeTypeType -> T@T!val!11`, which is what we're seeing in the debugger.  

Critically, though, in the same modelfile, we have that "not-an-index index" bound seemingly to an instance of a State datatype and a Value datatype interchangably?

Here's one where it appears to map to `val` (which is, in the repro case, of type `type Block = seq<uint8>`, the correct type for values in the crashing seq:):
```
   1 *** MODEL
...
  82 val#0 -> T@U!val!50
...
 418 *** STATE <initial>
...
 439   val#0 -> T@U!val!50
 440 *** END_STATE
 443 *** END_MODEL
```

And later, to `s`, a `datatype State`, which is the _incorrect type_ for indexes into the given seq:

```
1396 *** MODEL
...
1432 s#0 -> T@U!val!50
...
1802 *** STATE <initial>
...
1818   s#0 -> T@U!val!50
...
1820 *** END_STATE
1824 *** END_MODEL
```


Can I conform that `(- 1)` is, per the comment in the Language Server, some sort of internal uninterpreted function, and _not_ unary negation?

**Comment by MikaelMayer** [comment]
I don't have an idea about this. Any easy fix?

**Comment by dijkstracula** [comment]
One trivial way would be to, at the LSP level, simply filter out any indices whose internal Dafny types are not a `Model.Integer` - this fixes the crash and also removes any indices that don't strictly make sense, at the expense of a potental "actual fix" which might involve resolving whatever `(- 1)` is to something that the user might want to actually see.

If you're ok with the filtering solution, that's a quick fix and I can put that patch out this morning.

**Comment by dijkstracula** [comment]
> Would that work?

Definitely - agreed that not dropping the mysterious value does seem preferable.
