### ISSUE TITLE
HowToFAQ single page view

### ISSUE THREAD

**Issue by selig** [dafny-lang/dafny#3163]
### What change in documentation do you suggest?

I love https://dafny.org/dafny/HowToFAQ/ but sometimes I want to search all answers for a particular keyword. Can we get a view that puts all Q/A pairs on a single page that is searchable. 

Personally, I think this is a better solution than trying to build a keyword index or introduce tags etc, although those solutions would also be helpful for my lookup problem.

**Comment by davidcok** [comment]
Giles, please comment on this preview: https://davidcok.github.io/dafny/HowToFAQ/onepage
(This format was easily created using a script to concatenate and, with sed, slightly edit all the other pages -- hopefully not too much more is needed to meet your need)

**Comment by davidcok** [comment]
The preview is now at https://dafny.org/dafny/HowToFAQ/onepage
