### ISSUE TITLE
Consider associating unique IDs with errors

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#3182]
### Summary

Should Dafny errors have unique IDs? And what form and internal API is needed to support them?

Somewhat related: are dafny error messages ever going to be localized?

### Background and Motivation

Some motivations:
- A unique error ID can be shown to the user and associated with documentation about the problem; it might also provide helpful information in a problem report. Con: Dafny error messages themselves are unique strings or string templates.
- A unique ID (not necessarily exposed to the user) could be used internally. For example the IDE, upon encountering an error with ID, could automatically link to information that provided more context for the user.

Note that some error messages are templates -- that is strings with holes that are filled in differently in different contexts. For example: Error: a _decl_ cannot be declared 'ghost'.
So there is not a unique string literal for each possible message

Implementation questions:
- is the error code an int or a string? Edit: I see that LSP error codes can be ints or strings. And to clarify here: this issue is concerned with diagnostics related to the Dafny source code, not communication errors between the LS and its client.
- is it simply embedded in the error message in a structured way or do we modify all the error propagation methods in the dafny tool to propagate the error code in parallel with the error message  (like location information is)?

### Proposed Feature

No proposal yet.

**Comment by MikaelMayer** [comment]
You nailed it down ! The major benefit for unique IDs is that way we can always change the formulation later without impacting any tools relying on the error itself. This is especially important when developing IDE interaction plugins to resolve errors.
