### ISSUE TITLE
Bad error message in exports statement

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#3187]
### Dafny version

3.9.1+dev

### Code to produce this issue

```dafny
module M {
  const a: int
  const b: int
  export Z reveals a, provides b
}
```

### Command to run and resulting output

```code
dafny verify test.dfy

/Users/davidcok/projects/dafny/dafny/docs/try.dfy(4,22): Error: invalid IdentOrDigits

The problem is the , separating the reveals and provides clause, but this is not at all apparent from the text of the error message. I suggest either
1) improve the error message or
2) allow an optional , separating clauses of an export statement
```

### What happened?

Better error message

### What type of operating system are you experiencing the problem on?

Mac

**Comment by RustanLeino** [comment]
There's appeal to letting comma-separated lists end with an optional `,`. However, no other place in the language allows that. So, for now, I suggest just improving this error message.

For example, when parsing the comma-delimited lists for a `reveals` or `provides`, we could check if the token following a `,` is `reveals` or `provides` and then generate a different error message than the one we generate today. There's a wee bit of precedence for that kind of error message (see the `:` that's parsed in the `UpdateStmt` production, which causes the parser to output "did you forget the `label` keyword?").
