### ISSUE TITLE
Tab completion support on `dafny` cli

### ISSUE THREAD

**Issue by seebees** [dafny-lang/dafny#3190]
### Summary

Dafny has a lot of command line options,
I don't always remember them.
It would be great to be able to tab complete.

### Background and Motivation

When I try and run a command sometimes I forget
exactly what the command is called.
So I have to open a terminal, run `dafny /help`
search for my command and then I can run.

### Proposed Feature

`dafny path/to/file.dfy -timeLimit 30 -proc "*foo*" -ve`<tab>

```
/verifySeparately
/verifySnapshots
/verificationLogger
/verifyAllModules
/version
```

### Alternatives

This would make my life easier.
Workarounds abound :)

**Comment by keyboardDrummer** [comment]
Autocomplete is a feature of the library we used to make the new Dafny CLI UI, `dafny verify` etc, but I think it currently doesn't work because we also still support the old UI.
