### ISSUE TITLE
Dafny should warn when `old` is used on an expression that does not access the heap

### ISSUE THREAD

**Issue by mschlaipfer** [dafny-lang/dafny#320]
The following post-condition

`data[..] == old(data)[.. old(pos)] + [a] + old(data)[old(pos) + 1 ..]`

is translated to
```
Seq#Equal(Seq#FromArray($Heap, read($Heap, this, _24_Streams.StringWriter.data)), 
          Seq#Append(Seq#Append(Seq#Take(Seq#FromArray($Heap, read(old($Heap), this, _24_Streams.StringWriter.data)), 
                read(old($Heap), this, _24_Streams.StringWriter.pos)), 
              Seq#Build(Seq#Empty(): Seq Box, $Box(a#0))), 
            Seq#Drop(Seq#FromArray($Heap, read(old($Heap), this, _24_Streams.StringWriter.data)), 
              read(old($Heap), this, _24_Streams.StringWriter.pos) + 1)))
```

but it should be translated to 

```
Seq#Equal(Seq#FromArray($Heap, read($Heap, this, _24_Streams.StringWriter.data)), 
          Seq#Append(Seq#Append(Seq#Take(Seq#FromArray(old($Heap), read(old($Heap), this, _24_Streams.StringWriter.data)), 
                read(old($Heap), this, _24_Streams.StringWriter.pos)), 
              Seq#Build(Seq#Empty(): Seq Box, $Box(a#0))), 
            Seq#Drop(Seq#FromArray(old($Heap), read(old($Heap), this, _24_Streams.StringWriter.data)), 
              read(old($Heap), this, _24_Streams.StringWriter.pos) + 1)))
```

The difference is in the first arguments to `FromArray` on the RHS of the equals, which are missing the call to `old`.

**Comment by mschlaipfer** [comment]
Created a minimal example https://gist.github.com/mschlaipfer/34f713e2866b9b16ebe0a59803502caf

`C.f` and `C.h` are the same. `C.g` is the version analog to containing `old(pos)`. The first assertion fails, whereas the second one passes.

**Comment by mschlaipfer** [comment]
Tried to debug this, it seems to be related to line 14473 in Translator.cs, where the `HeapExpr` does not have the old for `g` (from the gist example).

**Comment by mschlaipfer** [comment]
The currently implemented behavior is as intended, but we should produce a warning when `old` does not apply any change in the Boogie encoding, as in this case.

**Comment by acioc** [comment]
We should warn on this

**Comment by davidcok** [comment]
Resolved: no code changes are needed. Warning will be added where it can be determined (at name/type resolution time) that no heap operations occur in the argument.  Also some explanatory text will be added to the RM.

**Comment by davidcok** [comment]
Explanatory text was added to the RM in some previous commit.

**Comment by keyboardDrummer** [comment]
Resolved by https://github.com/dafny-lang/dafny/pull/2610
