### ISSUE TITLE
Does Dafny use order relation in Boogie?

### ISSUE THREAD

**Issue by shazqadeer** [dafny-lang/dafny#3214]
Boogie supports a polymorphic partial order operator ```<:```. I am planning to drop this operator from Boogie because it is not widely used and its use can be easily replaced by an uninterpreted Boogie relation with accompanying axioms. In fact, the current implementation in Boogie handles ```<:``` does exactly that. 

I don't expect Dafny to be using this operator. In any case, I wanted to give a heads up.

**Comment by shazqadeer** [comment]
https://github.com/boogie-org/boogie/pull/667

**Comment by alex-chew** [comment]
Thanks for the heads up. As far as I can tell we don't use `<:`, and indeed a grep for `Opcode.Subtype` on the codebase turns up empty.
