### ISSUE TITLE
The Dafny run, build, translate commands need a --main option

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#3222]
### Dafny version

3.10.0

### Code to produce this issue

```dafny
The --main option (was /Main) is missing from dafny run and dafny build and dafny translate
```

### What happened?

Missing functionality

### What type of operating system are you experiencing the problem on?

Mac

**Comment by keyboardDrummer** [comment]
What's the use-case for this option, is using the `{:main}` attribute not more effective?

**Comment by keyboardDrummer** [comment]
(a) and (b) do not seem plausible. If I have multiple Main methods, I can put them in separate root files, and call `dafny` on the root file for which I want to generate an executable, instead of using a single root file that contains both methods and having to specify `/Main`.

> So we can certainly choose to deprecate the CLI option and require the attribute on the premise that (a) and (b) are uncommon enough. Is that the decision?

Yes
