### ISSUE TITLE
Request: generic traits

### ISSUE THREAD

**Issue by csgordon** [dafny-lang/dafny#323]
Currently it is not possible in Dafny to have a non-generic type inherit from a generic type, because Dafny doesn't support generic traits, and classes may only inherit from traits (not each other).  This makes it difficult to express common patterns (e.g., allowing a specialized data structure to implement an equivalent of IEnumerable<T>).  As far as I can tell, allowing generic traits is simpler than permitting general class inheritance, but I believe it would be enough to capture at least the cases I'm interested in.

Currently I'm working around this by writing a generic class to check that everything respects the abstraction, then manually doing template-expansion-as-traits to use these supertypes.

Is this a bandwidth-for-implementation issue, or something deeper?  How much work would it be for a newcomer familiar with implementing type checking for invariant generics in other contexts (e.g., C#) to get this working? I see the parsing support for trait generics is already there, but some later phase rejects the definition.

**Comment by RustanLeino** [comment]
Support for generic traits and generic (class or trait) extensions of generic traits has been added this summer. (Apparently, we missed closing this issue then.) They available available for use in the compilers for C#, Java, JavaScript, and Go.
