### ISSUE TITLE
module annotation causes invalid C# code

### ISSUE THREAD

**Issue by samuelgruetter** [dafny-lang/dafny#324]
Consider `CompileRefinement.dfy`:

```
abstract module Sig {
    class Foo {
        const v: int
        constructor () {}
        method hi()
    }
}

module Impl1 refines Sig {
    class Foo {
        const v := 42
        constructor () {}
        method hi() {
            print "Hello!\n";
        }
    }
}

module Program {
    import opened Impl1: Sig

    method Main() {
        var f := new Foo();
        // as expected, we get an assertion violation here because
        // the value of v is not specified in Sig
        // assert f.v == 42;
        f.hi();
    }
}
```

If I try to compile this file to C#, an invalid C# file is created:

```
$ dafny CompileRefinement.dfy /compile:3 /spillTargetCode:2 /out:./CompileRefinementOut
Dafny 2.3.0.10506

Dafny program verifier finished with 1 verified, 0 errors
Compiled program written to CompileRefinementOut.cs
Errors compiling program
c:\Users\kggruett\AppData\Local\Temp\wyqfk3ev.0.cs(1553,7) : error CS0246: The type or namespace name '_0_Sig' could not be found (are you missing a using directive or an assembly reference?)

c:\Users\kggruett\AppData\Local\Temp\wyqfk3ev.0.cs(1554,22) : error CS0246: The type or namespace name '_0_Sig' could not be found (are you missing a using directive or an assembly reference?)
```

This is a bug: The Dafny-to-C# compiler should never spit out invalid C# files. Either it should spit out a valid C# file, or produce an error saying why it is not capable of doing so.

Interestingly, if I comment out the `: Sig` annotation in the import, everything works as expected:

```
$ dafny CompileRefinement_noSigAnnotation.dfy /compile:3 /spillTargetCode:2 /out:./CompileRefinement_noSigAnnotationOut
Dafny 2.3.0.10506

Dafny program verifier finished with 1 verified, 0 errors
Compiled program written to CompileRefinement_noSigAnnotationOut.cs
Running...

Hello!
```

The relevant diff between the two created `.cs` files is:

```
1553,1554c1553,1554
<       _0_Sig.Foo _13_f;
<       var _nw0 = new _0_Sig.Foo();
---
>       _1_Impl1_Compile.Foo _12_f;
>       var _nw0 = new _1_Impl1_Compile.Foo();
```

No code is emitted for the definitions in `Sig`, because it's an abstract module, but yet, the constructor `new _0_Sig.Foo();` is called. The correct thing for the compiler to do would be to somehow bypass the `: Sig` annotation and use `new _1_Impl1_Compile.Foo();` in both cases.
Or, if that's too hard, it should emit an error saying `module annotations are not supported for compilation`.

**Comment by acioc** [comment]
This should complain when using `:` import

**Comment by samuelgruetter** [comment]
> This should complain when using `:` import
> 
> Such imports should only be allowed in abstract modules

I'm not sure if I understand what you mean, but there's at least one way to interpret this comment that would lead to an unsatisfactory fix, so here's another example that I think should also be addressed when fixing this issue:

```
abstract module Sig {
    class Foo {
        const v: int
        constructor () {}
        method hi()
    }
}

module Impl1 refines Sig {
    class Foo {
        const v := 42
        constructor () {}
        method hi() {
            print "Hello!\n";
        }
    }
}

abstract module AbstractProgram {
    import opened Impl1: Sig

    method Main() {
        var f := new Foo();
        // as expected, we get an assertion violation here because
        // the value of v is not specified in Sig
        // assert f.v == 42;
        f.hi();
    }
}

module Program refines AbstractProgram {}
```

It exposes the same bug as the original example, even though it respects the restriction "annotated imports should only be allowed in abstract modules", so this restriction is not sufficient.

**Comment by acioc** [comment]
Hi!

Apologies for my earlier response! We were triaging issues and labeling them for the Dafny 3.0 release (or post 3.0). The note was a high level note for the future implementer. I should have added more detail.

**Comment by RustanLeino** [comment]
Thanks for the additional test case, @samuelgruetter . Here are some notes about the example.

First off, the examples use a local name `Impl1`. This name has nothing to do with the module named `Impl1` in the examples. So, to be less confusing to look at, it would be better to pick a different name for one of these.

An `import :` declares a name for a module that is to be filled in. It is just a stand-in for something to come. Therefore, it cannot be compiled. (It's similar to a body-less method in this regard.) It seems reasonable to require the enclosing module of an `import :` declaration to be `abstract`, which says "don't compile this module". And this would side-step the bug reported.

In your second example, I think Dafny should also require `Program` to be abstract. By refining `AbstractProgram`, module `Program` gets that not-filled-in declaration of `Impl1`. Module `Program` could choose to fill it in, in which case the example is fine. But if (as in your second example) `Program` does not fill in the local name `Impl1`, then `Program` should also be required to marked as `abstract`.

**Comment by samuelgruetter** [comment]
Oohh thanks for the explanation, so I should actually read `import opened Impl1: Sig` like `import opened Sig as Impl1`, not like `import opened Impl1, hiding all declarations not in Sig`?

So would it be correct to refine the fix proposed by @acioc into "Every module that imports an abstract module or inherits an import of an abstract module needs to be abstract itself"?

**Comment by samuelgruetter** [comment]
I'm still confused, though: The following is accepted:

```
abstract module Sig {
    class Foo {
        constructor () {}
        method hi()
    }
}

abstract module AbstractProgram {
    import opened SigName: Sig

    method Main() {
        var f: /*SigName.*/Foo := new Foo();
        f.hi();
    }
}

module Program refines AbstractProgram {}
```

However, if I uncomment `/*SigName.*/`, I get the error `a compiled module is not allowed to use an abstract module (SigName)`. Is this the same bug as we're discussing?
Or asked differently: Do/should `SigName.Foo` and `Foo` refer to the same thing inside `Main`?
