### ISSUE TITLE
Compiling with {:test} on .NET fails

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#3260]
### Dafny version

3.10.0+dev

### Code to produce this issue

```dafny
method {:test} Main() {
  print "Hi!\n";
}
```

### Command to run and resulting output

```code
dafny run -t:cs test.dfy


Dafny program verifier finished with 0 verified, 0 errors
Errors compiling program into tmp2
(4995,6): error CS0246: The type or namespace name 'Xunit' could not be found (are you missing a using directive or an assembly reference?)
```

### What happened?

Should compile successfully (and run)

### What type of operating system are you experiencing the problem on?

Mac

**Comment by keyboardDrummer** [comment]
What behavior do you expect when using `dafny run`, which will run the main method, in combination with `{:test}` ? Should the `{:test}` attributes be ignored? Same for `dafny build`.

**Comment by davidcok** [comment]
With `dafny run` or `dafny build` the {: test} attributes can either be ignored or compiled in a way they could be but are not being run (if that is even possible or useful). Just not fail to compile at all, as now.
