### ISSUE TITLE
Better error message for misspelled or incorrect command

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#3267]
### Dafny version

3.10.0+dev

### Command to run and resulting output

```code
dafny format tmp.dfy
*** Error: 'format': Filename extension '' is not supported. Input files must be Dafny programs (.dfy) or supported auxiliary files (.cs, .dll)
```

### What happened?

In a command-focussed CLI, the first arg is supposed to be a command -- so this message will be confusing. Something like

*** Error: the first argument 'format', is neither a command, an option, a dafny file (*.dfy), nor a supported auxiliary file (_list_)

### What type of operating system are you experiencing the problem on?

Mac

**Comment by keyboardDrummer** [comment]
I'm not sure this is easy to resolve while still supporting the old CLI

**Comment by davidcok** [comment]
Well, we want to move toward the new CLI so the error message does need to be a compromise between the old and new, which I think my proposal is.

**Comment by keyboardDrummer** [comment]
OK but I don't see a way of detecting that the error message you suggested should be displayed, except hardcoding the word `format` to trigger this message.
