### ISSUE TITLE
/verifyAllModules == listing all files?

### ISSUE THREAD

**Issue by hmijail** [dafny-lang/dafny#3283]
### What change in documentation do you suggest?

As explained in the Dafny Reference, if A.dfy includes B.dfy, `dafny /compile:0 /verifyAllModules A.dfy` will verify both A and B.
Is this equivalent to running `dafny /compile:0 A.dfy B.dfy`?

I'm asking this because listing the files explicitly is needed by build systems like Make so that they can detect file changes and decide whether a new run of the verifier is required.

Possibly related: https://github.com/dafny-lang/dafny/issues/927

**Comment by hmijail** [comment]
The "Dafny Programs and Files" point in the Reference says that both calls are equivalent: https://dafny.org/dafny/DafnyRef/DafnyRef.html#253-dafny-programs-and-files

**Comment by davidcok** [comment]
Yes, these are equivalent. Any file on the command-line need not be in an include statement, but it is also OK to be named in both places. It is also OK to invoke dafny separately on each file, so long as the include statements include all their dependencies (else they won't type-check).
