### ISSUE TITLE
Replace `dafny --dev <verb> --help` by `dafny <verb> --help-dev`

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#3298]
### Summary

Improving the CL for hidden help

### Background and Motivation

The current `dafny --dev <verb> --help` is not intuitive and does not fit the rest of the new CLI design

### Proposed Feature

Implement `dafny <verb> --help-dev` instead

**Comment by MikaelMayer** [comment]
It makes sense, thanks for suggesting !

**Comment by davidcok** [comment]
Resolution: --help-internal
