### ISSUE TITLE
Is it OK to verify related files independently?

### ISSUE THREAD

**Issue by hmijail** [dafny-lang/dafny#3310]
### What change in documentation do you suggest?

Is verifying N files with a single `dafny` call equivalent to verifying them separately?
Or is there something to be gained by verifying all related files together? 

Asking this because verifying files independently is very convenient for a build system, and is the default behavior anyway. However this is not explicitly stated in the documentation.

**Comment by keyboardDrummer** [comment]
> Is verifying N files with a single dafny call equivalent to verifying them separately?

What sort of differences are you concerned about? There are differences in performance. Using a single CLI call performs better than multiple, since included files will have to be processed multiple times when doing multiple calls.

**Comment by hmijail** [comment]
Well, I'm not a formal methods person, so pardon the handwaving :). My understanding is that some tools/types of analysis can be more comprehensive if they can gather all the involved parts into a single analysis, even if doing so is not a requirement. 

So I wonder if it's the same with Dafny; whether doing file-by-file analysis it might just miss something that it would have found with all files together. Say, am I losing any guarantees?

I get that verifying file-by-file will cause some duplicate work; but if I can verify a couple of modified files instead of verifying the whole project, that quickly turns into a win.

**Comment by MikaelMayer** [comment]
That's a good concern to have, and I'm surprised that the documentation did not do a better job at explaining the following.
Dafny was designed with modularity in mind, meaning that if you verify each component separatedly, is the same as verifying the whole system at once.
Could you point me where in the documentation you have been looking for something like that but couldn't find an answer? Or keywords you might have typed?

Under the hood, the files form an acyclic graph, and dependencies are assumed when it comes to verify each file.(unless you pass the option `-verifyAllModules`, or its new CLI equivalent which does not seem to be documented @keyboardDrummer )

**Comment by davidcok** [comment]
The option with the new CLI is --verify-included-files
It is documented in the development version of the RM: https://dafny.org/dafny/DafnyRef/DafnyRef
but the change has been since the last release, so it is not yet in the 3.10.0 manual (https://dafny.org/latest/DafnyRef/DafnyRef)

The question of which files are verified is a property of the dafny tool (not the Dafny language) and is discussed in the User Guide section of the manual (section 25.2, 25.3 in the update). As it was not clear to you, I'll make a note to expand on the discussion there. But it would be helpful to learn from you how you were looking for the information.

Per Remy's comment, all recursively-included files are parsed and type-checked on each run, so that work is repeated if files are verified in separated runs of dafny. However, I would expect that for any but huge programs, the time to verify outweighs the time to parse and type-check (you can check that for your program). And the duplicate work can be constrained by limiting includes to just those that are actually needed.

**Comment by MikaelMayer** [comment]
Wow thanks for this excellent debugging of the documentation !
@davidcok is doing his best to resolve documentations issues like this, and I did not realize it would cause a cognitive problem until now you clearly state the problem.

**Comment by davidcok** [comment]
@hmijail Please give your comments on the revised text in https://github.com/dafny-lang/dafny/pull/3322/files
I have consolidated all the discussion of verification and included files etc in section 25.5.1.3

**Comment by hmijail** [comment]
I checked and think it is much clearer now, thank you!

**Comment by hmijail** [comment]
Sorry to come back to this, but I found a simple example that breaks my concept of verifying only files that change. I guess it is not possible after all? Was this only unclear to me?

file A.dfy:
```dafny
include "B.dfy"

function getsBroken(x:int) : int {
    B.f(x)
}
```

file B.dfy:
```dafny
module B {
    function f(x:int) : int
    //requires x>0                 //<-- uncomment this
    {
        x
    }
}
```


```bash
$ dafny /compile:0 A.dfy

Dafny program verifier finished with 0 verified, 0 errors

# Now uncomment the commented line in B.dfy
# Let's verify the modified file. 

$ dafny /compile:0 B.dfy

Dafny program verifier finished with 0 verified, 0 errors

# Only verifying the modified files stops here and everything looks good!
# But of course A.dfy is now broken:

$ dafny /compile:0 A.dfy
XXX/A.dfy(4,6): Error: function precondition might not hold
XXX/B.dfy(3,14): Related location

Dafny program verifier finished with 0 verified, 1 error
```

Makes sense after all. The comparable case of a Makefile recompiling an unmodified C file after an included file changed works only thanks to the compiler generating dependency files plus related machinery. Without some way to extract dependencies in Dafny, there is no way that to do this automatically.

So, going back to the original question that started this issue, I guess the correct statement is that Dafny can in principle verify files independently, BUT any given file needs re-verification if any of its dependents changed. Again, it sounds evident put that way, but I missed it.

Worth noting that the original text mentioned the order of verification, but the current version dropped it.
