### ISSUE TITLE
FAQ / doc request: requires / reads on lamdas

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/dafny#3314]
The following trips people regularly:

```
  class C {
    var p: (int, int);
  }

  function method Firsts0(cs: seq<C>): seq<int> {
    seq(|cs|, i => cs[i].p.0) // Two errors: `[i]` and `.p`
  }
```

This eliminates the error about `[i]`:

```
  function method Firsts1(cs: seq<C>): seq<int> {
    seq(|cs|, i requires 0 <= i < |cs| => cs[i].p.0)
  }
```

And this takes care of the `.p` access:

```
  function method Firsts2(cs: seq<C>): seq<int>
    reads set i | 0 <= i < |cs| :: cs[i]
  {
    seq(|cs|, i
      requires 0 <= i < |cs|
      reads set i | 0 <= i < |cs| :: cs[i] => cs[i].p.0)
  }
```

It might be nice to add it to the FAQ?

**Comment by MikaelMayer** [comment]
There is already something for the first one but it's in the section "verification debugging when it fails"
If you look for "seq(size, i => P)", you'll see the rewriting that adds the requires.
For the reads, as soon as we have extended error messages, it will be easier to figure out, but for now, the message is explicit enough, isn't it? I also count on code actions to solve that problem, along with the weakest precondition calculus. Also, you can just write `reads cs` like this:

```
  function method Firsts2(cs: seq<C>): seq<int>
    reads cs
  {
    seq(|cs|, i
      requires 0 <= i < |cs|
      reads cs => cs[i].p.0)
  }
```

**Comment by cpitclaudel** [comment]
> for now, the message is explicit enough, isn't it?

I'm not sure; it appears to trip some people regularly, so adding it to the FAQ would be good (not sure if we can improve the message)

> I also count on code actions to solve that problem

It would be nice if we had suggested fixes, yes.

Btw, another closely-related example is this:

```

  class C {
    var ps: seq<(int, int)>

    function method Firsts0(): seq<int>
      reads this
    {
      seq(|ps|, i => ps[i].0)
    }

    function method Firsts1(): seq<int>
      reads this
    {
      seq(|ps|, i requires 0 <= i < |ps| => ps[i].0)
    }

    function method Firsts2(): seq<int>
      reads this
    {
      seq(|ps|, i requires 0 <= i < |ps| reads this => ps[i].0)
    }
  }
```
