### ISSUE TITLE
Module refinement breaks outline, error reporting and gutter icons

### ISSUE THREAD

**Issue by seebees** [dafny-lang/dafny#3329]
There is strange behavior with the gutter icons when verifying refining an abstract modules.

```dafny
abstract module Test {
  method Encrypt()
    ensures false
}

module Ok refines Test {
  function test(): int {
    2
  }
  // Might not work as expected
  method Encrypt() {
  }
}
```
See the result here
![image](https://user-images.githubusercontent.com/3601079/204919623-0a8caa7f-f00b-413f-acff-002c7756f655.png)
* The error on the refined module is expressed in the abstract module, which completely breaks not only the gutter icons, but also the outline (there is no method Encrypt in the refined module)

We can use this behavior to pretend we prove false, at least on the gutter icons:
![image](https://user-images.githubusercontent.com/3601079/204919905-45bc1efc-e4a3-4e2c-9992-509fb4fc49ee.png)

It's even worse when the abstract module is included instead of being in the same file, because its errors are reported on the file containing the refined module, which is out of offset. Look at the postcondition error underlined.... in the comment.
![image](https://user-images.githubusercontent.com/3601079/204920193-4f2c4461-86a0-4ec3-9822-9dab6318a458.png)

**Comment by keyboardDrummer** [comment]
It seems this issue is already resolved. I get the following behavior given the example program, which seems good:

<img width="821" alt="image" src="https://github.com/dafny-lang/dafny/assets/3121201/369c6272-a9e6-49cd-aa41-11d66cc26093">
