### ISSUE TITLE
A way to allow specific warnings to be skipped

### ISSUE THREAD

**Issue by codyroux** [dafny-lang/dafny#3359]
### Summary

A command or pragma to cause a specific warning not to be raised by the Dafny top-level or compiler.

### Background and Motivation

Related to https://github.com/dafny-lang/dafny/issues/3358

In general most languages have a way of ignoring specific instances of warnings, especially in "0 warning mode" or when using `warningsAsErrors`.

A specific case might be if a top level theorem contains a `forall`, but no trigger is found; since the toplevel theorem probably won't ever be instantiated, this is a legitimate case to skip the warning.

### Proposed Feature

Probably a pragma of the form `{:ignoreWarning warn_number}` should work.

### Alternatives

Can be worked around by simply not failing on warnings.

**Comment by MikaelMayer** [comment]
For, now, for your specific problem, I just found a workaround, which consists of adding a custom trigger that is never used.

```dafny
lemma Test()
  ensures forall i: int, j: int {:trigger IgnoreWarnings } | i < j :: i + 1 != i
{
}

const IgnoreWarnings := 1
```

**Comment by codyroux** [comment]
Clever!
