### ISSUE TITLE
Array initializers required in contrast to documentation Section 15.1 ?

### ISSUE THREAD

**Issue by HPGumm** [dafny-lang/dafny#3370]
### What change in documentation do you suggest?

The Documentation says in section 15.1,  that I should be able to allocate arrays without initialization, such as e.g.

  a := new int[10];

Dafny, however, refuses that with an error message 
      "unless an initializer is provided for the array elements, a new array of 'int' must have empty size"

I am using Dafny VS-Code extension version 3.0.3. Here is an example code:

method Manual_Examples_15_1() returns (r:int)
{  
    var a := new int[10];
    var b : array < int > := new int[8];
    var c : array := new int[9];
   // none of the above lines are accepted by Dafny   
    r := 0;
}

**Comment by keyboardDrummer** [comment]
This behavior will be changed in the upcoming Dafny release so that the code you showed will be accepted, unless the `--enforce-determinism` option is used.
