### ISSUE TITLE
Support for heap-based witnesses

### ISSUE THREAD

**Issue by parno** [dafny-lang/dafny#339]
It would be convenient to be able to define a subset type of non-null heap-based objects.  For example, I might want to have an array-based type that promises to always have exactly one element.  Unfortunately, that doesn't seem to be possible at present.  Here are a couple of attempts, along with the accompanying errors:

`type NonEmpty = a:array<int> | a.Length == 1 `
`Error: trying witness null: result of operation might violate subset type constraint for 'array'`

`type NonEmpty = a:array<int> | a.Length == 1 witness [1]`
`Error: witness expression must have type 'array<int>' (got 'seq<int>')`

`type NonEmpty = a:array<int> | a.Length == 1 witness new int[1]`
`Error: invalid LogicalExpression`

My current workaround is to use:
`type NonEmpty = a:array?<int> | a == null || a.Length == 1 `
which does succeed, so this isn't a showstopper.  It just means that I'm back to adding non-null preconditions throughout my code.

**Comment by robin-aws** [comment]
I'm also wondering whether it could be possible to drop the need for a witness if you're trying to use Dafny with no non-determinism, and hence no need for default values of every type.

**Comment by RustanLeino** [comment]
While it is still now allowed to give a heap-based witness, the recent PR #1066 allows you to opt out of giving a witness. This is done by writing `witness *`. If you opt out, Dafny won't know if the type is inhabited or not, so it will treat the type as being possibly empty (which is also a new feature, made possible by PRs #1061, #1062, #1066). Such a possibly empty type is always subject to definite-assignment rules.
