### ISSUE TITLE
Request: Increase responsiveness of formatting by doing it before the resolution phase

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#3416]
For the formatter of https://github.com/dafny-lang/dafny/issues/3415,
currently, on the Dafny Language server, the parsing and resolution phase are combined. It would be good if we could avoid the resolution phase alltogether and directly format the code after parsing.

**Comment by keyboardDrummer** [comment]
Judging by the call to `ParsedProgram`, this is already resolved: https://github.com/dafny-lang/dafny/blob/master/Source/DafnyCore/Pipeline/Compilation.cs#L438
