### ISSUE TITLE
"dafny translate" a bit different than "dafny compile:0 /spillTargetCode:3"

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#3441]
### Dafny version

3.10.0

### Code to produce this issue

```dafny
// File.dfy

method Main() {
}
```

### Command to run and resulting output

```code
dafny -out:GeneratedFromDafny.cs File.dfy -compile:0 -spillTargetCode:3 -noVerify
dafny translate cs --output GeneratedFromDafny2.cs File.dfy
diff GeneratedFromDafny.cs GeneratedFromDafny2.cs
```

### What happened?

I expected no diff, but I got:
```diff
-[assembly: DafnyAssembly.DafnySourceAttribute(@"// dafny 3.10.0.41215
-// Command Line Options: /out:GeneratedFromDafny.cs File.dfy /compile:0 /spillTargetCode:3 /noVerify
-// File.dfy
+[assembly: DafnyAssembly.DafnySourceAttribute(@"// File.dfy
```

Note that if I changed spillTargetCode from 3 to 1 in the old comamnd line, I get the new result as well which does not contain metadata.
```
dafny -out:GeneratedFromDafny.cs File.dfy -compile:0 -spillTargetCode:1 -noVerify
```

### What type of operating system are you experiencing the problem on?

Windows

**Comment by keyboardDrummer** [comment]
Could you explain why you want the command line arguments to be printed in the source attribute in the translated file?

**Comment by keyboardDrummer** [comment]
I think it's indeed better to have the command line arguments included as a comment in the source in the source attribute. We can add it without affecting the output of the `--print` option.
