### ISSUE TITLE
Erroneous example in Reference

### ISSUE THREAD

**Issue by ajewellamz** [dafny-lang/dafny#3481]
### What change in documentation do you suggest?

The reference says

```
newtype int32 = x | -0x8000_0000 <= x < 0x8000_0000

then the code fragment is erroneous, since the result of the addition may fail to satisfy the predicate in the definition of int32. The code fragment can be rewritten as

var mid := lo + (hi - lo) / 2;

in which case it is legal for both int and int32.
```

but the following code, correctly, does not verify

```
newtype int32 = x | -0x8000_0000 <= x < 0x8000_0000

function method foo(x : int32, y : int32) : int32
{
  if x < y then
    x + (y - x) / 2
  else
    y + (x - y) / 2
}
```

Although it would verify with an unsigned type.

**Comment by davidcok** [comment]
I'm not sure what you think is erroneous about the example as it stands. In that example, we know that 0 <= lo <= hi < 0x8000_0000.

Are you suggesting to add the additional example, to expand on it?
