### ISSUE TITLE
Need to fix 2 unstable tests

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#3494]
I have seen this test fail twice on osx on one of my PR:
```
DafnyPipeline.Test.IntraMethodVerificationStability.EqualProverLogWhenReordering
```
The error is that on line 250, when it asserts that there is no resolution error, there are 3 resolution errors.

On Windows, I have seen the following unstable test:
```
DafnyPipeline.Test.PluginsTest.EnsurePluginIsExecuted
```

**Comment by keyboardDrummer** [comment]
Closing this since it's old and we've done fixes since then
