### ISSUE TITLE
Error message for assume statement is misleading

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#3496]
### What change in documentation do you suggest?

If an `assume` statement is left in the source code, Dafny complains:

    Error: an assume statement without an {:axiom} attribute cannot be compiled

This message seems to suggest that an `assume` statement _can_ be compiled if you only add the `{:axiom}` attribute to it. Here's a replacement error message that I think is more to the point:

    Error: an assume statement cannot be compiled (use the {:axiom} attribute to let the compiler ignore the statement)

**Comment by davidcok** [comment]
I'll add this to a list of error message improvements I'm making.
