### ISSUE TITLE
Deprecate forall statement with no bound variables

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#3497]
### Summary

Dafny allows a `forall` statement to take no bound variables. For example,

``` dafny
forall
  ensures F(x) == 100
{
  // proof why F(x) == 100...
}
```

This degenerate form of `forall` was once useful for stating and proving properties in the middle of code. However, Dafny has now for years had an `assert by` statement that does the same thing:

``` dafny
assert F(x) == 100 by {
  // proof why F(x) == 100...
}
```

The `assert by` keywords immediately suggest the meaning of the statement, whereas the degenerate form of the `forall` statement looks mysterious or ill-formed. Clearly, the `assert by` statement is to be preferred.

I therefore suggest we deprecate the 0-variable form of the `forall` statement. This will promote the clearer statement and will reduce code paths in the Dafny implementation.

### Background and Motivation

.

### Proposed Feature

.

**Comment by davidcok** [comment]
Fixed in a current branch.
