### ISSUE TITLE
Allow a directory as the value of --libraries

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#3513]
### Summary

Currently Dafny requires all library files to be listed individually as .dfy files. This requires users to know just what is needed from a possibly large collection of files.

### Background and Motivation

A user should be able to use a library without having to worry too much about how it is internally packaged -- which files are present, which depend on which etc. While include files are helpful, the usual way to use a library is for the user to be able to say: here is a library, use what you need.

### Proposed Feature

That --libraries take a directory as its value, meaning all the .dfy files recursively in that directory

**Comment by keyboardDrummer** [comment]
I'd rather have this option accept a list of arguments, so users can use shell filename expansion to do various things such as pass all dafny files reachable from a directory.

**Comment by davidcok** [comment]
A comma-separated list of arguments would be great. But it does not really replace allowing a directory. To get the equivalent, one would have to use `find` to list the *.dfy files and then massage that list into a comma-separated or `--library:` - prefixed list. Just in working with the library code I've found the option to give a directory very helpful, as it has been for `dafny format` also.
