### ISSUE TITLE
Devise a single file package for a group of .dfy files (e.g. a library)

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#3514]
### Summary

To ship around and use a library, it is convenient to have them be in a single file and not to have to unpack them into a directory structure.

### Background and Motivation

Lots of libraries work like this: e.g. jar files, .so and .a files, .dll files

### Proposed Feature

a) Decide on a single file container for .dfy files, say a .zip file. It might also contain non-.dfy files (tet files, Dafny project files etc.)
b) Allow the dafny tool to take such a file as the value of the --library option and perhaps also on the command-line.
The meaning is as if every file in that package that is meaningful to the --library option or on the command-line is extracted and listed individually.

**Comment by keyboardDrummer** [comment]
This single file container can also be a .dfy file that combines the contents of all the source .dfy files.

**Comment by davidcok** [comment]
A concatenated file is easy to package, but requires the user's use of dafny to at least parse the entire file. Having a packaging that breaks that up into multiple .dfy files makes it possible to be smarter about what is parsed/resolved and what is not.
