### ISSUE TITLE
Character Arithmetic Underflow Rejection

### ISSUE THREAD

**Issue by alex-usher** [dafny-lang/dafny#3517]
### Dafny version

3.11.0.50201

### Code to produce this issue

```dafny
method Main() {
    var v1 := 'c';

    if ('c' - (v1 + 'c') < 'c') {
        print 'a';
    } else {
        print 'b';
    }
}
```

### Command to run and resulting output

```code
$ dafny /noVerify /compile:2 /compileTarget:cs main.dfy
$ dotnet main.dll
> b

$ dafny /noVerify /compile:2 /compileTarget:go main.dfy
$ ./main
> a
```

### What happened?

Hi! 

I recently identified the above case which generates different outputs across the backends - 'b' for cs, java and js, 'a' for go and cpp, and for py it is rejected by the Python interpreter. 

Would you be able to clarify the expected behaviour for cases with character arithmetic underflow - is it the case that the compiler assumes a program doesn't contain this behaviour since the verifier checks for this? I would otherwise have expected cases like this to be rejected.

Thanks! Alex

### What type of operating system are you experiencing the problem on?

Mac

**Comment by fabiomadge** [comment]
You are correct, the compiler is only intended to be used with valid Dafny programs, so it it only sound to use the compiler if the verifier accepts the program.
