### ISSUE TITLE
setup-dafny action should support latest-release and latest-nightly

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#3530]
### Summary

The setup-dafy action only supports specific release numbers

### Background and Motivation

The need to be able to install the latest dafny release within an action script, -- in particular, in the tests of the Dafny libraries

### Proposed Feature

Enhance the action script to support latest-release and latest-nightly

**Comment by alex-chew** [comment]
Related issue in the setup-dafny-action repo: https://github.com/dafny-lang/setup-dafny-action/issues/12

**Comment by alex-chew** [comment]
latest-nightly is supported as of setup-dafny-action@v1.6.0. latest-release support is not planned for now:

> It goes against repeatable builds, and especially in Dafny's case automatically picking up the latest version just means being forced to immediately deal with verification variability.

(https://github.com/dafny-lang/setup-dafny-action/pull/13#issuecomment-1430188304)
