### ISSUE TITLE
bv-to-char conversion results in malformed Boogie

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#356]
A conversion from a bitvector type (like `bv32`) to `char` produces malformed Boogie, as illustrated by the following repro:

```
method Test(b: bv32, n: nat)
  requires b < 0x1_0000
  requires n < 0x1_0000
{
  var ch: char;
  ch := n as char;  // translates into char#FromInt(n), which is good
  ch := b as char;  // translates into nat_from_bv32(b), which crashes; should be char#FromInt(nat_from_bv32(b))
  assert true;
}
```

**Comment by davidcok** [comment]
Reviewed and implemented all missing combinations among {int, char, bv, real, ordinal}, both static verification and all compilers. PR#660

**Comment by davidcok** [comment]
Added tests for conversions of subset types. Identified and fixed bug in conversions of real-based subset types.
