### ISSUE TITLE
Change of unicode-char also changes the presentation of output strings

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#3560]
### Dafny version

3.11.0 + dev

### Code to produce this issue

```dafny
See the test: DafnyTests/RunAllTestsOption.dfy
```

### Command to run and resulting output

```code
With unicode-char:false, it produces tests like VoidOutcome.VoidFailure(Whoopsie)
with unicode-char:true, it produces output like VoidOutcome.VoidFailure("Whoopsie")

Is this intended? (Caused a test failure on moving to Dafny 4 -- locked the test at unicode-char:false
```

### What happened?

See above

### What type of operating system are you experiencing the problem on?

Mac

**Comment by alex-chew** [comment]
@davidcok Did you experience this when compiling this to C#, and/or others?

**Comment by davidcok** [comment]
It happens the same for every backend, and just when unicode-char is true

**Comment by robin-aws** [comment]
Yes this is as intended. It's not explicitly documented in the reference manual (as we never explicitly documented the details of how values are printed) but it is at least described in this implementation note: https://github.com/dafny-lang/dafny/blob/master/docs/Compilation/StringsAndChars.md#printing-strings-and-characters
