### ISSUE TITLE
Test contract-wrappers/AllExterns.dfy requires unicode-char:false for no apparent reason

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#3562]
### Dafny version

3.11.0+dev

### Code to produce this issue

Test contract-wrappers/AllExterns.dfy
Also comp/Arrays.dfy

### What happened?

Fails with unicode-char:true, though it does not seem to deal with characters. Perhaps it is OutputCheck?

### What type of operating system are you experiencing the problem on?

Mac

**Comment by robin-aws** [comment]
This is actually an issue with the "halt recovery" functionality used by `/runAllTests`/`dotnet test` not doing the right thing in `--unicode-char` mode: in that mode strings are only printed like strings if the static type of the expression is known to be a `string`, but the halt recovery AST node doesn't pass on the knowledge that the captured string at runtime is in fact a string. Running the `RunAllTestsOptoion.dfy` test with `--unicode-char` produces similar looking failures:

```
...
 TestModule.Passing1: PASSED
 Passing1: PASSED
 Passing2: PASSED
 Failing1: FAILED
-	RunAllTestsOption.dfy(21,2): expectation violation
+	['R', 'u', 'n', 'A', 'l', 'l', 'T', 'e', 's', 't', 's', 'O', 'p', 't', 'i', 'o', 'n', '.', 'd', 'f', 'y', '(', '2', '1', ',', '2', ')', ':', ' ', 'e', 'x', 'p', 'e', 'c', 't', 'a', 't', 'i', 'o', 'n', ' ', 'v', 'i', 'o', 'l', 'a', 't', 'i', 'o', 'n']
...
```

Working on a separate patch that can safely go into the 3.x stream.
