### ISSUE TITLE
Dafny Runtime libraries are different for different unicode-char choice. Do we ship both or just the new default for Dafny 4

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#3570]
### Dafny version

3.11+dev

### Code to produce this issue

```dafny
Run the Runtime test for the Dafny 4 vs 3 defaults -- the library files are changing -- e.g. the go test, which changes the source
```

### What happened?

The precompiled versions of the Dafny runtime library are different for Dafny 3 vs. 4, because of the change in --unicode-char. So do we prepare and ship both?

For `dafny run`, it would appear that we need both available and pick the right one depending on the option setting. Plus need to acquaint the users with the need to use the correct one in their build systems.

So there is a design issue here of how to package and present these alternatives.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by robin-aws** [comment]
Can you clarify this a bit? "the library files are changing -- e.g. the go test, which changes the source". Which go test is that?

The intention at least is that the runtimes contain the implementation for either mode, e.g. boxing datatypes like "CodePoint". The compiler just emits different references in the different modes.

**Comment by robin-aws** [comment]
Ah I see, if you use `--unicode-char` when bootstrap-compiling the `DafnyRuntimeDafny` project inside the Dafny implementation, you get slightly different output:

```
salkeldr@c889f3b60fe4 DafnyRuntimeDafny % make test
dotnet run --project ../../Dafny --no-build -- verify ./test/dafnyRuntimeFeasibility.dfy ./test/dafnyRuntimeFeasibilityTest.dfy ./src/dafnyRuntimeGo.dfy ./src/dafnyRuntime.dfy

Dafny program verifier finished with 225 verified, 0 errors
dotnet run --project ../../Dafny --no-build -- translate go --no-verify --use-basename-for-filename --bootstrapping --unicode-char src/dafnyRuntimeGo.dfy

Dafny program verifier did not attempt verification
diff src/dafnyRuntimeGo-go/src/dafny/dafny.go ../DafnyRuntimeGo/DafnyRuntimeFromDafny.go
247c247,248
<     panic("dafnyRuntime.dfy[DafnyGo](575,6): " + (Companion_Sequence_.Concatenate(Companion_Sequence_.Concatenate(_dafny.UnicodeSeqOfUtf8Bytes("Concatenation result cardinality would be larger than the maximum ("), Companion_Helpers_.DafnyValueToDafnyString(Companion_Default___.SIZE__T__MAX())), _dafny.UnicodeSeqOfUtf8Bytes(")"))).VerbatimString(false))}
---
>     panic("dafnyRuntime.dfy[DafnyGo](575,6): " + (Companion_Sequence_.Concatenate(Companion_Sequence_.Concatenate(SeqOfString("Concatenation result cardinality would be larger than the maximum ("), Companion_Helpers_.DafnyValueToDafnyString(Companion_Default___.SIZE__T__MAX())), SeqOfString(")"))).String())
>   }
382c383,384
<       panic("dafnyRuntime.dfy[DafnyGo](747,6): " + (_dafny.UnicodeSeqOfUtf8Bytes("expectation violation")).VerbatimString(false))}
---
>       panic("dafnyRuntime.dfy[DafnyGo](747,6): " + (SeqOfString("expectation violation")).String())
>     }
443c445,446
<       panic("dafnyRuntime.dfy[DafnyGo](765,6): " + (_dafny.UnicodeSeqOfUtf8Bytes("Unsupported Sequence implementation")).VerbatimString(false))}
---
>       panic("dafnyRuntime.dfy[DafnyGo](765,6): " + (SeqOfString("Unsupported Sequence implementation")).String())
>     }
make: *** [check-go] Error 1
```

This isn't actually an issue at all, because the Dafny-generated code in the Go runtime is created when building Dafny itself, and not affected by any user configuration. The only thing to fix is to explicitly add `--unicode-char:false` to the Makefile that compiles the bootstrapping Dafny code, so it doesn't break over Dafny 4.0.

**Comment by robin-aws** [comment]
The command to add `--unicode:false` to: https://github.com/dafny-lang/dafny/blob/master/Source/DafnyRuntime/DafnyRuntimeDafny/Makefile#L15

**Comment by davidcok** [comment]
This has been added and fixes the testing problem in runtime tests. Closing this issue, presuming that there are tests that check that all runtimes  libraries work with either unicode setting.
