### ISSUE TITLE
Update z3 dependency

### ISSUE THREAD

**Issue by chenrui333** [dafny-lang/dafny#3601]
re-raise [the previous issue](https://github.com/dafny-lang/dafny/issues/810), currently the project is still using z3 4.8.5, it would be nice to update it to the latest, which is 4.12.1. Thanks!

**Comment by atomb** [comment]
We've got a PR open, #3400, to upgrade, and plan to include this change in the next release.

**Comment by chenrui333** [comment]
I see, thanks @atomb!

**Comment by chenrui333** [comment]
got covered by [3.13.0 release](https://github.com/Homebrew/homebrew-core/pull/124672)
