### ISSUE TITLE
Range of bounds variables in set comprehensions not limited to allocated objects

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#3605]
### Dafny version

3.12.0.50221

### Code to produce this issue

```dafny
method M()
  ensures false
{
  ghost var s, r;
  s := set c: C | True(c);
  label L:
  r := Same(s);

  var c := new C;
  assert c in s; // because s includes all C's, both allocated and unallocated
  assert c !in r; // because t is known to include only allocated objects
  // yet, s and t are equal
}

class C { }

predicate True(s: C) {
  true
}

ghost method Same(s: set<C>) returns (r: set<C>)
  ensures r == s
{
  r := s;
}
```

### Command to run and resulting output

```code
% dafny test.dfy

Dafny program verifier finished with 2 verified, 0 errors
Compiled assembly into test.dll
```

### What happened?

The problem is that the set comprehension `set c: C | True(c)` is modeled as containing _all_ `C` objects, not just those `C` objects that have been allocated in the program. From that encoding, one can prove `false`, as is done in the postcondition of method `M`.

The problem comes about from the too-frugal encoding in the default `/allocated:3`. While the description of `/allocated:4` seems like it would cure the problem, `allocated:4` crashes all over the place.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by jtristan** [comment]
Fxied by #3609
