### ISSUE TITLE
`dafny test` and `--output` option

### ISSUE THREAD

**Issue by DavePearce** [dafny-lang/dafny#3612]
### Summary

_(This is related to #3611)_

Unlike `dafny build`, the `dafny test` command does not support the `--output` option.  When run with the `--target java` option it just dumps the generated `java` files into the directory where the file being tested is contained (in my case `src/dafny` directory).  This is not an ideal place to store generate files, and it would be nice to have some control here.

### Background and Motivation

I'm trying to update by project build file to use the new CLI syntax (e.g. `dafny build`, etc).

### Proposed Feature

Adding `--output` as an option for `dafny test`.

**Comment by keyboardDrummer** [comment]
How would you feel about the generated files being placed in a temporary directory by default for `dafny test` and `dafny run` ? The generated files don't seem particularly relevant for either of these commands.

Also, should the default value of `--output` be something like `output` or `build` ?

**Comment by hmijail** [comment]
One use case for controlling the output in all cases is for build pipelines. If the build product exists and is newer than the sources then we know we don't need to rebuild.

**Comment by DavePearce** [comment]
> How would you feel about the generated files being placed in a temporary directory by default for `dafny test` and `dafny run`

Well, in essence that's what its doing now isn't?  Or do you mean an OS-generated temporary directory (e.g. in `/tmp/` on UNIX systems)?  I think that would be sensible.  Eitherway, as long as I can control where they go, then that is enough.

**Comment by keyboardDrummer** [comment]
> Or do you mean an OS-generated temporary directory (e.g. in /tmp/ on UNIX systems)?

Yes that's what I meant, with the purpose of not letting these temporary files pollute the user's file space.

**Comment by DavePearce** [comment]
> Do you need to control it for run and test, if the files don't get in your way?

Hmmmm, well I feel like control is always a good thing.  For example, if I want to compile directly against an external dependency.  Whilst I did successfully work around that by using an interface with a default implementation for Dafny to compile against, this didn't feel like a great solution.

**Comment by keyboardDrummer** [comment]
> Hmmmm, well I feel like control is always a good thing. For example, if I want to compile directly against an external dependency.

If you want to use `dafny run` with an external dependency, then you have to pass that it on the CLI, like `dafny run myDafnySource.dfy myDotNetDependency.dll`. In this case, why do you want control over where intermediate `.dll` files are placed?

**Comment by DavePearce** [comment]
> If you want to use dafny run with an external dependency, then you have to pass that on the CLI,

Hmmm, so I could pass a `jar` file on the command-line then?  I guess that works.  Generally speaking though, when working with a build system (e.g.  Maven, Gradle, Cargo, etc) you have a directory where generated files get placed (e.g. `bin`, `target`, etc).  Being able to specify where the temporary files go is consistent with that.  It means, for example, I can always clean that directory up.  It also means I can inspect the actual generated code easily enough if I want to, etc.  Otherwise, I have to go digging to figure out where Dafny placed the temporary files if I need to debug them.  Also, if Dafny crashes for some reason, it may not clean up the temporary files, etc.

Anyway, we're probably getting side tracked.  Using a temporary directory for the intermediate files resolves the main issue.  Whether or not you choose to support `--output` I guess is a secondary thing.  Like I said, control is always a good thing IMHO.

**Comment by keyboardDrummer** [comment]
> Generally speaking though, when working with a build system (e.g. Maven, Gradle, Cargo, etc) you have a directory where generated files get placed (e.g. bin, target, etc). Being able to specify where the temporary files go is consistent with that. It means, for example, I can always clean that directory up. It also means I can inspect the actual generated code easily enough if I want to, etc. Otherwise, I have to go digging to figure out where Dafny placed the temporary files if I need to debug them. Also, if Dafny crashes for some reason, it may not clean up the temporary files, etc.

Makes sense. Thanks for adding this!
