### ISSUE TITLE
Extension fails to download latest nightly build on Mac OS ARM64

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#3653]
It seems to construct the download URL incorrectly:

Attempted (leads to 404): `https://github.com/dafny-lang/dafny/releases/download/nightly/dafny-nightly-2023-02-28-dbba173-arm64-osx-11.0.zip`
Should be: `https://github.com/dafny-lang/dafny/releases/download/nightly/dafny-nightly-2023-02-28-dbba173-arm64-macos-11.zip`

I suspect this is a result of tweaking the packaging related to including our own builds of Z3.

**Comment by atomb** [comment]
Ah, yes, we'll need to update the IDE plugin to account for this.

**Comment by atomb** [comment]
See https://github.com/dafny-lang/ide-vscode/pull/361
