### ISSUE TITLE
Investigate disappearance of the blog link

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#3689]
### Dafny version

4.0.0

### What happened?

It appears that the index.html file (on dafny.org) was not properly updated or was overwritten with an older version on doing the 3.13.1 and/or 4.0.0 snapshot. Investigate why and fix.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by fabiomadge** [comment]
I don't there is an issue. `dafny-lang.github.io` should have as little to do with `dafny` as possible. That way we don't have to polute the history with website stuff. Just as the blog is separate.

**Comment by fabiomadge** [comment]
Somewhat related: At the moment, the latest docs are at `dafny.org/latest/DafnyRef/DafnyRef`. I think it would be nicer if they were at `dafny.org/docs`, or maybe `dafny.org/manual`. The whole point of checking them into `dafny-lang.github.io` was getting nicer URLs, but we didn't deliver on that. Older versions could be at `dafny.org/manual/3.12.0`.

**Comment by davidcok** [comment]
The index.html is not copied over during the documentation snapshot, so changes to the development docs/index.html will not automatically appear on the landing page -- the landing page has different embedded links. Such changes are rare.
