### ISSUE TITLE
Dafny internal error on version 3.13.1 and 4.0.0

### ISSUE THREAD

**Issue by Nangos** [dafny-lang/dafny#3691]
### Dafny version

3.13.1 and 4.0.0

### Code to produce this issue

```dafny
trait A {
  predicate f()
  method g() ensures f()     // Line 3
}

class B<T> extends A {       // Line 6
  predicate f() { true }     // Line 7
  method g() ensures f()
}
```

### Command to run and resulting output

```code
Command: `dafny build`

Error: `System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') ...`
```

### What happened?

This happens during my development, but I have made up the minimal example above, and have no further idea what went wrong.

The above code snippet verifies normally on 3.12.0 and earlier versions.

If you remove any one of the following, the error disappears and the code verifies normally:
- `ensures f()` in Line 3
- `<T>` in Line 6
- `{ true }` in Line 7

### What type of operating system are you experiencing the problem on?

Windows

**Comment by fabiomadge** [comment]
To do the override check, we turn an expression that talks about A.f() into one talking about B.f(). This substitution didn't account for the different amounts of type arguments.

**Comment by fabiomadge** [comment]
Thanks a lot for the concise repro! We'll put out a fix shortly.

**Comment by fabiomadge** [comment]
This will be in tomorrow's [nightly build](https://github.com/dafny-lang/dafny/releases/tag/nightly). I'd be thankful if you would try it on your code, to ensure it solves all problems.
