### ISSUE TITLE
Qualified import needs local name

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#371]
Currently, Dafny insists that a qualified import explicitly be given a local name. I don't see a need for this restriction, since Dafny could just as well automatically pick the last component of the qualified name as the local name.

Repro:

```
module MA {
  module Inner {
    type T17 = x | 0 <= x < 17
  }
}

import MA.Inner  // currently disallowed, but I think it should be allowed
```

gives:

```
$ dafny test.dfy
Dafny 2.3.0.10506
test.dfy(7,10): Error: Qualified imports must be given a name.
1 parse errors detected in test.dfy
```

**Comment by davidcok** [comment]
Implemented, using the last name segment as the missing name, with a warning. PR#658

**Comment by davidcok** [comment]
Warning removed.

**Comment by davidcok** [comment]
Note also Issue #659, which adds similar functionality when an export set is specified.
