### ISSUE TITLE
Recursive datatype has incorrectly initialized Java type descriptor

### ISSUE THREAD

**Issue by alex-chew** [dafny-lang/dafny#3766]
### Dafny version

4.0.0.50303 (also occurs in 3.10)

### Code to produce this issue

```dafny
// Good

datatype Tree = Tree(ts: seq<Tree>)

datatype Nothing = Nothing
{
  predicate IsFailure() { false }
}

method Main() {
  var nothing: Nothing := Nothing;
  :- expect nothing;
}

// Bad

datatype Tree = Tree(ts: seq<Tree>)

datatype Nothing<T> = Nothing
{
  predicate IsFailure() { false }
}

method Main() {
  var nothing: Nothing<Tree> := Nothing;
  :- expect nothing;
}
```

### Command to run and resulting output

```code
# Good

$ dafny run --target:java Tmp.dfy
Dafny program verifier finished with 1 verified, 0 errors

$ echo $?
0

# Bad

$ dafny run --target:java Tmp.dfy
Dafny program verifier finished with 1 verified, 0 errors
Exception in thread "main" java.lang.ExceptionInInitializerError
        at _System.__default.Main(__default.java:16)
        at _System.__default.__Main(__default.java:21)
        at Tmp.lambda$main$0(Tmp.java:11)
        at dafny.Helpers.withHaltHandling(Helpers.java:279)
        at Tmp.main(Tmp.java:11)
Caused by: java.lang.NullPointerException: Cannot invoke "dafny.TypeDescriptor.newArray(int)" because "type" is null
        at dafny.ArrayDafnySequence.empty(DafnySequence.java:506)
        at dafny.DafnySequence.empty(DafnySequence.java:68)
        at _System.Tree.<clinit>(Tree.java:39)
        ... 5 more

$ echo $?
3
```

### What happened?

The bad program crashes with a `NullPointerException`, whereas the good program run without errors. The only difference between the two programs is that `Nothing` is parametrized by a recursive datatype in the bad program, but is non-generic in the good program.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by alex-chew** [comment]
The compiled `Tree` class includes the following snippet:

```java
public class Tree {
  // ...

  private static final Tree theDefault = _System.Tree.create(dafny.DafnySequence.<Tree> empty(Tree._typeDescriptor()));
  public static Tree Default() {
    return theDefault;
  }
  private static final dafny.TypeDescriptor<Tree> _TYPE = dafny.TypeDescriptor.referenceWithInitializer(Tree.class, () -> Default());
  public static dafny.TypeDescriptor<Tree> _typeDescriptor() {
    return (dafny.TypeDescriptor<Tree>) (dafny.TypeDescriptor<?>) _TYPE;
  }

  // ...
}
```

During static initialization, `theDefault` initializes with a call to `Tree._typeDescriptor()` before `_TYPE` is initialized, storing a `null` type descriptor. As a first-order fix, swapping the order of the static initializations of `theDefault` and `_TYPE` should resolve the issue, but I'm unsure if this would be safe with respect to other generated code.

**Comment by alex-chew** [comment]
There is a known workaround, which is to force the Java compiler to select a non-recursive default value. For example, if the type parameter of `Nothing` within `Main` is instead the following datatype:

```dafny
datatype Ints = Nil | Cons(x: int, xs: Ints)
```

then the Java compiler will generate a default value of `Nil` and will not call or store the return value of `Tree._typeDescriptor()`.

**Comment by ssomayyajula** [comment]
Some notes for myself:

Default value initialization happens before that of type descriptors in the Java backend; the first uses the second when the datatype in question can only have a default value of nested recursive type.

So, this smaller example will cause an NPE running on the Java backend.

```dafny
datatype Tree = Tree(ts : seq<Tree>) {
  predicate IsFailure { false }
}

method Main() {
  var bad: Tree := Tree([]);
  :- expect bad;
}
```

Wherever else type descriptors are emitted --- classes, tuples, and codatatypes --- seem to not cause any problems (nor do other backends). I will put explanations as to why shortly.
