### ISSUE TITLE
Inconsistency between language server and CLI when using mutually recursive includes

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/dafny#3825]
### Dafny version

4.0.0

### Code to produce this issue

```dafny
// File A.dfy
include "B.dfy"

module A {}

// File B.dfy
include "A.dfy"

module B {}
```

### Command to run and resulting output

```code
dafny resolve A.dfy
```

```
Dafny program verifier did not attempt verification
```

Now open the file through `dafny server`, and get the error "Duplicate module name: A"

### What happened?

Equivalent behavior between `dafny resolve` and `dafny server`

### What type of operating system are you experiencing the problem on?

Mac

**Comment by keyboardDrummer** [comment]
Should be resolved by the work planned in https://github.com/dafny-lang/dafny/issues/3109

**Comment by keyboardDrummer** [comment]
I'm guessing this issue is caused by equivalent file paths not being detected as being equivalent, when using `dafny server`, so a single file is included multiple times. @MikaelMayer didn't we already fix this?

**Comment by MikaelMayer** [comment]
Yes. If you have a repro, to debug this, you can have a look a the function `Canonicalize()`, if you see that it returns two different things for the same file, that's a discrepancy.

**Comment by MikaelMayer** [comment]
We fixed it for Windows recently.
