### ISSUE TITLE
[unsoundness bug] An ode to /allocated:2

### ISSUE THREAD

**Issue by jaybosamiya** [dafny-lang/dafny#384]
Oh thou are a powerful tool.
When proofs are hard, or scare you- boo!
About heaps you are asserting,
About heaps you are assuming:
On every heap, every reference foo
must be found to be allocated too.

Much better than allocated:3.
This is how you want every proof to be.
No trouble with reads.
This works for all your needs.
I believe you'll all agree,
this isn't all just hyperbole.

Well one moment I was just fooling around,
and what I saw was a massive let down.
This damn proof should not go through:
false is simply not true.
I guess I must expound:
allocated:2 is unsound.

## Unsoundness

```
class A {
  constructor()
    ensures false;
  {
  }
}
```

**Expected behavior:** Should complain about the `false`.
**Actual behavior:** Proves it :open_mouth: 
**Tested on:** Current master (https://github.com/dafny-lang/dafny/commit/33eaa4fd4f75533a20db98424ec29ce5c074f1ec) and latest release (https://github.com/dafny-lang/dafny/releases/tag/v2.3.0) -- bug exists on both.

```
$ dafny /compile:0 /allocated:2 bug.dfy
Dafny 2.3.0.10506

Dafny program verifier finished with 1 verified, 0 errors
```
```
$ dafny /compile:0 bug.dfy
Dafny 2.3.0.10506
bug.dfy(4,2): Error BP5003: A postcondition might not hold on this return path.
bug.dfy(3,12): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0

Dafny program verifier finished with 0 verified, 1 error
```
```
$ dafny /compile:0 /allocated:1 bug.dfy
Dafny 2.3.0.10506
bug.dfy(4,2): Error BP5003: A postcondition might not hold on this return path.
bug.dfy(3,12): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0

Dafny program verifier finished with 0 verified, 1 error
```

**Comment by RustanLeino** [comment]
Awesome poem! Thanks for the bug report.
