### ISSUE TITLE
Bugs in Dafny tutorial

### ISSUE THREAD

**Issue by johnwickerson** [dafny-lang/dafny#385]
I found a few bugs (and other opportunities for mild improvements) in the [Dafny tutorial](https://rise4fun.com/Dafny/tutorial/guide) that I thought it might be useful to report.

* "If statements require parentheses around the boolean condition" -> should say "do not require".

* In the spec for `Abs`, you have `ensures 0 <= x ==> x == y` and `ensures x < 0 ==> y == -x`. These could be made more symmetric if the first clause said `ensures 0 <= x ==> y == x"`

* "What precondition doe you need" -> typo

* "Dafny will complain that our post condition doesn't hold" -> should be "postcondition"

* "repairing it relatively easy" -> missing "is"

* "But the crucial step from the loop to the postcondition wouldn't hold." -- I don't think this sentence is true. I think that the reasoning itself still holds, it's just that it doesn't tell us that the loop terminates.

**Comment by RustanLeino** [comment]
Nice suggestions. Thank you!

Once the PR gets approved and merged, the changes will go out on rise4fun with the next release there (which will probably coincides with the next binary release of Dafny).

**Comment by jtojnar** [comment]
It has been over a year, more than two years for [some](https://github.com/dafny-lang/dafny/issues/173#issuecomment-423853049) [of the older](https://github.com/dafny-lang/dafny/issues/177#issuecomment-423853045) [fixes](https://github.com/dafny-lang/dafny/issues/188#issuecomment-378733678). Is the rise4fun update still planned?
