### ISSUE TITLE
Inconsistent Handling of Map Displays across Backends

### ISSUE THREAD

**Issue by alex-usher** [dafny-lang/dafny#3856]
### Dafny version

4.0.0

### Code to produce this issue

```dafny
method Main() {
    var x := map[1 := 1, 1 := 2];
    assert(x[1] == 2);
    print x[1];
}
```

### Command to run and resulting output

```code
- dafny main.dfy && dotnet main.dll # outputs 2
- dafny /compileTarget:js main.dfy && node main.js # outputs 1
```

### What happened?

Hi! I've found this interesting case which I thought you should be made aware of:

For the backends (cs, java, py) it is verified and outputs 2, while for (js, go) it is verified but outputs 1. 
Since this program is verified by Dafny we should expect for js and go backends to output 2, or the program should not be verified.

Thanks! I appreciate I've submitted a couple of issues recently - I'm doing this as part of a project at Imperial College London to fuzz test the Dafny compiler. Feel free to reach out if there are any language features you think are worth fuzzing, and I'm more than happy to help fix any issues if you need it! :)

### What type of operating system are you experiencing the problem on?

Mac

**Comment by robin-aws** [comment]
Thanks for the bug report! Looks like a duplicate of https://github.com/dafny-lang/dafny/issues/1367

I'm curious to hear more about your fuzzing approach. Some similar bugs were found by @sorawee using https://github.com/dafny-lang/xdsmith, and I'd love to put more concerted effort into such regular fuzz testing.

**Comment by alex-usher** [comment]
Ah sorry for the duplicate! I'll try and do a better job of checking next time.
With regards to the fuzzing approach: myself and @dilan-s are both (separately) creating generational fuzzers for testing the Dafny compiler, supervised by Alastair Donaldson at Imperial. Our choice with generation-based testing was to try and overcome the language limitations that using XSmith placed upon XDSmith.
If it would be useful for you, I could drop you an email with more details! We're also in contact with John Tristan who has some perspective on this too. Thanks!

**Comment by robin-aws** [comment]
Dupe of https://github.com/dafny-lang/dafny/issues/1367
