### ISSUE TITLE
Ghost parameters cannot be passed to constructors

### ISSUE THREAD

**Issue by tchajed** [dafny-lang/dafny#386]
It's not possible to pass a ghost variable to a ghost parameter if it's in a constructor, but this works for ordinary class methods, and the constructor definition works out:

```
class Foo {
    // this is accepted
    constructor(ghost b: set<bool>) {}
    constructor Mk() {}
    method Initialize(ghost b: set<bool>) {}
}

method TestConstructor() {
    ghost var b: set<bool> := {};
    var f := new Foo(b);
    // error: ghost variables are only allowed in specification contexts
}

method TestInitialize() {
    ghost var b: set<bool> := {};
    var f := new Foo.Mk();
    // works
    f.Initialize(b);
}
```

I'm using Dafny 2.3.0.10506.

**Comment by samuelgruetter** [comment]
Probably has the same root cause as https://github.com/dafny-lang/dafny/issues/374

**Comment by tchajed** [comment]
Yup, you're right, that's the actual bug.

**Comment by davidcok** [comment]
#374 is fixed. The code example here is added as an additional test case. (git-issue-386.dfy)
