### ISSUE TITLE
Wrong implementation for RotateAny

### ISSUE THREAD

**Issue by ChuyueSun** [dafny-lang/dafny#3866]
https://github.com/dafny-lang/dafny/blob/f4836e93e5bb28195818f685f411b13a86b0c84b/Test/VSI-Benchmarks/b5.dfy#L94-L120

The impl for Rotate and RotateAny are identical. Seems like a typo.

**Comment by robin-aws** [comment]
Good eye, but I don't think it's a typo: `RotateAny` has a weaker specification than `Rotate`, ensuring that the contents have been rotated by SOME number of elements rather than exactly 1. The same implementation happens to satisfy both specifications.
