### ISSUE TITLE
Python Runtime Error during Multiset Iteration

### ISSUE THREAD

**Issue by alex-usher** [dafny-lang/dafny#3874]
### Dafny version

4.0.0

### Code to produce this issue

```dafny
method Main() {
    var s: multiset<bool> := multiset{true};

    while (s != multiset{}) {
        var x :| x in s;
	s := s[x := 0];
    }
}
```

### Command to run and resulting output

```code
dafny /compileTarget:py main.dfy && python main-py/main.py
```

### What happened?

Running the output Python produces the following error:
```
Exception: assign-such-that search produced no value (line 5)
```
Running on other backends terminates successfully. 
From running this with prints, it appears that the loop is entered twice which is why we get the assign-such-that exception.
I can reproduce this for the following Python versions: 3.8, 3.9. I can't reproduce it with 3.11.

### What type of operating system are you experiencing the problem on?

Linux, Mac

**Comment by fabiomadge** [comment]
Thanks for reporting this. Python 3.10 introduced rich comparisons between Counters, which we base our multiset implementation on. With those, inequality is defined as the negation of equality, as we define it, but prior to that, it presumably relied on reference equality, irrespective of the presence of any equality overrides.
