### ISSUE TITLE
"Build against a custom Boogie" procedure needs to use the correct Boogie version

### ISSUE THREAD

**Issue by mattmccutchen-amazon** [dafny-lang/dafny#3876]
### What change in documentation do you suggest?

Today I tried to build the current Dafny `master` (b956d2374d471f08189bc2fffdf5e292d1226c2f) against Boogie from source following [the instructions](https://github.com/dafny-lang/dafny/wiki/INSTALL#build-against-a-custom-boogie), but I got a bunch of errors:

```
Build FAILED.

REDACTED/Source/DafnyCore/Verifier/Translator.ClassMembers.cs(903,9): error CS1503: Argument 6: cannot convert from 'System.Collections.Generic.List<Microsoft.Boogie.Requires>' to 'bool' [REDACTED/Source/DafnyCore/DafnyCore.csproj]
[More errors omitted...]
REDACTED/Source/DafnyCore/Verifier/Translator.TrStatement.cs(1575,23): error CS7036: There is no argument given that corresponds to the required formal parameter 'body' of 'WhileCmd.WhileCmd(IToken, Expr, List<PredicateCmd>, List<CallCmd>, StmtList)' [REDACTED/Source/DafnyCore/DafnyCore.csproj]
    0 Warning(s)
    30 Error(s)
```

It looks like the problem is that the given command `git clone git@github.com:boogie-org/boogie.git` uses the current `master` of Boogie by default, but Boogie has a breaking API change.  When I instead checked out Boogie tag `v2.16.4`, corresponding to the Boogie version that was specified in `Source/DafnyCore/DafnyCore.csproj` before it was patched by `customBoogie.patch`, then I had a successful build.

So I imagine that the instructions should have an additional step to check out the version of Boogie that Dafny is using.  It may not matter if Dafny is caught up on Boogie API changes at any given time, but for the instructions to be correct in the general case, they should include this step.

**Comment by robin-aws** [comment]
Good catch! I updated the wiki to specify checking out the required tag.
