### ISSUE TITLE
INSTALL.md doesn't mention lit, wiki/INSTALL assumes it does

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#392]
Minor issue with the installation instructions: the wiki says to follow INSTALL.md for Mac OS X and Linux, and then the next section says to run the tests using lit.

https://github.com/dafny-lang/dafny/wiki/INSTALL#mac-os-x-and-linux

I figured out how to install it by reading the Windows instructions, so not the end of the world! :)

**Comment by davidcok** [comment]
I encountered this when coming up to speed on Dafny installation, and submitted PR#480 to add essentially the same instructions as are in the Windows documentation.
If you are satisfied you might close this issue.

**Comment by robin-aws** [comment]
Perfect, thanks! :)
