### ISSUE TITLE
Accept multiple instances of the --boogie CLI flag 

### ISSUE THREAD

**Issue by alex-chew** [dafny-lang/dafny#3939]
### Background and Motivation

The `--boogie` CLI flag allows to pass Boogie flags through Dafny subcommands (e.g. `verify` and `build`). Boogie defines several CLI flags that can appear multiple times in a command line, including`/proc`, `/noProc`, `/proverOpt`, and `/logPrefix`.

For example, in Dafny 4.0.0, the following two Dafny command lines are not equivalent:

```bash
# Boogie only sees /logPrefix:b_
# so the solver logs are named b_test.*
$ dafny verify --solver-log='@PREFIX@test' \
  --boogie='/logPrefix:a_' --boogie='/logPrefix:b_' test.dfy

# Boogie sees both /logPrefix:a_ and /logPrefix:b_
# so the solver logs are named a_b_test.*
$ dafny verify --solver-log='@PREFIX@test' \
  --boogie='/logPrefix:a_ /logPrefix:b_' test.dfy
```

### Proposed Feature

It would improve the composability of the Dafny CLI to allow the `--boogie` CLI flag to itself appear multiple times, so that all the provided arguments are joined before being passed to Boogie.

### Alternatives

The simplest workaround is to concatenate all desired Boogie flags into a single `--boogie` Dafny flag.

**Comment by keyboardDrummer** [comment]
I think this is already implemented in master: https://github.com/dafny-lang/dafny/issues/3939
