### ISSUE TITLE
Unexpected handling of variables in match cases 

### ISSUE THREAD

**Issue by Dilan-s** [dafny-lang/dafny#3949]
### Dafny version

4.1.0

### Code to produce this issue

```dafny
method Main() returns () {
  var v: int := 1;

  print v, " \n";
  match 0 {
    case v => {
      print v, " UNEXPECTED\n";
    }
    case _ => {
      print v, " EXPECTED\n";

    }
  }
  print v, " \n";

}
```

### Command to run and resulting output

```code
$ dafny /compile:4 test.dfy
test.dfy(9,4): Warning: this branch is redundant

Dafny program verifier finished with 0 verified, 0 errors
Running...

1 
0 UNEXPECTED
1
```

### What happened?

When a case has a variable which has previously been assigned, dafny appears to reassign the variables value for the scope of the case instead of testing whether its value is equal to the one being matched.

According to the [documentation](https://dafny.org/latest/DafnyRef/DafnyRef#sec-match-statement), this behaviour should only occur on "unused" identifiers. 

In addition this leads to the warning being produced, where the intended behaviour is that the default case is required.

### What type of operating system are you experiencing the problem on?

Linux

**Comment by MikaelMayer** [comment]
I think the easiest way to fix this is to actually fix the documentation which was merely a user-oriented suggestion, not a formal definition.
Dafny authorizes the overwrite and shadowing of existing variables, and pattern matching is no stranger to that.
Thanks for reporting.
