### ISSUE TITLE
Does Dafny support dotnet 7?

### ISSUE THREAD

**Issue by tchajed** [dafny-lang/dafny#3992]
### What change in documentation do you suggest?

The Homebrew formula for Dafny [depends on dotnet@6](https://github.com/Homebrew/homebrew-core/blob/e7bbc68273847775d450f47a5d69da09c961c2cd/Formula/dafny.rb), but my testing suggests that dotnet 7 is totally fine. Can you confirm that Dafny supports dotnet 7?

This issue is labeled as a documentation request but answering here is fine as far as I'm concerned - I'll update the Homebrew formula and that will serve as a form of global documentation.

**Comment by tchajed** [comment]
Looks like dotnet in the Homebrew formula works for me locally but not in Homebrew CI, so it might actually be needed for the build.

**Comment by atomb** [comment]
In some early testing we did with dotnet 7, we saw some rare but recurrent crashes that we wanted to investigate before migrating to it in production. For the moment, dotnet 6 is probably still your best bet, though I hope that doesn't remain true for too long.

**Comment by tchajed** [comment]
Thanks for confirming! The Homebrew tests are actually failing with dotnet 6 for reasons I don't understand (perhaps the build actually checks the dotnet version through a property of the solution file). While it's the recommended version we'll leave things as they are, though.
