### ISSUE TITLE
Proof that worked with v4.0.0 fails with v4.1.0

### ISSUE THREAD

**Issue by khieta** [dafny-lang/dafny#4013]
### Dafny version

4.1.0

### Code to produce this issue

```dafny
// Adapted from http://leino.science/papers/krml275.html

ghost predicate IsTotalOrder<A(!new)>(R: (A, A) -> bool) {
  // connexity
  && (forall a, b :: R(a, b) || R(b, a))
  // antisymmetry
  && (forall a, b :: R(a, b) && R(b, a) ==> a == b)
  // transitivity
  && (forall a, b, c :: R(a, b) && R(b, c) ==> R(a, c))
}

lemma ThereIsAMinimum<A(!new)>(s: set<A>, R: (A, A) -> bool)
  requires s != {} && IsTotalOrder(R)
  ensures exists x :: x in s && forall y :: y in s ==> R(x, y)
{
  var x :| x in s;
  if s == {x} {
    assert forall y :: y in s ==> x == y;
  } else {
    var s' := s - {x};
    assert s == s' + {x};
    ThereIsAMinimum(s', R);
    var z :| z in s' && forall y :: y in s' ==> R(z, y);
    if
    case R(z, x) =>
      forall y | y in s ensures R(z, y) { assert x == y || y in s'; }
    case R(x, z) =>
      forall y | y in s ensures R(x, y) { assert y in s' ==> R(z, y); }
  }
}
```

### What happened?

[This proof](https://github.com/cedar-policy/cedar-spec/blob/main/cedar-dafny/def/util.dfy#L38) (copied above) succeeds with Dafny version 4.0.0, but times out with version 4.1.0. Looking for advice on how to get rid of the timeout.

To build our code, you can clone our repository [cedar-policy/cedar-spec](https://github.com/cedar-policy/cedar-spec), change into the `cedar-dafny` directory and run `make`:
```
git clone https://github.com/cedar-policy/cedar-spec.git
cd cedar-spec/cedar-dafny
make
```
Our build systems sets the Dafny version through [cedar-dafny/.config/dotnet-tools.json](https://github.com/cedar-policy/cedar-spec/blob/main/cedar-dafny/.config/dotnet-tools.json), so to change the Dafny version you'll need to edit that file.

Alternatively, you can build the proof in VS Code.

**Related question:** While looking into this, I found that the proof would time out in VS Code, but just hang on the command line. Do I need to set a timeout manually?

### What type of operating system are you experiencing the problem on?

Mac

**Comment by MikaelMayer** [comment]
Can you please add the attribute `{:vcs_split_on_every_assert}` and `{:rlimit 3000}` to the lemma and let me know precisely where the proof now fail? I can't repro it on my local machine with just the example.

**Comment by khieta** [comment]
Thanks for getting back to me! When I run `make` with those annotations I get the following output.
```
$ make
dotnet tool restore
Tool 'dafny' (version '4.1.0') was restored. Available commands: dafny

Restore was successful.
rm -rf TestResults/*.csv TestResults/*.trx
dotnet tool run dafny /dafnyVerify:1 /dafnyVerify:1 /compile:0 /warnShadowing /warningsAsErrors /vcsLoad:1 /definiteAssignment:3 /verificationLogger:csv def/util.dfy
/Users/khieta/Code/cedar-policy/cedar-spec/cedar-dafny/def/util.dfy(38,52): Verification out of resource (def.util.ThereIsAMinimum (correctness))

Dafny program verifier finished with 16 verified, 0 errors, 1 out of resource
Results File: /Users/khieta/Code/cedar-policy/cedar-spec/cedar-dafny/TestResults/2023-05-15_16_01_23-0.csv
make: *** [def/util.dfy] Error 4

```

Interestingly: when I isolate the code snippet I copied in my issue into its own module, I don't see a timeout. It's only when it's in the context of the file I linked. Perhaps this is why you couldn't reproduce?

**Comment by MikaelMayer** [comment]
What I means is to use these annotations within VSCode. See there result of using them. It shows that the postcondition failed to prove (in the context of your code.

![image](https://github.com/dafny-lang/dafny/assets/3601079/6a3c19a0-f7e9-4cfe-9489-d3f8633a4704)

Other than that, for the little I've investigated, you've found real incompleteness bug, although I also have the same issue in 4.0.0 on my machine.

**Comment by stefan-aws** [comment]
Note that I recently [added](https://github.com/dafny-lang/libraries/blob/b57bcff594637ac298b69ebd59cbd0b097de30b1/src/Collections/Sets/Sets.dfy#L293) the result you refer to to the standard library.

**Comment by stefan-aws** [comment]
I can confirm that building with 4.0 works, whereas with 4.1. it leads to a timeout. Verification within VSCode works for me with both 4.0 and 4.1.

**Comment by stefan-aws** [comment]
This slight variation of your proof works both in 4.0 and 4.1 for me:

```
lemma ThereIsAMinimum<A(!new)>(s: set<A>, R: (A, A) -> bool)
  requires s != {} && IsTotalOrder(R)
  ensures exists x :: x in s && forall y | y in s :: R(x, y)
{
  var x :| x in s;
  if s == {x} {
    assert forall y | y in s :: x == y;
  } else {
    var s' := s - {x};
    assert s == s' + {x};
    ThereIsAMinimum(s', R);
    var z :| z in s' && forall y | y in s' :: R(z, y);
    if
    case R(z, x) =>
      assert s == s' + {x};
      assert z in s;
      forall y | y in s ensures R(z, y) { if y == x { assert R(z, x); } else { assert y in s'; } }
    case R(x, z) =>
      assert x in s;
      forall y | y in s ensures R(x, y) { if y == x { assert R(x, x); } else { assert y in s'; } }
  }
}
```

Generally, I'd recommend using `forall y | y in s :: P(y)` instead of `forall y | y in s ==> P(y)`.

**Comment by stefan-aws** [comment]
Finally, here is a shorter version that removes most of the assertions (see also the standard library).

```
lemma ThereIsAMinimum2<A(!new)>(s: set<A>, R: (A, A) -> bool) returns (m: A)
  requires s != {} && IsTotalOrder(R)
  ensures m in s && (forall y :: y in s ==> R(m, y))
{
  var x :| x in s;
  if s == {x} {
    //assert forall y :: y in s ==> x == y;
    m := x;
  } else {
    var s' := s - {x};
    //assert s == s' + {x};
    var z := ThereIsAMinimum2(s', R);
    //var z :| z in s' && forall y :: y in s' ==> R(z, y);
    if
    case R(z, x) =>
      m := z;
      //forall y | y in s ensures R(z, y) { assert x == y || y in s'; }
    case R(x, z) =>
      m := x;
      //forall y | y in s ensures R(x, y) { assert y in s' ==> R(z, y); }
  }
}
```
