### ISSUE TITLE
Cannot prove tautology even with quantifiers

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#4042]
### Dafny version

Latest

### Code to produce this issue

```dafny
opaque ghost predicate R21(i: int, j: int) {
  true
}

lemma Identity(i: int)
  requires forall j: int :: R21(i, j)
  ensures forall j: int :: R21(i, j)
{
  forall j: int ensures R21(i, j) {

  }
}
```

### Command to run and resulting output

```code
Paste in VSCode
```

### What happened?

![image](https://github.com/dafny-lang/dafny/assets/3601079/e140818f-bfb7-4763-8322-da9509ee32a1)
Normally it should verify. It does verify if I remove "opaque".
The reason why I have "opaque" is that it's because I would like to remember later that I want to implement it as an opaque function

### What type of operating system are you experiencing the problem on?

Windows

**Comment by keyboardDrummer** [comment]
Closing because this verifies in Dafny 4.6
