### ISSUE TITLE
Assigning to variables in `by` clause leads to unsoundness

### ISSUE THREAD

**Issue by dddzzz18** [dafny-lang/dafny#408]
It looks like you can modify program variables inside of a `by` scope.  This allows you to assert false like so:
```
lemma foo() {
    ghost var x := 5;
    assert x == 6 by {
        x := 6;
    }
    assert x == 5; // this is still true
    assert false;
}
```
reproduced by compiling Dafny commit `cc0b23ce` (the most recent one).

**Comment by RustanLeino** [comment]
An embarrassing omission. Thank you!
