### ISSUE TITLE
Change "semi expected" to "semicolon expected"

### ISSUE THREAD

**Issue by glhrmv** [dafny-lang/dafny#414]
One of the parser errors is the expectation of a semicolon that wasn't found. To the user, this error message is "`semi expected`", which I would argue is less clearer than "`semicolon expected`". The parser error message is found in this line:

https://github.com/dafny-lang/dafny/blob/cc0b23ced11ee65d545728b05a5013fa58330c13/Source/Dafny/Parser.cs#L5773

If this is a desired change, I can submit a pull request addressing this.

**Comment by RustanLeino** [comment]
Yes, please submit a pull request. Note, however, that `Parser.cs` is automatically generated by Coco. So, you'll need to make a change in `Dafny.atg` and then re-run Coco using `Source/Dafny/Makefile` (for Windows) or `Source/Dafny/Makefile.Linux` (for Linux or Mac).

Thanks!
