### ISSUE TITLE
Resolution regression

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#4144]
### Dafny version

28397e8

### Code to produce this issue

```dafny
module P {
  predicate m() reads {}
} 
module Q refines P {
  predicate m() { true }
}
```

### Command to run and resulting output

```code
dafny resolve

The above example ran without error in past versions of dafny, 
but now fails with recent commit 28397e8 on 6/6.
```

### What happened?

Recent commit broke at least one valid example.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by RustanLeino** [comment]
This is a bug. It should infer the type of this `{}` (in the `reads` clause) to be `set<object>`. As a workaround, omit the `reads {}` altogether.

**Comment by davidcok** [comment]
Per Rustan, the {} should resolve as set<object>
