### ISSUE TITLE
Reserved name in go not escaped

### ISSUE THREAD

**Issue by fabiomadge** [dafny-lang/dafny#4181]
### Dafny version

4.1.0

### Code to produce this issue

```dafny
module C {}

method Main(){
    print "done\n";
}
```

### What happened?

Compiling the go sources fails.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by fabiomadge** [comment]
The reserved names, like `fmt`, are still not escaped properly.

**Comment by MikaelMayer** [comment]
It seems that you have more tests in reserve than this issue described.
Can you please create a separate issue for other reserved names that are not escaped properly? #4431 fixes only the problem mentioned in this issue.

**Comment by fabiomadge** [comment]
I just used the shortest example I could find, I don't have a complete list, sorry.

**Comment by MikaelMayer** [comment]
Closed in favor of https://github.com/dafny-lang/dafny/issues/5283
