### ISSUE TITLE
Auto-ghost doesn't work in match

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#425]
If a method call declares new local variables for the out-parameters of the call, then those actual out-parameters will automatically be declared as ghost when the corresponding formal out-parameters are ghost. However, this mechanism is broken for calls inside `match` statements.

```
method M() returns (x: int, ghost y: int)

datatype Color = Red | Blue
  
method Main() {
  var x0, y0 := M();  // this is fine: x0 is compiled, y0 is ghost
  var c: Color;
  match c
  case Red =>
    var x1, y1 := M();  // this generates an error, saying y1 is not ghost :(
  case Blue =>
}
```

**Comment by davidcok** [comment]
Auto detection of ghost was missing because Cloner.CloneExpr was missing a case for AutoGhostIdentifierExpr.

Fixed in PR #843
