### ISSUE TITLE
Induction proof fails when the predicate is opaque

### ISSUE THREAD

**Issue by VictorYYW** [dafny-lang/dafny#4266]
### Dafny version

4.0.30319

### Code to produce this issue

```dafny
opaque ghost predicate P(i: nat)

lemma SimpleInduction(j: nat)
  requires P(0)
  requires forall i: nat :: P(i) ==> P(i+1)
  ensures P(j)
{
  if j == 0 {
  } else {
    assert forall i: nat :: P(i) ==> P(i+1); // failure
    SimpleInduction(j-1);
  }
}
```

### Command to run and resulting output

```code
Proof failed on Dafny Playground.
```

### What happened?

Making the predicate opaque prevents the precondition of the induction to be proved.

### What type of operating system are you experiencing the problem on?

Linux

**Comment by fabiomadge** [comment]
Thanks for the report! It looks like we resolved the underlying issue in master. Until the next release, you can try the lastest [nightly build](https://github.com/dafny-lang/dafny/releases/tag/nightly).

**Comment by VictorYYW** [comment]
Fabio, thank you for checking! Can confirm `dafny-nightly-2023-07-10` does not have this bug.
