### ISSUE TITLE
multiple decreases clauses (is this a bug?)

### ISSUE THREAD

**Issue by Meijster** [dafny-lang/dafny#4268]
I played with Dafny and the exercises from Leino's book. Exercise 3.5 asks for a decreases clause to prove the termination of the following function:

```
function K(x: nat, y: nat, z: nat): int
{
    if x < 10 || y < 5 
    then x + y
    else if z == 0
        then K(x-1, y, 5)
        else K(x, y-1, z-1)
}
```
Now, I added the clause "decreases x + y" which works fine (as expected). But what also works is "decreases 6*(x+y) + z" (also as expected). What does not work is "decreases 5*(x+y) + z" (also as expected).

But what surprised me is that I can have two (or even more) decreases clauses, and it appears that as soon as one of the decreases works, the others are happily accepted (or should I say ignored?).

Is that a bug, or intended behavior (in which case I miss the point)?

```
function K(x: nat, y: nat, z: nat): int
    decreases 5*(x+y) + z
    decreases x+y
{
    if x < 10 || y < 5 
    then x + y
    else if z == 0
        then K(x-1, y, 5)
        else K(x, y-1, z-1)
}
```
This is accepted by Dafny, but if you comment out the "decreases x+y" line, it fails (and that is correct).

**Comment by stefan-aws** [comment]
In general, the two clauses
```
decreases x
decreases y
```
are equivalent to the single lexicographically-order clause
`decreases x, y`,
see https://dafny.org/latest/DafnyRef/DafnyRef#sec-decreases-clause.

In your case, `decreases 5*(x+y) + z, x+y` verifies, even though `decreases 5*(x+y) + z` alone does not.

As a side note: this means that the order of `decreases` clause is important. For example, the function below verifies

```
function F(x: nat, y: nat): nat
  decreases x
  decreases y
{
  if x == 0 then
    0 
  else 
    F(x - 1, y * 2)
}
```
but the function 
```
function F(x: nat, y: nat): nat
  decreases y
  decreases x
{
  if x == 0 then
    0 
  else 
    F(x - 1, y * 2)
}
```
does not.
