### ISSUE TITLE
Resolution depends on order of class and newtype

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/dafny#4272]
### Dafny version

4.1

### Code to produce this issue

```dafny
module Bar {
  class Foo {
    const c0: b1 := 4 // Has error 'type for constant 'c0' is 'b1', but its initialization value type is 'int''
  }
  newtype b1 = x | 0 <= x < 11/2
}

module Zar {
  newtype b1 = x | 0 <= x < 11/2
  class Foo {
    const c0: b1 := 4 // No error
  }
}
```

**Comment by harvey-challinor** [comment]
I have produced a minimal example that produces no verification error with Dafny 4.1.0 but does for Dafny 4.2.0:
```
newtype Num = x | 0 <= x < 10
const maxNum: Num := 9
```
The error is `issue4272.dfy(2,6): Error: type for constant 'maxNum' is 'Num', but its initialization value type is 'int'`

**Comment by keyboardDrummer** [comment]
@harvey-challinor thanks for the report. Your issue is indeed related to the above one. 

Dafny 4.1 translated your example to

```dafny
newtype b1 = x | 0 <= x < 11/2
class _default {
  const c0: b1 := 4 // No error
}
```

while 4.2 translates it to

```dafny
class _default {
  const c0: b1 := 4 // Error
}
newtype b1 = x | 0 <= x < 11/2
```

Which triggers the problem this issue reported

**Comment by RustanLeino** [comment]
This is fixed in new type inference, which is not yet part of Dafny. In the meantime, there is a simple workaround, which is to give the type of `x` explicitly:

``` dafny
newtype Num = x: int | 0 <= x < 10
const maxNum: Num := 9
```

**Comment by keyboardDrummer** [comment]
Closing because this is resolved when using `--type-system-refresh`, which will soon become the default
