### ISSUE TITLE
Dafny printing change with inconsistencies

### ISSUE THREAD

**Issue by Dilan-s** [dafny-lang/dafny#4358]
### Dafny version

4.2.0

### Code to produce this issue

```dafny
method Main() {
  print "abcd", "\n";
  print (1, "abcd"), "\n";
}
```

### Command to run and resulting output

```code
$ Dafny /compile:4 /compileTarget:- test.dfy 

Dafny program verifier finished with 0 verified, 0 errors
Running...

abcd
(1, ['a', 'b', 'c', 'd'])
```

### What happened?

This issue occurs on all backends, with the string portion being printed differently when they are contained within another type. For example, above is shown that the string prints as expected (though previously it would have printed as ```"abcd"``` containing the quotation marks), whereas when the string is placed within a tuple, it is treated as a seq<char> which previously it did not do unless it was more than one level deep (i.e. seq<seq<char>> would print as above previously).

### What type of operating system are you experiencing the problem on?

Linux

**Comment by atomb** [comment]
I think I remember this being an intentional decision that came along with the switch to proper Unicode characters. Do I remember that correctly, @robin-aws?

**Comment by Dilan-s** [comment]
```dafny
method Main() returns ()
{
  var c: char := 'c';
  var s: string := "string";
  var c_in_seq:seq<char> := ['c', 'h', 'a', 'r'];
  var s_in_seq:seq<string> := ["string1", "string2"];
  var s_in_seq_seq: seq<seq<string>> := [["string1", "string2"], ["string3", "string4"]];
  var c_in_seq_seq: seq<seq<char>> := [['c', 'h'], ['a', 'r']];

  print c, "\n";
  print s, "\n";
  print s_in_seq, "\n";
  print c_in_seq, "\n";
  print s_in_seq_seq, "\n";
  print c_in_seq_seq, "\n";
}
```

```shell
'c'
string
[['s', 't', 'r', 'i', 'n', 'g', '1'], ['s', 't', 'r', 'i', 'n', 'g', '2']]
[['s', 't', 'r', 'i', 'n', 'g', '1'], ['s', 't', 'r', 'i', 'n', 'g', '2']]
char
[[['s', 't', 'r', 'i', 'n', 'g', '1'], ['s', 't', 'r', 'i', 'n', 'g', '2']], [['s', 't', 'r', 'i', 'n', 'g', '3'], ['s', 't', 'r', 'i', 'n', 'g', '4']]]
[['c', 'h'], ['a', 'r']]
```

If this is a design decision then it would be good to understand why, it seems strange to have the inconsistency from the approach of a user who may be expecting the string variable in their sequence to be printed as such, but instead to see the characters? @atomb @robin-aws 

This issue can also be closed if this is the decision being made.
