### ISSUE TITLE
Crash of the language server on a super small code

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#4380]
### Dafny version

4.2.0

### Code to produce this issue

```dafny
class A {
  method
```

### Command to run and resulting output

```code
Paste in VSCode. It crashes the server (although it does recover if I fix it)
```

### What happened?

This code is typical of what I am writing in Dafny. Seeing crashes on the language server because of that is annoying.

### What type of operating system are you experiencing the problem on?

Windows

**Comment by keyboardDrummer** [comment]
What's the stacktrace?
