### ISSUE TITLE
unresolved identifiers when using export reveals (VSCode only)

### ISSUE THREAD

**Issue by akravc** [dafny-lang/dafny#4407]
### Dafny version

4.2.0

### Code to produce this issue

```dafny
module X.Y {
  export reveals Z

  function Z(i: int): int {
    i
  }
}

module A {
  import X 

  function B(i: int): int {
    X.Y.Z(i)
  }
}
```

### Command to run and resulting output

```code
Run in VSCode
```

### What happened?

Should verify, but results in a resolver error with the message: "unresolved identifier: Z"

This only happens in VSCode, works fine from the command line.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by MikaelMayer** [comment]
Fixed recently by #4237
