### ISSUE TITLE
Documentation issue: surprising that /noVerify blocks /compile and /spillTargetCode 

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#442]
Some combinations of these flags results in the Dafny CLI failing to output CS code:

```
> echo "method Main() {}" >> test.dfy

> dafny test.dfy
Dafny 2.3.0.10506

Dafny program verifier finished with 0 verified, 0 errors
Compiled assembly into test.exe

> dafny test.dfy /noVerify
Dafny 2.3.0.10506

Dafny program verifier finished with 0 verified, 0 errors

> dafny test.dfy /compile:0 /spillTargetCode:2
Dafny 2.3.0.10506

Dafny program verifier finished with 0 verified, 0 errors
Compiled program written to test.cs

dafny test.dfy /compile:0 /spillTargetCode:2 /noVerify
Dafny 2.3.0.10506

Dafny program verifier finished with 0 verified, 0 errors
```

**Comment by robin-aws** [comment]
Turns out this may be by design and I just misread the flag documentation: raising the /compile or /spillTargetCode flag levels to where they apply "regardless of verification outcome". In other words, /noVerify is interpreted as a failing and blocking verification outcome.

```
> dafny test.dfy /compile:2 /noVerify
Dafny 2.3.0.10506

Dafny program verifier finished with 0 verified, 0 errors
Compiled assembly into test.exe

> dafny test.dfy /compile:0 /spillTargetCode:3 /noVerify
Dafny 2.3.0.10506

Dafny program verifier finished with 0 verified, 0 errors
Compiled program written to test.cs
```

Leaving this issue open as more of a documentation bug. I'd suggest these flags should be refactored to be more intuitive and readable, as it's easy to forget what each magic number means and how they interact.

**Comment by RustanLeino** [comment]
The interactions between these flags is indeed tricky and not always thought out. In the above, an additional complication is that `/noVerify` is a Boogie flag--Dafny pays no attention to it and just passes it down to Boogie. This could also be changed.
