### ISSUE TITLE
Is there a way to force dafny to compile unverified code with "/noVerify"?

### ISSUE THREAD

**Issue by ChuyueSun** [dafny-lang/dafny#4491]
### What change in documentation do you suggest?

The "/noVerify" flag does not seem to do that.

**Comment by atomb** [comment]
If you're using the old-style options, `/compile:2` should do that for you. Use it in conjunction with `/noVerify` to not attempt verification.

If you're using the new top-level commands, `dafny translate`, `dafny build`, and `dafny run` accept a `--no-verify` flag to skip verification.
