### ISSUE TITLE
Pattern-matching assignment omits ghost check

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#452]
A ghost cannot be assigned to a compiled variable. But this check is missing for the assignment statement that takes a pattern on the left.

```
function TwinPrimes(): (int, int) {
  (41, 43)
}

method Main() {
  // var p := TwinPrimes();  // uncommented, this gives an error, as expected
  var (x, y) := TwinPrimes();  // this should not be allowed, but the Resolver doesn't do the check
  print x, " ", y, "\n";
}
```

Without the check, the compiler produces malformed code:

```
$ dafny /compile:3 test.dfy
Dafny 2.3.0.10506

Dafny program verifier finished with 0 verified, 0 errors
Errors compiling program
/tmp/uq2q7gh0.0.cs(1628,71) : error CS0117: `_module.__default' does not contain a definition for `TwinPrimes'
```

  Rustan

**Comment by davidcok** [comment]
Fixed in PR#842. Confirming a fix previously done somewhere.

**Comment by davidcok** [comment]
Discussion expanded this issue. For any declaration statement (var ...), with local variables or a pattern, with an initialization then all the new variables should be auto-ghost. Which would make the two examples above allowed, except for the print statement.

**Comment by davidcok** [comment]
Another example:

datatype Record = Record(a: int, ghost b: int)
function method TwinPrimes(): Record {
  Record(41, 43)
}
method Main() {
  var u :=
    var Record(x, y) := TwinPrimes();
    y;
  print u, "\n";
}

**Comment by davidcok** [comment]
Added test cases and code for this example also
