### ISSUE TITLE
Type error around + and if is incorrect

### ISSUE THREAD

**Issue by tchajed** [dafny-lang/dafny#4547]
### Dafny version

4.2.0

### Code to produce this issue

```dafny
function bits(n: nat): seq<nat>
{
  if n == 0 then []
  else (if (n % 2 == 0) then 0 else 1) + bits(n/2)
}
```

### Command to run and resulting output

```code
$ dafny verify
  |
4 |   else (if (n % 2 == 0) then 0 else 1) + bits(n/2)
  |         ^^

src/examples/type_bug.dfy(4,8): Error: the two branches of an if-then-else expression must have the same type (got int and int)
  |
4 |   else (if (n % 2 == 0) then 0 else 1) + bits(n/2)
  |         ^^

src/examples/type_bug.dfy(4,8): Error: the two branches of an if-then-else expression must have the same type (got int and int)
```

### What happened?

Dafny's type checking error message is confusing and incorrect for this code: "the two branches of an if-then-else expression must have the same type (got int and int)" (this is for `if (n % 2 == 0) then 0 else 1`, not the outer `if`). There's no type mismatch in that code.

This code _does_ have a type error: that if expression has type `nat` when it needs to have type `seq<nat>` to be compatible with the right-hand side.

I'm running Dafny nightly (on 2023-09-13).

### What type of operating system are you experiencing the problem on?

Mac

**Comment by keyboardDrummer** [comment]
We're currently working on a large change in Dafny's type inference mechanism. This might already be resolved in the new mechanism (@RustanLeino ?), but in any case it's more practical if we resolve this once that mechanism becomes the default.

**Comment by keyboardDrummer** [comment]
The error is fixed in the new time system, it now reports: 

```
/Users/rwillems/Documents/Sync/Temp/HasProjectFile2/newTypeSystem.dfy(4,29): Error: integer literal used as if it had type seq<int>
  |
4 |   else (if (n % 2 == 0) then 0 else 1) + bits(n/2)
  |                              ^

/Users/rwillems/Documents/Sync/Temp/HasProjectFile2/newTypeSystem.dfy(4,36): Error: integer literal used as if it had type seq<int>
  |
4 |   else (if (n % 2 == 0) then 0 else 1) + bits(n/2)
  |                                     ^
```
