### ISSUE TITLE
array != null

### ISSUE THREAD

**Issue by ChuyueSun** [dafny-lang/dafny#4578]
### What change in documentation do you suggest?

Whenever I check if an array<T>!=null, I always get this warning:
[Warning: the type of the other operand is a non-null type, so this comparison with ‘null’ will always return ‘bool‘hint ](https://dafny.org/dafny/HowToFAQ/Errors#r_trivial_null_test)

But I cannot find any documentation saying that array<T> is non-nullable. There is also old dafny code that suggests array<T> used to be nullable. [stackoverflow code](https://stackoverflow.com/questions/31629705/why-does-this-dafny-assertion-involving-arrays-fail)
[cmu lec notes](https://www.cs.cmu.edu/~mfredrik/15414/lectures/17-notes.pdf) 
or even here in the [doc](https://github.com/dafny-lang/dafny/blob/bc9419dc53af4a1e80b2fa10067f6af2271cadc2/docs/OnlineTutorial/guide.md#predicates)

**Comment by julioapm** [comment]
Dear friend, section "5.6.3.2. Non-null types" present the concept of null and non-null types. The type "array" is non-null, and type "array?" is nullable.

**Comment by ChuyueSun** [comment]
Is array used to be nullable?

**Comment by MikaelMayer** [comment]
Yes array used to be nullable, and I'm grateful for the day it was decided to introduce a type for the nullable version of the array.
