### ISSUE TITLE
Is there an option to generate constrained Horn clauses?

### ISSUE THREAD

**Issue by Columpio** [dafny-lang/dafny#4580]
I am looking for an option of the Dafny to extract constraint Horn clauses in smt2 format, so that you could run Spacer on it.

**Comment by zafer-esen** [comment]
I don't believe there is currently any support for constrained Horn clauses (CHCs) in Dafny / Boogie. The closest thing I could find was [this](https://github.com/horn-ice/hice-dt), but it doesn't look like it does what you are looking for.  

I think it would be very interesting to explore how CHCs can be used in the context of Dafny & Boogie.

**Comment by Columpio** [comment]
It's a pity. Anyway, thank you for the answer.
