### ISSUE TITLE
Allow Dafny commands on individual files to take metadata from a project file

### ISSUE THREAD

**Issue by fzaiser** [dafny-lang/dafny#4624]
### Summary

It would be very useful if I could run a `dafny <command>` on an individual file, while taking metadata, i.e. information about includes & options, from the project file `dfyconfig.toml` *without running the command on all files in the project*. (This feature request is related to #4622.)

### Background and Motivation

Using a project file `dfyconfig.toml` is great because of improved IDE features and not having to write `include`s anymore. That's why we're using it in [the VMC repository](https://github.com/dafny-lang/Dafny-VMC) and got rid of our `include`s. However, without the `include`s, one cannot run dafny commands on a single file anymore. Instead one can only run `dafny <command> dfyconfig.toml`. Running commands on a single file can be desirable because it is often faster, especially for `dafny build` or `dafny verify`.

### Proposed Feature

I see two ways to implement this.

*1. an explicit command line option*: add a command-line option `dafny <command> ... --config dfyconfig.toml` to all dafny commands (naming & details are of course subject to bike-shedding). This will read metadata (list of files & options) from `dfyconfig.toml` and run `dafny <command> ...`, with the difference that the files in `dfyconfig.toml` are automatically included and the options listed in `dfyconfig.toml` are applied to `dafny <command>`. Options specified on the command line take precedence over the options in `dfyconfig.toml`.

*2. automatically looking for a project file*: Dafny automatically looks for a `dfyconfig.toml` for any `dafny <command>` like `dafny server` does, if I understand correctly. Otherwise this works like the first way.

### Alternatives

Currently the only workaround is running `dafny <command> dfyconfig.toml` but that runs `dafny <command>` on all files listed in `dfyconfig.toml`, which can be a lot slower than running it on an individual file. For `dafny run` there is currently no way at all because `dafny run` does not support project files (see #4622).

**Comment by keyboardDrummer** [comment]
> It would be very useful if I could run a dafny <command> on an individual file

I don't think this is what you want. What I think you want is the ability to specify which method in a project to run when using `dafny run`.

I suggest adding an option specifically for that, which you can then use in this way: `dafny run projectfile.toml --main=<qualified.path.to.method>`

For `dafny verify`, there is already an option to verify only a single method, called `--boogie-filter`, although it's not super mature.

For `dafny translate` and `dafny build`, I do not yet see a use-case for doing something method or file specific.

---

> automatically looking for a project file: Dafny automatically looks for a dfyconfig.toml for any dafny <command> like dafny server does, if I understand correctly. Otherwise this works like the first way.

I think it's best if users that use a project file no longer have to reference any `.dfy` files, but instead can think in terms of semantic objects such as modules and methods.

**Comment by keyboardDrummer** [comment]
The option `--main` is really easy to add since the back-end code is already there.

You just have to add:
```c#
  public static readonly Option<string> MainOverride =
    new("--main-method", "Override the method used to start the program, using a fully qualified method name.");

  static CommonOptionBag() {
    DafnyOptions.RegisterLegacyBinding(MainOverride, (options, value) => {
      options.MainMethod = value;
    });
  }
```

and reference `MainOverride` in the `Options` list in `RunCommand`.

**Comment by fzaiser** [comment]
Thanks for the quick response! Your two PRs (#4628 and #4629) look like they'd be very helpful to us.

The reason I asked for this feature for build and translate is that it was quite a bit faster in our CI before we moved to project files. But now the running time has changed again, so I'm not sure anymore if that's actually the case.

Regarding verification, thanks for making me aware of `--boogie-filter`, but I'm not sure it's as good an alternative as simply verifying a single file. For one thing, it is not really documented in the reference: `restricts the set of verification tasks (for debugging)` is not enough information. How does it filter? By exact match? Partial match? Regular expressions? It's also less convenient. When proving something, I'm usually working on one module/file, so it is natural that I only want to verify that file because I did not touch anything else. It is annoying to have to wait for other files to verify first. I guess this would be less of a problem with caching/incremental verification.

**Comment by keyboardDrummer** [comment]
For filtering verification, I suggest we enable you to filter by regex which needs to match with a substring of the fully qualified name of the method, so you could filter by module.

In the future I'd like files to declare implicit modules, so then you could filter on the filename to get the same affect as filtering on the file. Without implicit modules you'll have to start your file with a module declaration.

**Comment by fzaiser** [comment]
That sounds reasonable. In situations where a project file is used, people hopefully use modules already.

May I suggest simply calling this option `--filter` instead of `--boogie-filter`? The average Dafny programmer should not have to know about boogie to specify what should be verified.

**Comment by keyboardDrummer** [comment]
> May I suggest simply calling this option --filter instead of --boogie-filter? The average Dafny programmer should not have to know about boogie to specify what should be verified.

I agree. The current option is called `--boogie-filter` because it filters on the Boogie names of things (similar to the Dafny names but with some added things), because making that was cheap. Once we add a version that filters on the Dafny names we should call it `--filter` and hide `--boogie-filter` from help.

**Comment by fzaiser** [comment]
Thanks, @keyboardDrummer! Since your PR says "Partially fixes", this issue shouldn't be closed yet, right?

**Comment by keyboardDrummer** [comment]
> Thanks, @keyboardDrummer! Since your PR says "Partially fixes", this issue shouldn't be closed yet, right?

Feel free to reopen this one if you think there's more to address.
