### ISSUE TITLE
Type checker fails to determine type of a datatype constructor's argument

### ISSUE THREAD

**Issue by markrtuttle** [dafny-lang/dafny#4708]
### Dafny version

4.3.0

### Code to produce this issue

```dafny
module Example {
  datatype JSON =
    String(str: string) |
    Object(obj: seq<(string, JSON)>)

  method example(json: JSON)
    requires json.Object?
  {
    // Declaration 1: Type checker fails at expect with this declaration
    // Note: Hovering over pairs in VSCode shows type seq<(string,JSON)>
    var pairs := json.obj;

    // Declaration 2: Parser succeeds at expect with this declaration
    // var pairs: seq<(string, JSON)> := json.obj;

    expect |pairs| == 2;
    var (str0, json0) := pairs[0];
    var (str1, json1) := pairs[1];

    // Type checker says "type of the receiver is not fully determined at this program point"
    expect json0.String?;
  }
}
```

### Command to run and resulting output

```code
dafny resolve example.dfy
```

### What happened?

The dafny type checker fails at the line 
```
expect json0.String?;
```
and points to `String?` with the error "type of the receiver is not fully determined at this program point".  If I comment the first declaration of `pairs` and uncomment the second declaration that gives the type explicitly, the type checker succeeds.

Alternatively, if I replace the use of `pairs` with the use of `json.obj`, the type checker succeeds.

I think there is something about the indirection introduced by the variable `pairs` that is causing the type checker to fail.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by fabiomadge** [comment]
Thanks for reporting!

This behaviour is indeed strange. Here's my minimally invasive workaround:
```Dafny
var (str0, json0: JSON) := pairs[0];
```

Fortunately the new type inference, available under `/typeSystemRefresh:1`, gets this right, so it probably not worth investing time into a a fix.

**Comment by keyboardDrummer** [comment]
Closing because this is resolved with the new type system.
