### ISSUE TITLE
Dafny reports a warning on an `assert` statement, saying it is an unnecessary assumption

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/dafny#4719]
Dafny reports a warning on an `assert` statement, saying it is an unnecessary assumption.

It's confusing that Dafny calls an assert statement an assumption, especially Dafny also has assume statements. I suggest changing the text to "unnecessary assertion".

Alternatively Dafny could be more verbose and say that this assert statement was not required to prove other assert statements or ensures clauses.

**Comment by atomb** [comment]
To fix this, we'd need a special case here to identify assumptions that come from `assert` statements.

https://github.com/dafny-lang/dafny/blob/master/Source/DafnyCore/ProofDependencyWarnings.cs#L61-L65
