### ISSUE TITLE
Dafny reports an "unnecessary" warning on an expression, while only part of the expression is unnecessary

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/dafny#4720]
Given the code:

```dafny
const partialOrdering := (a: int, b: int) => !(a == 9 && b == 10) && a <= b
method {:test} TestRelationProperties() 
  ensures !StronglyConnected(partialOrdering)
{
  assert !partialOrdering(9,10) && !partialOrdering(10,9);
}

ghost predicate StronglyConnected<T(!new)>(R: (T, T) -> bool) {
  forall x, y :: R(x, y) || R(y, x)
}
```

`dafny verify` reports:

```
  |
5 |   assert !partialOrdering(9,10) && !partialOrdering(10,9);
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

DafnyExamples/warnAssumptions/falsePositiveUnnecessaryAssumption.dfy(5,9): Warning: unnecessary assumption
```

While actually only the second part of the expression `!partialOrdering(10,9)`, is unused.

**Comment by atomb** [comment]
The reason for this is that the Dafny -> Boogie translation breaks up Dafny `assert` statements into multiple Boogie `assert` statements. This happens in several places, such as here: https://github.com/dafny-lang/dafny/blob/master/Source/DafnyCore/Verifier/BoogieGenerator.TrStatement.cs#L552-L567

It generates multiple Boogie statements, each of which could be included or not included in a successful proof. However, Boogie statements don't have range tokens, so the error messages use the range token from the original Dafny statement. Extending `TrSplitExpr` to keep track of the range token of each of its list of results would allow us to give a better message here.

FWIW, there are also some other instances in the translation where a range token isn't readily available, so the translation constructs a new one, of span 0, based on just the line and column of a normal token (used as both the start and end position). I'd be inclined to use this issue to track fixing those, too.

**Comment by keyboardDrummer** [comment]
> However, Boogie statements don't have range tokens

I'm not sure I agree with that. When `flags.ReportRanges` is true, the `IToken`s that we pass to Boogie are all of type `BoogieRangeToken`, and those are later used to extract ranges. I think the trick is to use the right Dafny nodes when generating tokens (using `IToken GetToken(INode node)`) for the Boogie nodes.

**Comment by atomb** [comment]
> > However, Boogie statements don't have range tokens
> 
> I'm not sure I agree with that. When `flags.ReportRanges` is true, the `IToken`s that we pass to Boogie are all of type `BoogieRangeToken`, and those are later used to extract ranges. I think the trick is to use the right Dafny nodes when generating tokens (using `IToken GetToken(INode node)`) for the Boogie nodes.

Aha, so this might be easier than I thought!

**Comment by atomb** [comment]
I've made some progress on refining how these ranges are reported, but it turns out that it doesn't resolve this particular instances. In this case, neither side of the assertion itself is actually necessary. It's only necessary to have something like either `partialOrdering(9,10)` or `partialOrdering(10, 9)` somewhere in the goal for triggers to fire. For example, this version verifies for me:

```
const partialOrdering := (a: int, b: int) => !(a == 9 && b == 10) && a <= b
method {:test} TestRelationProperties().
  ensures !StronglyConnected(partialOrdering)
{
  var a := partialOrdering(9,10);
  var b := partialOrdering(10, 9);
  //assert !partialOrdering(9,10) && !partialOrdering(10,9);
}

ghost predicate StronglyConnected<T(!new)>(R: (T, T) -> bool) {
  forall x, y :: R(x, y) || R(y, x)
}
```

**Comment by atomb** [comment]
The improved range reporting is merged, so I'm going to close this. The interaction between triggers and redundant assumptions is something that we should think more about, however.
