### ISSUE TITLE
Inconsistent printing of strings inside datatypes in Rust backend

### ISSUE THREAD

**Issue by shadaj** [dafny-lang/dafny#4742]
In `git-issue-364.dfy`, the Rust backend prints the string contents directly inside of the datatype:

```
NatOutcome.Failure(it could be worse) true NatOutcome.Failure(it could be worse)
```

rather than wrapping it with quotes:

```
NatOutcome.Failure("it could be worse") true NatOutcome.Failure("it could be worse")
```

Fixing this will require some changes to `DafnyPrint` to track a top-level versus inner stringification.

**Comment by keyboardDrummer** [comment]
Closing since this issue has been resolved.
