### ISSUE TITLE
Rethink "DafnyStdLibs" module name for standard libraries

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#4785]
We're not totally happy with this name and don't want to release without improving it. :)

I'd also like to do one last holistic pass over all the libraries to check for consistency, especially if there are any other names we're like to take the opportunity to tweak.

Edit by Mikael:

Here is a table of "vote", you can put your name and 0-2 below each proposition so far, with 2 being in favor, and 0 be a dislike

| Comments \ Proposition |  First Letter Capital | first letter lowercase | Dfy | Std | D | Predefined | DafnyStdLibs
| -------------------------- | -- | -- | -- | -- | -- | -- | -- |
| Mikael | 2 | 1 | 2 | 2 | 1 | 1 | 0 |
| Robin (inferred by Mikael) | 2 | 1 | 1 | 2 | 0 | 0 | 1 |
| Alex | 2 | 1 | 0 | 2 | 0 | 0 | 0 |
| Aaron | 2 | 0 | 1 | 2 | 0 | 1 | 0 |
| Siva | 2 | 0 | 1 | 1 | 0 | 0 | 0 |
| Fabian | 2 | 1 | 0 | 2 | 0 | 0 | 0 |
| John | 2 | 1 | 1 | 1 | 0 | 0 | 1 |
| Stefan | 2 | 0 | 1 | 2 | 0 | 0 | 1 |

**Comment by MikaelMayer** [comment]
* Dfy
* dfy
* Std
* std
* D
* d

**Comment by robin-aws** [comment]
> D

https://dlang.org/ would like a word :D

**Comment by keyboardDrummer** [comment]
I think having `Dafny` in the name does not add meaning, since this name only occurs in a Dafny context.

**Comment by robin-aws** [comment]
> I think having Dafny in the name does not add meaning, since this name only occurs in a Dafny context.

+1

> Maybe Predefined. ?

Don't love that because it makes them sound baked-in and not optional. So far I like `Std` a little better because it feels like "usually already there" but not necessarily always.

**Comment by robin-aws** [comment]
Another naming pattern I'm questioning is the plurality of all the `Collections` modules: if you're not `import open`ing them, `Seqs.Map` doesn't read as well as `Seq.Map` to me (and plus that one in particular was `Seq` in the `dafny-lang/libraries` copy so we're asking for extra code edits to migrate to `Seqs`).

**Comment by MikaelMayer** [comment]
I second your opinion on keeping most module names or namespaces singular. By definition  they contain methods that will apply to many inputs of a given type. In Scala, modules are just the "companion object" of a given class and share the same visible name, no 's' added.

**Comment by MikaelMayer** [comment]
I'm adding a table of votes to the head of this thread so that everyone so we can record everyone's opinion. I inferred yours @robin-aws , feel free to edit.

**Comment by fzaiser** [comment]
Can't edit the first post, but I'd like the name to be concise and easy to type. Many languages use `std` and it works well, so I'd be in favor of that. My full preferences are: first capital: 2, first lower: 1, Dfy: 0, Std: 2, D: 0, Predefined: 0, DafnyStdLibs: 0

**Comment by ssomayyajula** [comment]
Namespace `Dafny` could work too.

**Comment by alex-chew** [comment]
Unfortunately we can't easily use the namespace `Dafny` because it would risk naming conflicts with parts of the Dafny runtime and some compiled Dafny code.

**Comment by jtristan** [comment]
Stdlib

**Comment by stefan-aws** [comment]
I'm fine with either the existing `DafnyStdLibs.*`, `Std.*` or `Stdlib.*`.
