### ISSUE TITLE
Incorrect Cyclic Datatype Dependency Error

### ISSUE THREAD

**Issue by whonore** [dafny-lang/dafny#4793]
### Dafny version

4.3.0

### Code to produce this issue

```dafny
datatype A = A(b: (B, B))
datatype B = B
```

### Command to run and resulting output

```code
$ dafny verify test.dfy

  |
1 | datatype A = A(b: (B, B))
  |          ^

test.dfy(1,9): Error: because of cyclic dependencies among constructor argument types, no instances of datatype 'A' can be constructed
```

### What happened?

This should succeed since there aren't actually any cyclic dependencies. The error goes away if `B` is declared before `A` or if `A` is instead just `A(b: B)`.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by keyboardDrummer** [comment]
Closing because this has been resolved in Dafny 4.6 (and possibly earlier versions)
