### ISSUE TITLE
Go to Definition in IDE on standard library references produces error

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#4797]
Love that resolution/verification works after #4770! I got greedy and tried to Go to Definition on `DafnyStdLibs.Wrappers` and got "The editor could not be opened due to an unexpected error: Unable to resolve resource dllresource://dafnypipeline/DafnyStandardLibraries.doo"

The simplest fix is probably just to block opening `.doo` files in general and fail cleanly for now. I'd love to be able to browse the source code from the libraries eventually, but `.doo` files currently don't include any documentation/comments so we probably shouldn't enable it just yet.

**Comment by keyboardDrummer** [comment]
It's not just go to def that doesn't work properly, it's also diagnostics that link to .doo files that can't be opened. For example, if you do not satisfy a requires clause that's inside a .doo file, the diagnostics will give you a broken link to it.

**Comment by keyboardDrummer** [comment]
Seems like the VSCode extension should register a textDocumentContentProvider:

https://code.visualstudio.com/api/references/vscode-api#TextDocumentContentProvider

> A text document content provider allows to add readonly documents to the editor, such as source from a dll or generated html from md.

> Content providers are [registered](https://code.visualstudio.com/api/references/vscode-api#workspace.registerTextDocumentContentProvider) for a [uri-scheme](https://code.visualstudio.com/api/references/vscode-api#Uri.scheme). When a uri with that scheme is to be [loaded](https://code.visualstudio.com/api/references/vscode-api#workspace.openTextDocument) the content provider is asked.

**Comment by keyboardDrummer** [comment]
Another little IDE leak:

<img width="715" alt="image" src="https://github.com/dafny-lang/dafny/assets/3121201/cfc6144c-4907-4fbf-8835-d87c625d834d">

**Comment by keyboardDrummer** [comment]
> The simplest fix is probably just to block opening .doo files in general and fail cleanly for now.

I'm not sure how to do that ! There's no single location where you can tell the Dafny server not to let any Uris that end in `.doo` be sent to the client. You would have to go through various APIs and filter out results based on Uris. 

From the client side, the best I have managed to get is:
<img width="677" alt="image" src="https://github.com/dafny-lang/dafny/assets/3121201/98c62fab-eab0-4f52-aa23-85a104cd8e60">

**Comment by jtristan** [comment]
@keyboardDrummer If I run dafny get-source, would I then be able to go to a definition and have proper diagnostics without broken links? If so, it is a +1 for me.

**Comment by keyboardDrummer** [comment]
> @keyboardDrummer If I run dafny get-source, would I then be able to go to a definition and have proper diagnostics without broken links? If so, it is a +1 for me.

You wouldn't need to run anything, `dafny get-source` would be called by the Dafny VSCode extension to load the contents of files for which it currently can not, and then yes nothing would be broken.

I would mark the `get-source` command as hidden since I'm not sure whether it's the right API.

**Comment by robin-aws** [comment]
As per offline conversation, my preference would be:

1. Make the change to have a cleaner error message when the IDE tries to open a .doo file as in the screen shot above, before releasing. That makes the experience a little nicer and hides the `dllresource://...` URIs that are intended to be internal.
2. Implement `dafny get-source` later on, after also making some improvements to ensuring the source stored in a doo file is more usable (e.g. there are known issues here I need to log, such as losing all newlines in expressions, making them harder to read and even flagged with formatter warnings, and not preserving any comments)

**Comment by robin-aws** [comment]
More work to do to actually support reading doo file source in the IDE, but the release blocker is addressed by https://github.com/dafny-lang/ide-vscode/pull/454
