### ISSUE TITLE
The Dafny reference Manual is two+ years old and needs refreshing

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#481]

**Comment by davidcok** [comment]
One source of updated information is  https://github.com/dafny-lang/dafny/releases

The source documents is the madoko source file its in GitHub at
https://github.com/dafny-lang/dafny/tree/master/Docs/DafnyRef/DafnyRef.mdk

**Comment by davidcok** [comment]
The manual has been substantially refreshed for the 3.0 release.

**Comment by robin-aws** [comment]
I think it's fair to close this specific issue now, but I cut https://github.com/dafny-lang/dafny/issues/1450 to track remaining TODOs as a fresher issue.
