### ISSUE TITLE
Spurious resolver error depending on declaration order

### ISSUE THREAD

**Issue by erniecohen** [dafny-lang/dafny#4819]
### Dafny version

4.3

### Code to produce this issue

```dafny
datatype A = A(b:B) 
type B = B_
datatype B_ = B
```

### What happened?

The code gets a resolver error "because of cyclic dependencies among constructor argument types, no instances of datatype 'A' can be constructed".
If the first declaration is moved to the end, this error goes away.
Resolution should not depend on declaration order.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by whonore** [comment]
This seems similar to #4793.

**Comment by keyboardDrummer** [comment]
This has been resolved in Dafny 4.6
