### ISSUE TITLE
Project files prevent formatting from happening correctly

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#4836]
### Dafny version

latest-nightly

### Code to produce this issue

```dafny
When opening a large project with a Dafny file, right clicking and selecting format produces unexpected random formatting issues.
```

### What happened?

I guess that there are shared variables that should not be shared between files, like the indentation per file. That might solve the issue.

### What type of operating system are you experiencing the problem on?

Other

**Comment by MikaelMayer** [comment]
Since I work on a project file now and want to format, I have the same issue now.

It all boils down to the following:

- In the command line, "dafny format" does not load the project file currently, only parses it, so that it can reformat it correctly.
- when there is a project file, "dafny format" has no longer a working method to determine if the token it's trying to format is part of the file or not, and it will try to apply the formatting of all the files on the current file.

So it's good that the methodology guarantees we print the same tokens. It's just that for some reason "format" is launched on all the files of the project at the same time while all the formatting happens on the current file, which triggers random formatting issues.

**Comment by keyboardDrummer** [comment]
Thanks for fixing https://github.com/dafny-lang/dafny/pull/4918 !!!
