### ISSUE TITLE
Update Maven's Java DafnyRuntime to 4.4.0

### ISSUE THREAD

**Issue by lucasmcdonald3** [dafny-lang/dafny#4883]
### Summary

The DafnyRuntime hosted on Maven only goes up to 4.2.0: https://search.maven.org/artifact/org.dafny/DafnyRuntime

Could 4.4.0 also be published?

This is blocking Smithy-Dafny from running `replaceable` modules testing in Java.

### Background and Motivation

Problem: I want to use 4.4.0's `replaceable` modules in Java. It seems that the generated Java code for 4.3.0+ references symbols like `dafny.Function2`, which are not in the 4.2.0 runtime.

### Proposed Feature

DafnyRuntime 4.4.0 is on Maven central: https://search.maven.org/artifact/org.dafny/DafnyRuntime

It might be nice to have 4.3.0 for completeness, but I don't need this.

**Comment by alex-chew** [comment]
Hi Lucas, thanks for the report. Version 4.4.0 is available on Maven Central now: https://central.sonatype.com/artifact/org.dafny/DafnyRuntime/4.4.0
