### ISSUE TITLE
Cannot do `dafny run target:py` on Windows

### ISSUE THREAD

**Issue by alexporter8013** [dafny-lang/dafny#4922]
### Dafny version

4.4.0+707b18acee078b3aa4d84c0590a980966bf22428

### Code to produce this issue

```dafny
method Main()
{
    print "hello, world!";
}
```

### Command to run and resulting output

```code
dafny run --target:py python_noworky.dfy
```

### What happened?

When VSCode runs the above, the following is printed to the console:
```
Error: Unable to start python3: An error occurred trying to start process 'python3' with working directory 'C:\Users\Username\source\playground\program_proofs'. The system cannot find the file specified.
```

I would expect to see the same output as when doing `dafny run python_noworky.dfy` which is `hello, world!`

It seems from this perspective that the current implementation depends on the system-wide implementation being accessible globally through the command `python3`, which is not typically true on Windows. Additionally, there does not seem to be a way to retarget which interpreter is used, which would seem prudent to me.

Suggestions:
- Allow command-line option to override the target interpreter.
- Allow environmental variable to override the target interpreter.
- Add `dfyconfig.toml` option for target interpreter.

### What type of operating system are you experiencing the problem on?

Windows

**Comment by fabiomadge** [comment]
Using `dafny translate` and running the generated sources manually seems like a decent workaround. Check out [this test](https://github.com/dafny-lang/dafny/blob/master/Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/manualcompile/ManualCompile.dfy) for a pointer.

**Comment by alexporter8013** [comment]
Agreed that this is a workaround. Aside from wanting to identify issues to allow for product improvement, I also wanted to give the fix a try for my own edification.
