### ISSUE TITLE
Documentation of `decreases` clause incomplete and error messages sometimes misleading

### ISSUE THREAD

**Issue by racko** [dafny-lang/dafny#4937]
### What change in documentation do you suggest?

Section [7.1.3. Decreases Clause](https://dafny.org/latest/DafnyRef/DafnyRef#sec-decreases-clause) of the documentation does not hint at the fact that the supplied expressions not only have to decrease but also reach some given lower bound when the loop condition becomes false or the recursion's base case is reached.

Example (https://en.wikipedia.org/wiki/Bisection_method):
```dfy
  function bisection(f: real->real, l: real, r: real, eps: real): (real, real)
    decreases r - l
    requires l < r
    requires f(l) < 0.0
    requires f(r) > 0.0
    requires eps > 0.0
  {
    if r - l < eps then
      (l, r)
    else
      var c := 0.5 * (l + r);
      if f(c) < 0.0 then
        assert r - c < r - l;
        bisection(f, c, r, eps)
      else if f(c) > 0.0 then
        assert c - l < r - l;
        bisection(f, l, c, eps)
      else
        (c, c)
  }
```
Here the verifier complains in both recursive calls that the decreases clause may not decrease - even though the assertions proving the decrease (in the literal sense of the word, not in the sense that Dafny uses) verify[^1]. For a while I thought that dafny didn't *actually* allow reals in decreases clauses until I found that a `real` fibonacci function verifies:

```dfy
  function Fib(n: real) : real
  {
    if n < 2.0 then n else Fib(n-2.0) + Fib(n-1.0)
  }
```

Now I am left to wonder what exactly I'd have to prove to get `bisection` to verify. I realize that the `real` case is especially tricky because of Zeno's paradox. But that's not the point of this issue. Rather it is the fact that neither the documentation, nor the error message hint at the exact proof obligation.
[^1]: I was able to verify the `bisection` function by computing the number of remaining iterations and proving that it decreases.

**Comment by racko** [comment]
I just got worried that maybe Dafny just doesn't print the assertion failures as long as it can't prove termination. I remembered that `--log-format text` might tell me whether they verified. It doesn't, really, but it does actually show `decreases expression is bounded below by 0.0` and `loop or recursion terminates` proof obligations. Still not quite what I'm looking for, though :confused: 
```
dafny verify --log-format text decreases_real.dfy
decreases_real.dfy(21,8): Error: decreases clause might not decrease
   |
21 |         bisection(f, c, r, eps)
   |         ^^^^^^^^^

decreases_real.dfy(24,8): Error: decreases clause might not decrease
   |
24 |         bisection(f, l, c, eps)
   |         ^^^^^^^^^


Dafny program verifier finished with 0 verified, 2 errors

Results for decreases_real.bisection (well-formedness)
  Overall outcome: Errors
  Overall time: 00:00:00.2628146
  Overall resource count: 31196
  Maximum assertion batch time: 00:00:00.1223021
  Maximum assertion batch resource count: 31196

  Assertion batch 0:
    Outcome: Invalid
    Duration: 00:00:00.1223021
    Resource count: 31196

    Assertions:
      decreases_real.dfy(23,22): assertion always holds
      decreases_real.dfy(24,9): function precondition satisfied
      decreases_real.dfy(24,9): function precondition satisfied
      decreases_real.dfy(24,9): function precondition satisfied
      decreases_real.dfy(24,9): function precondition satisfied
      decreases_real.dfy(24,9): decreases expression is bounded below by 0.0
      decreases_real.dfy(24,9): loop or recursion terminates
      decreases_real.dfy(20,22): assertion always holds
      decreases_real.dfy(21,9): function precondition satisfied
      decreases_real.dfy(21,9): function precondition satisfied
      decreases_real.dfy(21,9): function precondition satisfied
      decreases_real.dfy(21,9): function precondition satisfied
      decreases_real.dfy(21,9): decreases expression is bounded below by 0.0
      decreases_real.dfy(21,9): loop or recursion terminates
```

**Comment by keyboardDrummer** [comment]
I agree with your assessment that the current documentation and error reporting is unsatisfactory for the example program you gave.

I'm no expert when it comes to Dafny decreases clauses, but I looked at the generated Boogie code using the option `--bprint=<filename>`, and there we can see that the decreases clause check comes down to `assert decreasesCallee < decreasesCaller - 1`, so `assert r - c < r - l - 1` in one of your cases.

These seems like a bit of a hack to me that doesn't work well in all cases. @RustanLeino can you comment on the reasoning behind this behavior? I believe it would be better to refactor your program to one where the decreasing expression can be expressed without reals, to get more reliable behavior.

The following adaption of your program does pass the decreases clause checker:
```
function bisection(f: real->real, l: real, r: real, eps: real): (real, real)
  decreases r - l
  requires l < r
  requires f(l) < 0.0
  requires f(r) > 0.0
  requires eps > 0.0
{
  if r - l < eps then
    (l, r)
  else
    var c := 0.5 * (l + r);
    if f(c) < 0.0 then
      assume r - c < r - l - 1.0;
      bisection(f, c, r, eps)
    else if f(c) > 0.0 then
      assume c - l < r - l - 1.0;
      bisection(f, l, c, eps)
    else
      (c, c)
}
```

**Comment by racko** [comment]
>I'm no expert when it comes to Dafny decreases clauses, but I looked at the generated Boogie code using the option `--bprint=<filename>`, and there we can see that the decreases clause check comes down to assert `decreasesCallee < decreasesCaller - 1`, so `assert r - c < r - l - 1` in one of your cases.

Thank you for pointing out `--bprint` :slightly_smiling_face: 
Actually the check is `assert {:id "id22"} ##r#1 - ##l#1 <= r#0 - l#0 - 1e0;` (note `<=`), so it's rather `assert r - c <= r - l - 1` which surprises me less than `assume r - c < r - l - 1.0;` :sweat_smile:

>@racko I believe it would be better to refactor your program to one where the decreasing expression can be expressed without reals, to get more reliable behavior.

That's what I later did, actually. I proved a decrease in `bisection_steps`:
```dfy
  function ilog2(v: nat): nat
  {
    if v > 1 then
      1 + ilog2(v / 2)
    else
      0
  }

  function bisection_steps(l: real, r: real, eps: real): nat
    requires l <= r
    requires eps > 0.0
  {
    ilog2((2.0 * ((r - l) / eps)).Floor)
  }
```

---
I was able to think some more about the root of my confusion.

In A Discipline of Programming, Chapter 6, On the Design of Properly Terminating Constructs, Dijkstra argues that given
```dfy
while BB
  decreases t
  invariant P
```
one not only needs to prove a decrease in `t` but also that `P && BB ==> t > 0` needs to be true for all iterations, which is equivalent to `P && t <= 0 ==> !BB`. Since the truth of `P` is maintained, these reduce to `BB ==> t > 0` and `t <= 0 ==> !BB`, stating that `t > 0` during iteration and `t <= 0` having to coincide with termination.
This is why I claimed in this issue that "the supplied expressions not only have to decrease but also reach some given lower bound when the loop condition becomes false or the recursion's base case is reached".
But I cannot find this proof obligation in other references of the [weakest precondition calculus](https://en.wikipedia.org/wiki/Predicate_transformer_semantics#Total_Correctness) or the [Hoare calculus](https://en.wikipedia.org/wiki/Hoare_logic#While_rule_for_total_correctness) so I assume that proving the decrease is sufficient.
When I read the book I wondered about the significance of this proof obligation and thought it to be important because: If the decreased function is a function on the natural numbers and reaches 0 before the loop condition becomes false, we cannot actually prove that it is decreased in each iteration. But simply proving that it is decreased by the loop body would not show this issue.
I now realize that in Dafny this proof obligation bubbles up in other places:
```dfy
method foo()
{
  var i: nat := 10;
  while i > 0
    decreases (i - 10) as nat
  {
    i := i - 1;
  }
}
```
Here the verifier correctly complains that `i - 10` may not be a `nat`.

And the other variant, a decreases clause that would reach 0 *after* the loop condition becomes false is harmless: Since the loop condition becomes false in this  scenario, the loop terminates, which is the only thing we care about in this context.

So this part of the point that I was trying to make is moot.

What's left is the part where the well-founded order for `real`s surprised me (and gave me false confidence that there was some other, hidden proof obligation) and may surprise others, since the following is the closest thing that I could find in the documentation about it:
>What does “strictly smaller” mean? Dafny provides a built-in well-founded order for every type and, in some cases, between types.

Even though the well-founded order surprises me, I understand that there may be no "better" one and that the current one can be useful in some use cases. But since it is not exactly "natural" for reals, I would still argue that the documentation could mention it.

**Comment by RustanLeino** [comment]
Thanks for the suggestion to improve the error message and documentation. I agree. At the very least, when section 7.1.3 mentions "well-founded order", it should reference section 12.7, which explains what the well-founded orders that Dafny users are. (Author plug: I think the best description of how to think of termination in Dafny is found in chapter 3 of my book _Program Proofs_.)

Here follow some other comments.

## A correction

> but also reach some given lower bound when the loop condition becomes false or the recursion's base case is reached.

This is common misconception, but it is _not_ true. There is never an obligation to reach any particular value of the termination metric. The only proof obligation is that, at the time of a recursive call (or mutually recursive call, or when taking the back-edge of a loop), the termination metric is strictly smaller (in some fixed well-founded order) than at the start of the enclosing function or method (or loop, if we're talking about loop termination). For example, if an expression `e` can be used as a termination metric, then so can `e + 100`.

## Well-founded orders for numbers

It _is_ true that there must be a lower bound in the well-founded order. This is part of what it means, mathematically, to be a well-founded order. Frequently, we use some numeric expression as the termination metric. Then, it is not enough to just use arithmetic less-than, because that would not be a well-founded order. Instead (which has been hinted at in the comments above), there needs to be some lower bound and some fixed step size. For that lower bound, Dafny uses `0` for integers and `0.0` for reals. For the step size, Dafny uses `1` for integers and `1.0` for reals. This makes the order well-founded. (As a detail, Dafny places the bound only on one of the two numbers, see the table in section 12.7. This is more permissive than placing it on both, and is still a well-founded order.)

If you wish for a smaller lower-bound, then simply add some offset in your `decreases` clause. For example, the following function adds an offset of `20`:

``` dafny
function F(x: int): int
  decreases x + 20
{
  if x < -4 then
    7
  else
    F(x - 92)
}
```

Note also that this termination metric (`x + 20`) is _not_ certain to reach `0` in the base case. (If fact, the expression `x + 20` may also be negative, but only if there will be no recursive call.)

Similarly, if you wish for a different step size for reals, just multiply your expression to scale it according to your needs.

## Back to the bisection example

The expression `r - l` in the `bisection` examples above does not decrease in Dafny's well-founded order. It is bounded below by `0.0`, but you need to scale it by `2.0 / eps`. Here's a verifying version that does that:

``` dafny
  function Bisection(f: real -> real, l: real, r: real, eps: real): (real, real)
    requires l < r && 0.0 < eps
    requires f(l) < 0.0 < f(r)
    decreases Metric(r - l, eps)
  {
    ghost var D := r - l;
    if r - l < eps then
      (l, r)
    else
      var c := 0.5 * (l + r);
      if f(c) < 0.0 then
        ShowDecrease(D, r - c, eps);
        Bisection(f, c, r, eps)
      else if f(c) > 0.0 then
        ShowDecrease(D, c - l, eps);
        Bisection(f, l, c, eps)
      else
        (c, c)
  }

  ghost function Metric(d: real, eps: real): real
    requires 0.0 < eps
  {
    2.0 * d / eps
  }

  lemma ShowDecrease(D: real, d: real, eps: real)
    requires 0.0 < eps <= D
    requires d == D / 2.0
    ensures 1.0 <= Metric(D, eps) - Metric(d, eps) && 0.0 <= Metric(D, eps)
  {
    calc {
      Metric(D, eps) - Metric(d, eps);
    ==  // by definition of Metric
      2.0 * D / eps - 2.0 * d / eps;
    ==
      ((2.0 * D) - (2.0 * d)) / eps;
    ==
      2.0 * (D - d) / eps;
    ==  { assert D - d == d; }
      2.0 * d / eps;
    ==  { assert 2.0 * d == D; }
      D / eps;
    }

    calc {
      1.0 <= Metric(D, eps) - Metric(d, eps);
    ==  // by the calculation above
      1.0 <= D / eps;
    ==  { assert 0.0 <= D && 0.0 < eps; }
      eps <= D;
    }
  }
```

It was not so easy to get this to verify, because Dafny's verifier is rather brittle for non-linear arithmetic. When writing my version of this code, I frequently found that small changes could cause some steps not to verify. This is unfortunate, but a known problem (and one we're trying to improve on).

**Comment by racko** [comment]
Thank you very much for the elaborate answer. I think that I understand termination better now.
>(Author plug: I think the best description of how to think of termination in Dafny is found in chapter 3 of my book Program Proofs.)

And now I see that the table from reference section 12.7 is in section 3.2 of the book. Damn, I could have known :see_no_evil:
>Similarly, if you wish for a different step size for reals, just multiply your expression to scale it according to your needs.

I wondered about that possibility when @keyboardDrummer pointed out the proof obligation to me but I didn't follow up on it. Seeing your version, I see now how it relates to my integer `bisection_steps` version :astonished: 

Thank you for the documentation update :slightly_smiling_face:
