### ISSUE TITLE
DafnyServer does not support project files

### ISSUE THREAD

**Issue by racko** [dafny-lang/dafny#4938]
### Dafny version

4.4.0+707b18acee078b3aa4d84c0590a980966bf22428

### Code to produce this issue

```dafny
// example.dfy
function method foo(): int
{
  0
}
```
```toml
[options]
function-syntax = 3
```
`dafnyserver_input.json`:
```json
{
  "args": [],
  "source": "example.dfy",
  "sourceIsFile": true,
  "filename": "example.dfy"
}
```

### Command to run and resulting output

```code
$ dafny verify dfyconfig.toml

Dafny program verifier finished with 0 verified, 0 errors
```
```
$ echo -e "verify\n$(base64 dafnyserver_input.json)" |  DafnyServer
example.dfy(1,0): Error: the phrase 'function method' is not allowed when using --function-syntax:4; to declare a compiled function, use just 'function' (ID: p_deprecating_function_method)

From Dafny 4 on, the phrases `function method` and `predicate method` are no
longer accepted. Use `function` for compiled, non-ghost functions and
`ghost function` for non-compiled, ghost functions, and similarly for predicates.
See [the documentation here](https://dafny.org/latest/DafnyRef/DafnyRef#sec-function-syntax).
Verification completed successfully!
[SUCCESS] [[DAFNY-SERVER: EOM]]
```

### What happened?

As can be seen above, `DafnyServer` doesn't respect settings in `dfyconfig.toml` - at least not in a way that I could find.

The [documentation](https://dafny.org/latest/DafnyRef/DafnyRef#sec-dafny-server) states:
>The Dafny Server is still supported, but we recommend using the [Language Server](https://github.com/dafny-lang/dafny/tree/master/Source/DafnyLanguageServer) instead.

So is this considered a bug in `DafnyServer` or should the documentation mention that some things aren't supported?

### What type of operating system are you experiencing the problem on?

Linux

**Comment by keyboardDrummer** [comment]
Dafny server is feature frozen, and it does not support features that were recently added to Dafny, such as project files.

Made a PR to update the documentation: https://github.com/dafny-lang/dafny/pull/4945
