### ISSUE TITLE
Standard Library fails to build to target:lib (doo)

### ISSUE THREAD

**Issue by ShubhamChaturvedi7** [dafny-lang/dafny#4964]
### Dafny version

4.4

### Code to produce this issue

```dafny
Line 25, UTF8.dfy in Standard Library

function method {:extern "Encode"} Encode(s: string): (res: Result<ValidUTF8Bytes, string>)
   // US-ASCII only needs a single UTF-8 byte per character
   ensures IsASCIIString(s) ==> res.Success? && |res.value| == |s|
   // The following MUST be true for any correct implementation of Encode
   // If it weren't, then data would be lost.
   ensures res.Success? ==> Decode(res.value).Success? && Decode(res.value).value == s
```

### Command to run and resulting output

```code
Command:

build
--target:lib
--function-syntax:3
--quantifier-syntax:3

Output:

Error: Function with [{:extern}] attribute.
   |
25 |   function method {:extern "Encode"} Encode(s: string): (res: Result<ValidUTF8Bytes, string>)
   |                                      ^^^^^^
```

### What happened?

Got the below error. Same code builds with `target:go`.
```
Error: Function with [{:extern}] attribute.
   |
25 |   function method {:extern "Encode"} Encode(s: string): (res: Result<ValidUTF8Bytes, string>)
   |                                      ^^^^^^
```

### What type of operating system are you experiencing the problem on?

Mac

**Comment by keyboardDrummer** [comment]
I'm changing the checks that are done when building a doo file, which should resolve this problem. 

Step 1: track whether a doo file was built with warnings: https://github.com/dafny-lang/dafny/pull/4971
Step 2: add additional warnings related to axioms in verification: https://github.com/dafny-lang/dafny/pull/3553
Step 3: stop looking at the auditor results when building doo files, and add options for warning on particular constructs such as functions with {:extern}
