### ISSUE TITLE
Support `is` for subtyping

### ISSUE THREAD

**Issue by txiang61** [dafny-lang/dafny#4978]
### Dafny version

4.4.0

### Code to produce this issue

```dafny
trait M<A> {}

type TM extends M<string> {}

type C = m: M<string> | m is TM witness *

function toFoo(x: C): TM {
  x as TM
}

predicate foo(x: C) {
  x is TM
}
```

### Command to run and resulting output

```code
dafny verify --general-traits=Datatype --type-system-refresh

Error: a type test to 'TM' must be from a compatible type (got 'C').
```

### What happened?

`as` is allowed but `is` gives a type incompatible error.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by keyboardDrummer** [comment]
This was resolved with https://github.com/dafny-lang/dafny/pull/5061
