### ISSUE TITLE
Doc: Dafny Tutorial missing 404 (but still referenced)

### ISSUE THREAD

**Issue by turbotimon** [dafny-lang/dafny#4980]
### What change in documentation do you suggest?

The Dafny tutorial went missing (404): https://dafny.org/dafny/OnlineTutorial/guide (even in older [snapshots](https://dafny.org/Snapshots))

However, it is still referenced on e.g. on https://dafny.org/dafny/DafnyRef/DafnyRef (as well as others)
> ... on your machine as you follow along with the [Dafny tutorial](https://dafny.org/dafny/OnlineTutorial/guide).

**Comment by turbotimon** [comment]
Btw: There is no link on the website to https://dafny.org/dafny/Installation anymore (and the page is not rendered properly, looks like css is missing)

**Comment by fabiomadge** [comment]
Thanks for letting us know! We recently updated the Jekyll version we use, but didn't notice that our sources aren't compatible with the newer version. The linked PR fixed the issues I found on the live version, but the released Dafny Version still experience the same issue.
