### ISSUE TITLE
Decreases clauses crashing in datatype traits

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#4982]
### Dafny version

4.4

### Code to produce this issue

```dafny
module Hello {
  trait Censored {
    ghost function Decrease(): int {
      0
    }

    ghost function NotCensored(): int
      decreases Decrease()
  }

  datatype Bar extends Censored =
    | Foo
  {
    opaque ghost function NotCensored(): int
      decreases 0
    {
      0
    }
  }
}
```

### Command to run and resulting output

```code
Use type-system-refresh and general-traits=datatype
```

### What happened?

Crashes in the IDE

### What type of operating system are you experiencing the problem on?

Windows

**Comment by ssomayyajula** [comment]
Running from the command line, do you get the same error as in #4969?

**Comment by MikaelMayer** [comment]
Yes, actually this is the same bug.

I nailed it down to two things that don't work out well.

The override check first, is translated like this:

```dafny
implementation {:smt_option "smt.arith.solver", "2"} {:verboseName "Hello.Bar.NotCensored (override check)"} OverrideCheck$$Hello.Bar.NotCensored(this: DatatypeType)
{
  var Bar_$_ReadsFrame: <beta>[ref,Field beta]bool;
    assert {:id "id2"} LitInt(0) <= Hello.Censored.Decrease(this)
       && (LitInt(0) == Hello.Censored.Decrease(this) ==> true);
    Bar_$_ReadsFrame := (lambda<alpha> $o: ref, $f: Field alpha :: 
      $o != null && read($Heap, $o, alloc): bool ==> false);
    assert {:id "id3"} (forall<alpha> $o: ref, $f: Field alpha :: false ==> false);
}
```
The first problem is that "this" is of type "DatatypeType" but Decrease accepts a Box (logically being a trait, so could accept both datatypes and references)

Changing the line `id2` to the following works for the type checker:

```boogie
assert {:id "id2"} LitInt(0) <= Hello.Censored.Decrease($Box(this))
   && (LitInt(0) == Hello.Censored.Decrease($Box(this)) ==> true);
```

However, this is not sufficient to prove the assertion despite the axiom for `Hello.Censored.Decrease` being very simple:

```boogie
axiom 0 <= $FunctionContextHeight
   ==> (forall this: Box :: 
    { Hello.Censored.Decrease(this) } 
    Hello.Censored.Decrease#canCall(this)
         || (0 < $FunctionContextHeight && $IsBox(this, Tclass.Hello.Censored()))
       ==> true);
```

The problem is that the context in which the override check is performed is defined by this procedure

```
procedure {:verboseName "Hello.Bar.NotCensored (override check)"} OverrideCheck$$Hello.Bar.NotCensored(this: DatatypeType
       where $Is(this, Tclass.Hello.Bar()) && $IsAlloc(this, Tclass.Hello.Bar(), $Heap));
  free requires 0 == $FunctionContextHeight;
  modifies $Heap;
```

Here, you see that $FunctionContextHeight is zero, which makes it not possible to obtain the axiom of `Hello.Censored.Decrease`
Changing this function context height to 1 solves the trick; however, I'm not sure if it's the thing to do as it might have other impact.

**Comment by RustanLeino** [comment]
To fix the crash, yes, `this` should be changed to `$Box(this)`.

For the other issue, we should not change the function context heights. Rather, I suggest looking into if you emit the assumption `Hello.Censored.Decrease#canCall(this)`. It may require some more thinking, but I think that's fine. (You might also ask @fabiomadge, who fixed some issues related to termination in overrides a year or more ago.)
