### ISSUE TITLE
Doo files not compatible with `--function-syntax:3`

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#4985]
### Dafny version

4.4

### Code to produce this issue

```dafny
predicate Foo() {
  true
}
```

### Command to run and resulting output

```code
> dafny build -t:lib src/Scratch.dfy --function-syntax:3

Dafny program verifier finished with 0 verified, 0 errors
> dafny resolve src/Scratch.doo --function-syntax:3 
src/Scratch.doo(5,0): Error: a predicate cannot be declared 'ghost' (it is 'ghost' by default when using --function-syntax:3)
  |
5 | ghost predicate Foo()
  | ^^^^^

1 parse errors detected in Scratch.doo
```

### What happened?

Two things happened leading to the error:

1. When the program was serialized into the doo file, it used the default `--function-syntax:4` mode.
2. When trying to parse the doo file, the passed in `--function-syntax:3` mode was used instead.

1 is arguably okay if perhaps a bit surprising. The real issue is using the local mode when parsing the doo file, since that might not match however it was created.

Caused by https://github.com/dafny-lang/dafny/pull/4854, but that change made sense for flags like `--read-clauses-on-methods`. The simplest fix may be to record flags like `--function-syntax` and `--quantifier-syntax` in the doo file as well even though they don't affect verification.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by keyboardDrummer** [comment]
> The simplest fix may be to record flags like --function-syntax and --quantifier-syntax in the doo file as well even though they don't affect verification.

I like that. I think we're missing an way of specifying that an option is module level, and these need to be recorded for the library so it can be parsed/resolved with all its module level options.
