### ISSUE TITLE
Confusion in suggested rewriting for failing assert cases

### ISSUE THREAD

**Issue by racko** [dafny-lang/dafny#4986]
The second to last [rewrite](https://dafny.org/latest/DafnyRef/DafnyRef#sec-failing-asserts-special-cases) suggests the following, in which `T` is both a type (`j: T`) and a valid Right-hand-side expression (`var x := T;`):
```dfy
method m_mod(i) returns (j: T)
   requires A(i)
   modifies this, i
   ensures B(i, j)
{
   ...
}

method n_mod() {
   ...
   assert A(k);
   modify this, i; // Temporarily
   var x := T; // Temporarily
   assume B(k, x);
  // var x := m_mod(k);
   assert P(x);
```
Is this an error or am I misinterpreting the suggestion?

**Comment by MikaelMayer** [comment]
good find, thanks for reporting!
