### ISSUE TITLE
Can't rebuild standard library files on Windows

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#4989]
Follow up from https://github.com/dafny-lang/dafny/pull/4824

The `check-binary` Make targets work by rebuilding the doo files, then comparing them to the checked in copies. They do this by unzipping and comparing the contents. Because the currently committed doo files are generally built on Macs, this means if a developer makes changes and rebuilds them on a Windows machine, the comparison fails because of the difference in line endings.

I propose fixing this by standardizing line endings inside doo files. This does imply altering program content when serializing to doo files, but this is already happening (merging multiple original source files into one, not yet maintaining comments or formatting of expressions in general) and needs to be allowed in general in order to optimize doo files in the future.

**Comment by MikaelMayer** [comment]
Yeah I agree. Before parsing the source files that will eventually generate the doo files, we should convert line endings to be "\n" in any case so that it will solve the problem on Windows.
