### ISSUE TITLE
help output needs to be generalized for other compilers

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#499]
The help output makes many references to C# output. Presumably most if not all of these should
refer to the output of the selected compiler. 

For example, under /compile

                2 - always attempt to compile Dafny program to C# program
                    out.cs, regardless of verification outcome
 and under /spillTargetCode

                2 - write the compiled Dafny program as a .cs file, provided
                    it passes the verifier, regardless of /compile setting

**Comment by RustanLeino** [comment]
Yes, it would be good to rewrite these.

**Comment by davidcok** [comment]
Text edited. PR #654.
