### ISSUE TITLE
Verification Optimization Guide 404

### ISSUE THREAD

**Issue by racko** [dafny-lang/dafny#5010]
### What change in documentation do you suggest?

https://dafny.org/latest/DafnyRef/DafnyRef#sec-verification-debugging-slow references https://dafny.org/latest/VerificationOptimization/VerificationOptimization, which is not found:
![dafny org_latest_VerificationOptimization_VerificationOptimization](https://github.com/dafny-lang/dafny/assets/1660674/84016a7f-14d9-458c-a396-5e968d98f96a)

**Comment by fabiomadge** [comment]
Thanks! I was hoping that #4981 had straightened everything out, but I sure hope this is the last try.
