### ISSUE TITLE
Definite-assignment checks too lenient

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#5023]
### Dafny version

4.4.0

### Code to produce this issue

```dafny
type Five = x: int | x == 5 ghost witness 5

class ContainsFive {
  var five: Five

  constructor () {
    five := *;
  }
}

method Main() {
  var five: Five := *;
  print five, "\n";

  var c := new ContainsFive();
  print c.five, "\n";
}
```

### Command to run and resulting output

```code
% dafny run test.dfy

Dafny program verifier finished with 3 verified, 0 errors
0
0
```

### What happened?

The subset type `Five` is declared with a `ghost witness`. For ghost variables and ghost fields of such type, a simple `:= *` assignment suffices to make them usable (that is, `:= *` is enough to satisfy the definite-assignment rules). Alas, the verifier also considers `:= *` to be enough if the variable or field being assigned is non-ghost. This leads to unsoundness, as shown in the example.

In the example above, I printed the incorrect values. An additional statement

``` dafny
var x :=
  var f: Five := five; 
  assert f == 5;
  if f == 5 then 200 else 200/0; // crash: division by 0
```

shows that the generated code also crashes. However, the soundness issue lies with the verifier, not the compilers (apparently, there's no github label that describes this, or maybe I don't know how to interpret the label descriptions).

### What type of operating system are you experiencing the problem on?

Mac

**Comment by keyboardDrummer** [comment]
Can you elaborate on the meaning of `x := *` ? If the meaning is, assign any value that satisfies this type, then wouldn't the above be a code generator bug, where the code generator should have either said "no non-ghost witness found for subset type" or generated `x := 5` ?

**Comment by RustanLeino** [comment]
Correct, the meaning of `x := *;` is "assign to `x` any value of the type of `x`". And indeed, for the code example above, Dafny _should_ report "you're asking the compiler to assign to `x` an arbitrary value of type `Five`, but `Five` is not an auto-init type (it is only a nonempty type), so the compiler does not know how to generate code for such an assignment". The Dafny bug is that this error was not reported (so the program made it to the compilation phase, and somehow this caused the compiler to generate a "placebo value" for `x`--such values are used by the compiler when the target language requires _some_ assignment but it is known, in the Dafny program due to the definite-assignment rules in Dafny, that the placebo value will never be used; of course, this assumes that programs like the one above don't pass the verifier).
