### ISSUE TITLE
Assertion violation after bitvector cast

### ISSUE THREAD

**Issue by superymk** [dafny-lang/dafny#505]
I get verification timeout on the code snippet:

var a:int := 0x0000_0010_DEAD_BEEF;
var testbv:bv64 := a as bv64;
var testval:int := testbv as int;

assert testval == a;   // "Timed out on: assertion violation"

the command I use is Dafny.exe /trace /errorTrace:0 /timeLimit:10 /ironDafny /allocated:1 /induction:1 /arith:10 /compile:0 test1.dfy
The dafny version I use is the commits on 10/24/2019, cc0b23c. I fail to compile the latest Dafny source code on windows with VS 2019, as I see DafnyPipeline uses Mono.Cesil and not sure if I need to install Mono alongside with .Net Core.

**Comment by robin-aws** [comment]
Hi @superymk! For the compiling issue, note that a recent change (#464) introduced the dependency on Mono.Cecil, but also added a step to the build instructions for running `nuget` on the Dafny solution, which will take care of downloading the package and any future dependencies:

```
nuget restore Source/Dafny.sln
```

There are a few other methods for restoring packages depending on your toolset: https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore

Mono.Cecil is a completely independent library from Mono, it just happened to be developed as part of Mono initially.

**Comment by superymk** [comment]
Thanks! After running the nuget command, building Dafny.sln in VS2019 has the error "Your project does not reference ".NETFramework,Version=v4.5" framework. Add a reference to ".NETFramework,Version=v4.5" in the "TargetFrameworks" property of your project file and then re-run NuGet restore.	DafnyRuntime"

The source code I use is git commit d164508

**Comment by superymk** [comment]
Hi, I compiled Dafny 650a6bbebdf5b696a0a0b2cdc7d77b0c502b7be5 using VS2019, and has the same issue.

In test1.dfy:
lemma b()
{
    var a:int := 0x0000_0010_DEAD_BEEF;
    var testbv:bv64 := a as bv64;
    var testval:int := testbv as int;

    assert testval == a; // "Timed out on: assertion violation"
}

Output:
E:/utils/dafny-latest/Dafny.exe /trace /errorTrace:0 /timeLimit:100 /allocated:1 /induction:1 /arith:10 /compile:0 test1.dfy
[TRACE] Using prover: E:\utils\dafny-latest\z3.exe
Dafny 2.3.0.10506
Parsing test1.dfy
Coalescing blocks...
Inlining...

Running abstract interpretation...
  [0.0369013 s]
[TRACE] Using prover: E:\utils\dafny-latest\z3.exe

Verifying Impl$$_module.__default.b ...
  [100.282 s, 2 proof obligations]  timed out
test1.dfy(1,6): Verification of 'Impl$$_module.__default.b' timed out after 100 seconds
test1.dfy(7,19): Timed out on: assertion violation

Dafny program verifier finished with 0 verified, 0 errors, 1 time out
make: *** [test1.dfy.test.arith] Error 4

**Comment by davidcok** [comment]
Results correctly produced. Tests added for shorter bit vectors. Closing with Pr #672.
