### ISSUE TITLE
Formatting issues in VsCode when using --standard-libraries

### ISSUE THREAD

**Issue by franck44** [dafny-lang/dafny#5082]
### Dafny version

4.4.0.0

### Code to produce this issue

```dafny
this is a vscode issue.
```

### Command to run and resulting output

```code
"format document" in VsCode
```

### What happened?

- enable usage of standard libraries with a dfyconfig.toml file
- when formatting a file in VsCode the formatting goes crazy and changes if you format several times in a row.

When disabling the dfyconfig.toml file the formatting issue disappears and code is formatted properly.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by stefan-aws** [comment]
Thanks for reporting this. I was able to reproduce the issue on one of my own projects. Adding `standard-libraries = true` to `dfyconfig.toml` does indeed seem to change and break the behaviour of the formatter.

**Comment by MikaelMayer** [comment]
This was normally fixed in  the latest nightly by this PR: https://github.com/dafny-lang/dafny/pull/4918
Please confirm that using the latest nightly this bug is no longer present, and if so please close this issue. Sorry for the inconvenience in the meantime.

**Comment by keyboardDrummer** [comment]
Closing since I believe we've resolved the issue and the issue is stale.
