### ISSUE TITLE
Hang with `dafny verify` on `Std`

### ISSUE THREAD

**Issue by atomb** [dafny-lang/dafny#5088]
### Dafny version

5cf477ae52f9d7805f0a2bb0ed924d556e8d9316

### Code to produce this issue

https://github.com/dafny-lang/dafny/blob/73fcdf32d81ab61a8262cbf62a4b59f7fc95747d/Source/DafnyStandardLibraries/src/Std/Strings.dfy#L84-L93

### Command to run and resulting output

```code
(In Source/DafnyStandardLibraries/src/Std)

$ dafny verify dfyconfig.toml --boogie-filter "*Strings.ParametricConversion*ToNat*"

(hangs with 0% CPU use after a minute or so)

$ dafny /compile:0 /readsClausesOnMethods:1 /proc:"*Strings.ParametricConversion*ToNat*" `find . -name "*.dfy" | grep -v TargetSpecific`

Dafny program verifier finished with 7 verified, 0 errors
$
```

### What happened?

Even with `--cores 1`, `dafny verify` hangs, but the old-style CLI works correctly.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by keyboardDrummer** [comment]
I think this is a bug that occurs when using `dafny verify` with `--boogie-filter`, introduced in https://github.com/dafny-lang/dafny/pull/4798

If you set a verification time limit and wait for that to pass, does it return an internal error? If yes that would confirm the above.

I'm inclined to remove support for `--boogie-filter` from `dafny verify` since we have `--filter-position` now and it's not easy to fix.

**Comment by atomb** [comment]
Yep, I think you're right. I do get an internal error when adding a time limit.

I like the ability to use wildcards to limit to everything in a given module, or even a subset of definitions in a module. Do you have any plans for a filtering option that allows that, using Dafny-centric names?

**Comment by atomb** [comment]
When running `dafny verify dfyconfig.toml --filter-symbol "Strings.ParametricConversion"`, I still get a hang. Is filtering by module expected to work? And, if not, we should have an error message instead of a hang.

**Comment by atomb** [comment]
For context, this came about when trying to verify the standard libraries with `--warn-{redundant,contradictory}-assumptions`. The process was hanging, which it doesn't when using old-style options. I used `--boogie-filter` to try to identify which definition was leading to the hang, under the hypothesis that this might be occurring due to a Z3 crash.

I just double-checked, and can confirm that this hang is still happening with `dafny verify` (even with `--cores 1`), but not with old-style options (even with multiple cores).

**Comment by keyboardDrummer** [comment]
> When running `dafny verify dfyconfig.toml --filter-symbol "Strings.ParametricConversion"`, I still get a hang. Is filtering by module expected to work? And, if not, we should have an error message instead of a hang.

Should work yes.

**Comment by keyboardDrummer** [comment]
Closing because we've removed support for `--boogie-filter`
