### ISSUE TITLE
Malformed Python code for some functions involving lambdas

### ISSUE THREAD

**Issue by fabiomadge** [dafny-lang/dafny#5092]
### Dafny version

4.4.0

### Code to produce this issue

```dafny
function True(): bool {
  if false 
    then false
    else if (_ => false)(false)
      then false 
      else true
}

method Main(){
    print True(), "\n";
}
```

### Command to run and resulting output

```code
dafny /compile:4 /compileTarget:py git-issue-5092.dfy
```

### What happened?

The lambda is in the wrong place.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by robin-aws** [comment]
Label nit-picking: shouldn't this be [during 3: execution of incorrect program](https://github.com/dafny-lang/dafny/labels/during%203%3A%20execution%20of%20incorrect%20program) instead?

**Comment by fabiomadge** [comment]
I don't think so. We emit invalid Python, which the validation that we run if no code gets executed catches.
