### ISSUE TITLE
Subtraction of non-native type is not yet supported in C++ backend - BigNumber issue

### ISSUE THREAD

**Issue by shenweihai1** [dafny-lang/dafny#5095]
### Dafny version

3.0.0.30204

### Code to produce this issue

```dafny
abstract module BankSpec {

  type AccountSeq(!new)
  method TryAccountTransfer(
      accountSeq: AccountSeq,
      i: int
  )
  returns (success: bool)
}

module BankImplementation refines BankSpec {
  type AccountSeq = seq<bool>

  method TryAccountTransfer(
      accountSeq: AccountSeq,
      i: int
  )
  returns (success: bool)
  ensures success == true
  {
      var a: nat;
      var b: nat;
      a := 2;
      b := 1;
      // ok
      success:=a==2;
      // ERROR: Unhandled exception. System.Exception: Subtraction of non-native type is not yet supported
      success:=(a-b)==1;
  }
}
```

### Command to run and resulting output

```code
// Verify in Dafny: 1 verified, 0 errors
.dafny/dafny//Scripts/dafny  /noNLarith /induction:0  /compile:0 {intput}.dfy

// Try to compile it into cpp code: throw an error
.dafny/dafny//Scripts/dafny  /noNLarith /induction:1 /compile:0 /noVerify /spillTargetCode:3 /countVerificationErrors:0 /out:/root/verified-betrfs/build/Bundle-i.cpp /compileTarget:cpp {input}.dfy
```

### What happened?

It looks like there is no way to do a subtraction between two numbers in C++ backend. Dafny can verify this code, but can not compile it into cpp code, throwing an `error: exception. System.Exception: Subtraction of non-native type is not yet supported.`

The root reason for this, in C++ backend, it translates nat or int in Dafny to "BigNumber", and this does not support "-". However, in fact, there is no BigNumber implementation, it seems Dafny assumes we have BigNumber implementation ready.

Is there any way to compile it into cpp code by ignoring or suppressing this error? 

### What type of operating system are you experiencing the problem on?

Linux

**Comment by MikaelMayer** [comment]
According to the documentation
> The C++ compiler does not support BigIntegers, so do not use int, or raw instances of arr.Length, or sequence length,

So intead of using "int", please use `uint64` or `int64` and you should have substraction.
If that solves your issue, you can close it.

**Comment by shenweihai1** [comment]
> According to the documentation
> 
> > The C++ compiler does not support BigIntegers, so do not use int, or raw instances of arr.Length, or sequence length,
> 
> So intead of using "int", please use `uint64` or `int64` and you should have substraction. If that solves your issue, you can close it.

Thank you for your reply. This is one way to solve it. 

However, my situation is that I have an other's verified codebase. In their code, they use nat and subtraction/add a lot. If I use int64 to replace it, it requires significant work to add many extra verifications to deal with overflow and maybe some unseen issues.

So, what I think is perfect:
(1) I implement a cpp library `BigNumber` (not need to be verified, so it should be kind of easy)
(2) Dafny helps me compile dafny into cpp code, for example, something like,
| Dafny code  | Compile cpp |
|-----------------|-----------------|
| var a : nat; <br> var b : nat; <br> var c : nat; <br>  c := a - b; |  BigNumber a = new BigNumber(); <br> BigNumber b = new BigNumber();  <br> BigNumber c = new BigNumber();  <br>   c = a.**subtract**(b) |

However, right now, Dafny prevents compiling it.

**Comment by MikaelMayer** [comment]
That's a nice idea. Dafny being an open-source project, we depend on the contributions of the community, and I'm happy to be the reviewer of such a feature if someone cuts a PR for that.

There might be a way to have big integers with without changing the compiler, using `{:extern}` `{:compile false}` annotations, but I have no experience in how it works for C++

**Comment by shenweihai1** [comment]
Thank you for reply, it looks like there is no perefct solution. My current solution is (it still has many problems, just reference to others) ,

1) define a int64 in Dafny's codebase, mapping to long in c++: `newtype{:nativeType "long"} nat64 = i:int | 0 <= i < 0x8000000000000000`
2) for any place using "+" or "-" operator between two nats in Dafny's codebase, bypass it! --> replace it with int64 and then do a reassignment, for example, -----> **_However, it is NOT correct for verification using int64 directly in this way. My purpose here is just to compile dafny code into c++ and run it for some baseline measurement_**

| Dafny code  | Compile cpp |
|-----------------|-----------------|
| var a : nat; <br> var b : nat; <br> var c : nat; <br>  c := a - b; | var aa: int64; aa := a as int64; <br> var bb : int64; bb := b as int64;<br> var cc : int64; **cc := aa - bb**; <br> c := cc as nat; |

3) in auto-generated cpp code, do serveral modifications on BigNumber to treat it as long directly,  ----> **_the reason i didn't write BigNumber implementation is it involves so many errors and takes time, for example, it can't be a key for a hashmap etc._**

| Dafny code  |
|-----------------|
| 1. Add `using BigNumber = int;` <br> 2. replace `new BigNumber(X)` to `X` <br> 3. remove `.Int64()` <br> 4. remove `_dafny.AsInt64()`|
