### ISSUE TITLE
dafny run file.dfy --include file.cs does not raise errors

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#5097]
### Dafny version

latest-nightly

### Code to produce this issue

```dafny
Have a file.dfy and a file.cs
```

### Command to run and resulting output

```code
dafny run file.dfy --include file.cs does not raise errors
```

### What happened?

--include is parsed as an argument to main. It should be detected that it's an option and required that it's after a --

### What type of operating system are you experiencing the problem on?

Windows

**Comment by codyroux** [comment]
+1

**Comment by robin-aws** [comment]
`--include` isn't a Dafny CLI option though, you want `--input` :)

**Comment by codyroux** [comment]
Indeed, but Dafny does not say this, it simply does not include the C# file. Lost a good hour to this.

**Comment by keyboardDrummer** [comment]
> Indeed, but Dafny does not say this, it simply does not include the C# file. Lost a good hour to this.

How could it detect that you don't mean `--include` to mean an option of the user program?

**Comment by keyboardDrummer** [comment]
> Git just does `git command --flags -- user_input possibly including flags`. Would that be an option? (note the space after the `--`)

Can you provide a concrete example? 

I'm guessing Git does the same as Dafny, because we're following the POSIX standard and I'd be surprised if `git` does not. https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html

**Comment by MikaelMayer** [comment]
Is the documentation wrong, or did something change? Either way, we documented something untested:

> `dafny run A.dfy --no-verify` – builds the Main program in A.dfy using the --no-verify option, and then runs the program with no command-line arguments
> `dafny run A.dfy -- --no-verify` – builds the Main program in A.dfy (not using the --no-verify option), and then runs the program with one command-line argument, namely --no-verify

https://dafny.org/latest/DafnyRef/DafnyRef#sec-dafny-run

Either way, with this issue raised and my awareness being more acute, my preference would be that any thing not starting with "-" after the file name be recognized as an argument for the main function, and anything starting with "-", if not after a "--", be considered as an option for Dafny and, if not recognized, says something like "If you want to pass this as an argument to the Dafny program, resolve the ambiguity by adding the special argument "--" before it"

**Comment by codyroux** [comment]
Here is git's behavior:

`git status foo.dfy --some-bogus-flag bar.dfy`

raises an error (unrecognized flag).

`git status foo.dfy -- --some-bogus-flag bar.dfy`

does not. I'd like identical behavior.

I _think_ that's what POSIX says? I'm not sure.
