### ISSUE TITLE
Lambda `requires` clauses intentionally opaque?

### ISSUE THREAD

**Issue by racko** [dafny-lang/dafny#5106]
The following assertion fails (with Dafny 4.4):
```dfy
var f := (x: int) requires x != 0 => x;
assert forall x: int | f.requires(x) :: x != 0;
```
I interpret this to mean that "we can't get information out of `f.requires(x)` other than that `f(x)` can be called".

If I understand this correctly, is this by design or a bug?

Since I guess that this is by design: Would you consider changing it?

---
Background: I'm implementing and proving lemmas about a [derivative](https://en.wikipedia.org/wiki/Derivative#As_a_limit) definition using a [limit](https://en.wikipedia.org/wiki/Limit_of_a_function#(%CE%B5,_%CE%B4)-definition_of_limit) definition for partial functions[^1] (I'm quoting from Wikipedia while using Dafny-like notation ...):
>Let `S` be a subset of the real numbers. Let `f: S -> R` be a real-valued function. Let `p`be a point such that there exists some open interval `(a, b)` containing `p` with `(a, p) + (p, b) < S`. It is then said that the limit of `f` as `x` approaches `p` is `L`, if:
>  For every real `eps > 0`, ...

Since `S` as a type isn't very helpful[^2], I want to just use the actual domain of `f`, as defined by `f.requires` in place of `S`. What I get is:
```dfy
ghost predicate limit(f: real-->real, p: real, L: real)
{
  exists a: real, b: real ::
    && (a < p < b)
    && (forall x: real | a < x < p :: f.requires(x))
    && (forall x: real | p < x < b :: f.requires(x))
    && (forall eps: real | eps > 0.0 :: ...)
}

ghost predicate derivative(f: real-->real, x: real, df: real)
{
  && f.requires(x)
  && limit(c requires c != x && f.requires(c) => (f(c) - f(x)) / (c - x), x, df)
}
```

Now, to prove something like `derivative(f, x, df) ==> derivative(x' requires f.requires(x') => a * f(x'), x, c * df)` I need to use the `a` and `b` values from the `limit` guarantee in `derivative(f, x, df)` and prove a `limit` statement about `var g := x' requires f.requires(x') => a * f(x')` using those `a` and `b`. The only guarantees I have that `g` can be called in this interval would be
```dfy
    && (forall x: real | a < x < p :: f.requires(x))
    && (forall x: real | p < x < b :: f.requires(x))
```
However, `derivative` only provides the guarantee that `var f' := c requires c != x && f.requires(c) => (f(c) - f(x)) / (c - x)` can be called in the interval. I cannot prove `forall x': real | f'.requires(x') :: f.requires(x')` within Dafny, thus I can't prove that `g` can be called either.

I can work around this problem by providing information about the domains of the functions as parameters to `limit` and `derivative`, but this complicates the solution.

[^1]: Because the [difference quotient](https://en.wikipedia.org/wiki/Difference_quotient) is usually partial on the domain of `f`.
[^2]: Because I don't want to introduce a new type for every function with a new domain.

**Comment by stefan-aws** [comment]
It seems to me that this only occurs for lambdas, i.e. the following verifies:

```
function f(x: int): int 
  requires x != 0
{
  0
}

function g(x: int): int 
  ensures forall x | f.requires(x) :: x != 0
{
  0
}


lemma L()
  ensures forall x | f.requires(x) :: x != 0
{}
```

Would it be possible for you to restructure your code such that the lambda in the definition of `derivative` is externalized?

**Comment by racko** [comment]
First of all: Thanks for pointing this out - I didn't think of trying it :slightly_smiling_face:

With this information, I now would guess that lambdas not supporting the same is not the result of a design decision, right?

>Would it be possible for you to restructure your code such that the lambda in the definition of derivative is externalized?

I didn't believe that I could, but with the following, I actually got it to work :sweat_smile:
```dfy
datatype DifferenceQuotient = DifferenceQuotient(f: real-->real, x: real)
{
  opaque function Call(c: real): real
    requires f.requires(x) // datatype constructors can't have requires clauses, right?
    requires f.requires(c)
    requires c != x
  {
    (f(c) - f(x)) / (c - x)
  }
}

opaque ghost predicate derivative(f: real-->real, x: real, df: real)
{
  && f.requires(x)
  && limit(DifferenceQuotient(f, x).Call, x, df)
}
```
So, thanks for this suggestion. I'll actually use it. But I also hope that this is not taken as "See, we don't need to improve lambdas!" :laughing:

**Comment by stefan-aws** [comment]
Glad you were able to work your way around it. I understand it would have been easier if the `requires` clause of a lambda would not be `opaque`. We might want to look into changing that in the future.

**Comment by racko** [comment]
Duplicate: https://github.com/dafny-lang/dafny/issues/5106
