### ISSUE TITLE
Judging by the current code --iterations option is ignored

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/dafny#5134]
https://github.com/dafny-lang/dafny/blob/master/Source/DafnyDriver/Commands/MeasureComplexityCommand.cs#L42

We should make a Boogie change to update VerificationTask so it's cloneable. Dafny can then clone VerificationTasks when it sees --iterations is used, and run each clone. There's a request to output for each iteration which --randomSeed argument should be used to reproduce that iterations, so we can do that in the meantime: https://github.com/dafny-lang/dafny/issues/5126#issuecomment-1970264367

**Comment by keyboardDrummer** [comment]
> But given a random number from a PRNG like the one in C#, AFAIK there is no way to get which random seed will generate that number, right? If anything one would need the pair random seed, number of iterations.
> 
> Else, one would need another way to generate random numbers, in which any number is also a seed. Like with repeated hashing.

We already have two phases of PRNG, one that is used to generate a new seed for each iteration, and another that takes an iteration seed to generate random numbers for that iteration. So, we can use the literal `--random-seed` value as an iteration seed for the very first iteration, then use PRNG to generate iteration seeds for the other iterations, based off of `--random-seed`, and print for each iteration the used iteration seed.

Then if you specify `--random-seed` with the iteration seed of a previous iteration, the very first iteration will match that previous one.

**Comment by hmijail** [comment]
Yes, and separating those two phases sounds more robust. Thank you!

**Comment by robin-aws** [comment]
Fixed by https://github.com/dafny-lang/dafny/pull/5138
