### ISSUE TITLE
IDE can't resolve more than once with --standard-libraries

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#5187]
### Dafny version

master (not present in 4.4.0)

### Code to produce this issue

```dafny
(Doesn't matter)
```

### Command to run and resulting output

```code
1. Specify `--standard-libraries`, either with "Dafny: Language Server Launch Args" or a dfyconfig.toml project file.
2. Load any file, which should trigger successful resolution.
3. Make an edit to the file (e.g. adding a space), which should trigger resolution again.
4. At the top-left corner of file (or of the project file if using):

the referenced file DafnyStandardLibraries-notarget.dfy contains error(s) but is not owned by this project. The first error is:
a replaceable module may only be replaced once
```

### What happened?

Likely caused by #4891 somehow (which was a good change but likely just needed to adjust how the standard library doo files are handled in the language server)

### What type of operating system are you experiencing the problem on?

Mac

**Comment by MikaelMayer** [comment]
Oh yeah thanks for fixing that! I had this issue every day as well but did not realize it could be reproducible as other issues prevented the code from resolving anyway.
