### ISSUE TITLE
Feature request: dynamic type tests

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#533]
As shown in the reproduction code for #532, this is technically possible already (assuming the compiler bug gets fixed), but having a more direct mechanism for "downcasting" is highly desirable.

I have two syntaxes in mind for this, the first of which is likely much easier to implement, but both would be very handy to have.

Assume this prelude for both examples (shamelessly stolen from #532):

```
trait Tr {
  var x: int
}

class C extends Tr {
  var y: int
}

class D extends Tr {
  var z: int
}

method Main() {
  var c := new C;
  var d := new D;
  c.x, c.y := 5, 6;
  d.x, d.z := 100, 102;

  M(c);
  M(d);
  M(c);
}
```

### 1. Match statements ###

This would mirror the approach in Scala. For example:

```
method M(t: Tr)
  modifies t
{
  print "t.x=", t.x, "  ";
  match t {
    case c: C => {
      print "The given Tr is a C, and c.y=", c.y, "\n";
      c.y := c.y + 10;
    }
    case _ => {
      print "The given Tr is not a C\n";
    }
  }
}
```

This would likely depend on PR #458, which makes ordering of case statement significant, since these kinds of tests are not guaranteed to be mutually exclusive. @osavaryb, I'm curious to hear your take on how hard this would be to implement. 

### 2. `is` operator with context-sensitive typing ###

This would mirror Kotlin's "smart casts", where the code in the control flow of a successful `x is T` test safely assumes that `x` is of type `T`, so there is no additional symbol bound. It would be less verbose for simple type tests and likely intuitive for programmers used to other languages with "instance of" operators, but likely harder to implement than 1. On the other hand, Dafny is already very good at carrying context-sensitive information like this; testing for null already allows code to assume a variable is non-null, for example.

```
method M(t: Tr)
  modifies t
{
  print "t.x=", t.x, "  ";
  if (t is C) {
    print "The given Tr is a C, and t.y=", t.y, "\n";
    t.y := t.y + 10;
  } else {
    print "The given Tr is not a C\n";
  }
}
```

**Comment by osavaryb** [comment]
It would be easy to implement (1) as desugaring to (2), in the same way we desugar constant matching to if-then-else decision trees in PR #458. 
Regarding notation, as we are already using ":" for type annotation (instead of guard) in CasePatterns (and ExtendedPatterns in PR #458), we could use "is" in ExtendedPatterns or introduce "when" guards to patterns in the style of Caml?

**Comment by robin-aws** [comment]
> It would be easy to implement (1) as desugaring to (2), in the same way we desugar constant matching to if-then-else decision trees in PR #458.

Good point. The more I ponder it the more it feels like `is` would be useful in many circumstances.

I also realized dynamic type tests are very useful when you make heavy use of subtypes and want to "downcast". Checking membership in the subtype directly would be cleaner and more readable than testing the attached predicate (if it's defined that way), or even duplicating the predicate expression.

> Regarding notation, as we are already using ":" for type annotation (instead of guard) in CasePatterns (and ExtendedPatterns in PR #458), we could use "is" in ExtendedPatterns or introduce "when" guards to patterns in the style of Caml?

So that would look something like this?

```
match t {
  case c when t is C => {
    ...
  }
  ...
}
```

That seems like it's going to make the implementation more complex, since it has to infer that c is of type `C` anyway based on the when guard. I'm sure it's possible, but is there an actual syntax ambiguity if we use ":" as in the proposed samples? That option seems to be both more understandable and easier to implement AFAICT.

**Comment by osavaryb** [comment]
I was thinking of something like
`match t {
  case p when P(v_1, ...,v_n) => {
    ...
  }
  ...
}`
where v_1, ..., v_n  are variables bound in pattern p. It doesn't make the pattern-matching compiler much more complex, and it is more general than adding support for "is" in patterns, and less adhoc than interpreting ":" as a smart cast or dynamic type test in patterns rather than as a type annotation (although that wouldn't break any of the current code, since c:C implies c is C).

**Comment by acioc** [comment]
Potential proposal: https://github.com/dafny-lang/dafny/issues/704

**Comment by robin-aws** [comment]
Adequately addressed by https://github.com/dafny-lang/dafny/pull/1220 as far as I'm concerned. Expanding the scope of these operations can be tracked by other issues.
