### ISSUE TITLE
Standard libraries not working with general-newtypes=true

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#5345]
### Dafny version

latest-nightly

### Code to produce this issue

```dafny
# dfyconfig.toml

[options]
standard-libraries=true
type-system-refresh=true
general-newtypes=true
```

### Command to run and resulting output

```code
> dafny verify dfyconfig.toml

DafnyStandardLibraries.dfy(4398,14): Error: type conversion to a char type is al
lowed only from numeric and bitvector types, char, and ORDINAL (got bv6)
     |
4398 |       (i - 4) as char
     |               ^^
```

### What happened?

There should have been no errors from the standard library.
This error is preventing me from using newtypes in my application that requires the standard library.

### What type of operating system are you experiencing the problem on?

Windows

**Comment by RustanLeino** [comment]
With `--general-newtypes`, the conversion has to go via `int`:

``` dafny
(i - 4) as int as char
```
