### ISSUE TITLE
Missing autocut step from some downstream customer nightly tests

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#5379]
Some projects are automatically cutting release blockers to this repo when their nightly builds fail, e.g. https://github.com/smithy-lang/smithy-dafny/blob/main-1.x/.github/workflows/nightly_dafny.yml#L36. But there are some that don't have this step yet because their nightlies are currently broken and would just create noise. Cutting this issue just to hold off on the next release until this is addressed.

**Comment by MikaelMayer** [comment]
If I understand correctly, we are going to test these projects ourselves when releasing, so I'll close this issue for now.
