### ISSUE TITLE
Boogie moved out from under Dafny

### ISSUE THREAD

**Issue by jonhnet** [dafny-lang/dafny#543]
AddZ3Option() disappeared in the most recent Boogie, but is still referenced here:
https://github.com/dafny-lang/dafny/blob/master/Source/Dafny/DafnyOptions.cs#L417

**Comment by robin-aws** [comment]
Legit breakage to fix, but FYI we recently changed the build process to lock the dependency on Boogie to 2.4.2, to avoid these breakages: https://github.com/dafny-lang/dafny/blob/master/buildspec.yml#L18

We should update the installation instructions accordingly though.

**Comment by robin-aws** [comment]
PR to fix INSTALL.md: https://github.com/dafny-lang/dafny/pull/544

**Comment by davidcok** [comment]
Fixed by PR #544, which is merged.
