### ISSUE TITLE
Nighty failed because a MacOS node timed out

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/dafny#5432]
https://github.com/dafny-lang/dafny/actions/runs/9064782607/job/24903792744

The job almost took 120m, which is when it times out.

**Comment by fabiomadge** [comment]
https://github.com/dafny-lang/dafny/actions/runs/9176479820/job/25231851880

**Comment by keyboardDrummer** [comment]
Resolved by https://github.com/dafny-lang/dafny/pull/5535
