### ISSUE TITLE
Z3 installation link might need an update

### ISSUE THREAD

**Issue by rishav-karanjit** [dafny-lang/dafny#5468]
### What change in documentation do you suggest?

Hi, the link to get Z3 in the [wiki](https://github.com/dafny-lang/dafny/wiki/INSTALL#mac-source) needs an update. Maybe the link should be updated to https://github.com/dafny-lang/solver-builds/releases/download/snapshot-2023-08-02/z3-4.12.1-x64-macos-11-bin.zip

**Comment by fabiomadge** [comment]
Thanks! The instructions should be up to date yet again.
