### ISSUE TITLE
Feature request: support redundancy

### ISSUE THREAD

**Issue by layus** [dafny-lang/dafny#552]
A feature that I am missing from my former OpenJML experience is redundancy of specifications. JML has the requires_redundantly for example, which allows to ascertain that an assertion is always valid in the precondition, wihtout expanding it.

I guess I need it most for pedagogical purposes, but it is also very useful to have examples, and to be able to attract the reader's attention on particular implications of the specification.

**Comment by robin-aws** [comment]
I can definitely see the benefits of being able to illustrate cases like this. One option would be to add `assert` statements to the beginning of the body, as those assertions will need to hold given the `require` statements. I'm assuming `requires_redundantly` clauses still have to be verifiable, they are just permitted to assume the regular `requires` clauses hold?

**Comment by samuelgruetter** [comment]
You can also put `assert` statements inside `requires` clauses:

```
method M(N: int, a: array<int>) returns (sum: int, max: int)
  requires 0 <= N && a.Length == N
  requires (assert 0 <= N; true)
  ensures sum <= N * max
{ ... }
```

So `requires_redundantly P` can be encoded as `requires (assert P; true)`.
(And note that if you change the order of the two `requires` clauses in the example, it will fail, because they are processed in one by one.)

**Comment by layus** [comment]
> I'm assuming requires_redundantly clauses still have to be verifiable, they are just permitted to assume the regular requires clauses hold?

Yes, that was my idea. It can also be seen as a simplified lemma that states `myfun.requires(x, y) ==> some redundant requires`

> You can also put `assert` statements inside `requires` clauses:

Nice catch! I has no idea you could do that. The ordering property is also very usefull :-).

A case where using asserts is not so nice is with invariants, because you need to assert at tree different locations to replace invariant_redundantly.

**Comment by RustanLeino** [comment]
If you want to write a redundant invariant, you can still use @samuelgruetter 's trick:

    invariant (assert MyRedudantExpression; true)

**Comment by layus** [comment]
Indeed :man_facepalming:. I guess we could make the syntax a bit better, but it suits my need at the moment.

**Comment by layus** [comment]
Thanks for your answer :)
