### ISSUE TITLE
Typo in INSTALL.md for building on Linux ?

### ISSUE THREAD

**Issue by xinqin23** [dafny-lang/dafny#561]
Hi! 
May I consult for Building on linux instruction in:

INSTALL.md (https://github.com/dafny-lang/dafny/blob/master/INSTALL.md)

In 3. Download and build Dafny:

git clone https://github.com/dafny-lang/dafny.git
mono ../nuget.exe restore dafny/Source/**Boogie.sln**
msbuild dafny/Source/Dafny.sln

Shall 'Boogie.sln' above be 'Dafny.sln' ?

I use the instruction of building on Mac OS X and succeeded. 
Thought above might be a typo in the INSTALL.md

thank you for reading!

**Comment by robin-aws** [comment]
Hi @xinqin23! You are absolutely correct - copy and paste error on my part. :)

Fixed in db47af9649334e4ac1f01706c760c56948a72eb5. Thanks for catching that!
