### ISSUE TITLE
Support for enumerating finite datatypes in Rust

### ISSUE THREAD

**Issue by fabiomadge** [dafny-lang/dafny#5643]
### Dafny version

4.7.0

### Code to produce this issue

```dafny
datatype D = A | B

const c := set d: D | true :: d

method Main() {
  print c, "\n";
}
```

### What happened?

`EmitDatatypeBoundedPool` unsupported

### What type of operating system are you experiencing the problem on?

Mac

**Comment by ssomayyajula** [comment]
(documenting for anyone watching) workaround: declare `c` directly from the singleton constructors of `D`
