### ISSUE TITLE
Valid Lhs of a Method call with multiple out-parameters

### ISSUE THREAD

**Issue by fabiomadge** [dafny-lang/dafny#5660]
### What change in documentation do you suggest?

```Dafny
method Main() {
  var one_var := foo();
}

method foo() returns (a: int, b: int, c: int) {
  return 1, 2, 3;
}
```
This program gets rejected, but is valid according to our [documentation](https://github.com/dafny-lang/dafny/blame/8600061046003793e5d5260e3df550420c3ad83a/docs/DafnyRef/Statements.md#L182-L183).

**Comment by RustanLeino** [comment]
Drop the

```
or there must be just one ``Lhs`` to the left of
the `:=`, which then is assigned a tuple of the out-parameters
```

from the documentation. It is incorrect.
