### ISSUE TITLE
Confused outputs about errors

### ISSUE THREAD

**Issue by superymk** [dafny-lang/dafny#568]
When the verification takes long time, Dafny (650a6bbebdf5b696a0a0b2cdc7d77b0c502b7be5) says errors in individual functions but not in summary. In one example:

```
Verifying CheckWellformed$$_module.__default.va__code____usbtd__slot__submit__qtd32 ...
  [2.473 s, 159 proof obligations]  verified

Verifying CheckWellformed$$_module.__default.va__lemma____usbtd__slot__submit__qtd32 ...
  [2.359 s, 496 proof obligations]  verified
Linearising   [0.872057 s]

Verifying Impl$$_module.__default.va__lemma____usbtd__slot__submit__qtd32 ...
  [625.637 s, 5354 proof obligations]  errors

Dafny program verifier finished with 2 verified, 0 errors
```

In this example, "[625.637 s, 5354 proof obligations]  errors" is conflict with "2 verified, 0 errors"

**Comment by davidcok** [comment]
Can you add the code that demonstrated the problem to the issue?

**Comment by davidcok** [comment]
This appears to be fixed, at least I cannot reproduce it. All my trials with and without timeouts produce an accurate summary statement. Not creating a test because the verbose output (obtained by using /tracePOs) in question contains timing data that would be nondeterministic.
