### ISSUE TITLE
Feature request : `--root false` 

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#5710]
Currently, the Dafny to Rust code generator emits a root Rust file, so that it takes care of defining which files and folders to include as part of the compilation.
However, in some cases, the root file might already exist, and a user would like to integrate some Dafny code not into a sub-crate, but directly as part of an existing crate.

I suggest a Rust-specific CLI option like `--root:false` which could make it possible to emit a non-root Rust file, provided a name different than `lib` in `--output`. That way, users would have full control over the root files and which modules to include.

In this mode, it would not be possible to provide extern Rust files on the command-line, however, it would still be possible to use extern attributes in Dafny source files.

**Comment by robin-aws** [comment]
This is related to https://github.com/dafny-lang/dafny/issues/5641 as well - we'll likely want something like `--rust-crate-name` and `--rust-module-name`.

**Comment by MikaelMayer** [comment]
Closed in favor of https://github.com/dafny-lang/dafny/issues/5641
