### ISSUE TITLE
Dafny assertion time outs hidden as errors

### ISSUE THREAD

**Issue by acioc** [dafny-lang/dafny#581]
It looks like assertion time outs only show up as assertion violations when verifying.

For context, my IDE (VSCode) pointed out time outs, but the CLI itself looks like it just had an Error: assertion violation. I will update this issue if the assertion violation was in fact invalid.

**Comment by acioc** [comment]
In this particular case, we had 2 assertion violations. They were formatted as follows:

```
    assert MyFirstAssertion by {
      someLogicHere
      assert MySecondAssertion;
    }
```

Dafny verify, showed both assertions as failing. MyFirstAssertion almost certainly failed because  MySecondAssertion failed. I believe MySecondAssertion timed out, but this was hidden.

**Comment by davidcok** [comment]
It would be helpful if you could provide a minimal example showing the problem.
