### ISSUE TITLE
Clarify build/ run requirements for Dafny

### ISSUE THREAD

**Issue by acioc** [dafny-lang/dafny#582]
As a follow up to https://github.com/dafny-lang/dafny/pull/579 where the base version of .NET framework was changed, the README should likely be updated to reflect...

1. What does Dafny need to build
2. What does Dafny need to verify
3. What does Dafny generated (transpiled) code need to actually run

**Comment by davidcok** [comment]
The installation instructions (on the wiki) now contain this information.

**Comment by MikaelMayer** [comment]
I am closing this because I believe that the README correctly points to the installation instructions now, as @davidcok mentions it. Please let us know or even feel free to cut a PR if you think we could add more information.
