### ISSUE TITLE
Verification inconsistency between Dafny versions

### ISSUE THREAD

**Issue by RitvikKapila** [dafny-lang/dafny#5855]
### Dafny version

4.8.1

### What happened?

In the [Encryption SDK in Dafny](https://github.com/aws/aws-encryption-sdk-dafny), I updated the Dafny version to `4.8.1` and suddenly the verification (which was passing with `4.8.0`) started failing. [Here is the CI verification run](https://github.com/aws/aws-encryption-sdk-dafny/actions/runs/11467131092/job/31909338572?pr=685#step:7:179) that timed out and failed for the first time on bumping versions from `4.8.0` to `4.8.1`. [This is the only change](https://github.com/aws/aws-encryption-sdk-dafny/pull/685/commits/ed714a7b7bbc53f823761aa6740609215a761507) I had made after which the verification started failing. The error I got was `Error: Verification of 'MessageBody.ReadFramedMessageBody' timed out after 100 seconds`. I tried to verify this file `MessageBody.dfy` on my laptop and the Dafny verifier in VS Code also complained: `Could not prove ReadFramedMessageBody` which is a method in file `MessageBody.dfy`. When I looked at the VS Code verification, the issue was with [proving this line](https://github.com/aws/aws-encryption-sdk-dafny/blob/864c2e2446ccf8a85ae2394ab53494de4afec8fe/AwsEncryptionSDK/dafny/AwsEncryptionSdk/src/MessageBody.dfy#L1043).

@seebees and I looked at the verification issue and @seebees came up with the idea to update the verification code to write a cleaner proof. [Here's the PR](https://github.com/aws/aws-encryption-sdk-dafny/pull/690/files) in which I made the change. The problem is that this new code now verifies with the version `4.8.1` but fails with version `4.8.0`. [Here's the CI verification run](https://github.com/aws/aws-encryption-sdk-dafny/actions/runs/11488659993/job/31975852196#step:7:779) that fails on this PR (which is on `4.8.0`).

I have also verified this on my local using the Dafny vscode extension that the original code fails with `4.8.1` but passes with `4.8.0`. And this new change fails with `4.8.0` but passes with `4.8.1`.

## Reproducing steps
You can reproduce this issue by cloning the [Encryption SDK in Dafny](https://github.com/aws/aws-encryption-sdk-dafny), and in the `mainline` branch, navigating to [this file](https://github.com/aws/aws-encryption-sdk-dafny/blob/mainline/AwsEncryptionSDK/dafny/AwsEncryptionSdk/src/MessageBody.dfy) on your laptop. Set the dafny version to `4.8.1` or nightly and the verification will fail. If you set the Dafny version to `4.8.0`, it will pass.

To reproduce the second issue where after updating the proof it starts failing with `4.8.0`, pull down the branch `rkapila/dafny-verification-fix` and navigate to the same file as above. If you set your Dafny version in the vscode extension to be `4.8.0`, it will fail, and if you set it to `4.8.1`, it will pass.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by ssomayyajula** [comment]
Hi Ritvik -- looks like the culprit is the opacity of `CorrectlyReadRange` connecting to one of the preconditions in that function method. This fix verifies for me on 4.8.0, 4.8.1, and the upcoming 4.9.

```dafny
      var res := Success(SuccessfulRead(nextRegularFrames, regularFrame.tail));
      assert CorrectlyRead(buffer, res, WriteMessageRegularFrames) by {
        var readRange := Frames.WriteRegularFrame(regularFrame.data);
        
        AppendToCorrectlyReadByteRange(buffer, continuation, regularFrame.tail, readRange);
        assert buffer.bytes[buffer.start..regularFrame.tail.start] == buffer.bytes[buffer.start..continuation.start] + readRange;
        assert buffer.start <= regularFrame.tail.start <= |buffer.bytes|;
        assert CorrectlyReadRange(buffer, regularFrame.tail, buffer.bytes[buffer.start..regularFrame.tail.start]);
        
        // Obvious: regularFrame.tail == res.value.tail;
        assert buffer.bytes[buffer.start..regularFrame.tail.start] == WriteMessageRegularFrames(nextRegularFrames) by {
          assert WriteMessageRegularFrames(nextRegularFrames) == WriteMessageRegularFrames(regularFrames) + readRange;
          assert WriteMessageRegularFrames(regularFrames) == buffer.bytes[buffer.start..continuation.start] by {
            assert CorrectlyRead(buffer, Success(SuccessfulRead(regularFrames, continuation)), WriteMessageRegularFrames);
            reveal CorrectlyReadRange();
          }
        }
      }
```
