### ISSUE TITLE
Rust code generation with --rust-module-name

### ISSUE THREAD

**Issue by ajewellamz** [dafny-lang/dafny#5864]
### Dafny version

4.8.1 (nightly)

### Code to produce this issue

```dafny
any
```

### Command to run and resulting output

```code
dafny -t rs
```

### What happened?

Normally, dafny produces something like this at the top of implementation_from_dafny
```
pub mod aes_gcm;
pub mod _dafny_externs {
  pub use crate::aes_gcm::*;
}
```
When compiling with `--rust-module-name` the same thing is produced, where it should only produce
```
pub mod _dafny_externs {
  pub use crate::aes_gcm::*;
}
```
because otherwise it's referring to implementation_from_dafny::aes_gcm which does not exist.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by MikaelMayer** [comment]
Linked to https://github.com/dafny-lang/dafny/pull/5747
