### ISSUE TITLE
Go: Type labels within a package should not be prefixed by package name

### ISSUE THREAD

**Issue by TonyZhangND** [dafny-lang/dafny#588]
Consider this minimal Dafny example 

```dafny
module myclass {
class MyClass
{
  var num: int;

  constructor (x: int) 
  {
      num := x;
  }
}

method main()
{ 
    var c_obj := new MyClass(2);
}
}
```

When compiling Dafny into Go, the compiler produces a Go package `_0_myclass_Compile` where _within the package_, there are variable declarations such as 

```go
var _13_c__obj *_0_myclass_Compile.MyClass
```

When compiling the Go code using the Go compiler, this declaration results in an error of the form

```
src/0_myclass_Compile_/0_myclass_Compile_.go:113:19: undefined: _0_myclass_Compile
```

Removing the package prefix from the declaration, i.e. changing it to 
```go
var _13_c__obj *MyClass
``` 
resolves the issue.

**Comment by davidcok** [comment]
Is already fixed. Added test case.
