### ISSUE TITLE
Calling Dafny without .dfy with a .cs input file throws unhandled exception.

### ISSUE THREAD

**Issue by WouterSchols** [dafny-lang/dafny#590]
Running Dafny from the command line with a switch which containing a .cs file as input will throw a  NullReferenceException

This error can be reproduced by just running "dafny something.cs" file "something.cs" does not need to exist

**Comment by davidcok** [comment]
Fixed by PR641

**Comment by robin-aws** [comment]
Please don't close issues until the PRs that fix them are actually merged. Sometimes it can take a while for a PR to actually be merged, or turns out to be the wrong solution in the first place. :)

**Comment by davidcok** [comment]
Agreed, and I purposefully didn’t, but ...

**Comment by robin-aws** [comment]
> Agreed, and I purposefully didn’t, but ...

My apologies, my wrist-slap was directed at @WouterSchols but wasn't precise enough. :)
