### ISSUE TITLE
In Rust, `constant` returns different values.

### ISSUE THREAD

**Issue by ajewellamz** [dafny-lang/dafny#5925]
### Dafny version

4.9.1 (b998ed949)

### Code to produce this issue

```dafny
// const SuccessTestingRequiredEncryptionContextKeysReproducedEncryptionContext := ...
method {:test} RunManifestTests() {
  var orig := SuccessTestingRequiredEncryptionContextKeysReproducedEncryptionContext;
  for i := 0 to 100 {
    expect orig == SuccessTestingRequiredEncryptionContextKeysReproducedEncryptionContext;
  }
}
```

### Command to run and resulting output

```code
git clone --recurse-submodules git@github.com:aws/aws-cryptographic-material-providers-library.git
cd aws-cryptographic-material-providers-library
git checkout ajewell/test-fail
cd TestVectorsAwsCryptographicMaterialProviders
make polymorph_rust transpile_rust test_rust

You should see a single test failure, in the test shown above.
```

### What happened?

A constant should be constant. In Rust, this constant is variable.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by RitvikKapila** [comment]
The `constant` `SuccessTestingRequiredEncryptionContextKeysReproducedEncryptionContext` is defined [here](https://github.com/aws/aws-cryptographic-material-providers-library/blob/683a26d337c300110385ebe84757696d53d44b4f/TestVectorsAwsCryptographicMaterialProviders/dafny/TestVectorsAwsCryptographicMaterialProviders/src/VectorsComposition/AllRequiredEncryptionContextCmm.dfy#L34). It is a set composition and should output a set of 5 values every-time, but this constant computation is flaky.

A heads up, you will have to comment out the line inside the main function of `implementation_from_dafny.rs` to make the above configuration work every time you transpile code in Rust.

**Comment by ajewellamz** [comment]
This can be worked around n the Dafny code, so closing.

**Comment by robin-aws** [comment]
This turned out to be because of an invalid extern in the definition of the constant: a `function` that did not necessarily return the same output for the same input (because it depended on HashSet ordering).

Closing this, but also considering it a +1 on #5861
