### ISSUE TITLE
Dafny ensures false

### ISSUE THREAD

**Issue by LukeXuan** [dafny-lang/dafny#600]
@jaylorch and I ran into a problem with Dafny when it proved incorrect consequences when dealing with datatypes and sequence residency. The following code snippet demonstrates the issue by proving false with no preconditions.

```
datatype D = D(n: int)

function f(s: seq<int>): int
  requires |s| != 0
  ensures  f(s) in s
{
  s[0]
}

predicate vacuous_fact(ds: seq<D>, s: seq<int>)
{
  0 in s && |s| == 0 ==> ds[f(s)].n == 0
}

lemma False()
  ensures false
{
  assert vacuous_fact([], []);
}

```

I have confirmed that both the latest release (2.3.0) and the master branch verify this lemma.

**Comment by RustanLeino** [comment]
Thanks for the bug report and the small repro.
