### ISSUE TITLE
Dafny linting rules

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#614]
This would be extremely useful, and could cover a wide-range of code quality issues as outlined in the style guide: https://github.com/dafny-lang/dafny/blob/master/Docs/StyleGuide/Style-Guide.md

It could even go deeper than that and detect things like redundant pre-/post-conditions or dead code.

**Comment by robin-aws** [comment]
Just to clarify: we don't intend to build a separate linting tool at this time, only to add more warnings for `dafny` itself to output. We also need to break down individual warnings to track them separately.

**Comment by keyboardDrummer** [comment]
Closing this since it's too ambiguous: we should specify which warnings to implement instead of saying we implement some.

**Comment by davidcok** [comment]
It is not ambiguous -- it identifies a task to figure out what to warn about...
