### ISSUE TITLE
Issue a warning on pre-conditions (requires) equivalent to false

### ISSUE THREAD

**Issue by franck44** [dafny-lang/dafny#620]
This issue is not a bug in Dafny, probably an enhancement.

The function `foo` below has a pre-condition (Pre) logically equivalent to `false`.
As a consequence any code in the body (Body) and any post-condition (Post) will satisfy the pre-post constraints (the function can not be run for any input, so it is trivially correct).
Indeed, Dafny verifies `foo` as the verification conditions is: is `Pre && Body && !Post` SAT? the answer being no as `Pre == false`.
There is no logical flaw or bug in the SMT-solver or the Dafny verification engine, but it may be helpful to issue a warning when a pre-condition is equivalent to `false`. 

1. first, it probably reveals a glitch in the spec,
2. second, the flawed spec is not detected unless function `foo` is called (and then Dafny may issue a violation of pre-condition),
3. third, the problem may somehow be propagated arbitrarily to other parts of the code
(e.g. `foo1` that calls `foo`, and `foo1` verifies too) and get unnoticed for a while (until you write `foo100` for instance that does not use the require of the callee). This can make it hard to debug.

Feasibility of issuing a warning: seems doable as I was able to write an `assert !( ... <==> false)` with the (conjunctions of the) pre-conditions and Dafny rightly pointed to a violation of the `assert`. 

Actually the code snippets below are a simplified version for the sake of explaining the problem, but I stumbled upon this issue while writing a larger piece of code and the preconditions involved constraints on types (that were unsatisfiable). When a violation was detected by the verifier I had written quite a few functions and it took me while to discover the actual problem.
 
```
function foo100(x: nat) : nat 
    requires x >= 0
    ensures foo100(x) >= 11
{
    foo1(x) + 1
}

// a function with pre-condition equivalent to false
function method foo(x: nat) : nat
    requires x < 2 && x > 2. // equiv to false
    ensures foo(x) >= 10. // we can conclude whatever even false
{
    x + 1
}

function foo1(x: nat) : nat 
    requires foo.requires(x)
    ensures foo1(x) >= 11
{
    foo(x) + 1
}
```

**Comment by atomb** [comment]
With the `--warn-contradictory-assumptions` flag, Dafny now warns about such situations, including all of the contradictions in that example.
