### ISSUE TITLE
Export consistency check incorrectly disallows exporting constants as "provides"

### ISSUE THREAD

**Issue by danmatichuk** [dafny-lang/dafny#621]
The following Dafny program fails during resolution:
```
module M {
  export provides D, MyData

  datatype D = D1 | D2

  const MyData : D := D1
}
```

With an error claiming that the export set is not consistent, saying that `MyData` must be given a defining value.

**Comment by davidcok** [comment]
Cannot provide D1, D2
Works OK if 'reveals D' is added

**Comment by davidcok** [comment]
Actually, with updated master, this bug is gone.
