### ISSUE TITLE
Include Boogie as a git submodule

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#625]
This would be a much cleaner way to handle the dependency, including locking down the required version, compared to the manual installation/build steps we currently specify.

**Comment by parno** [comment]
Do you mean as a git submodule?  My impression is that git submodules sound like a good idea, but they usually end in tears, as it's very easy for them to get out of sync.

**Comment by robin-aws** [comment]
I did, and I agree. :) But I figure having a submodule is still incrementally better than the "poor-man's submodule" model of manually fetching the target version of Boogie in both the build (https://github.com/dafny-lang/dafny/blob/master/.github/workflows/msbuild.yml#L28-L33) and dev setup documentation. At least this way if your submodule is out of sync with what's checked in, it would show up in the git status.

It would certainly be much better to have Dafny depend on Boogie components as nuget packages instead, but Boogie doesn't currently publish components with enough granularity to work.

**Comment by keyboardDrummer** [comment]
+1,

What's the work involved for this, apart from defining the submodule and updating the Boogie path references? Is this something I could pick up?

Also, I imagine that having Boogie as a submodule instead of as a nuget dependency can improve development speed when making changes in Dafny that depend on Boogie changes.

**Comment by robin-aws** [comment]
@keyboardDrummer By all means! It should be pretty simple and a great first issue to tackle.

**Comment by keyboardDrummer** [comment]
This PR should address this issue: https://github.com/dafny-lang/dafny/pull/772

**Comment by davidcok** [comment]
Can this issue be closed now?
