### ISSUE TITLE
Dafny to Go compilation over multiple Dafny files results in invalid syntax

### ISSUE THREAD

**Issue by lavaleri** [dafny-lang/dafny#633]
Dafny to go compilation will result in invalid go if performing over multiple dafny files. e.g. running `dafny my_program1.dfy my_program2.dfy`. This is because the compiler will default the stubbed my_program1.go to have package name "the program", like so:
[Edit: only if there is no main method ]

```
// Dafny program the program compiled into Go
package the program

import (
...
```

This is originally set in https://github.com/dafny-lang/dafny/blob/14d0af1074f12981a32b43313fefe3cc2483d4e8/Source/DafnyDriver/DafnyDriver.cs#L200
And used by the go compiler here: https://github.com/dafny-lang/dafny/blob/14d0af1074f12981a32b43313fefe3cc2483d4e8/Source/Dafny/Compiler-go.cs#L43-L48

This results in invalid go syntax, because a package names must only consist of lower case characters: https://blog.golang.org/package-names

**Comment by davidcok** [comment]
Changes the name of the module from (the illegal in go) "the program" to "the_program" in cases where there are multiple input files and no Main method.
