### ISSUE TITLE
Update brew formulae to link to Dafny README

### ISSUE THREAD

**Issue by acioc** [dafny-lang/dafny#638]
Currently the brew formulae https://formulae.brew.sh/formula/dafny#default links to an old Microsoft research page. Ideally, this should link to the dafny README directly, since the README represents the latest, single point of truth. 

The page the formulae links to is https://www.microsoft.com/en-us/research/project/dafny-a-language-and-program-verifier-for-functional-correctness/ which links to the dafny location at: https://github.com/Microsoft/dafny This properly auto-redirects to this repo, but it would be ideal if we make it clear that Dafny is community owned.

**Comment by RustanLeino** [comment]
Here is the site where I think one files a PR to make this change: https://github.com/Homebrew/homebrew-core

**Comment by davidcok** [comment]
PR made on Brew site. Waiting for it to be merged by brew developers.

**Comment by davidcok** [comment]
PR merge complete.
