### ISSUE TITLE
expect statement message should include program location

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#643]
This termination message from an expect statement

Program halted: expectation violation

should include a program location

**Comment by robin-aws** [comment]
I like this idea, but have to investigate whether it is feasible in all current (and future) language implementations.

As a workaround, `expect` takes an optional second `string` argument that can help diagnose the failure.

**Comment by davidcok** [comment]
An alternative is to have the default second argument be something that incorporate file and position information. The user can always override this with an explicit empty string.

**Comment by robin-aws** [comment]
Agreed, if it's possible to provide it I'd definitely prefer it to the current generic default.

**Comment by davidcok** [comment]
Here is a code snippet that can supply the location information (Compiler.cs around line 2100):

      } else if (stmt is ExpectStmt) {
        var s = (ExpectStmt)stmt;
        // TODO there's potential here to use target-language specific features such as exceptions
        // to make it more target-language idiomatic and improve performance
        TargetWriter guardWriter;
        TargetWriter bodyWriter = EmitIf(out guardWriter, false, wr);
        var negated = new UnaryOpExpr(s.Tok, UnaryOpExpr.Opcode.Not, s.Expr);
        negated.Type = Type.Bool;
        TrExpr(negated, guardWriter, false);
        string location = "expectation violation at " + s.Tok.filename + ":" + s.Tok.line + ":" + s.Tok.col;
        s.Message = new StringLiteralExpr(s.Tok, location, false);
        s.Message.Type = Type.String();
        EmitHalt(s.Message, bodyWriter);

Note that these expect strings print out as character sequences in Java -- not sure why that was done.

**Comment by robin-aws** [comment]
Ah true, I confused myself into thinking the target runtimes had to provide the information dynamically, but you're right, we just want the Dafny source location.

I think the inconsistency with Java string printing you're describing is a known issue: https://github.com/dafny-lang/dafny/blob/master/Test/expectations/ExpectWithNonStringMessage.dfy.expect#L9

**Comment by davidcok** [comment]
Too much of a pain not to have this. So I just implemented it. PR #677.
