### ISSUE TITLE
Missing well-formedness check for static receiver

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#664]
A static member `M` of a type `C` is typically denoted `C.M`. But Dafny--for better or worse--also allowed it to be referenced by `E.M` where `E` is an expression whose type is `E`. At run time, the "receiver" argument `E` in `E.M` is ignored. Nevertheless, the verifier should check that `E` is well-formed. That check is currently missing.

Here are some tests. The same tests apply if `C` is not a `class`, but a `trait`, `datatype`, or `newtype`.

```
class C {
  static const X: int
  static method M() { }
  static function method F(): int { 5 }
}

method TestClass(c: C) {
  if
  case true =>
    var x := (if 5/0 == 2 then c else c).X;  // error: receiver is not well-formed
  case true =>
    (if 5/0 == 2 then c else c).M();  // error: receiver is not well-formed
  case true =>
    var x := (if 5/0 == 2 then c else c).F();  // error: receiver is not well-formed
  case true =>
    var f := (if 5/0 == 2 then c else c).F;  // error: receiver is not well-formed
}
```

**Comment by davidcok** [comment]
Not as easy to fix as I expected. The receiver is rewritten as a reference to the static class during type checking, which is long before well-formedness checks are introduced in translation. So the receiver expression is no longer available for WF checking.

**Comment by davidcok** [comment]
Fixed by hanging the original receiver expression, resolved, off the AST for the static receiver node that is the result of the rewriting. Then during well-formedness checks, that cached expression is checked as well. This has the side effect of checking the receiver expression for other problems, such as lack of definite assignment.

Fixed in PR# 709
