### ISSUE TITLE
Missing error apparently caused by erroneous type inference

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#668]
class X {
  function method F(): int { 2 }
}

class K { }

method P0(x: X, k: K) {
  var o;  // type inferred to be object
  o := x;
  o := k;
  var u := o.F();  // F does not exist in object
}

With Rustan's PR https://github.com/dafny-lang/dafny/pull/667, this program checks without errors! That’s bad.

**Comment by RustanLeino** [comment]
As a note, before PR #667, this example would crash. So, while #667 fixed that crash, it revealed another problem.
