### ISSUE TITLE
Incorrect default values for generic types

### ISSUE THREAD

**Issue by parno** [dafny-lang/dafny#674]
[cf #610]

In the code below, we should (provably) never reach the print statements, and yet the executable produced via C# does print them both (at least as of c580b1e8100fbb2a).  
[ Edit: As of 8/5, master (945ca6d989e0a5d9b6f67a86470ca4994fa0f9fb) exhibits correct behavior for js and go, incorrect behavior for java and C#)]

In the tuple portion of the example below, the emitted C# code is:
```
_System.Tuple2<BigInteger,BigInteger> _15_p = _System.Tuple2<BigInteger,BigInteger>.Default;
```
whereas we want the right-hand side at least to be `_System.Tuple2<pos, pos>.Default`.

The relevant line (for C#) appears to be this one:
https://github.com/dafny-lang/dafny/blob/ba5777b4faf18ec2dd0512490b55fa468e238f63/Source/Dafny/Compiler-Csharp.cs#L1056
where it’s calling `TypeNames` on the `TypeArgs`, which calls `TypeName`, which starts by calling `NormalizeExpand`, which converts `pos` into `int`. 

I'm afraid I'm not sure what the appropriate fix is, unless it's a version of `TypeName` (and hence `TypeNames` that takes an option to not expand the type it's handed.

```
type pos = i:int | i > 0 witness 1

datatype Generic<T> = Gen(p:T)

method Main() {
  var p:(pos, pos);
  var (a, b) := p;
  assert a > 0;
  assert b > 0;

  if a == 0 {
    assert false;
    print "We should not arrive here, and yet we do.\n";
  }

  var e:Generic<pos>;
  var Gen(n) := e;
  assert n > 0;
  if n == 0 {
    assert false;
    print "We should not arrive here, and yet we do.\n";
  }
}
```

**Comment by davidcok** [comment]
Still a problem for C#. OK for other languages.
