### ISSUE TITLE
Resolver ignores bodies of redundant cases

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#686]
The resolver (type-checking phase) of Dafny warns about about redundant `case`s in a `match`. That is, for any `case` that can be determined to already be fully covered by previous `case`s, Dafny generates a helpful "this branch is redundant" warning. However, the resolver then ignores the body of that `case`, which ain't right.

As a repro, Dafny produces two warnings for this program, but then happily compiles and runs the program without ever having resolved and type checked the bodies of the redundant cases. 

```
datatype Color = Blue | Red
  
function method Foo(c: Color): int {
  match c
  case Blue => 4
  case Blue =>  // warning: redundant branch
    assert doesNotExist == TotallyBogus + (3 && true);  // BOGUS: there should be complaints about this line, but there aren't
    5
  case Red => 6
}

method Moo(c: Color) returns (x: int) {
  match c
  case Blue =>
  case Blue =>  // warning: redundant branch
    doesNotExist := TotallyBogus + 3 && true;  // BOGUS: there should be complaints about this line, but there aren't
  case Red =>
}

method Main() {
  var x := Moo(Red);
  print Foo(Red), " ", x, "\n";
}
```

**Comment by acioc** [comment]
From @robin-aws : potentially make this an error instead of a warning.

**Comment by davidcok** [comment]
Closed with merging PR902
