### ISSUE TITLE
Incorrect compilation to Java: boxed/unboxed type mismatch

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#701]
The following program verifies, compiles, and runs with the C#, JavaScript, and Go compilers, but emits malformed target code with the Java compiler.

``` dafny
method Main() {
  var ca := new ClassA;
  print ca.y, " ", ca.k, " ", ca.l, "\n";
  var cb := new ClassB;
  print cb.y, " ", cb.k, " ", cb.l, "\n";
  var cc := new ClassC;
  print cc.y, " ", cc.k, " ", cc.l, "\n";
}

trait Trait<Y> {
  const y: Y
  const k: Y := y
  const l: Y
}

datatype C<T> = Atom(T) | Nothing

class ClassA extends Trait<bv8> { }
class ClassB extends Trait<array<bv8>> { }
class ClassC extends Trait<C<bv8>> { }
```

The problem is that the fields that each class inherits from `Trait` get a more specific type in the class. For example, the code emitted for `ClassA` includes:

``` java
public interface Trait<Y> {
  public Y y();
}
public class ClassA implements Trait<Byte> {
  public ClassA() {
    this._y = (byte) 0;
  }
  public byte _y;
  public byte y()
  {
    return this._y;
  }
}
```

Since `ClassA` implements `Trait<Byte>`, the expected return type of the `y()` method should be `Byte`, not `byte`. (The field `_y` can be declared to be either of type `byte` or type `Byte`.)

Note, if a trait or class declares a field to be of type `bv8` (as opposed to a type parameter that is later instantiated with `bv8`), then the target type should always be `byte`, not `Byte`. So, the compiler needs to compare the type of the field with the type of the overridden field. (For fields, that is done in the compiler implementation by looking at `.OverriddenMember`, whereas functions and methods can involve several override steps to get to the original declaration, which is accomplished by the `.Original` property.)

The implementation of the Java compiler has a method `TypeName`, which produces the likes of `byte` above, and a method `BoxedTypeName`, which produces the likes of `Byte` above. So, to fix this issue, some call to `TypeName` should be changed to a call to `BoxedTypeName`.

The example above uses a `const`, but a mutable field, function, or method probably suffers from the same problem.

In addition, `ClassB` above reveals one more problem, which is that when `ClassB.k()` calls the RHS for `k`, which lives in the companion class for `Trait`, it calls it as:

    return _Companion_Trait.<byte[]>k((dafny.Type.BYTE).arrayType(), this);

This is met by the following Java-compiler complaint:

    incompatible types: Type<CAP#1> cannot be converted to Type<byte[]>

I don't understand what this means (perhaps it wants `byte[]` to be `Byte[]`?).

**Comment by davidcok** [comment]
Fixed in PR #730
