### ISSUE TITLE
as and is

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#704]
WIP PARTIAL DRAFT:

This proposal is to expand the use of 'as' and add the operator 'is'. The syntax is 'e is T' and  'e as T' where e is an expression and T is a type.

- e is T returns a boolean
- e as T returns a T if e is T true, and fails if e is T is false. This condition is checked by the verifier (that is, its must be provable that e is T).

- the expressions e is T and e as T, where t is the (static) type of e, are type-valid (equivalently t is convertible to T) only if t and T are the same or the following are true:
-- neither t nor T is a type parameter
-- if t is either boolean, char or numeric, then T must correspondingly be boolean, char, or numeric
-- if t is a tuple type, T must be a tuple type with the same rarity, and t.n must be convertible to T.n for each component n of the tuple
-- if t is a collection type, T must be a collection type of the same arity, and the type parameters of t must be convertible to the corresponding type parameters of T
-- if t is an iterator type, T must be a iterator type and the type parameter of t must be convertible to the type parameter of T
-- if t is a function type, T must be a function type with the same number of parameters and the parameter types of T must be convertible to the corresponding parameter types of t, and the return type of t must be convertible to the return type of T
-- if t is an algebraic data type, then T must be the same data type
-- if t is a non-array reference type, then T must be a reference type and t must be a sub or super type of T
-- if t is an array type, then T must be an array type with the same number of dimensions and the type parameter of t must be convertible to the type parameter of T
-- named, opaque, synonym ???

- e is T is true precisely in the following cases, where t is the static type of e:
-- t is equal to T
-- t and T are both numeric types (int or real or bit-vector) or subset types or new types with numeric base types, and the value of e is a valid value of type T
-- [if ever subset types of non-numeric types are permitted, then] t and T are subset types of the same base type B (or are the base type B) and the value of e is a valid value of the subset type T. t and T may also be newtypes that are subset types.
-- t and T are non-array reference types and T is a super type of t
-- t and T are non-array reference types and T is a subtype of t and T is a supertype of the (dynamic) class of the value of e
-- t is an array type and for each element ei of e, 'ei is Tp' holds where Tp is the type parameter of the array type T
-- t is an iterator type, and for each element ei returned by the iterator, 'ei is Tp' holds where Tp is the type parameter of the iterator type T

**Comment by robin-aws** [comment]
Looks like this can be resolved because of #1220 - if there's any disagreement in semantics between this proposal and what's implemented now, we can investigate that with separate issues. Please reopen or cut further issues as needed!
