### ISSUE TITLE
ICE with provided datatype member

### ISSUE THREAD

**Issue by utaal** [dafny-lang/dafny#757]
The following throws an exception:

```
module M {
  export
    provides A, A.New
  datatype A<T> = A(s:seq<T>) {
    static method New() returns (self: A<T>) {
      self := A([]);
    }
  }
}

module M2 {
  import M

  method test() {
    var a := M.A<int>.New(); // throws when adding this line
  }
}
```

Thrown exception:

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.Collections.Generic.KeyNotFoundException: The given key 'T' was not present in the dictionary.
```

It seems related to `A` not being revealed in `test`. If I switch `provides A` to `reveals A`, everything's fine.

I'm not super clear on the syntax for exports of members, so it's possible I'm misusing something too.

**Comment by davidcok** [comment]
Fixed bug in resolution of generics within modules
