### ISSUE TITLE
Feature request: allow potentially-empty types, subset types without witnesses

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#774]
Witnesses are required in order to prove that a type is non-empty. 

Some Dafny code bases will be using stronger values for `/definiteAssignment` and avoiding other sources of non-determinism, to the point where there is never a need to choose an arbitrary value from some types, or for soundness to depend on the non-emptiness of a type.

We will have to think through the implications carefully, but it seems like it should be possible to allow empty types, under the assumption that other mechanisms will provide soundness when it matters. For example, a subset type declaration could omit the witness declaration, with the consequence that the subset type would not have the `(0)` "zero initializable" type characteristic. 

If this was possible, #339 would become less important: in many cases it will be easier to not specify a witness at all, and I suspect this solution is less of a can of worms than allowing heap-based witnesses.

**Comment by RustanLeino** [comment]
Empty types are now allowed (by pull requests #1061, #1062, #1066).
To opt out of giving a witness, you can now write `witness *`. (The absence of a `witness` clause still essentially means `witness 0`.)
