### ISSUE TITLE
DafnyExtension solution does not build on master, and is not built on the build server

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/dafny#776]
The DafnyExtension solution is currently not being built on the build server, and currently it does not build on master. One cause is [this commit](https://github.com/dafny-lang/dafny/commit/ab7232410005fd070dba3a6044b52a7bfeb02c05) which removes a required field because it's thought to be unused. Is this extension still relevant? I'm guessing it's used in Visual Studio but has become outdated.

I see several options:
1. Remove the DafnyExtension solution and related projects.
1. Resolve the DafnyExtension build errors and 
   1. Remove `DafnyExtension.sln` and add its projects to `Dafny.sln`. 
   1. Add `DafnyExtension.sln` to the build server steps. This option seems strictly worse than 1.i, since here committers are likely to see build errors only on the build server.
 1. Move `DafnyExtension.sln` and related projects to another repository, and reference Dafny either through NuGet or through a git submodule of this repository. This way the Dafny version is pinned and `DafnyExtension.sln` can move at its own pace.

I recommend option 2/i only if the extension is considered a permanent and integral part of Dafny, since it slows down Dafny development. I'm guessing 3 is best option then, right?

**Comment by RustanLeino** [comment]
Thanks for pointing this out. The DafnyExtension is a Dafny plug-in for the full Microsoft Visual Studio. It provides some functionality that the VS Code and Emacs IDEs do not. Most prominently:

* it has hover text that shows the types of variables,
* it shows when the verifier is still working and distinguishes that from program text that has not yet been sent to the verifier,
* it highlights the control path within a method that leads to an error, and
* it includes the Boogie Verification Debugger, which can show values of variables in each state leading to an error.

Despite this functionality, the recommended IDE for Dafny is VS Code (and Emacs, for those who prefer Emacs). In fact, last I had my fingers in DafnyExtension, I remember that some part of the Visual Studio extension API had changed and that gave some errors.

I consider DafnyExtension as no longer supported. My suggestion is therefore your option 1.

**Comment by keyboardDrummer** [comment]
PR: https://github.com/dafny-lang/dafny/pull/781
