### ISSUE TITLE
Dafny type resolution is not performed in an 'old' context

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#801]
This code
```
class A {
  
  var i: int;

  method m(k : int)
    requires i == 2 && k == 3;
    modifies this;
  {
    var i: bool := true;
    var k: bool := true;
    assert old(i) == 2;
    assert old(k) == 2;
  }
}
```
gives type errors on the asserts, which it should not do.

**Comment by RustanLeino** [comment]
Why? The local variable `i` shadows the field `i`. If you want to refer to the field `i` in the asserted expression, you have to write `this.i`.

**Comment by davidcok** [comment]
I'd prefer the interpretation that old (and labels) refer to the scope at the designated context, not just the value. To me it makes more sense from a user point of view.

**Comment by RustanLeino** [comment]
The expression is resolved at the program location where it is written. But the heap used to interpret the value of the expression is in the old state.

**Comment by davidcok** [comment]
Issue behaves as designed. Leaving open until some explanatory documentation is written in the RefMan.
