### ISSUE TITLE
Update z3 dependency

### ISSUE THREAD

**Issue by acioc** [dafny-lang/dafny#810]
For Dafny 3.0, we should update the dependency on z3 to the latest version.

**Comment by carlocab** [comment]
Just leaving a note here so it's not forgotten:

Please also update the [Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/dafny.rb) when the z3 dependency is updated. Thanks.

**Comment by RustanLeino** [comment]
Thanks, @carlocab. The brew formula has now been updated for Dafny 3.0.0 (and the components it uses).

**Comment by carlocab** [comment]
Thanks. I see it's still not using the Homebrew version of z3, however. Is Dafny not compatible with z3 4.8.10?

**Comment by davidcok** [comment]
Correct, it is not. A first step was moving to .NET 5.0 from 3.1, and to current versions of other dependencies. The team is working on moving to the current version of Z3, but not there yet.

**Comment by RustanLeino** [comment]
>  Is Dafny not compatible with z3 4.8.10?

@carlocab The Dafny test suite currently uses Z3 v4.8.5. The interface to newer versions of Z3 is the same. However, we have found severe performance problems for Dafny when using Z3 v4.8.8, v4.8.9, and (a pre-release of) v4.8.10. If you'd like to try Z3 v4.8.10, you probably want to set `smt.candidate_models=true`, see https://github.com/Z3Prover/z3/issues/4924 and https://github.com/Z3Prover/z3/commit/f519c58acec47c11c64eab4a145f8735fa63a6e6.

**Comment by tchajed** [comment]
@RustanLeino what's the status of this issue? Is there progress on migrating to Z3 4.8.14?
