### ISSUE TITLE
Building the parser locally and in CI

### ISSUE THREAD

**Issue by acioc** [dafny-lang/dafny#812]
Creating a separate issue linked to https://github.com/dafny-lang/dafny/issues/462 to track the comment 
"A similar problem we should be solving is around the automatic generation of the parser."

Paraphrasing @RustanLeino: Currently, we have a file `Source/Dafny/Dafny.atg` that defines the parser and scanner. A Makefile should be run after changing `Dafny.atg`, which generates `Parser.cs` and `Scanner.cs`. Currently, all 3 of `Dafny.atg`, `Parser.cs`, and `Scanner.cs` are checked into the repository, and a developer who changes `Dafny.atg` is responsible for running the Makefile and checking in the changes.

What we should do is only check in `Dafny.atg` and have both the local build process and CI perform the build process that the Makefile handles today (with the additional files being part of a `.gitignore`). This would mean we would no longer need to check in all files manually, and we would know we're always running the latest version.

As an additional note, the Makefile currently runs the parser generator Coco. Coco produces two known warnings. It would be nice if the CI was aware of these two warnings and would complain if any additional warnings are produced. Unknown how this would be handled (outside of potentially a `.expect` file variant).

**Comment by davidcok** [comment]
Actually there are 5 warnings, currently.  These should be analyzed and cleaned up also.

**Comment by davidcok** [comment]
PR 812 
- builds the parser in CI
- removes generated files from GitHub
- builds and tests DafnyRuntime.jar in CI
- removes it from GitHub

Remains to fix the warnings issued by Coco

**Comment by davidcok** [comment]
Fixed parser (PR 827). Coco now issues just these correct informational messages:
  OldSemi deletable
  OptGenericInstantiation deletable

**Comment by davidcok** [comment]
The number of Coco warnings has ballooned.  They ought to be investigated.

**Comment by keyboardDrummer** [comment]
> The number of Coco warnings has ballooned. They ought to be investigated.

How are these visible? Could you open a separate issue for that and provide reproduction details?

**Comment by davidcok** [comment]
Follow on notes in #3124
