### ISSUE TITLE
Server test server/simple-session.transcript is broken

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#814]
This test broke when the deprecated int(...) syntax was removed. The problem is that the test is constructed using hashes and we don't have the tools to inspect or regenerate the hash for a revised input. So the test is marked XFAIL for now, but should be fixed at some point, and the tools to make and inspect transcripts should be identified and documented.

**Comment by keyboardDrummer** [comment]
Resolved in https://github.com/dafny-lang/dafny/commit/703af50e46c2086632ec988c4b72063f1124a06d#diff-0e443c0ae54eaf9fb54bdcd6afa81454f8999e5df37a641ae06be1cf69265427
