### ISSUE TITLE
Inductive lemmas drop precondition label

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#816]
When a precondition is given a label, it is necessary to use `reveal` to introduce the precondition as an assumption in the body. This is currently not happening for inductive lemmas. (Note, it is not a problem for co-inductive lemmas, where the preconditions are not copied.)

## Repro

``` dafny
lemma P0(x: int)
  requires X: x == 17
{
  assert x == 17;  // error: because X hasn't been revealed
}

lemma P1(x: int)
  requires X: x == 17
{
  reveal X;
  assert x == 17;  // this verifies, because X has been revealed
}

inductive lemma Q(x: int)
  requires X: x == 17
{
  assert x == 17;  // this SHOULD be an error, but it isn't; evidently, the X is ignored
}

colemma R(x: int)
  requires X: x == 17
{
  assert x == 17;  // error: because X hasn't been revealed
}
```

Another way to inspect what has gone wrong is to use `/rprint` to show the prefix lemmas that are created for the two extreme lemmas. The label `X` is shown for `Q`, `R`, and `R#`, but is conspicuously missing for `Q#`.

## Fix

A quick inspection of the code suggests that the problem can be fixed by changing the following line in Resolver.cs so that it also passes in `p.Label` to the `MaybeFreeExpression` constructor.

```
              prefixLemma.Req.Add(new MaybeFreeExpression(pre, p.IsFree));
```

**Comment by davidcok** [comment]
Fixed as suggested. PR #848.
