### ISSUE TITLE
Dafny does not support unicode characters (outside of escape sequences)

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#818]
Although Coco claims to support UTF-8 encoded input, the scanner it generates for Dafny does not currently do so. Even the most recent executable from the CoCo/R website does not. Perhaps some setting needs to be set or the executable is not consistent with the source code.

The effect is that in characters and in strings, one may only use ASCII characters, and so unicode content must be constructed as escape sequences. Dafny's verbatim strings can contain unicode characters currently, but they will be misunderstood.

**Comment by robin-aws** [comment]
https://github.com/dafny-lang/dafny/pull/2717 partially fixed this, but there is still Coco-generated code that casts from `int` to a `char`, and hence truncates any code point outside of the BMP.
