### ISSUE TITLE
ghost parameter of constructor call not treated as specification context

### ISSUE THREAD

**Issue by erniecohen** [dafny-lang/dafny#833]
class C {
    ghost var x:int;
    method f(ghost y:int) {}
    method test0() { f(x);}  // passes
    constructor(ghost y:int) {x:=y;}
    method test1() returns (c:C) { c := new C(x); } // fails with "ghost fields are allowed only in specification contexts"
}

**Comment by davidcok** [comment]
Ernie - this works without errors on current master (for me). For you also?

**Comment by erniecohen** [comment]
Yes, this seems to be fixed now. I think the issue was from 2.3.
