### ISSUE TITLE
Syntax Update statement for Datatypes are 

### ISSUE THREAD

**Issue by WouterSchols** [dafny-lang/dafny#849]
According to the reference manual fields of a datatype can be updated using the following syntax:
`datatype Test = Test(v: nat)`
`var newTest: Test := oldTest[v := 1];`
This returns an error message: 
`update requires a sequence, map, multiset, or datatype (got Test)` 
After some searching I found that this error occurs because the syntax is updated. The correct syntax is:
`var newTest := oldTest.(v := 1);`
The new syntax does not return an error. The error message and reference manual should be updated to the new syntax.

**Comment by davidcok** [comment]
Corrects error message and documentation regarding datatype update syntax
