### ISSUE TITLE
provided function/lemma misinterpreted as an imported method

### ISSUE THREAD

**Issue by erniecohen** [dafny-lang/dafny#854]
The assertion below gets the errors "expression is not allowed to invoke a method (l)" and "method call is not allowed in an expression context":

module M {
    export provides l   
    lemma l() ensures true {}
} 
module N {
    import M
    function f():nat { assert M.l(); 3 } 
}

**Comment by davidcok** [comment]
Ernie, Just call the lemma, don't assert it. The following works fine:

module M {
    export provides l   
    lemma l() ensures true {}
} 
module N {
    import M
    function f():nat { M.l(); 3 } 
}

I'll leave this issue open to see if the error message can be improved.

**Comment by davidcok** [comment]
Adjusted error messages. PR #855

**Comment by erniecohen** [comment]
Sorry, this arose from trying to simplify an example of a different problem. I'll file it separately.
