### ISSUE TITLE
Oversized arrays can cause runtime errors or crashes

### ISSUE THREAD

**Issue by danmatichuk** [dafny-lang/dafny#856]
The following program in Dafny successfully verifies:

```
method Crash() returns ()
{
  var big := 9223372036854775808;
  var a := new int[big];
  assert a.Length == big;
}
```

But the resulting C# program crashes when run.

```
public static void Crash()
{
  BigInteger _20_big;
  _20_big = new BigInteger(9223372036854775808UL);
  BigInteger[] _21_a;
  var _nw0 = new BigInteger[(int)(_20_big)];
  _21_a = _nw0;
}
```

Since the `big` integer cannot be cast from a `BigInteger` to an `int`, the result is an overflow runtime exception.

Similarly, in Java the `BigInteger` is cast to an `int` via `BigInteger.intValue()` which truncates the value to its lower 32 bits, and invalidates the assertion.

For this to be sound, Dafny either needs to enforce some upper bound on array sizes, or the target languages need to implement arrays with a collection type that can be indexed on BigIntegers directly.

**Comment by davidcok** [comment]
Consider the same issue when casting indices to ints.

**Comment by davidcok** [comment]
Fixed in PR 882
