### ISSUE TITLE
Refinement of extended traits doesn't see fields of the extendee

### ISSUE THREAD

**Issue by erniecohen** [dafny-lang/dafny#864]
```
module M1 {
    trait T0 {
        var b:bool
    }
    trait T1 extends T0 { 
    }
}
module M2 refines M1 {
    trait T1 {
        predicate p() {b}   // error: unresolved identifier: b
    }
}
```

**Comment by davidcok** [comment]
trait T1 { is an error -- repeated name
trait T1 ... {    is required to indicate that M2.T1 is refining M1.T1

Same rule for classes.

**Comment by RustanLeino** [comment]
Compare with syntax in https://github.com/dafny-lang/dafny/issues/857

**Comment by davidcok** [comment]
Note that ... is now required in any refining declaration.  This is a backward incompatibility.

**Comment by keyboardDrummer** [comment]
Seems like this is resolved:
```
module M1 {
  trait T0 {
    var b: bool
  }

  trait T1 extends T0 { }
}

module M2 refines M1 {
  trait T1 ...  {
    predicate p()
    {
      b
    }
  }
}
```

results in

```
Error: trait 'T1' is in a different module than trait 'M1.T0'. A trait may only extend a trait in the same module, unless the parent trait is annotated with {:termination false}.
```
Although adding the `...` gives

```
Error: trait 'T1' is in a different module than trait 'M1.T0'. A trait may only extend a trait in the same module, unless the parent trait is annotated with {:termination false}.
```

And then adding the `{:termination false}` results in a crash, for which I cut a ticket: https://github.com/dafny-lang/dafny/issues/1316

@erniecohen can we close this?

**Comment by robin-aws** [comment]
Closing as stale - @erniecohen please reopen as needed!
