### ISSUE TITLE
-countVerificationErrors:0 overrides parsing errors as well

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#887]
Resolved - with possible outstanding task: rename or remove this option after testing is ported to an XUNit based system in which exit values can be checked.

-------------

The documentation for the `countVerificationErrors:0` option states:

```
If preprocessing succeeds, set exit code to 0 regardless of the number of verification errors.
```

This takes effect even if the Dafny file cannot be parsed, though, which is surprising to say the least. To reproduce:

```
$ echo "This is definitely not Dafny source" >> NotDafny.dfy
$ dafny -countVerificationErrors:0 NotDafny.dfy; echo $?
Dafny 3.0.0.20820
/Users/salkeldr/Documents/GitHub/dafny/Test/NotDafny.dfy(1,0): Error: EOF expected
1 parse errors detected in NotDafny.dfy
0
```

**Comment by robin-aws** [comment]
Looks like this also overrides compilation errors. Example from the test suite (not currently run because this one isn't working for Go yet):

```
Test $ dafny /countVerificationErrors:0 comp/ExternCtors.dfy /compile:4 /noVerify /compileTarget:go comp/ExternCtors-externs/Library.go
Dafny 3.0.0.20820

Dafny program verifier did not attempt verification
Compiled program written to ExternCtors-go/src/ExternCtors.go
Additional code written to ExternCtors-go/src/dafny/dafny.go
Additional code written to ExternCtors-go/src/System_/System_.go
Running...

Additional input comp/ExternCtors-externs/Library.go copied to comp/ExternCtors-go/src/Library/Library.go
# command-line-arguments
comp/ExternCtors-go/src/ExternCtors.go:49:47: not enough arguments in call to Library.New_Class_
	have ()
	want (dafny.Int)
Test $ echo $?
0
```

**Comment by RustanLeino** [comment]
It seems that `/countVerificationErrors:0` is used through our lit-based test suite. So, wouldn't we want the current behavior for any test that is testing parsing (of which there are not many, if any)? If so, would you rather have another value of the switch that does what you suggest (which I presume you need for the new test harness)?

**Comment by davidcok** [comment]
countVerificationErrors is misnamed. Its sole purpose is to suppress the exit value for all but command-line errors. It is only used in testing.

**Comment by davidcok** [comment]
Outstanding task: Possibly rename or remove this option, particularly once testing is ported to Unit where exit values can be tested

**Comment by davidcok** [comment]
This option has been removed. PR 3634
