### ISSUE TITLE
There are no negated literals

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#889]
Up until now, Dafny has not had any negated literals. Instead, an expression like `-3` is parsed as a unary expression that applies operator `-` to the (non-negative) literal `3`. This is awkward in at least two situations, see below.

This Issue suggests that the grammar should change to parse a single `-` token in front of a numeric literal as part of the numeric literal.

## Repros

One awkward situation is when trying to write a negative literal for a type that doesn't have the same corresponding positive literal. Here are two examples:

``` dafny
newtype int8 = x | -128 <= x < 128
newtype smallneg = r | -1.0 <= r <= 0.0

method M() returns (b: int8, r: smallneg) {
  if {
    case true =>
      b := -128;  // this currently gives an error: the argument to unary `-`, the literal `128`, is not a value of type `int8`
    case true =>
      b := -127 - 1;  // fine
    case true =>
      b := (-128) as int8;  // fine
    case true =>
      b := -128 as int8;  // `-` binds stronger than `as`, so this is the same as the previous line
    case true =>
      b := -(128 as int8);  // this is, and should continue to be, an error
 }

  if {
    case true =>
      r := -1.0;  // error: 1.0 violates newtype type constraint
    case true =>
      r := -1.0 as smallneg;  // fine
  }
}
```

The other situation is when trying to use a negative literal in a `case` pattern:

``` dafny
method MatchCaseParsing(x: int, pair: (int, int))
  requires x == 2 || x == -1
  requires p.0 == 10 && (p.1 == 10 || p.1 == -10)
{
  match x {
    case 2 =>
    case -1 =>  // this gives a parse error
    // Note, `case (-1) =>` is not a workaround, because parenthetic expressions are not allowed in patterns
  }
  match pair {
    case (10, 10) =>
    case (10, -10) =>  // this gives a parse error
  }
}
```

## Implementation note

Bitvector arithmetic is modular, that is, is wraps around. However, literals still have to be proper values of the type. So, _after_ implementing this Issue, we would expect:

``` dafny
method Bitvectors() returns (v: bv8) {
  if
  case true =>
    v := -3;  // error: too small to be a bv8
  case true =>
    v := 300;  // error: too large to be a bv8
  case true =>
    v := -(3);  // fine, since this is still a unary-minus expression applied to 3, and - wraps on bitvectors
  case true =>
    v := 200 + 100;  // fine, since 200 and 100 are both bv8 values, and + wraps on bitvectors
}
```

**Comment by davidcok** [comment]
Clarification question: is white space allowed between - and digits in a negated literal?  I would suggest not, though that means that -1 is a literal and - 1 is a negation operation
