### ISSUE TITLE
Feature request: access control to members of a class (private, public, protected)

### ISSUE THREAD

**Issue by joaopascoalfariafeup** [dafny-lang/dafny#900]
To make sure that implementation details (namely internal state representation) are not exposed in the pre/post specifications of (public) operations of a class, it would be helpful to mark as private (or protected) the fields that represent the internal state, mark as public (but readonly) the state abstraction variables or functions, and mark as public the operations to be used by clients of the class.   
Then Dafny should verify that explicit pre/post conditions of an operation (constructor, method, function or predicate) don't refer to members with less visibility.

**Comment by RustanLeino** [comment]
Such access control in Dafny can only be done using modules and _export sets_, see http://leino.science/papers/krml261.pdf. Within one module (or within a particular type inside a module), there is no such access control.

This should be documented more directly in the reference manual.

**Comment by davidcok** [comment]
Explanatory text added to RM - PR 916
