### ISSUE TITLE
Code verifies in Rise4Fun but fails in VSCode + Plugin

### ISSUE THREAD

**Issue by julioapm** [dafny-lang/dafny#901]
The code available in https://rise4fun.com/Dafny/eGUn verifies as correct, but when running the same code in Visual Studio Code with Dafny plugin version 0.18.0 (running Windows 10) gives an error on the invariant invariant
line[at..at+i] == old(line[at+p..at+p+i])
Any ideas why this happens?
Can anyone reproduce the same behavior?

Julio Machado

**Comment by RustanLeino** [comment]
The program verifies with the latest Dafny (built from sources, and quite possibly the latest binary release as well). If you want the fix before the VS Code plug-in uses the latest Dafny, you can install the latest binaries yourself and point the VS Code plug-in to use them.
