### ISSUE TITLE
Problem in variable names' generation in intermediate Boogie file

### ISSUE THREAD

**Issue by franck44** [dafny-lang/dafny#904]
The following example `fun-in-const.dfy` generates an error when verified:

```dafny

module FOO {
    //  two fields are needed
    datatype D = D( 
        f1: nat, 
        f2: nat 
    )  

    function method f(d : D) : nat 
        ensures f(d) != 0

    const D0 := D(0, 0)
    const D1 :=  f(D0) 

    //  Similar outcomes occur using f1 or f2
    const C1 :=  D0.(f2 := f(D0))
    const C2 :=  D0.(f2 := D1)
   
    class E {
        var a : D
        constructor ()  {  
            a := C1; 
        }
    }
}
```
Running 
```bash
dafny.exe  /dafnyVerify:1 /compile:0 /tracePOs /traceTimes /noCheating:0 bug-reports/fun-in-const.dfy
(0,-1): Error: more than one declaration of variable name: dt_update_tmp#0#0
1 name resolution errors detected in /Users/franck/tmp/fun-in-const_FOO.bpl

*** Encountered internal translation error - re-running Boogie to get better debug information

>>> Starting resolution   [0.559347 s]
/Users/franck/tmp/fun-in-const_FOO.bpl(3043,16): Error: more than one declaration of variable name: dt_update_tmp#0#0
1 name resolution errors detected in /Users/franck/tmp/fun-in-const_FOO.bpl
```
# Initial investigation

1. the problem seems to stem from the assignment section in the constructor (commenting out suppresses it),
2. using C2 (and D1) instead of C1 (and D0) also suppresses the problem,
3. the problem does not show up if `datatype D` has one field. 

# Work around
Pre-compute the value f(D0)  (and use C2 (and D1))

# Dafny versions impacted
Occurs in the following versions on MacOSX:
* Dafny 3.0.0.20817
* Dafny 2.3.0.10506

# How discovered
The problem occurred in a more complicated setting in [this project](https://github.com/PegaSysEng/eth2.0-dafny) and was trimmed down to an (hopefully) minimal version.

**Comment by davidcok** [comment]
Problem was that in the generation of the WellFormedness check, there is a call of SetupBoundVarsAsLocals, which acts on a let expression generated from the use of the const declarations. However, SetupBoundVarsAsLocals was called in a way that the generated local variables had the same names as the original bound variables (which were also used in the generated method), hence the duplicate declaration error. It is straightforward to fix this by calling SetupBoundVarsAsLocals in a way that appends a unique suffix to the new locals.

**Comment by franck44** [comment]
Great! Thanks @davidcok.
