### ISSUE TITLE
String subset types based on length unsound under concatenation

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#921]
To reproduce:

```
module StringsOfLength {
  type ShortString = s: string | |s| < 10

  method M() {
    var x: ShortString := "Far too long I'm sure you'll agree"; // value does not satisfy the subset constraints of 'ShortString'
    var x2: ShortString := "Far " + "too long " + "I'm sure " + "you'll agree"; // no error!
  }
}
```

**Comment by RustanLeino** [comment]
The result of each `+` in the rhs of the assignment to `x2` should be `string` (not `ShortString`), and the verifier should notice that the assignment to `x2` has a rhs of type `string` and therefore needs a subset range check.

**Comment by davidcok** [comment]
Manually verified the problem is fixed. Also it is test git-issue-921
