### ISSUE TITLE
homebrew formula pours in incompatible version of Z3

### ISSUE THREAD

**Issue by emptylambda** [dafny-lang/dafny#947]
Currently homebrew [formula](https://formulae.brew.sh/formula/dafny#default) pours in Z3 version 4.8.9 (latest)
as dependency of dafny 2.3.0 (stable). 

But since[ Z3 version 4.8.6](https://github.com/Z3Prover/z3/blob/6d427d9dae4f374107297b5bf0dd0fa5651c0d1b/RELEASE_NOTES#L57) the keyword `model_compress` has been removed and replaced with `model.compact` and cause prover error: 

```
Dafny 2.3.0.10506
Prover error: line 18 column 28: unknown parameter 'model_compress'
```

I suggest either updating the homebrew formula with dafny 3.0.0 or modify the dependency on homebrew and roll back to Z3 version 4.8.4 to get rid of this issue. (dafny 2.3.0 was meant to be paired with z3 4.8.4)

**Comment by davidcok** [comment]
Brew is fix for v 2.3.0 -- it builds Z3 4.8.4

An update to the formula for the 3.0 release will be attempted once we cleanup the current build problems.
