### ISSUE TITLE
Refining module cannot use predicate subtype of parent datatype as datatype field

### ISSUE THREAD

**Issue by erniecohen** [dafny-lang/dafny#953]
The following gets the error "because of cyclic dependencies among constructor argument types, no instances of datatype 'C' can be constructed":

```
module P {
    datatype T_ = T() 
    type T = t:T_ | true ghost witness T()
}
module C refines P {
    datatype C = C(t:T)       
}
```

**Comment by RustanLeino** [comment]
This was fixed (surprisingly) as part of PR #926.
Once you get passed the type-checking problem, there was a compilation bug, which has been fixed in PR #943.

We should add the example above as a test case, to make sure it stays fixed.
