### ISSUE TITLE
Member declarations for inductive datatypes with multiple constructors

### ISSUE THREAD

**Issue by erniecohen** [dafny-lang/dafny#956]
Member declarations do not seem to be possible for inductive datatypes with multiple constructors. For example, the following gets the error "destructor 'y' can only be applied to datatype values constructed by 'T2'":
```
datatype T = T1(x:nat) | T2(y:nat) {
    predicate i() {
        y > 0
    }
}
```

**Comment by davidcok** [comment]
Ernie - the member is a member of the datatype, not just of a particular constructor. SO you need a precondition that 'this' is actually a T2 before you can select 'y', as in

datatype T = T1(x:nat) | T2(y:nat) {
    predicate i() requires T2? {
        y > 0
    }
}
