### ISSUE TITLE
surprising behavioral divergence between forall proof with empty body and forall assertion

### ISSUE THREAD

**Issue by erniecohen** [dafny-lang/dafny#962]
One would expect that
```
forall ... ensures p {}
```
to be semantically equivalent (since there is nothing to hide) to 
```
assert forall ... ==> p;
```
But there are examples where the former succeeds but the latter fails.

**Comment by RustanLeino** [comment]
Can you please post an example?

**Comment by RustanLeino** [comment]
Closing for lack of repro.
