### ISSUE TITLE
Problem combining export sets and module refinement

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#981]
This example produces an error and it seems it should not.
```
module A {
  export reveals a
  const a := 10;
}

module B refines A {
  export reveals *  // complains duplicate B
}
```

The internal problem seems to be that export set A when copied into module B retains its 'default ness' and but is given the name B, after a check whether an export set B is already present, so there ends up being two B's, and an error. SO an implicit invariant is being violated.

1) In any case, it should certainly be possible to override any inherited default export set
but also
2) in what way and with what name should default export set A be inherited, perhaps
a) as export B extends A
b) as export B reveals * extends A
c) as export B reveals *
?
3) What if the refinement parent has an export set (or any other declaration) that matches the name of the refining module? Keeping the export set namespace separate from other declarations might help but not solve this problem.

**Comment by RustanLeino** [comment]
The implicit name of the export set in `A` is `A`. From what you're saying, it sounds like the syntax `export reveals a` in inherited into `B` and only _then_ is the omitted name converted to the name of the enclosing module, which by that time is `B`. Instead, I think the refinement cloner should detect when it's cloning an `export` declaration that doesn't have an explicit name. When it does, it should then introduce the name of the _refined module_ (that is, `A` in the example) as that inherited export set.

So, here's the modules from the example above:

``` dafny
module A {
  export reveals a  // this is the same as "export A reveals a" inside A
  const a := 10
}

module B refines A {
  // export A reveals a    // this is inherited from A
  // const a := 10    // this is inherited from A
  export reveals *  // this is the same as "export B reveals *" inside B
}
```

If the program contained an additional module `C` without any `export C ...` or `export /*no name*/ ...` declaration, then (as we had discussed in person) it seems reasonable to add an eponymous export set to `C` that extends the parent's eponymous export set.

``` dafny
module C refines A {
  // export A reveals a    // this is inherited from A
  // const a := 10    // this is inherited from A
  export C extends A  // this is to be generated automatically since C did not declare its own eponymous export set
  const c := 12
}
```

So, for question 2, I'd say:
d) as `export A // and then the rest of the declaration from A`

For 3, I think we should give an error. The error message can be "a module `B` cannot refine a module that contains a top-level name `B`".
